#!/usr/bin/env bash
set -euo pipefail

# ------------------------------------------------------------
# Locate MPLAPACK root, BLAS/LAPACK source dirs, and output file
# ------------------------------------------------------------

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
mplapack_root="$(cd "${script_dir}/.." && pwd)"
lapack_version="${LAPACK_VERSION:-3.9.1}"
blas_src="${mplapack_root}/external/lapack/work/internal/lapack-${lapack_version}/BLAS/SRC"
lapack_src="${mplapack_root}/external/lapack/work/internal/lapack-${lapack_version}/SRC"
out="${script_dir}/mplapack_name_map.txt"

if [[ ! -d "$blas_src" ]]; then
    echo "Error: BLAS source directory not found: $blas_src" >&2
    exit 1
fi
if [[ ! -d "$lapack_src" ]]; then
    echo "Error: LAPACK source directory not found: $lapack_src" >&2
    exit 1
fi

# Redirect all stdout to the output file
: > "$out"
exec > "$out"

# ------------------------------------------------------------
# Exception lists: files that should NOT be converted
# ------------------------------------------------------------

# Exclude any file whose basename starts with these prefixes
EXCLUDE_PREFIXES=( s c )

# Basenames that will be converted manually (not generated by the automatic rule below)
EXCLUDE_BASENAMES_MANUAL=( )

# Basenames that are not needed on the C++ side
EXCLUDE_BASENAMES_UNUSED=( icamax isamax dsdot )

# Other helper/utility routines to be excluded from this pass
EXCLUDE_BASENAMES_MISC=( )

# Combined basename exception list (for iteration)
EXCLUDE_BASENAMES=(
  "${EXCLUDE_BASENAMES_MANUAL[@]}"
  "${EXCLUDE_BASENAMES_UNUSED[@]}"
  "${EXCLUDE_BASENAMES_MISC[@]}"
)

# ------------------------------------------------------------
# Manual mappings:
#   fortran_name -> cpp_name
# These are emitted as-is and then skipped by the automatic rule.
# ------------------------------------------------------------

MANUAL_MAPPINGS=(
  "dznrm2 RCnrm2"
  "dzasum RCasum"
  "idamax iRamax"
  "izamax iCamax"
  "xerbla Mxerbla"
  "xerbla_array Mxerbla_array"
  "lsame Mlsame"
  "dcabs1 RCabs1"
  "zdcal CRscal"
  "dlamch Rlamch"
  "ilaenv iMlaenv"
  "zdrot CRrot"
  "zdscal CRscal"
  "zdrscl CRrscl"
  "dzsum1 RCsum1"
  "izmax1 iCmax1"
  "iparmq iMparmq"
  "ieeeck iMieeeck"
  "ilauplo iMlauplo"
  "dlamc3 Rlamc3"
  "ilaenv2stage iMlaenv2stage"
  "iladlc iMladlc"
  "iladlr iMladlr"
  "ilazlc iMlazlc"
  "ilazlr iMlazlr"
  "ilatrans iMlatrans"
  "iparam2stage iMparam2stage"
  "dladiv2 Rladiv2"
  "la_isnan Mla_isnan"
  "ilaprec iMlaprec"
)

# ------------------------------------------------------------
# Helper functions
# ------------------------------------------------------------

in_array() {
    local needle="$1"; shift
    local x
    for x in "$@"; do
        [[ "$x" == "$needle" ]] && return 0
    done
    return 1
}

has_excluded_prefix() {
    local base="$1"
    local p
    for p in "${EXCLUDE_PREFIXES[@]}"; do
        [[ "$base" == "${p}"* ]] && return 0
    done
    # no excluded prefix matched
    return 1
}

is_excluded_basename() {
    local base="$1"
    in_array "$base" "${EXCLUDE_BASENAMES[@]}"
}

# Map Fortran routine name to MPLAPACK-style C++ name
# d*/s* -> R*, z*/c* -> C*
make_cpp_name_from_prefix() {
    local base="$1"
    local first="${base:0:1}"
    local rest="${base:1}"
    case "$first" in
        d|s) echo "R${rest}" ;;
        z|c) echo "C${rest}" ;;
        *)   echo "${base}"  ;;
    esac
}

# ------------------------------------------------------------
# Main
# ------------------------------------------------------------

# Input file list:
#   1) use command-line arguments if given
#   2) otherwise, use "*.f" and "*.f90" in the BLAS and LAPACK source directories
files=()
if [[ "$#" -gt 0 ]]; then
    files=("$@")
else
    mapfile -t files < <(
        {
            find "$blas_src"   -maxdepth 1 -type f \( -name '*.f' -o -name '*.f90' \)
            find "$lapack_src" -maxdepth 1 -type f \( -name '*.f' -o -name '*.f90' \)
        } | sort
    )
fi

# To avoid duplicates for the same basename
declare -A SEEN_BASES=()

# First emit manual mappings
for entry in "${MANUAL_MAPPINGS[@]}"; do
    set -- $entry
    src="$1"
    dst="$2"
    printf "%-16s %s\n" "$src" "$dst"
    SEEN_BASES["$src"]=1
done

# Now auto-generate mappings from filenames
for src in "${files[@]}"; do
    base="${src##*/}"
    base="${base%.*}"  # strip .f/.f90

    # Skip if already handled by MANUAL_MAPPINGS
    if [[ -n "${SEEN_BASES["$base"]+x}" ]]; then
        continue
    fi

    # Skip by excluded prefixes
    if has_excluded_prefix "$base"; then
        continue
    fi

    # Skip by excluded basenames
    if is_excluded_basename "$base"; then
        continue
    fi

    # Default mapping rule
    cpp_name="$(make_cpp_name_from_prefix "$base")"

    printf "%-16s %s\n" "$base" "$cpp_name"
    SEEN_BASES["$base"]=1
done
