#!/usr/bin/env bash
set -euo pipefail

# ------------------------------------------------------------
# Locate MPLAPACK root, source dirs, and output files
# ------------------------------------------------------------

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
mplapack_root="$(cd "${script_dir}/.." && pwd)"
lapack_version="${LAPACK_VERSION:-3.12.1}"

# Core (BLAS/LAPACK library) sources
blas_src="${mplapack_root}/external/lapack/work/internal/lapack-${lapack_version}/BLAS/SRC"
lapack_src="${mplapack_root}/external/lapack/work/internal/lapack-${lapack_version}/SRC"

# Testing sources (kept completely separate from core map)
eig_src="${mplapack_root}/external/lapack/work/internal/lapack-${lapack_version}/TESTING/EIG"
lin_src="${mplapack_root}/external/lapack/work/internal/lapack-${lapack_version}/TESTING/LIN"
matgen_src="${mplapack_root}/external/lapack/work/internal/lapack-${lapack_version}/TESTING/MATGEN"

# Output name maps (MUST be separate)
out_core="${script_dir}/mplapack_name_map.txt"
out_testing="${script_dir}/mplapack_testing_name_map.txt"

check_dir() {
    local d="$1"
    local label="$2"
    if [[ ! -d "$d" ]]; then
        echo "Error: ${label} directory not found: $d" >&2
        exit 1
    fi
}

check_dir "$blas_src"   "BLAS source"
check_dir "$lapack_src" "LAPACK source"
check_dir "$eig_src"    "LAPACK TESTING/EIG"
check_dir "$lin_src"    "LAPACK TESTING/LIN"
check_dir "$matgen_src" "LAPACK TESTING/MATGEN"

# ------------------------------------------------------------
# Exception lists: files that should NOT be converted
# ------------------------------------------------------------

# Exclude any file whose basename starts with these prefixes
EXCLUDE_PREFIXES=( s c )

# Basenames that will be converted manually (not generated by the automatic rule below)
EXCLUDE_BASENAMES_MANUAL=( )

# Basenames that are not needed on the C++ side
EXCLUDE_BASENAMES_UNUSED=( icamax isamax dsdot )

# Other helper/utility routines to be excluded from this pass
EXCLUDE_BASENAMES_MISC=( )

# Combined basename exception list (for iteration)
EXCLUDE_BASENAMES=(
  "${EXCLUDE_BASENAMES_MANUAL[@]}"
  "${EXCLUDE_BASENAMES_UNUSED[@]}"
  "${EXCLUDE_BASENAMES_MISC[@]}"
)

# ------------------------------------------------------------
# Manual mappings:
#   fortran_name -> cpp_name
#
# IMPORTANT:
# - MANUAL_MAPPINGS_CORE applies ONLY to BLAS/SRC + LAPACK/SRC.
# - MANUAL_MAPPINGS_TESTING applies ONLY to TESTING/{EIG,LIN,MATGEN}.
# - Do NOT merge BLAS/LAPACK entries into the testing name map.
# ------------------------------------------------------------

MANUAL_MAPPINGS_CORE=(
  "chkxer Chkxer"
  "dcabs1 RCabs1"
  "dladiv2 Rladiv2"
  "dlaisnan Risnan"
  "dlamc3 Rlamc3"
  "dlamch Rlamch"
  "droundup_lwork Rroundup_lwork"
  "dzasum RCasum"
  "dznrm2 RCnrm2"
  "dzsum1 RCsum1"
  "idamax iRamax"
  "ieeeck iMieeeck"
  "iladlc iMladlc"
  "iladlr iMladlr"
  "ilaenv iMlaenv"
  "ilaenv2stage iMlaenv2stage"
  "ilaprec iMlaprec"
  "ilatrans iMlatrans"
  "ilauplo iMlauplo"
  "ilazlc iMlazlc"
  "ilazlr iMlazlr"
  "iparam2stage iMparam2stage"
  "iparmq iMparmq"
  "izamax iCamax"
  "izmax1 iCmax1"
  "la_isnan Risnan"
  "lsame Mlsame"
  "lsamen Mlsamen"
  "xerbla Mxerbla"
  "xerbla_array Mxerbla_array"
  "zdcal CRscal"
  "zdrot CRrot"
  "zdrscl CRrscl"
  "zdscal CRscal"
)

MANUAL_MAPPINGS_TESTING=(
  "xlaenv Mxlaenv"
  "zgeesx1 Cgeesx1"
  "zgeesx2 Cgeesx2"
  "zgeesx3 Cgeesx3"
  "zgeesx4 Cgeesx4"
  "zgeesx5 Cgeesx5"
  "zgeesx6 Cgeesx6"
  "zgeesx7 Cgeesx7"
  "zgeesx8 Cgeesx8"
  "zgeesx9 Cgeesx9"
  "zgeevx1 Cgeevx1"
  "zgeevx2 Cgeevx2"
  "zgeevx3 Cgeevx3"
  "zgeevx4 Cgeevx4"
  "zgeevx5 Cgeevx5"
  "zgeev1 Cgeev1"
  "zgeev2 Cgeev2"
  "zgeev3 Cgeev3"
  "zgeev4 Cgeev4"
  "zggev1 Cggev1"
  "zggev2 Cggev2"
  "zggev3 Cggev3"
  "zggev4 Cgvev4"
  "zgees1 Cgees1"
  "zgees2 Cgees2"
  "zggev31 Cggev31"
  "zggev32 Cggev32"
  "zggev33 Cggev33"
  "zggev34 Cggev34"
  "zchkhbstg Cchkhbstg"
  "dchksbstg Rchksbstg"
  "dgees1 Rgees1"
  "dgees2 Rgees2"
  "dgeesx1 Rgeesx1"
  "dgeesx2 Rgeesx2"
  "dgeesx3 Rgeesx3"
  "dgeesx4 Rgeesx4"
  "dgeesx5 Rgeesx5"
  "dgeesx6 Rgeesx6"
  "dgeesx7 Rgeesx7"
  "dgeesx8 Rgeesx8"
  "dgeesx9 Rgeesx9"
  "dgeevx1 Rgeevx1"
  "dgeevx2 Rgeevx2"
  "dgeevx3 Rgeevx3"
  "dgeevx4 Rgeevx4"
  "dgeevx5 Rgeevx5"
  "dgeev1 Rgeev1"
  "dgeev2 Rgeev2"
  "dgeev3 Rgeev3"
  "dgeev4 Rgeev4"
  "dggev1 Rggev1"
  "dggev2 Rggev2"
  "dggev3 Rggev3"
  "dggev4 Rgvev4"
  "dggev31 Rggev31"
  "dggev32 Rggev32"
  "dggev33 Rggev33"
  "dggev34 Rggev34"
  "dpfsv Rpfsv"
)

# ------------------------------------------------------------
# Helper functions
# ------------------------------------------------------------

in_array() {
    local needle="$1"; shift
    local x
    for x in "$@"; do
        [[ "$x" == "$needle" ]] && return 0
    done
    return 1
}

has_excluded_prefix() {
    local base="$1"
    local p
    for p in "${EXCLUDE_PREFIXES[@]}"; do
        [[ "$base" == "${p}"* ]] && return 0
    done
    # no excluded prefix matched
    return 1
}

is_excluded_basename() {
    local base="$1"
    in_array "$base" "${EXCLUDE_BASENAMES[@]}"
}

# Map Fortran routine name to MPLAPACK-style C++ name
# d*/s* -> R*, z*/c* -> C*
make_cpp_name_from_prefix() {
    local base="$1"
    local first="${base:0:1}"
    local rest="${base:1}"
    case "$first" in
        d|s) echo "R${rest}" ;;
        z|c) echo "C${rest}" ;;
        a|A) echo "A${rest}" ;;
        *)   echo "${base}"  ;;
    esac
}

# Write a name map to the given output file.
# Args:
#   $1: output path
#   $2: name of the manual mapping array variable
#   $3: name of the file list array variable
write_map() {
    local out="$1"
    local manual_name="$2"
    local files_name="$3"

    # Namerefs (bash 4.3+). The script already requires bash 4+ due to associative arrays.
    local -n manual="$manual_name"
    local -n files="$files_name"

    : > "$out"

    # Avoid duplicates for the same basename within THIS map.
    local -A seen=()

    local entry src dst
    for entry in "${manual[@]}"; do
        set -- $entry
        src="$1"
        dst="$2"
        printf "%-16s %s\n" "$src" "$dst" >> "$out"
        seen["$src"]=1
    done

    local f base cpp_name
    for f in "${files[@]}"; do
        base="${f##*/}"
        base="${base%.*}"  # strip extension (.f/.F/.f90/.F90)

        # Skip if already handled by manual mappings or earlier occurrences
        if [[ -n "${seen["$base"]+x}" ]]; then
            continue
        fi

        # Skip by excluded prefixes
        if has_excluded_prefix "$base"; then
            continue
        fi

        # Skip by excluded basenames
        if is_excluded_basename "$base"; then
            continue
        fi

        # Default mapping rule
        cpp_name="$(make_cpp_name_from_prefix "$base")"
        printf "%-16s %s\n" "$base" "$cpp_name" >> "$out"
        seen["$base"]=1
    done
}

# ------------------------------------------------------------
# Main
# ------------------------------------------------------------

core_files=()
testing_files=()

# If arguments are provided, split them into core vs testing by path pattern.
# If a basename-only is provided, it will be treated as core by default.
if [[ "$#" -gt 0 ]]; then
    for p in "$@"; do
        if [[ "$p" == *"/TESTING/EIG/"* || "$p" == *"/TESTING/LIN/"* || "$p" == *"/TESTING/MATGEN/"* ]]; then
            testing_files+=("$p")
        else
            core_files+=("$p")
        fi
    done

    if ((${#core_files[@]})); then
        mapfile -t core_files < <(printf '%s\n' "${core_files[@]}" | sort)
    fi
    if ((${#testing_files[@]})); then
        mapfile -t testing_files < <(printf '%s\n' "${testing_files[@]}" | sort)
    fi
else
    # Enumerate sources (keep core/testing separate; do NOT generate a superset testing map).
    mapfile -t core_files < <(
        {
            find "$blas_src"   -maxdepth 1 -type f \( -name '*.f' -o -name '*.F' -o -name '*.f90' -o -name '*.F90' \)
            find "$lapack_src" -maxdepth 1 -type f \( -name '*.f' -o -name '*.F' -o -name '*.f90' -o -name '*.F90' \)
        } | sort
    )

    mapfile -t testing_files < <(
        {
            find "$eig_src"    -maxdepth 1 -type f \( -name '*.f' -o -name '*.F' -o -name '*.f90' -o -name '*.F90' \)
            find "$lin_src"    -maxdepth 1 -type f \( -name '*.f' -o -name '*.F' -o -name '*.f90' -o -name '*.F90' \)
            find "$matgen_src" -maxdepth 1 -type f \( -name '*.f' -o -name '*.F' -o -name '*.f90' -o -name '*.F90' \)
        } | sort
    )
fi

write_map "$out_core"    MANUAL_MAPPINGS_CORE    core_files
write_map "$out_testing" MANUAL_MAPPINGS_TESTING testing_files

echo "Wrote: $out_core" >&2
echo "Wrote: $out_testing" >&2

