#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

REF_DIR="${ROOT}/mplapack/reference"
FIX_IMLAENV="${SCRIPT_DIR}/fix_iMlaenv.py"
PATCH_DIR="${SCRIPT_DIR}/3.12.1/lapack"

cd "${REF_DIR}"

echo "Post-processing mplapack/reference/iMlaenv.cpp with fix_iMlaenv.py"
python3 "${FIX_IMLAENV}" iMlaenv.cpp
python3 "${FIX_IMLAENV}" iMparmq.cpp

#https://claude.ai/chat/f3c3ff73-215d-44ed-9dae-8e75808e06d9
#https://chatgpt.com/c/69929fe4-b980-83a7-8fd7-0988abca4785
patch -p3 < "${PATCH_DIR}/patch-Cgejsv.cpp"
patch -p3 < "${PATCH_DIR}/patch-Cgesvj.cpp"
patch -p3 < "${PATCH_DIR}/patch-Rgejsv.cpp"
patch -p3 < "${PATCH_DIR}/patch-Rgesvj.cpp"
patch -p3 < "${PATCH_DIR}/patch-Ctrsyl3.cpp"
patch -p3 < "${PATCH_DIR}/patch-Rtrsyl3.cpp"
patch -p3 < "${PATCH_DIR}/patch-Rlaqz2.cpp"
patch -p3 < "${PATCH_DIR}/patch-Cbbcsd.cpp"
patch -p3 < "${PATCH_DIR}/patch-Cgttrs.cpp"
patch -p3 < "${PATCH_DIR}/patch-Cheequb.cpp"
patch -p3 < "${PATCH_DIR}/patch-Clargv.cpp"
patch -p3 < "${PATCH_DIR}/patch-Clartg.cpp"
patch -p3 < "${PATCH_DIR}/patch-Clahef_aa.cpp"
patch -p3 < "${PATCH_DIR}/patch-Claic1.cpp"
patch -p3 < "${PATCH_DIR}/patch-Clarnv.cpp"
patch -p3 < "${PATCH_DIR}/patch-Clasyf_aa.cpp"
patch -p3 < "${PATCH_DIR}/patch-Classq.cpp"
patch -p3 < "${PATCH_DIR}/patch-Rlassq.cpp"
patch -p3 < "${PATCH_DIR}/patch-Clatbs.cpp"
patch -p3 < "${PATCH_DIR}/patch-Clatps.cpp"
patch -p3 < "${PATCH_DIR}/patch-Clatrs.cpp"
patch -p3 < "${PATCH_DIR}/patch-Csyequb.cpp"
patch -p3 < "${PATCH_DIR}/patch-Ctfttp.cpp"
patch -p3 < "${PATCH_DIR}/patch-Ctpttf.cpp"
patch -p3 < "${PATCH_DIR}/patch-Ctrexc.cpp"
patch -p3 < "${PATCH_DIR}/patch-Ctrsyl.cpp"
patch -p3 < "${PATCH_DIR}/patch-Cunbdb.cpp"
patch -p3 < "${PATCH_DIR}/patch-Rbbcsd.cpp"
patch -p3 < "${PATCH_DIR}/patch-Rbdsvdx.cpp"
patch -p3 < "${PATCH_DIR}/patch-Rladiv.cpp"
patch -p3 < "${PATCH_DIR}/patch-Rlaln2.cpp"
patch -p3 < "${PATCH_DIR}/patch-Rlarnv.cpp"
patch -p3 < "${PATCH_DIR}/patch-Rlarrb.cpp"
patch -p3 < "${PATCH_DIR}/patch-Rlarrd.cpp"
patch -p3 < "${PATCH_DIR}/patch-Rlarrk.cpp"
patch -p3 < "${PATCH_DIR}/patch-Rlartg.cpp"
patch -p3 < "${PATCH_DIR}/patch-Rorbdb.cpp"
patch -p3 < "${PATCH_DIR}/patch-Rstebz.cpp"
patch -p3 < "${PATCH_DIR}/patch-Rsyequb.cpp"
patch -p3 < "${PATCH_DIR}/patch-Rtfttp.cpp"
patch -p3 < "${PATCH_DIR}/patch-Rtpttf.cpp"
patch -p3 < "${PATCH_DIR}/patch-iMieeeck.cpp"
patch -p3 < "${PATCH_DIR}/patch-iMlaenv.cpp"
patch -p3 < "${PATCH_DIR}/patch-iMparam2stage.cpp"
patch -p3 < "${PATCH_DIR}/patch-iMparmq.cpp"
patch -p3 < "${PATCH_DIR}/patch-Cunbdb3.cpp"
patch -p3 < "${PATCH_DIR}/patch-Rorbdb3.cpp"
