#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

REF_DIR="${ROOT}/mplapack/test"
PATCH_DIR="${SCRIPT_DIR}/3.12.1/lapack"

cd "${REF_DIR}/matgen"

patch  < "${PATCH_DIR}/patch-Clarnd.cpp"
patch  < "${PATCH_DIR}/patch-Claror.cpp"
patch  < "${PATCH_DIR}/patch-Clatm5.cpp"
patch  < "${PATCH_DIR}/patch-Clatms.cpp"
patch  < "${PATCH_DIR}/patch-Clatmt.cpp"
patch  < "${PATCH_DIR}/patch-Rlarnd.cpp"
patch  < "${PATCH_DIR}/patch-Rlaror.cpp"
patch  < "${PATCH_DIR}/patch-Rlatms.cpp"
patch  < "${PATCH_DIR}/patch-Rlatmt.cpp"

cd "${REF_DIR}/lin/common"
patch  < "${PATCH_DIR}/patch-Cchkaa.cpp"
patch  < "${PATCH_DIR}/patch-Cchkeq.cpp"
patch  < "${PATCH_DIR}/patch-Cchkrfp.cpp"
patch  < "${PATCH_DIR}/patch-Cerrlqt.cpp"
patch  < "${PATCH_DIR}/patch-Cerrlqtp.cpp"
patch  < "${PATCH_DIR}/patch-Cerrqrt.cpp"
patch  < "${PATCH_DIR}/patch-Cerrqrtp.cpp"
patch  < "${PATCH_DIR}/patch-Clatb4.cpp"
patch  < "${PATCH_DIR}/patch-Clatb5.cpp"
patch  < "${PATCH_DIR}/patch-Clatsp.cpp"
patch  < "${PATCH_DIR}/patch-Clatsy.cpp"
patch  < "${PATCH_DIR}/patch-Clattp.cpp"
patch  < "${PATCH_DIR}/patch-Clattr.cpp"
patch  < "${PATCH_DIR}/patch-Clqt04.cpp"
patch  < "${PATCH_DIR}/patch-Clqt05.cpp"
patch  < "${PATCH_DIR}/patch-Cdrvrf3.cpp"
patch  < "${PATCH_DIR}/patch-Cqrt04.cpp"
patch  < "${PATCH_DIR}/patch-Cqrt05.cpp"
patch  < "${PATCH_DIR}/patch-Cqrt13.cpp"
patch  < "${PATCH_DIR}/patch-Cqrt15.cpp"
patch  < "${PATCH_DIR}/patch-Ctsqr01.cpp"
patch  < "${PATCH_DIR}/patch-Cunhr_col01.cpp"
patch  < "${PATCH_DIR}/patch-Cunhr_col02.cpp"
patch  < "${PATCH_DIR}/patch-Rchkaa.cpp"
patch  < "${PATCH_DIR}/patch-Rchkeq.cpp"
patch  < "${PATCH_DIR}/patch-Rchkrfp.cpp"
patch  < "${PATCH_DIR}/patch-Rdrvrf3.cpp"
patch  < "${PATCH_DIR}/patch-Rlatb4.cpp"
patch  < "${PATCH_DIR}/patch-Rlatb5.cpp"
patch  < "${PATCH_DIR}/patch-Rlattr.cpp"
patch  < "${PATCH_DIR}/patch-Rorhr_col01.cpp"
patch  < "${PATCH_DIR}/patch-Rorhr_col02.cpp"
patch  < "${PATCH_DIR}/patch-Rtsqr01.cpp"

cd "${REF_DIR}/lin"
patch  < "${PATCH_DIR}/patch-Ctest.in"
patch  < "${PATCH_DIR}/patch-Rtest.in"

cd "${REF_DIR}/eig/common"
patch  < "${PATCH_DIR}/patch-Cchkbd.cpp"
patch  < "${PATCH_DIR}/patch-Cchkdmd.cpp"
patch  < "${PATCH_DIR}/patch-Cchkee.cpp"
patch  < "${PATCH_DIR}/patch-Cchkgg.cpp"
patch  < "${PATCH_DIR}/patch-Ccsdts.cpp"
patch  < "${PATCH_DIR}/patch-Cdrgsx.cpp"
patch  < "${PATCH_DIR}/patch-Cdrves.cpp"
patch  < "${PATCH_DIR}/patch-Cget24.cpp"
patch  < "${PATCH_DIR}/patch-Clctsx.cpp"
patch  < "${PATCH_DIR}/patch-Cslect.cpp"
patch  < "${PATCH_DIR}/patch-Rchkbd.cpp"
patch  < "${PATCH_DIR}/patch-Rchkdmd.cpp"
patch  < "${PATCH_DIR}/patch-Rchkee.cpp"
patch  < "${PATCH_DIR}/patch-Rchkgg.cpp"
patch  < "${PATCH_DIR}/patch-Rckcsd.cpp"
patch  < "${PATCH_DIR}/patch-Rcsdts.cpp"
patch  < "${PATCH_DIR}/patch-Rdrgsx.cpp"
patch  < "${PATCH_DIR}/patch-Rdrves.cpp"
#patch  < "${PATCH_DIR}/patch-Cdrvsg.cpp"
#patch  < "${PATCH_DIR}/patch-Rdrvsg.cpp"
patch  < "${PATCH_DIR}/patch-Rget24.cpp"
patch  < "${PATCH_DIR}/patch-Rget38.cpp"
patch  < "${PATCH_DIR}/patch-Rget34.cpp"
patch  < "${PATCH_DIR}/patch-Rlatb9.cpp"
patch  < "${PATCH_DIR}/patch-Rlctsx.cpp"
patch  < "${PATCH_DIR}/patch-Rslect.cpp"
patch  < "${PATCH_DIR}/patch-Rdrgvx.cpp"
patch  < "${PATCH_DIR}/patch-Cdrgvx.cpp"

cd "${REF_DIR}/eig"
patch < "${PATCH_DIR}/patch-Rgg.in"
patch < "${PATCH_DIR}/patch-csd.in"
patch < "${PATCH_DIR}/patch-gsv.in"
patch < "${PATCH_DIR}/patch-nep.in"
patch < "${PATCH_DIR}/patch-se2.in"
patch < "${PATCH_DIR}/patch-sep.in"
