#!/usr/bin/env python3
"""
Strip LAPACK boilerplate header comments from C++ / header files
generated by cout.py.

We remove at most one contiguous *comment* block per file.

Comment block definition (in the space of comment lines only):

- Start of the block: the first comment whose text satisfies ANY of:
    * contains "\\brief"            (newer LAPACK, doxygen-style)
    * contains "-- LAPACK"         (auxiliary / computational / driver)
    * contains "=========== DOCUMENTATION"
    * is exactly ".. Scalar Arguments .." (older LAPACK without \\brief)

- End of the block:
    * the first comment whose text is exactly
      ".. Executable Statements .." (case-insensitive)

Only comment lines between those two comment indices (inclusive)
are removed. Code lines (declarations, externals, etc.) are never
touched.

Additionally, any comment line whose text (after cout.py unwrapping)
starts with "> \\brief" is always removed, even if it is not part of
the main header block. This cleans up trailing brief lists such as:

    // > \brief \b Cgebal
    // > \brief \b Cgejsv
"""

import sys
from pathlib import Path
from typing import List, Optional, Set


def is_comment_line(line: str) -> bool:
    """Return True if the line is a C++ comment starting with '//'."""
    return line.lstrip().startswith("//")


def extract_comment_text(line: str) -> Optional[str]:
    """
    Extract logical comment content from a cout.py-generated comment line.

    Examples:
        //C*> \brief foo
            -> "*> \brief foo"

        //C     .. Executable Statements ..
            -> ".. Executable Statements .."

        // something else
            -> "something else"
    """
    stripped = line.lstrip()
    if not stripped.startswith("//"):
        return None

    # Drop leading //
    text = stripped[2:].lstrip()

    # cout.py marks original Fortran comments as //C...
    if text.startswith("C"):
        if len(text) == 1 or text[1].isspace():
            text = text[1:].lstrip()

    return text.rstrip("\r\n")


def compute_header_comment_src_indices(lines: List[str]) -> Set[int]:
    """
    Return a set of *source line indices* that belong to the LAPACK header
    comment block and/or trailing \\brief-list comments and should be removed.

    We work entirely in "comment index space" for the header block and
    map back to source indices, so we never delete code lines by accident.
    """
    comment_indices: List[int] = []
    comment_texts: List[str] = []

    for idx, line in enumerate(lines):
        if not is_comment_line(line):
            continue
        text = extract_comment_text(line)
        if text is None:
            text = ""
        comment_indices.append(idx)
        comment_texts.append(text)

    skip_src_indices: Set[int] = set()

    if comment_indices:
        # 1) Find header block start in comment-text space.
        start_ci: Optional[int] = None
        for ci, text in enumerate(comment_texts):
            t = text
            lower = t.lower()

            if "\\brief" in t:
                start_ci = ci
                break
            if "-- lapack" in lower:
                start_ci = ci
                break
            if "=========== documentation" in lower:
                start_ci = ci
                break
            if t.strip().lower() == ".. scalar arguments ..":
                start_ci = ci
                break

        # 2) Find header block end in comment-text space.
        if start_ci is not None:
            end_ci: Optional[int] = None
            for ci in range(start_ci, len(comment_texts)):
                t = comment_texts[ci]
                if t.strip().lower() == ".. executable statements ..":
                    end_ci = ci
                    break

            if end_ci is not None:
                # 3) Extend start_ci backwards over trivial padding comments
                #    (blank or "..") that immediately precede the header.
                s = start_ci
                while s - 1 >= 0:
                    prev_text = comment_texts[s - 1]
                    if prev_text.strip() in ("", ".."):
                        s -= 1
                    else:
                        break

                # 4) Map header comment indices back to source line indices.
                for ci in range(s, end_ci + 1):
                    src_idx = comment_indices[ci]
                    skip_src_indices.add(src_idx)

        # 5) Independently remove any trailing "> \\brief" comment lines.
        for ci, text in enumerate(comment_texts):
            t = text.lstrip()
            if t.startswith("> \\brief"):
                src_idx = comment_indices[ci]
                skip_src_indices.add(src_idx)

    return skip_src_indices


def strip_lapack_header_block(path: Path) -> None:
    """Remove the LAPACK header *comment* block from a single file, if present."""
    try:
        src = path.read_text(encoding="utf-8", errors="ignore")
    except OSError as e:
        print(f"strip_lapack_header: failed to read {path}: {e}", file=sys.stderr)
        return

    lines = src.splitlines(keepends=True)

    skip_src_indices = compute_header_comment_src_indices(lines)
    if not skip_src_indices:
        # No header or \\brief comments detected; leave file unchanged.
        return

    new_lines = [
        line for idx, line in enumerate(lines)
        if idx not in skip_src_indices
    ]

    try:
        path.write_text("".join(new_lines), encoding="utf-8")
    except OSError as e:
        print(f"strip_lapack_header: failed to write {path}: {e}", file=sys.stderr)


def main(argv: List[str]) -> None:
    if len(argv) < 2:
        print("Usage: strip_boilerplate_comments.py FILE [FILE...]", file=sys.stderr)
        sys.exit(1)

    for arg in argv[1:]:
        p = Path(arg)
        if not p.is_file():
            print(f"strip_lapack_header: {p} is not a file, skipping", file=sys.stderr)
            continue
        strip_lapack_header_block(p)


if __name__ == "__main__":
    main(sys.argv)
