#!/usr/bin/env python3
r"""
Strip netlib LAPACK boilerplate comments from C++ / header files
generated by cout.py.

We remove only comment lines, never code lines. Targets:

  (1) Netlib documentation blocks (Definition/Arguments/Authors etc.)
  (2) In-body LAPACK header blocks (-- LAPACK ..., .. Scalar Arguments ..)
  (3) Doxygen-style comments starting with "> " (\brief, \param, etc.)
  (4) Useless empty "//" directly between #include and a function definition.
"""

import sys
from pathlib import Path
from typing import List, Optional, Set, Tuple


def normalize_fmt_hdr_lines(lines: List[str]) -> List[str]:
    """Normalize cout.py FORMAT-heading tags.

    cout.py may emit FORMAT-heading comments as:
        //FMT_HDR
        //FMT_HDR      GE matrix types
    This function removes only the tag prefix and keeps the comment content as
    ordinary C++ comments:
        //
        //      GE matrix types
    """
    out: List[str] = []
    for line in lines:
        stripped = line.lstrip()
        if stripped.startswith("//FMT_HDR"):
            # Preserve indentation before '//' exactly as-is.
            prefix_len = len(line) - len(stripped)
            indent = line[:prefix_len]
            rest = stripped[len("//FMT_HDR"):]  # keep remainder including spaces and newline
            # If there is no remainder except newline/whitespace, emit empty comment.
            if rest.strip() == "":
                # Keep original line ending if present.
                newline = "\n" if line.endswith("\n") else ""
                out.append(f"{indent}//{newline}")
            else:
                # If remainder doesn't start with space, add one for readability.
                if not rest.startswith((" ", "\t")):
                    rest = " " + rest
                out.append(f"{indent}//{rest}")
        else:
            out.append(line)
    return out



def is_comment_line(line: str) -> bool:
    """Return True if the line is a C++ comment starting with '//'."""
    return line.lstrip().startswith("//")


def compute_lapack_header_blocks(lines):
    """
    Remove LAPACK/BLAS boilerplate header blocks, while preserving
    ordinary in-function comments (e.g., "Set NROWA as the number of rows of A.")
    that must NOT be deleted.

    This function identifies LAPACK/BLAS header markers and removes the
    surrounding contiguous comment block, but stops if a comment appears
    to be normal code documentation rather than boilerplate.
    """

    n = len(lines)
    skip = set()
    i = 0

    # Comments starting with these keywords are considered normal code comments
    # and must never be removed.
    SAFE_PHRASES = [
        "set",            # Set NROWA as the number of rows of A.
        "compute",        # Compute workspace size...
        "check",          # Check input arguments...
        "test",           # Test the input arguments...
        "quick return",   # Quick return if ...
    ]

    def is_safe_comment(text: str) -> bool:
        """Return True if this comment must be preserved."""
        lower = text.lower().strip()
        if not lower:
            return False
        return any(lower.startswith(word) for word in SAFE_PHRASES)

    def is_header_start(text: str) -> bool:
        """Detect LAPACK/BLAS boilerplate header markers."""
        lower = text.lower()
        return (
            "-- lapack auxiliary routine" in lower or
            "-- lapack computational routine" in lower or
            "lapack is a software package provided by" in lower or
            "reference blas" in lower or
            "blas is a software package provided by" in lower
        )

    while i < n:
        line = lines[i]
        if not is_comment_line(line):
            i += 1
            continue

        text = extract_comment_text(line) or ""
        stripped = text.strip()

        # Do not remove comments that are part of normal code documentation.
        if is_safe_comment(stripped):
            i += 1
            continue

        # Detect boilerplate header block start.
        if is_header_start(text):

            # Remove preceding empty comment lines (visual spacers).
            k = i - 1
            while k >= 0 and is_comment_line(lines[k]):
                prev = extract_comment_text(lines[k]) or ""
                if prev.strip() != "":
                    break
                skip.add(k)
                k -= 1

            # Remove the contiguous comment block,
            # but stop if we encounter a SAFE comment.
            j = i
            end = None
            while j < n and is_comment_line(lines[j]):
                t = extract_comment_text(lines[j]) or ""

                if is_safe_comment(t):
                    # Normal documentation comment → do NOT delete it
                    break

                skip.add(j)

                if t.strip().lower() == ".. executable statements ..":
                    end = j
                    break

                j += 1

            # Move to end of block
            if end is None:
                i = j
            else:
                i = end + 1

            continue

        i += 1

    return skip


def protect_test_comments(lines, skip_indices):
    """
    Ensure that comments like
        // Test the input parameters
        // Test the input arguments
    are never deleted, and keep their surrounding empty '//' spacers.
    """
    protected_phrases = [
        "test the input parameters",
        "test the input arguments",
    ]
    n = len(lines)

    for idx, line in enumerate(lines):
        if not is_comment_line(line):
            continue
        text = (extract_comment_text(line) or "").lower()
        if any(phrase in text for phrase in protected_phrases):
            # Never delete this line
            skip_indices.discard(idx)

            # Also keep preceding empty '//' spacer, if any
            if idx - 1 >= 0 and is_comment_line(lines[idx - 1]):
                prev_text = (extract_comment_text(
                    lines[idx - 1]) or "").strip()
                if prev_text == "":
                    skip_indices.discard(idx - 1)

            # And following empty '//' spacer, if any
            if idx + 1 < n and is_comment_line(lines[idx + 1]):
                next_text = (extract_comment_text(
                    lines[idx + 1]) or "").strip()
                if next_text == "":
                    skip_indices.discard(idx + 1)


def protect_set_comments(lines, skip_indices):
    """
    If a comment line begins with 'Set', also preserve the immediately
    preceding empty '//' comment line (if any).

    Example:
        //
        // Set NROWA as the number of rows of A.
    The leading '//' should not be removed.
    """

    n = len(lines)

    for idx, line in enumerate(lines):
        if not is_comment_line(line):
            continue

        text = extract_comment_text(line) or ""
        lower = text.lower().strip()

        # Detect "Set ..." comment lines
        if lower.startswith("set "):
            # Protect this line
            skip_indices.discard(idx)

            # Protect preceding empty comment line (if any)
            if idx - 1 >= 0 and is_comment_line(lines[idx - 1]):
                prev_text = extract_comment_text(lines[idx - 1]) or ""
                if prev_text.strip() == "":
                    skip_indices.discard(idx - 1)


def extract_comment_text(line: str) -> Optional[str]:
    """
    Extract logical comment content from a cout.py-generated comment line.

    Examples:
        //C*> \brief foo
            -> "*> \brief foo"

        //C     .. Executable Statements ..
            -> ".. Executable Statements .."

        // something else
            -> "something else"
    """
    stripped = line.lstrip()
    if not stripped.startswith("//"):
        return None

    # Drop leading //
    text = stripped[2:].lstrip()

    # cout.py marks original Fortran comments as //C...
    if text.startswith("C"):
        if len(text) == 1 or text[1].isspace():
            text = text[1:].lstrip()

    return text.rstrip("\r\n")


# ---------------------------------------------------------------------
#  (1) Netlib documentation blocks (anywhere in the file)
# ---------------------------------------------------------------------


DOC_MARKERS = [
    "=========== documentation",
    "online html documentation available at",
    "definition:",
    "arguments:",
    "authors:",
]


def compute_doc_block_indices(lines: List[str]) -> Set[int]:
    """
    Find documentation-style comment blocks and return their source indices.

    For each comment line whose text contains one of DOC_MARKERS, we remove
    the whole contiguous run of comment lines containing it (extend up/down
    over comment-only lines).
    """
    n = len(lines)
    skip: Set[int] = set()

    for idx, line in enumerate(lines):
        if not is_comment_line(line):
            continue
        text = extract_comment_text(line) or ""
        lower = text.lower()
        if not any(mark in lower for mark in DOC_MARKERS):
            continue

        # Extend upwards over contiguous comment lines.
        start = idx
        while start > 0 and is_comment_line(lines[start - 1]):
            start -= 1

        # Extend downwards over contiguous comment lines.
        end = idx
        while end + 1 < n and is_comment_line(lines[end + 1]):
            end += 1

        for j in range(start, end + 1):
            skip.add(j)

    return skip


# ---------------------------------------------------------------------
#  (2) In-body LAPACK header blocks
# ---------------------------------------------------------------------


HEADER_START_MARKERS = [
    "-- lapack",              # "-- LAPACK computational routine --" etc.
]

SECTION_START_MARKERS = [
    ".. scalar arguments ..",
    ".. array arguments ..",
    ".. parameters ..",
    ".. local scalars ..",
    ".. external functions ..",
    ".. local arrays ..",
    ".. external subroutines ..",
    ".. intrinsic functions ..",
]


def compute_inbody_header_indices(lines: List[str]) -> Set[int]:
    """
    Detect and remove in-body LAPACK header blocks, but preserve
    normal code comments such as:
        // Set NROWA as the number of rows of A.
        // Check arguments...
        // Quick return...
    """

    # Normal comments that must never be deleted
    SAFE_PREFIXES = [
        "set",
        "compute",
        "check",
        "test",
        "quick return",
    ]

    def is_safe_comment(text: str) -> bool:
        t = text.lower().strip()
        if not t:
            return False
        return any(t.startswith(pref) for pref in SAFE_PREFIXES)

    # Collect all comment lines
    comment_indices = []
    comment_texts = []
    for idx, line in enumerate(lines):
        if is_comment_line(line):
            t = extract_comment_text(line) or ""
            comment_indices.append(idx)
            comment_texts.append(t)

    if not comment_indices:
        return set()

    nci = len(comment_indices)

    # Find start of LAPACK header
    start_ci = None
    for ci, t in enumerate(comment_texts):
        lower = t.lower().strip()

        # Skip documentation blocks (handled elsewhere)
        if any(mark in lower for mark in DOC_MARKERS):
            continue

        # LAPACK header markers
        if "-- lapack" in lower or lower in SECTION_START_MARKERS:
            start_ci = ci
            break

    if start_ci is None:
        return set()

    # Find end of header block
    end_ci = None
    first_test_ci = None

    for ci in range(start_ci, nci):
        t = comment_texts[ci].lower().strip()

        # If we hit a SAFE comment, stop immediately
        if is_safe_comment(t):
            end_ci = ci - 1
            break

        # Proper end marker
        if t == ".. executable statements ..":
            end_ci = ci
            break

        # Fallback marker
        if "test the input parameters" in t or "test the input arguments" in t:
            first_test_ci = ci
            break

    if end_ci is None:
        if first_test_ci is not None:
            end_ci = first_test_ci - 1
        else:
            return set()

    if end_ci < start_ci:
        return set()

    # Mark lines to skip
    skip = set()
    for ci in range(start_ci, end_ci + 1):
        idx = comment_indices[ci]
        skip.add(idx)

    return skip


# ---------------------------------------------------------------------
#  (3) Doxygen "> ..." comments
# ---------------------------------------------------------------------


def compute_doxygen_indices(lines: List[str]) -> Set[int]:
    r"""
    Remove any Doxygen-style comment whose text starts with "> ".
    Examples:
        // > \brief \b Cgebal
        // > \param[in] N
    """
    skip: Set[int] = set()

    for idx, line in enumerate(lines):
        if not is_comment_line(line):
            continue
        text = extract_comment_text(line) or ""
        t = text.lstrip()
        # Only treat true Doxygen comments as boilerplate:
        #   > \brief, > \param, > \par, etc.
        if t.startswith("> \\"):
            skip.add(idx)

    return skip


# ---------------------------------------------------------------------
#  (4) Empty "//" between #include and function definition
# ---------------------------------------------------------------------


def compute_orphan_empty_comment_indices(lines: List[str]) -> Set[int]:
    """
    Remove useless empty '//' lines that sit directly between a #include
    and a function definition, e.g.

        #include <mpblas.h>
        #include <mplapack.h>
        //
        void Cgesdd(...)

    but do NOT touch empty '//' inside a function (where the next
    non-blank line is also a comment).
    """
    skip: Set[int] = set()
    n = len(lines)

    def is_empty_comment(idx: int) -> bool:
        if not is_comment_line(lines[idx]):
            return False
        text = extract_comment_text(lines[idx]) or ""
        return text.strip() == ""

    def find_prev_nonblank(i: int) -> Optional[int]:
        j = i - 1
        while j >= 0 and lines[j].strip() == "":
            j -= 1
        return j if j >= 0 else None

    def find_next_nonblank(i: int) -> Optional[int]:
        j = i + 1
        while j < n and lines[j].strip() == "":
            j += 1
        return j if j < n else None

    for idx in range(n):
        if not is_empty_comment(idx):
            continue

        prev_idx = find_prev_nonblank(idx)
        next_idx = find_next_nonblank(idx)

        if prev_idx is None or next_idx is None:
            continue

        prev_line = lines[prev_idx].lstrip()
        next_line = lines[next_idx].lstrip()

        # Only if previous is a preprocessor include and next is a function
        # signature do we consider this an orphan header spacer.
        if prev_line.startswith("#include") and not is_comment_line(next_line):
            # Very simple heuristic for "function definition": line starts
            # with an identifier-like token (void, REAL, COMPLEX, INTEGER, etc.)
            if any(next_line.startswith(prefix) for prefix in (
                "void ", "REAL ", "COMPLEX ", "INTEGER ", "bool ",
                "double ", "float ", "int ",
            )):
                skip.add(idx)

    return skip


def compute_leading_blank_and_comment_indices(lines: List[str]) -> Set[int]:
    """Return indices of leading blank lines and leading '//' comments.

    This matches the previous pipeline step that removed the initial
    blank and '//'-comment prefix emitted by fable/cout before the first
    non-comment, non-blank line.
    """
    skip: Set[int] = set()
    for idx, line in enumerate(lines):
        if line.strip() == "":
            skip.add(idx)
            continue
        if line.lstrip().startswith("//"):
            skip.add(idx)
            continue
        break
    return skip


# ---------------------------------------------------------------------
#  Main
# ---------------------------------------------------------------------


def protect_fmt_hdr_tagged_lines(lines, skip_indices):
    """Never delete cout.py FORMAT-heading tagged comment lines (//FMT_HDR...)."""
    for idx, line in enumerate(lines):
        if line.lstrip().startswith("//FMT_HDR"):
            skip_indices.discard(idx)


def strip_lapack_comments_text(src: str) -> Tuple[str, bool]:
    """Return (output_text, changed) after removing boilerplate comments."""
    lines = src.splitlines(keepends=True)

    to_skip: Set[int] = set()
    to_skip |= compute_leading_blank_and_comment_indices(lines)
    to_skip |= compute_doc_block_indices(lines)
    to_skip |= compute_inbody_header_indices(lines)
    to_skip |= compute_doxygen_indices(lines)
    to_skip |= compute_orphan_empty_comment_indices(lines)
    to_skip |= compute_lapack_header_blocks(lines)
    # Intentionally run twice: after big-block removal, new include/function
    # adjacencies can appear.
    to_skip |= compute_orphan_empty_comment_indices(lines)

    protect_set_comments(lines, to_skip)
    protect_test_comments(lines, to_skip)
    protect_fmt_hdr_tagged_lines(lines, to_skip)

    if not to_skip:
        return src, False

    out_lines = [line for idx, line in enumerate(lines) if idx not in to_skip]
    out_lines = normalize_fmt_hdr_lines(out_lines)
    out = "".join(out_lines)
    return out, (out != src)


def strip_lapack_comments_inplace(path: Path) -> bool:
    """Edit a file in-place. Returns True if the file changed."""
    try:
        src = path.read_text(encoding="utf-8", errors="ignore")
    except OSError as e:
        print(
            f"strip_lapack_comments: failed to read {path}: {e}", file=sys.stderr)
        return False

    out, changed = strip_lapack_comments_text(src)
    if not changed:
        return False

    try:
        path.write_text(out, encoding="utf-8")
    except OSError as e:
        print(
            f"strip_lapack_comments: failed to write {path}: {e}", file=sys.stderr)
        return False

    return True


def _print_usage(prog: str) -> None:
    print(
        f"Usage: {prog} [--inplace|-i] FILE [FILE...]",
        file=sys.stderr,
    )
    print(
        f"  Default (stdout): {prog} FILE > OUT",
        file=sys.stderr,
    )
    print(
        f"  In-place:         {prog} --inplace FILE [FILE...]",
        file=sys.stderr,
    )


def main(argv: List[str]) -> None:
    # Modes:
    #   (default) stdout: print processed content; if no change, print original.
    #   --inplace: edit files in-place, print nothing.
    inplace = False
    args: List[str] = []

    it = iter(argv[1:])
    for a in it:
        if a in ("--inplace", "-i"):
            inplace = True
        elif a in ("--help", "-h"):
            _print_usage(argv[0])
            return
        elif a == "--":
            args.extend(list(it))
            break
        else:
            args.append(a)

    if not args:
        _print_usage(argv[0])
        sys.exit(1)

    if not inplace and len(args) != 1:
        print(
            "strip_lapack_comments: stdout mode supports exactly one FILE. "
            "Use --inplace for multiple files.",
            file=sys.stderr,
        )
        sys.exit(2)

    if inplace:
        for arg in args:
            p = Path(arg)
            if not p.is_file():
                print(f"strip_lapack_comments: {p} is not a file, skipping",
                      file=sys.stderr)
                continue
            strip_lapack_comments_inplace(p)
        return

    # stdout mode
    p = Path(args[0])
    if not p.is_file():
        print(f"strip_lapack_comments: {p} is not a file", file=sys.stderr)
        sys.exit(3)

    try:
        src = p.read_text(encoding="utf-8", errors="ignore")
    except OSError as e:
        print(
            f"strip_lapack_comments: failed to read {p}: {e}", file=sys.stderr)
        sys.exit(4)

    out, _changed = strip_lapack_comments_text(src)
    sys.stdout.write(out)


if __name__ == "__main__":
    main(sys.argv)
