#!/usr/bin/env python3
"""
Strip netlib LAPACK boilerplate comments from C++ / header files
generated by cout.py.

We remove only comment lines, never code lines. Targets:

  (1) Netlib documentation blocks (Definition/Arguments/Authors etc.)
  (2) In-body LAPACK header blocks (-- LAPACK ..., .. Scalar Arguments ..)
  (3) Doxygen-style comments starting with "> " (\brief, \param, etc.)
  (4) Useless empty "//" directly between #include and a function definition.
"""

import sys
from pathlib import Path
from typing import List, Optional, Set


def is_comment_line(line: str) -> bool:
    """Return True if the line is a C++ comment starting with '//'."""
    return line.lstrip().startswith("//")

def compute_lapack_header_blocks(lines):
    """
    Find LAPACK header comment blocks anywhere in the file and return
    the set of source indices to skip.

    Header block pattern (in source line space):

        // -- LAPACK auxiliary routine --
        // -- LAPACK computational routine --
        // LAPACK is a software package provided by ...
        // .. Scalar Arguments ..
        // ..
        ...
        // .. Executable Statements ..

    We remove all contiguous comment lines from the first header marker
    down to the ".. Executable Statements .." line (inclusive).
    """
    n = len(lines)
    skip = set()
    i = 0

    while i < n:
        line = lines[i]
        if not is_comment_line(line):
            i += 1
            continue

        text = extract_comment_text(line) or ""
        lower = text.lower()

        # header start?
        if ("-- lapack auxiliary routine" in lower or
            "-- lapack computational routine" in lower or
            "lapack is a software package provided by" in lower):

            # Walk forward within this contiguous comment block
            j = i
            end = None
            while j < n and is_comment_line(lines[j]):
                skip.add(j)
                t = extract_comment_text(lines[j]) or ""
                if t.strip().lower() == ".. executable statements ..":
                    end = j
                    break
                j += 1

            # If we did not see ".. Executable Statements ..", just
            # keep what we marked so far and continue.
            if end is None:
                i = j
            else:
                i = end + 1
            continue

        i += 1

    return skip


def protect_test_comments(lines, skip_indices):
    """
    Ensure that comments like
        // Test the input parameters
        // Test the input arguments
    are never deleted, and keep their surrounding empty '//' spacers.
    """
    protected_phrases = [
        "test the input parameters",
        "test the input arguments",
    ]
    n = len(lines)

    for idx, line in enumerate(lines):
        if not is_comment_line(line):
            continue
        text = (extract_comment_text(line) or "").lower()
        if any(phrase in text for phrase in protected_phrases):
            # Never delete this line
            skip_indices.discard(idx)

            # Also keep preceding empty '//' spacer, if any
            if idx - 1 >= 0 and is_comment_line(lines[idx - 1]):
                prev_text = (extract_comment_text(lines[idx - 1]) or "").strip()
                if prev_text == "":
                    skip_indices.discard(idx - 1)

            # And following empty '//' spacer, if any
            if idx + 1 < n and is_comment_line(lines[idx + 1]):
                next_text = (extract_comment_text(lines[idx + 1]) or "").strip()
                if next_text == "":
                    skip_indices.discard(idx + 1)

def extract_comment_text(line: str) -> Optional[str]:
    """
    Extract logical comment content from a cout.py-generated comment line.

    Examples:
        //C*> \brief foo
            -> "*> \brief foo"

        //C     .. Executable Statements ..
            -> ".. Executable Statements .."

        // something else
            -> "something else"
    """
    stripped = line.lstrip()
    if not stripped.startswith("//"):
        return None

    # Drop leading //
    text = stripped[2:].lstrip()

    # cout.py marks original Fortran comments as //C...
    if text.startswith("C"):
        if len(text) == 1 or text[1].isspace():
            text = text[1:].lstrip()

    return text.rstrip("\r\n")


# ---------------------------------------------------------------------
#  (1) Netlib documentation blocks (anywhere in the file)
# ---------------------------------------------------------------------


DOC_MARKERS = [
    "=========== documentation",
    "online html documentation available at",
    "definition:",
    "arguments:",
    "authors:",
]


def compute_doc_block_indices(lines: List[str]) -> Set[int]:
    """
    Find documentation-style comment blocks and return their source indices.

    For each comment line whose text contains one of DOC_MARKERS, we remove
    the whole contiguous run of comment lines containing it (extend up/down
    over comment-only lines).
    """
    n = len(lines)
    skip: Set[int] = set()

    for idx, line in enumerate(lines):
        if not is_comment_line(line):
            continue
        text = extract_comment_text(line) or ""
        lower = text.lower()
        if not any(mark in lower for mark in DOC_MARKERS):
            continue

        # Extend upwards over contiguous comment lines.
        start = idx
        while start > 0 and is_comment_line(lines[start - 1]):
            start -= 1

        # Extend downwards over contiguous comment lines.
        end = idx
        while end + 1 < n and is_comment_line(lines[end + 1]):
            end += 1

        for j in range(start, end + 1):
            skip.add(j)

    return skip


# ---------------------------------------------------------------------
#  (2) In-body LAPACK header blocks
# ---------------------------------------------------------------------


HEADER_START_MARKERS = [
    "-- lapack",              # "-- LAPACK computational routine --" etc.
]

SECTION_START_MARKERS = [
    ".. scalar arguments ..",
    ".. array arguments ..",
    ".. parameters ..",
    ".. local scalars ..",
    ".. external functions ..",
    ".. local arrays ..",
    ".. external subroutines ..",
    ".. intrinsic functions ..",
]


def compute_inbody_header_indices(lines: List[str]) -> Set[int]:
    """
    Detect LAPACK header blocks inside a routine body and return the
    corresponding source indices of comment lines to remove.

    Header start (in comment-text space):
        - text contains "-- LAPACK"
        - or text matches a SECTION_START_MARKERS entry

    Header end:
        - first comment whose text is exactly ".. Executable Statements .."
          (case-insensitive), OR
        - the comment just before the first "Test the input" comment
          ("Test the input parameters", "Test the input arguments") if
          no Executable Statements marker exists.
    """
    comment_indices: List[int] = []
    comment_texts: List[str] = []

    for idx, line in enumerate(lines):
        if not is_comment_line(line):
            continue
        text = extract_comment_text(line)
        if text is None:
            text = ""
        comment_indices.append(idx)
        comment_texts.append(text)

    if not comment_indices:
        return set()

    # Find first header start.
    start_ci: Optional[int] = None
    for ci, text in enumerate(comment_texts):
        lower = text.lower().strip()
        # Skip comments that are clearly documentation blocks; those are
        # handled separately.
        if any(mark in lower for mark in DOC_MARKERS):
            continue

        if HEADER_START_MARKERS[0] in lower:
            start_ci = ci
            break
        if lower in SECTION_START_MARKERS:
            start_ci = ci
            break

    if start_ci is None:
        return set()

    # Find header end.
    end_ci: Optional[int] = None
    test_comment_ci: Optional[int] = None
    for ci in range(start_ci, len(comment_texts)):
        lower = comment_texts[ci].lower().strip()
        if lower == ".. executable statements ..":
            end_ci = ci
            break
        if "test the input parameters" in lower or "test the input arguments" in lower:
            test_comment_ci = ci
            # Do not break; Executable Statements, if present, is a better end marker.

    if end_ci is None and test_comment_ci is not None:
        end_ci = test_comment_ci - 1  # up to the line before "Test the input"

    if end_ci is None or end_ci < start_ci:
        return set()

    skip: Set[int] = set()
    for ci in range(start_ci, end_ci + 1):
        src_idx = comment_indices[ci]
        skip.add(src_idx)

    return skip


# ---------------------------------------------------------------------
#  (3) Doxygen "> ..." comments
# ---------------------------------------------------------------------


def compute_doxygen_indices(lines: List[str]) -> Set[int]:
    """
    Remove any Doxygen-style comment whose text starts with "> ".
    Examples:
        // > \brief \b Cgebal
        // > \param[in] N
    """
    skip: Set[int] = set()

    for idx, line in enumerate(lines):
        if not is_comment_line(line):
            continue
        text = extract_comment_text(line) or ""
        t = text.lstrip()
        # Only treat true Doxygen comments as boilerplate:
        #   > \brief, > \param, > \par, etc.
        if t.startswith("> \\"):
            skip.add(idx)

    return skip


# ---------------------------------------------------------------------
#  (4) Empty "//" between #include and function definition
# ---------------------------------------------------------------------


def compute_orphan_empty_comment_indices(lines: List[str]) -> Set[int]:
    """
    Remove useless empty '//' lines that sit directly between a #include
    and a function definition, e.g.

        #include <mpblas.h>
        #include <mplapack.h>
        //
        void Cgesdd(...)

    but do NOT touch empty '//' inside a function (where the next
    non-blank line is also a comment).
    """
    skip: Set[int] = set()
    n = len(lines)

    def is_empty_comment(idx: int) -> bool:
        if not is_comment_line(lines[idx]):
            return False
        text = extract_comment_text(lines[idx]) or ""
        return text.strip() == ""

    def find_prev_nonblank(i: int) -> Optional[int]:
        j = i - 1
        while j >= 0 and lines[j].strip() == "":
            j -= 1
        return j if j >= 0 else None

    def find_next_nonblank(i: int) -> Optional[int]:
        j = i + 1
        while j < n and lines[j].strip() == "":
            j += 1
        return j if j < n else None

    for idx in range(n):
        if not is_empty_comment(idx):
            continue

        prev_idx = find_prev_nonblank(idx)
        next_idx = find_next_nonblank(idx)

        if prev_idx is None or next_idx is None:
            continue

        prev_line = lines[prev_idx].lstrip()
        next_line = lines[next_idx].lstrip()

        # Only if previous is a preprocessor include and next is a function
        # signature do we consider this an orphan header spacer.
        if prev_line.startswith("#include") and not is_comment_line(next_line):
            # Very simple heuristic for "function definition": line starts
            # with an identifier-like token (void, REAL, COMPLEX, INTEGER, etc.)
            if any(next_line.startswith(prefix) for prefix in (
                "void ", "REAL ", "COMPLEX ", "INTEGER ", "bool ",
                "double ", "float ", "int ",
            )):
                skip.add(idx)

    return skip


# ---------------------------------------------------------------------
#  Main
# ---------------------------------------------------------------------


def strip_lapack_comments(path: Path) -> None:
    """Remove LAPACK boilerplate comment lines from a single file, if present."""
    try:
        src = path.read_text(encoding="utf-8", errors="ignore")
    except OSError as e:
        print(f"strip_lapack_comments: failed to read {path}: {e}", file=sys.stderr)
        return

    lines = src.splitlines(keepends=True)

    to_skip = set()
    to_skip |= compute_doc_block_indices(lines)
    to_skip |= compute_inbody_header_indices(lines)
    to_skip |= compute_doxygen_indices(lines)
    to_skip |= compute_orphan_empty_comment_indices(lines)
    to_skip |= compute_lapack_header_blocks(lines)
    to_skip |= compute_orphan_empty_comment_indices(lines)

    if not to_skip:
        return

    out_lines = [
        line for idx, line in enumerate(lines)
        if idx not in to_skip
    ]

    try:
        path.write_text("".join(out_lines), encoding="utf-8")
    except OSError as e:
        print(f"strip_lapack_comments: failed to write {path}: {e}", file=sys.stderr)


def main(argv: List[str]) -> None:
    if len(argv) < 2:
        print("Usage: strip_boilerplate_comments.py FILE [FILE...]", file=sys.stderr)
        sys.exit(1)

    for arg in argv[1:]:
        p = Path(arg)
        if not p.is_file():
            print(f"strip_lapack_comments: {p} is not a file, skipping", file=sys.stderr)
            continue
        strip_lapack_comments(p)


if __name__ == "__main__":
    main(sys.argv)
