FROM ubuntu:18.04

LABEL maintainer="maho.nakata@gmail.com"

RUN apt -y update && apt -y upgrade && apt -y dist-upgrade
RUN apt install -y tzdata
ENV TZ Asia/Tokyo
RUN apt install -y python3 sudo expect
RUN apt install -y build-essential gfortran
RUN apt install -y autotools-dev automake libtool pkg-config
RUN apt install -y git wget ccache time unifdef clang-format
RUN apt install -y ng-common ng-cjk emacs-nox

ARG DOCKER_UID=1000
ARG DOCKER_USER=docker
ARG DOCKER_PASSWORD=docker
RUN useradd -u $DOCKER_UID -m $DOCKER_USER --shell /bin/bash && echo "$DOCKER_USER:$DOCKER_PASSWORD" | chpasswd && echo "$DOCKER_USER ALL=(ALL) ALL" >> /etc/sudoers

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1
ARG WORK=/home/$DOCKER_USER

RUN cd ${WORK} && git clone https://github.com/universal-ctags/ctags.git
RUN cd ${WORK} && cd ctags && ./autogen.sh && ./configure --prefix=/usr/local && make && make install

USER docker     
RUN cd ${WORK} && who am i && wget https://raw.githubusercontent.com/cctbx/cctbx_project/master/libtbx/auto_build/bootstrap.py --no-check-certificate
RUN cd ${WORK} && who am i && python bootstrap.py hot update --builder=cctbx
RUN cd ${WORK} && who am i && wget https://repo.anaconda.com/miniconda/Miniconda2-4.5.11-Linux-x86_64.sh && chmod +x ./Miniconda2-4.5.11-Linux-x86_64.sh 
SHELL ["/bin/bash", "-c"]
RUN echo -e "#!/usr/bin/expect -f\n\
spawn ./Miniconda2-4.5.11-Linux-x86_64.sh\n\
set timeout -1\n\
expect \">>>\"\n\
send \"\\\n\"\n\
expect \"More\"\n\
send \"   \"\n\
expect \">>>\"\n\
send \"yes\\\n\"\n\
expect \">>>\"\n\
send \"/home/${DOCKER_USER}/miniconda2\\\n\"\n\
expect \">>>\"\n\
send \"no\\\n\"" >> ${WORK}/answerfile_miniconda
RUN cat ${WORK}/answerfile_miniconda
RUN chown $DOCKER_USER ${WORK}/answerfile_miniconda
RUN cd ${WORK} && chmod +x answerfile_miniconda && ./answerfile_miniconda

RUN cd ${WORK} && source miniconda2/etc/profile.d/conda.sh && conda create -y --name fable36 python=3.6 && conda activate fable36 && conda install six future && mkdir build36 && cd ${WORK}/build36 && python ../modules/cctbx_project/libtbx/configure.py fable
RUN source ${WORK}/build36/setpaths.sh && cd ${WORK}/build36 && make && cd ${WORK} && cd ${WORK}/build36 && make ; cd ${WORK}
RUN cd ${WORK} && echo "source /home/docker/miniconda2/etc/profile.d/conda.sh" >> .bashrc
RUN cd ${WORK} && echo "conda activate fable36" >> .bashrc
RUN cd ${WORK} && echo "source /home/docker/build36/setpaths.sh" >> .bashrc
RUN echo -e "\n\
        PROGRAM HELLO\n\
        PRINT *, 'HELLO, WORLD!'\n\
        END PROGRAM\n\
" >> ${WORK}/sample.f

ARG GIT_EMAIL="maho.nakata@gmail.com"
ARG GIT_NAME="NAKATA Maho"

RUN echo -e "\n\
[user]\n\
        email = ${GIT_EMAIL}\n\
        name = ${GIT_NAME}\n\
" >> /home/$DOCKER_USER/.gitconfig
RUN cd /home/$DOCKER_USER && echo "cd /home/$DOCKER_USER" >> .bashrc
RUN cd /home/$DOCKER_USER && git clone https://github.com/nakatamaho/mplapack.git
RUN cd /home/$DOCKER_USER/mplapack && git checkout v1.0.0
RUN cd /home/$DOCKER_USER/mplapack && git log -1
RUN cd /home/$DOCKER_USER/mplapack && bash -x misc/reconfig.ubuntu18.04.sh
#RUN cd /home/$DOCKER_USER/mplapack && make -j4

