# * How to build (for public users - read-only access)
#  docker build -f Dockerfile_ubuntu24.04_fable -t mplapack:fable .
#
# * How to build (for maintainers with SSH key - read-write access)
# DOCKER_BUILDKIT=1 docker build -f Dockerfile_ubuntu24.04_fable   --build-arg DOCKER_UID="$(id -u)"   --build-arg DOCKER_GID="$(id -g)"   --build-arg USE_SSH=true   --build-arg SSH_KEY_NAME="${SSH_KEY_NAME:-id_ed25519}"   --secret id=ssh_key,src="$HOME/.ssh/${SSH_KEY_NAME:-id_ed25519}"   -t mplapack:fable .
#
# * How to build with custom repository (for users with forks)
# DOCKER_BUILDKIT=1 docker build -f Dockerfile_ubuntu24.04_fable --build-arg DOCKER_UID=$(id -u) --build-arg DOCKER_GID=$(id -g) --build-arg MPLAPACK_REPO=https://github.com/username/mplapack.git -t mplapack:fable .
#
# * How to build with custom repository using SSH
# SSH_KEY_NAME=id_ed25519 DOCKER_BUILDKIT=1 docker build -f Dockerfile_ubuntu24.04_fable --build-arg DOCKER_UID=$(id -u) --build-arg DOCKER_GID=$(id -g) --build-arg USE_SSH=true --build-arg SSH_KEY_NAME=${SSH_KEY_NAME} --build-arg MPLAPACK_REPO=https://github.com/<username>/mplapack.git --secret id=ssh_key,src=$HOME/.ssh/${SSH_KEY_NAME} -t mplapack:fable .
#
# * How to run
#  sudo sh -c 'echo -1 >/proc/sys/kernel/perf_event_paranoid' # to run perf
#  or
#  sudo sysctl -w kernel.perf_event_paranoid=-1 # to run perf
#  docker run --privileged --gpus all -it --rm mplapack:fable /bin/bash
#
# * How to run with SSH key for git operations (maintainers only)
#  eval $(ssh-agent); ssh-add ~/.ssh/id_ed25519; docker run --privileged --gpus all -v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent -it --rm mplapack:fable /bin/bash
#
# https://hub.docker.com/r/nvidia/cuda/tags
FROM nvidia/cuda:13.0.1-devel-ubuntu24.04

#git setting
ARG GIT_EMAIL="maho.nakata@gmail.com"
ARG GIT_NAME="NAKATA Maho"
LABEL maintainer="maho.nakata@gmail.com"

# Build argument to choose between HTTPS (public) and SSH (maintainer)
ARG DOCKER_UID
ARG DOCKER_GID
ARG USE_SSH=false
ARG SSH_KEY_NAME

# Repository URLs - can be overridden to use forks
ARG MPLAPACK_REPO=https://github.com/nakatamaho/mplapack.git

# Validate required arguments for SSH mode
RUN if [ "$USE_SSH" = "true" ] && [ -z "$SSH_KEY_NAME" ]; then \
      echo "========================================"; \
      echo "ERROR: Maintainer mode requires SSH_KEY_NAME"; \
      echo "Usage: --build-arg SSH_KEY_NAME=id_ed25519"; \
      echo "========================================"; \
      exit 1; \
    fi

ARG DEBIAN_FRONTEND=noninteractive
RUN apt -y update
RUN apt -y upgrade
RUN apt install -y sudo 
RUN apt install -y tzdata
# set your timezone
ENV TZ=Asia/Tokyo
RUN echo "${TZ}" > /etc/timezone \
  && rm /etc/localtime \
  && ln -s /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
  && dpkg-reconfigure -f noninteractive tzdata

RUN apt install -y build-essential python3 gcc g++ gfortran
RUN apt install -y autotools-dev automake libtool libtool-bin gnuplot
RUN apt install -y gdb valgrind linux-tools-`uname -r` google-perftools linux-headers-`uname -r`
RUN apt install -y git wget gpg ccache time parallel bc
RUN apt install -y pkg-config clangd clang-format unifdef octave
RUN apt install -y ng-common ng-cjk emacs-nox
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1

### intel one api start ###
RUN wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
RUN apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
RUN echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
RUN apt update
# too big
#RUN apt install -y intel-basekit
#RUN apt install -y intel-hpckit
# sufficient
RUN apt-get install -y --no-install-recommends \
  intel-oneapi-compiler-dpcpp-cpp intel-oneapi-compiler-fortran \
  intel-oneapi-mkl intel-oneapi-mpi intel-oneapi-mpi-devel
### intel one api end ###

### mingw + wine start ###
RUN apt-get update -y && apt-get install -y mingw-w64 gfortran-mingw-w64 gdb-mingw-w64 wget gnupg2
RUN dpkg --add-architecture i386 && apt-get update -y
RUN mkdir -pm755 /etc/apt/keyrings
RUN wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
RUN wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources
RUN apt-get update -y && apt-get install -y --install-recommends winehq-stable
### mingw + wine end ###

### cuda start ###
#RUN apt install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" keyboard-configuration
#RUN apt install -y cuda-drivers
### cuda end ###

# create non-root user without password and allow passwordless sudo
ARG DOCKER_UID=2000
ARG DOCKER_GID=2000
ARG DOCKER_USER=docker
RUN groupadd -g ${DOCKER_GID} ${DOCKER_USER} 2>/dev/null || true \
 && useradd -u ${DOCKER_UID} -g ${DOCKER_GID} -m ${DOCKER_USER} --shell /bin/bash \
 && usermod -aG sudo ${DOCKER_USER} \
 && printf "%s ALL=(ALL) NOPASSWD:ALL\n" "${DOCKER_USER}" > /etc/sudoers.d/90-${DOCKER_USER}-nopasswd \
 && chmod 0440 /etc/sudoers.d/90-${DOCKER_USER}-nopasswd
ARG WORK=/home/$DOCKER_USER

#install ctag
RUN cd ${WORK} && git clone https://github.com/universal-ctags/ctags.git
RUN cd ${WORK} && cd ctags && ./autogen.sh && ./configure --prefix=/usr/local && make && make install

USER docker     
USER ${DOCKER_USER}
RUN echo "\n\
[user]\n\
        email = ${GIT_EMAIL}\n\
        name = ${GIT_NAME}\n\
" > /home/$DOCKER_USER/.gitconfig
SHELL ["/bin/bash", "-c"]
RUN cd ${WORK} && wget https://raw.githubusercontent.com/cctbx/cctbx_project/master/libtbx/auto_build/bootstrap.py --no-check-certificate
RUN cd ${WORK} && python bootstrap.py hot update --builder=cctbx
RUN cd ${WORK} && wget https://repo.anaconda.com/miniconda/Miniconda2-4.5.11-Linux-x86_64.sh
RUN cd ${WORK} && bash ./Miniconda2-4.5.11-Linux-x86_64.sh -b -p

RUN cd ${WORK} && source miniconda2/etc/profile.d/conda.sh && conda create -y --name fable38 python=3.8 && conda activate fable38 && conda install six future && mkdir build38 && cd ${WORK}/build38 && python ../modules/cctbx_project/libtbx/configure.py fable
RUN sed -i 's|#if PTHREAD_STACK_MIN > 0|#ifdef PTHREAD_STACK_MIN|g' ${WORK}/modules/boost/boost/thread/pthread/thread_data.hpp
RUN source ${WORK}/build38/setpaths.sh && cd ${WORK}/build38 && make && cd ${WORK} && cd ${WORK}/build38 && make ; cd ${WORK}
RUN cd ${WORK} && echo "source /home/docker/miniconda2/etc/profile.d/conda.sh" >> .bashrc
RUN cd ${WORK} && echo "conda activate fable38" >> .bashrc
RUN cd ${WORK} && echo "source /home/docker/build38/setpaths.sh" >> .bashrc
RUN echo -e "\n\
        PROGRAM HELLO\n\
        PRINT *, 'HELLO, WORLD!'\n\
        END PROGRAM\n\
" >> ${WORK}/sample.f

#setting lsp mode for C++ https://emacs-lsp.github.io/lsp-mode/tutorials/CPP-guide/
RUN cd ${WORK} && mkdir -p .emacs.d
RUN echo -e "\n\
[user]\n\
        email = ${GIT_EMAIL}\n\
        name = ${GIT_NAME}\n\
" >> /home/$DOCKER_USER/.gitconfig

RUN echo -e "(require 'package)\n\
(add-to-list 'package-archives '(\"melpa\" . \"http://melpa.org/packages/\") t)\n\
(package-initialize)\n\
\n\
(setq package-selected-packages '(lsp-mode yasnippet lsp-treemacs helm-lsp\n\
    projectile hydra flycheck company avy which-key helm-xref dap-mode))\n\
\n\
(when (cl-find-if-not #'package-installed-p package-selected-packages)\n\
  (package-refresh-contents)\n\
  (mapc #'package-install package-selected-packages))\n\
\n\
;; sample 'helm' configuration use https://github.com/emacs-helm/helm/ for details\n\
(helm-mode)\n\
(require 'helm-xref)\n\
(define-key global-map [remap find-file] #'helm-find-files)\n\
(define-key global-map [remap execute-extended-command] #'helm-M-x)\n\
(define-key global-map [remap switch-to-buffer] #'helm-mini)\n\
\n\
(which-key-mode)\n\
(add-hook 'c-mode-hook 'lsp)\n\
(add-hook 'c++-mode-hook 'lsp)\n\
\n\
(setq gc-cons-threshold (* 100 1024 1024)\n\
      read-process-output-max (* 1024 1024)\n\
      treemacs-space-between-root-nodes nil\n\
      company-idle-delay 0.0\n\
      company-minimum-prefix-length 1\n\
      lsp-idle-delay 0.1)  ;; clangd is fast\n\
\n\
(with-eval-after-load 'lsp-mode\n\
  (add-hook 'lsp-mode-hook #'lsp-enable-which-key-integration)\n\
  (require 'dap-cpptools)\n\
  (yas-global-mode))\n\
" >> ${WORK}/.emacs.d/init.el

RUN cd ${WORK} && echo "cd /home/$DOCKER_USER" >> .bashrc

## intel one api and wine settings start ###
RUN cd ${WORK} && echo "#source /opt/intel/oneapi/setvars.sh" >> .bashrc
RUN cd ${WORK} && echo "export WINEPATH=\"/usr/x86_64-w64-mingw32/lib/;/usr/lib/gcc/x86_64-w64-mingw32/10-win32/;/usr/lib/gcc/x86_64-w64-mingw32/10-posix;/home/$DOCKER_USER/MPLAPACK_MINGW/bin\"" >> .bashrc
RUN cd ${WORK} && echo "export PATH=\"$PATH:/opt/wine-stable/bin\"" >> .bashrc
RUN cd ${WORK} && echo "export WINEDEBUG=\"-all\"" >> .bashrc
## intel one api and wine settings end ###

### Git clone strategy: HTTPS (default) or SSH (with --build-arg USE_SSH=true) ###

# Prepare SSH environment if using SSH mode
RUN if [ "$USE_SSH" = "true" ]; then \
        mkdir -p /home/$DOCKER_USER/.ssh && \
        chmod 0700 /home/$DOCKER_USER/.ssh && \
        ssh-keyscan github.com > /home/$DOCKER_USER/.ssh/known_hosts; \
    fi

# Clone repositories - HTTPS mode (default, public access)
RUN if [ "$USE_SSH" != "true" ]; then \
        echo "=== Cloning via HTTPS (public read-only mode) ===" && \
        echo "Repository: ${MPLAPACK_REPO}" && \
        cd ${WORK} && git clone ${MPLAPACK_REPO} && \
        cd ${WORK}/mplapack && git checkout refactor/fable && \
        cd ${WORK}/mplapack && git log -1; \
    fi

# Clone repositories - SSH mode (maintainer access, requires --secret)
RUN --mount=type=secret,id=ssh_key,uid=${DOCKER_UID} \
    if [ "$USE_SSH" = "true" ]; then \
        echo "=== Cloning via SSH (maintainer mode) ===" && \
        SSH_REPO=$(echo "${MPLAPACK_REPO}" | sed 's|https://github.com/|git@github.com:|') && \
        echo "Repository: ${SSH_REPO}" && \
        mkdir -p /home/$DOCKER_USER/.ssh && \
        cp /run/secrets/ssh_key /home/$DOCKER_USER/.ssh/${SSH_KEY_NAME} && \
        chmod 600 /home/$DOCKER_USER/.ssh/${SSH_KEY_NAME} && \
        eval "$(ssh-agent -s)" && \
        ssh-add /home/$DOCKER_USER/.ssh/${SSH_KEY_NAME} && \
        cd ${WORK} && git clone ${SSH_REPO} && \
        cd ${WORK}/mplapack && git checkout refactor/fable && \
        cd ${WORK}/mplapack && git log -1 && \
        rm -f /home/$DOCKER_USER/.ssh/${SSH_KEY_NAME}; \
    fi

RUN cd ${WORK}/mplapack && bash -x misc/reconfig.ubuntu24.04.sh
#RUN cd ${WORK}/mplapack && make clean
#RUN cd ${WORK}/mplapack && make -j`getconf _NPROCESSORS_ONLN`
#RUN cd ${WORK}/mplapack && make install

#RUN cd ${WORK}/mplapack && bash -x misc/reconfig.ubuntu24.04.nvidia.sh
#RUN cd ${WORK}/mplapack && make clean
#RUN cd ${WORK}/mplapack && make -j`getconf _NPROCESSORS_ONLN`
#RUN cd ${WORK}/mplapack && make install

#ARG WINEPATH="/usr/x86_64-w64-mingw32/lib/;/usr/lib/gcc/x86_64-w64-mingw32/10-win32/;/usr/lib/gcc/x86_64-w64-mingw32/10-posix"
#ARG WINEDEBUG="-all"
#ENV PATH="$PATH:/opt/wine-stable/bin"
#RUN cd ${WORK}/mplapack && bash -x misc/reconfig.ubuntu24.04.mingw64.sh
#RUN cd ${WORK}/mplapack && make clean
#RUN cd ${WORK}/mplapack && make -j`getconf _NPROCESSORS_ONLN`
#RUN cd ${WORK}/mplapack && make install
