if(NOT DEFINED CMAKE_PC_DIR OR NOT DEFINED AUTOTOOLS_PC_DIR)
  message(FATAL_ERROR "CMAKE_PC_DIR and AUTOTOOLS_PC_DIR are required")
endif()

foreach(_flavor IN LISTS FLAVORS)
  set(_name "${_flavor}.pc")
  set(_cmake_pc "${CMAKE_PC_DIR}/${_name}")
  set(_autotools_pc "${AUTOTOOLS_PC_DIR}/${_name}")
  if(NOT EXISTS "${_cmake_pc}" OR NOT EXISTS "${_autotools_pc}")
    message(FATAL_ERROR
      "Missing pkg-config parity input: ${_cmake_pc} or ${_autotools_pc}")
  endif()
  foreach(_pc "${_cmake_pc}" "${_autotools_pc}")
    file(READ "${_pc}" _metadata)
    set(_required)
    if(_flavor MATCHES "^mplapack_gmp($|_)")
      set(_required gmpxx gmp)
    elseif(_flavor MATCHES "^mplapack_mpfr($|_)")
      set(_required mpc mpfr gmpxx gmp)
    elseif(_flavor MATCHES "^mplapack_(qd|dd)($|_)")
      set(_required qd m)
    endif()
    if(_flavor MATCHES "_opt($|_)")
      list(APPEND _required ${OPENMP_RUNTIME_LIBS})
    endif()
    foreach(_library IN LISTS _required)
      if(NOT _metadata MATCHES "-l${_library}([ \n]|$)")
        message(FATAL_ERROR "Missing ${_library} dependency metadata in ${_pc}")
      endif()
    endforeach()
    if(_metadata MATCHES "@[A-Za-z_]+@")
      message(FATAL_ERROR "Unsubstituted pkg-config field in ${_pc}")
    endif()
  endforeach()
  execute_process(
    COMMAND "${CMAKE_COMMAND}" -E compare_files
            "${_cmake_pc}" "${_autotools_pc}"
    RESULT_VARIABLE _result)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR
      "Autotools/CMake pkg-config mismatch for ${_name}")
  endif()
endforeach()
