SUBDIRS = 00_GeneralLinearEquations \
01_PositiveDefiniteLinearEquations \
02_LeastSquares \
03_SymmetricEigenproblems \
04_NonsymmetricEigenproblems \
05_SingularValueDecomposition \
06_SymmetricIndefiniteLinearEquations \
07_GeneralizedSymmetricDefiniteEigenproblems \
08_GeneralizedNonsymmetricEigenproblems \
09_GeneralizedSingularValueDecomposition \
90_PrecisionComparison

EXTRA_DIST = README.md run_smoke.sh
