#SUBDIRS =01_LinearLeastSquaresProblems \
#02_GeneralizedLinearLeastSquaresProblems \
#04_NonsymmetricEigenproblems \
#05_SingularValueDecomposition \
#06_GeneralizedSymmetricDefiniteEigenproblems \
#07_GeneralizedNonSymmetricEigenproblems \
#08_GeneralizedSingularValueDecomposition

SUBDIRS = 00_GeneralLinearEquations \
01_PositiveDefiniteLinearEquations \
02_LeastSquares \
03_SymmetricEigenproblems \
04_NonsymmetricEigenproblems \
05_SingularValueDecomposition \
06_SymmetricIndefiniteLinearEquations \
07_GeneralizedSymmetricDefiniteEigenproblems \
08_GeneralizedNonsymmetricEigenproblems \
09_GeneralizedSingularValueDecomposition \
90_PrecisionComparison
