/*
 * Copyright (c) 2008-2025
 *	Nakata, Maho
 * 	All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 */

#ifndef MPLAPACK_LIN_GMP_H
#define MPLAPACK_LIN_GMP_H

#include "mplapack_config.h"
#include <mplapack_gmpfrxx_mkII_config.h>
#include <gmpxx_mkII.h>
using namespace gmpxx;

#include <mpblas.h>
#include <mplapack.h>

#include <fem.hpp> // Fortran EMulation library of fable module
using namespace fem::major_types;
using fem::common;

#include <mplapack_matgen.h>
#include <mplapack_lin.h>
#include <mplapack_debug.h>
bool Cgennd(mplapackint const m, mplapackint const n, mpfc_class *a, mplapackint const lda);
bool Rgennd(mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda);
mpf_class Cqpt01(mplapackint const m, mplapackint const n, mplapackint const k, mpfc_class *a, mpfc_class *af, mplapackint const lda, mpfc_class *tau, mplapackint *jpvt, mpfc_class *work, mplapackint const lwork);
mpf_class Cqrt11(mplapackint const m, mplapackint const k, mpfc_class *a, mplapackint const lda, mpfc_class *tau, mpfc_class *work, mplapackint const lwork);
mpf_class Cqrt12(mplapackint const m, mplapackint const n, mpfc_class *a, mplapackint const lda, mpf_class *s, mpfc_class *work, mplapackint const lwork, mpf_class *rwork);
mpf_class Cqrt14(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mpfc_class *x, mplapackint const ldx, mpfc_class *work, mplapackint const lwork);
mpf_class Cqrt17(fem::str_cref trans, mplapackint const iresid, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mpfc_class *x, mplapackint const ldx, mpfc_class *b, mplapackint const ldb, mpfc_class *c, mpfc_class *work, mplapackint const lwork);
mpf_class Crzt01(mplapackint const m, mplapackint const n, mpfc_class *a, mpfc_class *af, mplapackint const lda, mpfc_class *tau, mpfc_class *work, mplapackint const lwork);
mpf_class Crzt02(mplapackint const m, mplapackint const n, mpfc_class *af, mplapackint const lda, mpfc_class *tau, mpfc_class *work, mplapackint const lwork);
mpf_class Rget06(mpf_class const rcond, mpf_class const rcondc);
mpf_class Rlamch_gmp(const char *cmach);
mpf_class Rqpt01(mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *a, mpf_class *af, mplapackint const lda, mpf_class *tau, mplapackint *jpvt, mpf_class *work, mplapackint const lwork);
mpf_class Rqrt11(mplapackint const m, mplapackint const k, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork);
mpf_class Rqrt12(mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *s, mpf_class *work, mplapackint const lwork);
mpf_class Rqrt14(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *x, mplapackint const ldx, mpf_class *work, mplapackint const lwork);
mpf_class Rqrt17(fem::str_cref trans, mplapackint const iresid, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *x, mplapackint const ldx, mpf_class *b, mplapackint const ldb, mpf_class *c, mpf_class *work, mplapackint const lwork);
mpf_class Rrzt01(mplapackint const m, mplapackint const n, mpf_class *a, mpf_class *af, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork);
mpf_class Rrzt02(mplapackint const m, mplapackint const n, mpf_class *af, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork);
mplapackint iMlaenv2stage_gmp(mplapackint const ispec, const char *name, const char *opts, mplapackint const n1, mplapackint const n2, mplapackint const n3, mplapackint const n4);
mplapackint iMlaenv_gmp(mplapackint const ispec, const char *name, const char *opts, mplapackint const n1, mplapackint const n2, mplapackint const n3, mplapackint const n4);
void Aladhd(mplapackint const iounit, fem::str_cref path);
void Alaerh(fem::str_cref path, fem::str_cref subnam, mplapackint const info, mplapackint const infoe, fem::str_cref opts, mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mplapackint const n5, mplapackint const imat, mplapackint const nfail, mplapackint &nerrs, mplapackint const nout);
void Alaesm(fem::str_cref path, bool const ok, mplapackint const nout);
void Alahd(mplapackint const iounit, fem::str_cref path);
void Alareq(fem::str_cref path, mplapackint const nmats, bool *dotype, mplapackint const ntypes, mplapackint const nin, mplapackint const nout);
void Alasum(fem::str_cref type, mplapackint const nout, mplapackint const nfail, mplapackint const nrun, mplapackint const nerrs);
void Alasvm(fem::str_cref type, mplapackint const nout, mplapackint const nfail, mplapackint const nrun, mplapackint const nerrs);
void Cchkeq(mpf_class const thresh, mplapackint const nout);
void Cchkgb(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mpfc_class *a, mplapackint const la, mpfc_class *afac, mplapackint const lafac, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchkge(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchkgt(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mpfc_class *a, mpfc_class *af, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchkhe(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchkhe_aa(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchkhe_aa_2stage(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchkhe_rk(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpfc_class *a, mpfc_class *afac, mpfc_class *e, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchkhe_rook(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchkhp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchklq(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpfc_class *a, mpfc_class *af, mpfc_class *aq, mpfc_class *al, mpfc_class *ac, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *tau, mpfc_class *work, mpf_class *rwork, mplapackint const nout);
void Cchklqt(mpf_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Cchklqtp(mpf_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Cchkpb(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint const nout);
void Cchkpo(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint const nout);
void Cchkpp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint const nout);
void Cchkps(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nrank, mplapackint *rankval, mpf_class const thresh, bool const tsterr, mplapackint const, mpfc_class *a, mpfc_class *afac, mpfc_class *perm, mplapackint *piv, mpfc_class *work, mpf_class *rwork, mplapackint const nout);
void Cchkpt(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mpfc_class *a, mpf_class *d, mpfc_class *e, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint const nout);
void Cchkq3(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mpf_class const thresh, mpfc_class *a, mpfc_class *copya, mpf_class *s, mpfc_class *tau, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchkql(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpfc_class *a, mpfc_class *af, mpfc_class *aq, mpfc_class *al, mpfc_class *ac, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *tau, mpfc_class *work, mpf_class *rwork, mplapackint const nout);
void Cchkqp3rk(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mpf_class const thresh, mpfc_class *a, mpfc_class *copya, mpfc_class *b, mpfc_class *copyb, mpf_class *s, mpfc_class *tau, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchkqr(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpfc_class *a, mpfc_class *af, mpfc_class *aq, mpfc_class *ar, mpfc_class *ac, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *tau, mpfc_class *work, mpf_class *rwork, mplapackint *, mplapackint const nout);
void Cchkqrt(mpf_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Cchkqrtp(mpf_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Cchkrq(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpfc_class *a, mpfc_class *af, mpfc_class *aq, mpfc_class *ar, mpfc_class *ac, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *tau, mpfc_class *work, mpf_class *rwork, mplapackint *, mplapackint const nout);
void Cchksp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchksy(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchksy_aa(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchksy_aa_2stage(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchksy_rk(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpfc_class *a, mpfc_class *afac, mpfc_class *e, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchksy_rook(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchktb(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpfc_class *ab, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint const nout);
void Cchktp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpfc_class *ap, mpfc_class *ainvp, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint const nout);
void Cchktr(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpfc_class *a, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint const nout);
void Cchktsqr(mpf_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Cchktz(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mpf_class const thresh, bool const tsterr, mpfc_class *a, mpfc_class *copya, mpf_class *s, mpfc_class *tau, mpfc_class *work, mpf_class *rwork, mplapackint const nout);
void Cchkunhr_col(mpf_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Cdrvgb(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mpfc_class *a, mplapackint const la, mpfc_class *afb, mplapackint const lafb, mpfc_class *asav, mpfc_class *b, mpfc_class *bsav, mpfc_class *x, mpfc_class *xact, mpf_class *s, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvge(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpfc_class *a, mpfc_class *afac, mpfc_class *asav, mpfc_class *b, mpfc_class *bsav, mpfc_class *x, mpfc_class *xact, mpf_class *s, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvgt(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mpfc_class *a, mpfc_class *af, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvhe(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvhe_aa(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvhe_aa_2stage(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvhe_rk(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpfc_class *a, mpfc_class *afac, mpfc_class *e, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvhe_rook(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvhp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvls(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mpf_class const thresh, bool const tsterr, mpfc_class *a, mpfc_class *copya, mpfc_class *b, mpfc_class *copyb, mpfc_class *c, mpf_class *s, mpf_class *copys, mplapackint const nout);
void Cdrvpb(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const, mpfc_class *a, mpfc_class *afac, mpfc_class *asav, mpfc_class *b, mpfc_class *bsav, mpfc_class *x, mpfc_class *xact, mpf_class *s, mpfc_class *work, mpf_class *rwork, mplapackint const nout);
void Cdrvpo(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const, mpfc_class *a, mpfc_class *afac, mpfc_class *asav, mpfc_class *b, mpfc_class *bsav, mpfc_class *x, mpfc_class *xact, mpf_class *s, mpfc_class *work, mpf_class *rwork, mplapackint const nout);
void Cdrvpp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const, mpfc_class *a, mpfc_class *afac, mpfc_class *asav, mpfc_class *b, mpfc_class *bsav, mpfc_class *x, mpfc_class *xact, mpf_class *s, mpfc_class *work, mpf_class *rwork, mplapackint const nout);
void Cdrvpt(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mpfc_class *a, mpf_class *d, mpfc_class *e, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint const nout);
void Cdrvrf1(mplapackint const nout, mplapackint const nn, mplapackint *nval, mpf_class const thresh, mpfc_class *a, mplapackint const lda, mpfc_class *arf, mpf_class *work);
void Cdrvrf2(mplapackint const nout, mplapackint const nn, mplapackint *nval, mpfc_class *a, mplapackint const lda, mpfc_class *arf, mpfc_class *ap, mpfc_class *asav);
void Cdrvrf3(mplapackint const nout, mplapackint const nn, mplapackint *nval, mpf_class const thresh, mpfc_class *a, mplapackint const lda, mpfc_class *arf, mpfc_class *b1, mpfc_class *b2, mpf_class *d_work_zlange, mpfc_class *z_work_zgeqrf, mpfc_class *tau);
void Cdrvrf4(mplapackint const nout, mplapackint const nn, mplapackint *nval, mpf_class const thresh, mpfc_class *c1, mpfc_class *c2, mplapackint const ldc, mpfc_class *crf, mpfc_class *a, mplapackint const lda, mpf_class *d_work_zlange);
void Cdrvrfp(mplapackint const nout, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mplapackint const nnt, mplapackint *ntval, mpf_class const thresh, mpfc_class *a, mpfc_class *asav, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *bsav, mpfc_class *xact, mpfc_class *x, mpfc_class *arf, mpfc_class *arfinv, mpfc_class *z_work_zlatms, mpfc_class *z_work_zpot02, mpfc_class *z_work_zpot03, mpf_class *d_work_zlatms, mpf_class *d_work_zlanhe, mpf_class *d_work_zpot01, mpf_class *d_work_zpot02, mpf_class *d_work_zpot03);
void Cdrvsp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvsy(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvsy_aa(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvsy_aa_2stage(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvsy_rk(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpfc_class *a, mpfc_class *afac, mpfc_class *e, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvsy_rook(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpfc_class *a, mpfc_class *afac, mpfc_class *ainv, mpfc_class *b, mpfc_class *x, mpfc_class *xact, mpfc_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cerrge(fem::str_cref path, mplapackint const nunit);
void Cerrgt(fem::str_cref path, mplapackint const nunit);
void Cerrhe(fem::str_cref path, mplapackint const nunit);
void Cerrlq(fem::str_cref path, mplapackint const nunit);
void Cerrlqt(fem::str_cref path, mplapackint const nunit);
void Cerrlqtp(fem::str_cref path, mplapackint const nunit);
void Cerrls(fem::str_cref path, mplapackint const nunit);
void Cerrpo(fem::str_cref path, mplapackint const nunit);
void Cerrps(fem::str_cref path, mplapackint const nunit);
void Cerrql(fem::str_cref path, mplapackint const nunit);
void Cerrqp(fem::str_cref path, mplapackint const nunit);
void Cerrqr(fem::str_cref path, mplapackint const nunit);
void Cerrqrt(fem::str_cref path, mplapackint const nunit);
void Cerrqrtp(fem::str_cref path, mplapackint const nunit);
void Cerrrfp(mplapackint const nunit);
void Cerrrq(fem::str_cref path, mplapackint const nunit);
void Cerrsy(fem::str_cref path, mplapackint const nunit);
void Cerrtr(fem::str_cref path, mplapackint const nunit);
void Cerrtsqr(fem::str_cref path, mplapackint const nunit);
void Cerrtz(fem::str_cref path, mplapackint const nunit);
void Cerrunhr_col(fem::str_cref path, mplapackint const nunit);
void Cerrvx(fem::str_cref path, mplapackint const nunit);
void Cgbt01(mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mpfc_class *a, mplapackint const lda, mpfc_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpfc_class *work, mpf_class &resid);
void Cgbt02(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mpfc_class *x, mplapackint const ldx, mpfc_class *b, mplapackint const ldb, mpf_class *rwork, mpf_class &resid);
void Cgbt05(fem::str_cref trans, mplapackint const n, mplapackint const kl, mplapackint const ku, mplapackint const nrhs, mpfc_class *ab, mplapackint const ldab, mpfc_class *b, mplapackint const ldb, mpfc_class *x, mplapackint const ldx, mpfc_class *xact, mplapackint const ldxact, mpf_class *ferr, mpf_class *berr, mpf_class *reslts);
void Cgeqls(mplapackint const m, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mpfc_class *tau, mpfc_class *b, mplapackint const ldb, mpfc_class *work, mplapackint const lwork, mplapackint &info);
void Cgerqs(mplapackint const m, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mpfc_class *tau, mpfc_class *b, mplapackint const ldb, mpfc_class *work, mplapackint const lwork, mplapackint &info);
void Cget01(mplapackint const m, mplapackint const n, mpfc_class *a, mplapackint const lda, mpfc_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpf_class *rwork, mpf_class &resid);
void Cget02(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mpfc_class *x, mplapackint const ldx, mpfc_class *b, mplapackint const ldb, mpf_class *rwork, mpf_class &resid);
void Cget03(mplapackint const n, mpfc_class *a, mplapackint const lda, mpfc_class *ainv, mplapackint const ldainv, mpfc_class *work, mplapackint const ldwork, mpf_class *rwork, mpf_class &rcond, mpf_class &resid);
void Cget04(mplapackint const n, mplapackint const nrhs, mpfc_class *x, mplapackint const ldx, mpfc_class *xact, mplapackint const ldxact, mpf_class const rcond, mpf_class &resid);
void Cget07(fem::str_cref trans, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mpfc_class *b, mplapackint const ldb, mpfc_class *x, mplapackint const ldx, mpfc_class *xact, mplapackint const ldxact, mpf_class *ferr, bool const chkferr, mpf_class *berr, mpf_class *reslts);
void Cget08(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mpfc_class *x, mplapackint const ldx, mpfc_class *b, mplapackint const ldb, mpf_class *rwork, mpf_class &resid);
void Cgtt01(mplapackint const n, mpfc_class *dl, mpfc_class *d, mpfc_class *du, mpfc_class *dlf, mpfc_class *df, mpfc_class *duf, mpfc_class *du2, mplapackint *ipiv, mpfc_class *work, mplapackint const ldwork, mpf_class *rwork, mpf_class &resid);
void Cgtt02(fem::str_cref trans, mplapackint const n, mplapackint const nrhs, mpfc_class *dl, mpfc_class *d, mpfc_class *du, mpfc_class *x, mplapackint const ldx, mpfc_class *b, mplapackint const ldb, mpf_class &resid);
void Cgtt05(fem::str_cref trans, mplapackint const n, mplapackint const nrhs, mpfc_class *dl, mpfc_class *d, mpfc_class *du, mpfc_class *b, mplapackint const ldb, mpfc_class *x, mplapackint const ldx, mpfc_class *xact, mplapackint const ldxact, mpf_class *ferr, mpf_class *berr, mpf_class *reslts);
void Chet01(fem::str_cref uplo, mplapackint const n, mpfc_class *a, mplapackint const lda, mpfc_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpfc_class *c, mplapackint const ldc, mpf_class *rwork, mpf_class &resid);
void Chet01_3(fem::str_cref uplo, mplapackint const n, mpfc_class *a, mplapackint const lda, mpfc_class *afac, mplapackint const ldafac, mpfc_class *e, mplapackint *ipiv, mpfc_class *c, mplapackint const ldc, mpf_class *rwork, mpf_class &resid);
void Chet01_aa(fem::str_cref uplo, mplapackint const n, mpfc_class *a, mplapackint const lda, mpfc_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpfc_class *c, mplapackint const ldc, mpf_class *rwork, mpf_class &resid);
void Chet01_rook(fem::str_cref uplo, mplapackint const n, mpfc_class *a, mplapackint const lda, mpfc_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpfc_class *c, mplapackint const ldc, mpf_class *rwork, mpf_class &resid);
void Chkxer(fem::str_cref srnamt, mplapackint const infot, mplapackint const nout, bool &lerr, bool &ok);
void Chpt01(fem::str_cref uplo, mplapackint const n, mpfc_class *a, mpfc_class *afac, mplapackint *ipiv, mpfc_class *c, mplapackint const ldc, mpf_class *rwork, mpf_class &resid);
void Clahilb(mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mpfc_class *x, mplapackint const ldx, mpfc_class *b, mplapackint const ldb, mpf_class *work, mplapackint &info, fem::str_cref path);
void Claipd(mplapackint const n, mpfc_class *a, mplapackint const inda, mplapackint const vinda);
void Claptm(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpf_class const alpha, mpf_class *d, mpfc_class *e, mpfc_class *x, mplapackint const ldx, mpf_class const beta, mpfc_class *b, mplapackint const ldb);
void Clarhs(fem::str_cref path, fem::str_cref xtype, fem::str_cref uplo, fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mpfc_class *x, mplapackint const ldx, mpfc_class *b, mplapackint const ldb, mplapackint (&iseed)[4], mplapackint &info);
void Clatb4(fem::str_cref path, mplapackint const imat, mplapackint const m, mplapackint const n, fem::str_ref type, mplapackint &kl, mplapackint &ku, mpf_class &anorm, mplapackint &mode, mpf_class &cndnum, fem::str_ref dist);
void Clatb5(fem::str_cref path, mplapackint const imat, mplapackint const n, fem::str_ref type, mplapackint &kl, mplapackint &ku, mpf_class &anorm, mplapackint &mode, mpf_class &cndnum, fem::str_ref dist);
void Clatsp(fem::str_cref uplo, mplapackint const n, mpfc_class *x, mplapackint (&iseed)[4]);
void Clatsy(fem::str_cref uplo, mplapackint const n, mpfc_class *x, mplapackint const ldx, mplapackint (&iseed)[4]);
void Clattb(mplapackint const imat, fem::str_cref uplo, fem::str_cref trans, fem::str_ref diag, mplapackint (&iseed)[4], mplapackint const n, mplapackint const kd, mpfc_class *ab, mplapackint const ldab, mpfc_class *b, mpfc_class *work, mpf_class *rwork, mplapackint &info);
void Clattp(mplapackint const imat, fem::str_cref uplo, fem::str_cref trans, fem::str_ref diag, mplapackint (&iseed)[4], mplapackint const n, mpfc_class *ap, mpfc_class *b, mpfc_class *work, mpf_class *rwork, mplapackint &info);
void Clattr(mplapackint const imat, fem::str_cref uplo, fem::str_cref trans, fem::str_ref diag, mplapackint (&iseed)[4], mplapackint const n, mpfc_class *a, mplapackint const lda, mpfc_class *b, mpfc_class *work, mpf_class *rwork, mplapackint &info);
void Clavhe(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mplapackint *ipiv, mpfc_class *b, mplapackint const ldb, mplapackint &info);
void Clavhe_rook(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mplapackint *ipiv, mpfc_class *b, mplapackint const ldb, mplapackint &info);
void Clavhp(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint *ipiv, mpfc_class *b, mplapackint const ldb, mplapackint &info);
void Clavsp(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint *ipiv, mpfc_class *b, mplapackint const ldb, mplapackint &info);
void Clavsy(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mplapackint *ipiv, mpfc_class *b, mplapackint const ldb, mplapackint &info);
void Clavsy_rook(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mplapackint *ipiv, mpfc_class *b, mplapackint const ldb, mplapackint &info);
void Clqt01(mplapackint const m, mplapackint const n, mpfc_class *a, mpfc_class *af, mpfc_class *q, mpfc_class *l, mplapackint const lda, mpfc_class *tau, mpfc_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Clqt02(mplapackint const m, mplapackint const n, mplapackint const k, mpfc_class *a, mpfc_class *af, mpfc_class *q, mpfc_class *l, mplapackint const lda, mpfc_class *tau, mpfc_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Clqt03(mplapackint const m, mplapackint const n, mplapackint const k, mpfc_class *af, mpfc_class *c, mpfc_class *cc, mpfc_class *q, mplapackint const lda, mpfc_class *tau, mpfc_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Clqt04(mplapackint const m, mplapackint const n, mplapackint const nb, mpf_class *result);
void Clqt05(mplapackint const m, mplapackint const n, mplapackint const l, mplapackint const nb, mpf_class *result);
void Cpbt01(fem::str_cref uplo, mplapackint const n, mplapackint const kd, mpfc_class *a, mplapackint const lda, mpfc_class *afac, mplapackint const ldafac, mpf_class *rwork, mpf_class &resid);
void Cpbt02(fem::str_cref uplo, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mpfc_class *x, mplapackint const ldx, mpfc_class *b, mplapackint const ldb, mpf_class *rwork, mpf_class &resid);
void Cpbt05(fem::str_cref uplo, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpfc_class *ab, mplapackint const ldab, mpfc_class *b, mplapackint const ldb, mpfc_class *x, mplapackint const ldx, mpfc_class *xact, mplapackint const ldxact, mpf_class *ferr, mpf_class *berr, mpf_class *reslts);
void Cpot01(fem::str_cref uplo, mplapackint const n, mpfc_class *a, mplapackint const lda, mpfc_class *afac, mplapackint const ldafac, mpf_class *rwork, mpf_class &resid);
void Cpot02(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mpfc_class *x, mplapackint const ldx, mpfc_class *b, mplapackint const ldb, mpf_class *rwork, mpf_class &resid);
void Cpot03(fem::str_cref uplo, mplapackint const n, mpfc_class *a, mplapackint const lda, mpfc_class *ainv, mplapackint const ldainv, mpfc_class *work, mplapackint const ldwork, mpf_class *rwork, mpf_class &rcond, mpf_class &resid);
void Cpot05(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mpfc_class *b, mplapackint const ldb, mpfc_class *x, mplapackint const ldx, mpfc_class *xact, mplapackint const ldxact, mpf_class *ferr, mpf_class *berr, mpf_class *reslts);
void Cpot06(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mpfc_class *x, mplapackint const ldx, mpfc_class *b, mplapackint const ldb, mpf_class *rwork, mpf_class &resid);
void Cppt01(fem::str_cref uplo, mplapackint const n, mpfc_class *a, mpfc_class *afac, mpf_class *rwork, mpf_class &resid);
void Cppt02(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mpfc_class *x, mplapackint const ldx, mpfc_class *b, mplapackint const ldb, mpf_class *rwork, mpf_class &resid);
void Cppt03(fem::str_cref uplo, mplapackint const n, mpfc_class *a, mpfc_class *ainv, mpfc_class *work, mplapackint const ldwork, mpf_class *rwork, mpf_class &rcond, mpf_class &resid);
void Cppt05(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpfc_class *ap, mpfc_class *b, mplapackint const ldb, mpfc_class *x, mplapackint const ldx, mpfc_class *xact, mplapackint const ldxact, mpf_class *ferr, mpf_class *berr, mpf_class *reslts);
void Cpst01(fem::str_cref uplo, mplapackint const n, mpfc_class *a, mplapackint const lda, mpfc_class *afac, mplapackint const ldafac, mpfc_class *perm, mplapackint const ldperm, mplapackint *piv, mpf_class *rwork, mpf_class &resid, mplapackint const rank);
void Cptt01(mplapackint const n, mpf_class *d, mpfc_class *e, mpf_class *df, mpfc_class *ef, mpfc_class *work, mpf_class &resid);
void Cptt02(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpf_class *d, mpfc_class *e, mpfc_class *x, mplapackint const ldx, mpfc_class *b, mplapackint const ldb, mpf_class &resid);
void Cptt05(mplapackint const n, mplapackint const nrhs, mpf_class *d, mpfc_class *e, mpfc_class *b, mplapackint const ldb, mpfc_class *x, mplapackint const ldx, mpfc_class *xact, mplapackint const ldxact, mpf_class *ferr, mpf_class *berr, mpf_class *reslts);
void Cqlt01(mplapackint const m, mplapackint const n, mpfc_class *a, mpfc_class *af, mpfc_class *q, mpfc_class *l, mplapackint const lda, mpfc_class *tau, mpfc_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Cqlt02(mplapackint const m, mplapackint const n, mplapackint const k, mpfc_class *a, mpfc_class *af, mpfc_class *q, mpfc_class *l, mplapackint const lda, mpfc_class *tau, mpfc_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Cqlt03(mplapackint const m, mplapackint const n, mplapackint const k, mpfc_class *af, mpfc_class *c, mpfc_class *cc, mpfc_class *q, mplapackint const lda, mpfc_class *tau, mpfc_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Cqrt01(mplapackint const m, mplapackint const n, mpfc_class *a, mpfc_class *af, mpfc_class *q, mpfc_class *r, mplapackint const lda, mpfc_class *tau, mpfc_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Cqrt01p(mplapackint const m, mplapackint const n, mpfc_class *a, mpfc_class *af, mpfc_class *q, mpfc_class *r, mplapackint const lda, mpfc_class *tau, mpfc_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Cqrt02(mplapackint const m, mplapackint const n, mplapackint const k, mpfc_class *a, mpfc_class *af, mpfc_class *q, mpfc_class *r, mplapackint const lda, mpfc_class *tau, mpfc_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Cqrt03(mplapackint const m, mplapackint const n, mplapackint const k, mpfc_class *af, mpfc_class *c, mpfc_class *cc, mpfc_class *q, mplapackint const lda, mpfc_class *tau, mpfc_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Cqrt04(mplapackint const m, mplapackint const n, mplapackint const nb, mpf_class *result);
void Cqrt05(mplapackint const m, mplapackint const n, mplapackint const l, mplapackint const nb, mpf_class *result);
void Cqrt13(mplapackint const scale, mplapackint const m, mplapackint const n, mpfc_class *a, mplapackint const lda, mpf_class &norma, mplapackint (&iseed)[4]);
void Cqrt15(mplapackint const scale, mplapackint const rksel, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mpfc_class *b, mplapackint const ldb, mpf_class *s, mplapackint &rank, mpf_class &norma, mpf_class &normb, mplapackint (&iseed)[4], mpfc_class *work, mplapackint const lwork);
void Cqrt16(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mpfc_class *x, mplapackint const ldx, mpfc_class *b, mplapackint const ldb, mpf_class *rwork, mpf_class &resid);
void Crqt01(mplapackint const m, mplapackint const n, mpfc_class *a, mpfc_class *af, mpfc_class *q, mpfc_class *r, mplapackint const lda, mpfc_class *tau, mpfc_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Crqt02(mplapackint const m, mplapackint const n, mplapackint const k, mpfc_class *a, mpfc_class *af, mpfc_class *q, mpfc_class *r, mplapackint const lda, mpfc_class *tau, mpfc_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Crqt03(mplapackint const m, mplapackint const n, mplapackint const k, mpfc_class *af, mpfc_class *c, mpfc_class *cc, mpfc_class *q, mplapackint const lda, mpfc_class *tau, mpfc_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Csbmv(fem::str_cref uplo, mplapackint const n, mplapackint const k, mpfc_class const alpha, mpfc_class *a, mplapackint const lda, mpfc_class *x, mplapackint const incx, mpfc_class const beta, mpfc_class *y, mplapackint const incy);
void Cspt01(fem::str_cref uplo, mplapackint const n, mpfc_class *a, mpfc_class *afac, mplapackint *ipiv, mpfc_class *c, mplapackint const ldc, mpf_class *rwork, mpf_class &resid);
void Cspt02(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mpfc_class *x, mplapackint const ldx, mpfc_class *b, mplapackint const ldb, mpf_class *rwork, mpf_class &resid);
void Cspt03(fem::str_cref uplo, mplapackint const n, mpfc_class *a, mpfc_class *ainv, mpfc_class *work, mplapackint const ldw, mpf_class *rwork, mpf_class &rcond, mpf_class &resid);
void Csyt01(fem::str_cref uplo, mplapackint const n, mpfc_class *a, mplapackint const lda, mpfc_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpfc_class *c, mplapackint const ldc, mpf_class *rwork, mpf_class &resid);
void Csyt01_3(fem::str_cref uplo, mplapackint const n, mpfc_class *a, mplapackint const lda, mpfc_class *afac, mplapackint const ldafac, mpfc_class *e, mplapackint *ipiv, mpfc_class *c, mplapackint const ldc, mpf_class *rwork, mpf_class &resid);
void Csyt01_aa(fem::str_cref uplo, mplapackint const n, mpfc_class *a, mplapackint const lda, mpfc_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpfc_class *c, mplapackint const ldc, mpf_class *rwork, mpf_class &resid);
void Csyt01_rook(fem::str_cref uplo, mplapackint const n, mpfc_class *a, mplapackint const lda, mpfc_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpfc_class *c, mplapackint const ldc, mpf_class *rwork, mpf_class &resid);
void Csyt02(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mpfc_class *x, mplapackint const ldx, mpfc_class *b, mplapackint const ldb, mpf_class *rwork, mpf_class &resid);
void Csyt03(fem::str_cref uplo, mplapackint const n, mpfc_class *a, mplapackint const lda, mpfc_class *ainv, mplapackint const ldainv, mpfc_class *work, mplapackint const ldwork, mpf_class *rwork, mpf_class &rcond, mpf_class &resid);
void Ctbt02(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpfc_class *ab, mplapackint const ldab, mpfc_class *x, mplapackint const ldx, mpfc_class *b, mplapackint const ldb, mpfc_class *work, mpf_class *rwork, mpf_class &resid);
void Ctbt03(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpfc_class *ab, mplapackint const ldab, mpf_class const scale, mpf_class *cnorm, mpf_class const tscal, mpfc_class *x, mplapackint const ldx, mpfc_class *b, mplapackint const ldb, mpfc_class *work, mpf_class &resid);
void Ctbt05(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpfc_class *ab, mplapackint const ldab, mpfc_class *b, mplapackint const ldb, mpfc_class *x, mplapackint const ldx, mpfc_class *xact, mplapackint const ldxact, mpf_class *ferr, mpf_class *berr, mpf_class *reslts);
void Ctbt06(mpf_class const rcond, mpf_class const rcondc, fem::str_cref uplo, fem::str_cref diag, mplapackint const n, mplapackint const kd, mpfc_class *ab, mplapackint const ldab, mpf_class *rwork, mpf_class &rat);
void Ctpt01(fem::str_cref uplo, fem::str_cref diag, mplapackint const n, mpfc_class *ap, mpfc_class *ainvp, mpf_class &rcond, mpf_class *rwork, mpf_class &resid);
void Ctpt02(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpfc_class *ap, mpfc_class *x, mplapackint const ldx, mpfc_class *b, mplapackint const ldb, mpfc_class *work, mpf_class *rwork, mpf_class &resid);
void Ctpt03(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpfc_class *ap, mpf_class const scale, mpf_class *cnorm, mpf_class const tscal, mpfc_class *x, mplapackint const ldx, mpfc_class *b, mplapackint const ldb, mpfc_class *work, mpf_class &resid);
void Ctpt05(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpfc_class *ap, mpfc_class *b, mplapackint const ldb, mpfc_class *x, mplapackint const ldx, mpfc_class *xact, mplapackint const ldxact, mpf_class *ferr, mpf_class *berr, mpf_class *reslts);
void Ctpt06(mpf_class const rcond, mpf_class const rcondc, fem::str_cref uplo, fem::str_cref diag, mplapackint const n, mpfc_class *ap, mpf_class *rwork, mpf_class &rat);
void Ctrt01(fem::str_cref uplo, fem::str_cref diag, mplapackint const n, mpfc_class *a, mplapackint const lda, mpfc_class *ainv, mplapackint const ldainv, mpf_class &rcond, mpf_class *rwork, mpf_class &resid);
void Ctrt02(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mpfc_class *x, mplapackint const ldx, mpfc_class *b, mplapackint const ldb, mpfc_class *work, mpf_class *rwork, mpf_class &resid);
void Ctrt03(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mpf_class const scale, mpf_class *cnorm, mpf_class const tscal, mpfc_class *x, mplapackint const ldx, mpfc_class *b, mplapackint const ldb, mpfc_class *work, mpf_class &resid);
void Ctrt05(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpfc_class *a, mplapackint const lda, mpfc_class *b, mplapackint const ldb, mpfc_class *x, mplapackint const ldx, mpfc_class *xact, mplapackint const ldxact, mpf_class *ferr, mpf_class *berr, mpf_class *reslts);
void Ctrt06(mpf_class const rcond, mpf_class const rcondc, fem::str_cref uplo, fem::str_cref diag, mplapackint const n, mpfc_class *a, mplapackint const lda, mpf_class *rwork, mpf_class &rat);
void Ctsqr01(fem::str_cref tssw, mplapackint const m, mplapackint const n, mplapackint const mb, mplapackint const nb, mpf_class *result);
void Cunhr_col01(mplapackint const m, mplapackint const n, mplapackint const mb1, mplapackint const nb1, mplapackint const nb2, mpf_class *result);
void Cunhr_col02(mplapackint const m, mplapackint const n, mplapackint const mb1, mplapackint const nb1, mplapackint const nb2, mpf_class *result);
void Mxerbla_gmp(const char *srname, int info);
void Mxlaenv(mplapackint const ispec, mplapackint const nvalue);
void Rchkeq(mpf_class const thresh, mplapackint const nout);
void Rchkgb(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mpf_class *a, mplapackint const la, mpf_class *afac, mplapackint const lafac, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchkge(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpf_class *a, mpf_class *afac, mpf_class *ainv, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchkgt(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mpf_class *a, mpf_class *af, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchklq(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpf_class *a, mpf_class *af, mpf_class *aq, mpf_class *al, mpf_class *ac, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *tau, mpf_class *work, mpf_class *rwork, mplapackint const nout);
void Rchklqt(mpf_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Rchklqtp(mpf_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Rchkorhr_col(mpf_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Rchkpb(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpf_class *a, mpf_class *afac, mpf_class *ainv, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchkpo(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpf_class *a, mpf_class *afac, mpf_class *ainv, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchkpp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpf_class *a, mpf_class *afac, mpf_class *ainv, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchkps(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nrank, mplapackint *rankval, mpf_class const thresh, bool const tsterr, mplapackint const, mpf_class *a, mpf_class *afac, mpf_class *perm, mplapackint *piv, mpf_class *work, mpf_class *rwork, mplapackint const nout);
void Rchkpt(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mpf_class *a, mpf_class *d, mpf_class *e, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint const nout);
void Rchkq3(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mpf_class const thresh, mpf_class *a, mpf_class *copya, mpf_class *s, mpf_class *tau, mpf_class *work, mplapackint *iwork, mplapackint const nout);
void Rchkql(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpf_class *a, mpf_class *af, mpf_class *aq, mpf_class *al, mpf_class *ac, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *tau, mpf_class *work, mpf_class *rwork, mplapackint const nout);
void Rchkqp3rk(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mpf_class const thresh, mpf_class *a, mpf_class *copya, mpf_class *b, mpf_class *copyb, mpf_class *s, mpf_class *tau, mpf_class *work, mplapackint *iwork, mplapackint const nout);
void Rchkqr(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpf_class *a, mpf_class *af, mpf_class *aq, mpf_class *ar, mpf_class *ac, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *tau, mpf_class *work, mpf_class *rwork, mplapackint *, mplapackint const nout);
void Rchkqrt(mpf_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Rchkqrtp(mpf_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Rchkrq(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpf_class *a, mpf_class *af, mpf_class *aq, mpf_class *ar, mpf_class *ac, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *tau, mpf_class *work, mpf_class *rwork, mplapackint *, mplapackint const nout);
void Rchksp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpf_class *a, mpf_class *afac, mpf_class *ainv, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchksy(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpf_class *a, mpf_class *afac, mpf_class *ainv, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchksy_aa(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpf_class *a, mpf_class *afac, mpf_class *ainv, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchksy_aa_2stage(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpf_class *a, mpf_class *afac, mpf_class *ainv, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchksy_rk(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpf_class *a, mpf_class *afac, mpf_class *e, mpf_class *ainv, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchksy_rook(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpf_class *a, mpf_class *afac, mpf_class *ainv, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchktb(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpf_class *ab, mpf_class *ainv, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchktp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const, mpf_class *ap, mpf_class *ainvp, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchktr(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpf_class *a, mpf_class *ainv, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchktsqr(mpf_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Rchktz(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mpf_class const thresh, bool const tsterr, mpf_class *a, mpf_class *copya, mpf_class *s, mpf_class *tau, mpf_class *work, mplapackint const nout);
void Rdrvgb(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mpf_class *a, mplapackint const la, mpf_class *afb, mplapackint const lafb, mpf_class *asav, mpf_class *b, mpf_class *bsav, mpf_class *x, mpf_class *xact, mpf_class *s, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvge(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpf_class *a, mpf_class *afac, mpf_class *asav, mpf_class *b, mpf_class *bsav, mpf_class *x, mpf_class *xact, mpf_class *s, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvgt(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mpf_class *a, mpf_class *af, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvls(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mpf_class const thresh, bool const tsterr, mpf_class *a, mpf_class *copya, mpf_class *b, mpf_class *copyb, mpf_class *c, mpf_class *s, mpf_class *copys, mplapackint const nout);
void Rdrvpb(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const, mpf_class *a, mpf_class *afac, mpf_class *asav, mpf_class *b, mpf_class *bsav, mpf_class *x, mpf_class *xact, mpf_class *s, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvpo(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const, mpf_class *a, mpf_class *afac, mpf_class *asav, mpf_class *b, mpf_class *bsav, mpf_class *x, mpf_class *xact, mpf_class *s, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvpp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const, mpf_class *a, mpf_class *afac, mpf_class *asav, mpf_class *b, mpf_class *bsav, mpf_class *x, mpf_class *xact, mpf_class *s, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvpt(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mpf_class *a, mpf_class *d, mpf_class *e, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint const nout);
void Rdrvrf1(mplapackint const nout, mplapackint const nn, mplapackint *nval, mpf_class const thresh, mpf_class *a, mplapackint const lda, mpf_class *arf, mpf_class *work);
void Rdrvrf2(mplapackint const nout, mplapackint const nn, mplapackint *nval, mpf_class *a, mplapackint const lda, mpf_class *arf, mpf_class *ap, mpf_class *asav);
void Rdrvrf3(mplapackint const nout, mplapackint const nn, mplapackint *nval, mpf_class const thresh, mpf_class *a, mplapackint const lda, mpf_class *arf, mpf_class *b1, mpf_class *b2, mpf_class *d_work_dlange, mpf_class *d_work_dgeqrf, mpf_class *tau);
void Rdrvrf4(mplapackint const nout, mplapackint const nn, mplapackint *nval, mpf_class const thresh, mpf_class *c1, mpf_class *c2, mplapackint const ldc, mpf_class *crf, mpf_class *a, mplapackint const lda, mpf_class *d_work_dlange);
void Rdrvrfp(mplapackint const nout, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mplapackint const nnt, mplapackint *ntval, mpf_class const thresh, mpf_class *a, mpf_class *asav, mpf_class *afac, mpf_class *ainv, mpf_class *b, mpf_class *bsav, mpf_class *xact, mpf_class *x, mpf_class *arf, mpf_class *arfinv, mpf_class *d_work_dlatms, mpf_class *d_work_dpot01, mpf_class *d_temp_dpot02, mpf_class *d_temp_dpot03, mpf_class *d_work_dlansy, mpf_class *d_work_dpot02, mpf_class *d_work_dpot03);
void Rdrvsp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpf_class *a, mpf_class *afac, mpf_class *ainv, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvsy(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpf_class *a, mpf_class *afac, mpf_class *ainv, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvsy_aa(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const, mpf_class *a, mpf_class *afac, mpf_class *ainv, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvsy_aa_2stage(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpf_class *a, mpf_class *afac, mpf_class *ainv, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvsy_rk(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpf_class *a, mpf_class *afac, mpf_class *e, mpf_class *ainv, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvsy_rook(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpf_class const thresh, bool const tsterr, mplapackint const nmax, mpf_class *a, mpf_class *afac, mpf_class *ainv, mpf_class *b, mpf_class *x, mpf_class *xact, mpf_class *work, mpf_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rerrge(fem::str_cref path, mplapackint const nunit);
void Rerrgt(fem::str_cref path, mplapackint const nunit);
void Rerrlq(fem::str_cref path, mplapackint const nunit);
void Rerrlqt(fem::str_cref path, mplapackint const nunit);
void Rerrlqtp(fem::str_cref path, mplapackint const nunit);
void Rerrls(fem::str_cref path, mplapackint const nunit);
void Rerrorhr_col(fem::str_cref path, mplapackint const nunit);
void Rerrpo(fem::str_cref path, mplapackint const nunit);
void Rerrps(fem::str_cref path, mplapackint const nunit);
void Rerrql(fem::str_cref path, mplapackint const nunit);
void Rerrqp(fem::str_cref path, mplapackint const nunit);
void Rerrqr(fem::str_cref path, mplapackint const nunit);
void Rerrqrt(fem::str_cref path, mplapackint const nunit);
void Rerrqrtp(fem::str_cref path, mplapackint const nunit);
void Rerrrfp(mplapackint const nunit);
void Rerrrq(fem::str_cref path, mplapackint const nunit);
void Rerrsy(fem::str_cref path, mplapackint const nunit);
void Rerrtr(fem::str_cref path, mplapackint const nunit);
void Rerrtsqr(fem::str_cref path, mplapackint const nunit);
void Rerrtz(fem::str_cref path, mplapackint const nunit);
void Rerrvx(fem::str_cref path, mplapackint const nunit);
void Rgbt01(mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mpf_class *a, mplapackint const lda, mpf_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpf_class *work, mpf_class &resid);
void Rgbt02(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *x, mplapackint const ldx, mpf_class *b, mplapackint const ldb, mpf_class *rwork, mpf_class &resid);
void Rgbt05(fem::str_cref trans, mplapackint const n, mplapackint const kl, mplapackint const ku, mplapackint const nrhs, mpf_class *ab, mplapackint const ldab, mpf_class *b, mplapackint const ldb, mpf_class *x, mplapackint const ldx, mpf_class *xact, mplapackint const ldxact, mpf_class *ferr, mpf_class *berr, mpf_class *reslts);
void Rgeqls(mplapackint const m, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *b, mplapackint const ldb, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rgerqs(mplapackint const m, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *b, mplapackint const ldb, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rget01(mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpf_class *rwork, mpf_class &resid);
void Rget02(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *x, mplapackint const ldx, mpf_class *b, mplapackint const ldb, mpf_class *rwork, mpf_class &resid);
void Rget03(mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *ainv, mplapackint const ldainv, mpf_class *work, mplapackint const ldwork, mpf_class *rwork, mpf_class &rcond, mpf_class &resid);
void Rget04(mplapackint const n, mplapackint const nrhs, mpf_class *x, mplapackint const ldx, mpf_class *xact, mplapackint const ldxact, mpf_class const rcond, mpf_class &resid);
void Rget07(fem::str_cref trans, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *b, mplapackint const ldb, mpf_class *x, mplapackint const ldx, mpf_class *xact, mplapackint const ldxact, mpf_class *ferr, bool const chkferr, mpf_class *berr, mpf_class *reslts);
void Rget08(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *x, mplapackint const ldx, mpf_class *b, mplapackint const ldb, mpf_class *rwork, mpf_class &resid);
void Rgtt01(mplapackint const n, mpf_class *dl, mpf_class *d, mpf_class *du, mpf_class *dlf, mpf_class *df, mpf_class *duf, mpf_class *du2, mplapackint *ipiv, mpf_class *work, mplapackint const ldwork, mpf_class *rwork, mpf_class &resid);
void Rgtt02(fem::str_cref trans, mplapackint const n, mplapackint const nrhs, mpf_class *dl, mpf_class *d, mpf_class *du, mpf_class *x, mplapackint const ldx, mpf_class *b, mplapackint const ldb, mpf_class &resid);
void Rgtt05(fem::str_cref trans, mplapackint const n, mplapackint const nrhs, mpf_class *dl, mpf_class *d, mpf_class *du, mpf_class *b, mplapackint const ldb, mpf_class *x, mplapackint const ldx, mpf_class *xact, mplapackint const ldxact, mpf_class *ferr, mpf_class *berr, mpf_class *reslts);
void Rlahilb(mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *x, mplapackint const ldx, mpf_class *b, mplapackint const ldb, mpf_class *work, mplapackint &info);
void Rlaord(fem::str_cref job, mplapackint const n, mpf_class *x, mplapackint const incx);
void Rlaptm(mplapackint const n, mplapackint const nrhs, mpf_class const alpha, mpf_class *d, mpf_class *e, mpf_class *x, mplapackint const ldx, mpf_class const beta, mpf_class *b, mplapackint const ldb);
void Rlarhs(fem::str_cref path, fem::str_cref xtype, fem::str_cref uplo, fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *x, mplapackint const ldx, mpf_class *b, mplapackint const ldb, mplapackint (&iseed)[4], mplapackint &info);
void Rlatb4(fem::str_cref path, mplapackint const imat, mplapackint const m, mplapackint const n, fem::str_ref type, mplapackint &kl, mplapackint &ku, mpf_class &anorm, mplapackint &mode, mpf_class &cndnum, fem::str_ref dist);
void Rlatb5(fem::str_cref path, mplapackint const imat, mplapackint const n, fem::str_ref type, mplapackint &kl, mplapackint &ku, mpf_class &anorm, mplapackint &mode, mpf_class &cndnum, fem::str_ref dist);
void Rlattb(mplapackint const imat, fem::str_cref uplo, fem::str_cref trans, fem::str_ref diag, mplapackint (&iseed)[4], mplapackint const n, mplapackint const kd, mpf_class *ab, mplapackint const ldab, mpf_class *b, mpf_class *work, mplapackint &info);
void Rlattp(mplapackint const imat, fem::str_cref uplo, fem::str_cref trans, fem::str_ref diag, mplapackint (&iseed)[4], mplapackint const n, mpf_class *a, mpf_class *b, mpf_class *work, mplapackint &info);
void Rlattr(mplapackint const imat, fem::str_cref uplo, fem::str_cref trans, fem::str_ref diag, mplapackint (&iseed)[4], mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *b, mpf_class *work, mplapackint &info);
void Rlavsp(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint *ipiv, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rlavsy(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rlavsy_rook(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rlqt01(mplapackint const m, mplapackint const n, mpf_class *a, mpf_class *af, mpf_class *q, mpf_class *l, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Rlqt02(mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *a, mpf_class *af, mpf_class *q, mpf_class *l, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Rlqt03(mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *af, mpf_class *c, mpf_class *cc, mpf_class *q, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Rlqt04(mplapackint const m, mplapackint const n, mplapackint const nb, mpf_class *result);
void Rlqt05(mplapackint const m, mplapackint const n, mplapackint const l, mplapackint const nb, mpf_class *result);
void Rorhr_col01(mplapackint const m, mplapackint const n, mplapackint const mb1, mplapackint const nb1, mplapackint const nb2, mpf_class *result);
void Rorhr_col02(mplapackint const m, mplapackint const n, mplapackint const mb1, mplapackint const nb1, mplapackint const nb2, mpf_class *result);
void Rpbt01(fem::str_cref uplo, mplapackint const n, mplapackint const kd, mpf_class *a, mplapackint const lda, mpf_class *afac, mplapackint const ldafac, mpf_class *rwork, mpf_class &resid);
void Rpbt02(fem::str_cref uplo, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *x, mplapackint const ldx, mpf_class *b, mplapackint const ldb, mpf_class *rwork, mpf_class &resid);
void Rpbt05(fem::str_cref uplo, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpf_class *ab, mplapackint const ldab, mpf_class *b, mplapackint const ldb, mpf_class *x, mplapackint const ldx, mpf_class *xact, mplapackint const ldxact, mpf_class *ferr, mpf_class *berr, mpf_class *reslts);
void Rpot01(fem::str_cref uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *afac, mplapackint const ldafac, mpf_class *rwork, mpf_class &resid);
void Rpot02(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *x, mplapackint const ldx, mpf_class *b, mplapackint const ldb, mpf_class *rwork, mpf_class &resid);
void Rpot03(fem::str_cref uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *ainv, mplapackint const ldainv, mpf_class *work, mplapackint const ldwork, mpf_class *rwork, mpf_class &rcond, mpf_class &resid);
void Rpot05(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *b, mplapackint const ldb, mpf_class *x, mplapackint const ldx, mpf_class *xact, mplapackint const ldxact, mpf_class *ferr, mpf_class *berr, mpf_class *reslts);
void Rpot06(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *x, mplapackint const ldx, mpf_class *b, mplapackint const ldb, mpf_class *rwork, mpf_class &resid);
void Rppt01(fem::str_cref uplo, mplapackint const n, mpf_class *a, mpf_class *afac, mpf_class *rwork, mpf_class &resid);
void Rppt02(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpf_class *a, mpf_class *x, mplapackint const ldx, mpf_class *b, mplapackint const ldb, mpf_class *rwork, mpf_class &resid);
void Rppt03(fem::str_cref uplo, mplapackint const n, mpf_class *a, mpf_class *ainv, mpf_class *work, mplapackint const ldwork, mpf_class *rwork, mpf_class &rcond, mpf_class &resid);
void Rppt05(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpf_class *ap, mpf_class *b, mplapackint const ldb, mpf_class *x, mplapackint const ldx, mpf_class *xact, mplapackint const ldxact, mpf_class *ferr, mpf_class *berr, mpf_class *reslts);
void Rpst01(fem::str_cref uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *afac, mplapackint const ldafac, mpf_class *perm, mplapackint const ldperm, mplapackint *piv, mpf_class *rwork, mpf_class &resid, mplapackint const rank);
void Rptt01(mplapackint const n, mpf_class *d, mpf_class *e, mpf_class *df, mpf_class *ef, mpf_class *work, mpf_class &resid);
void Rptt02(mplapackint const n, mplapackint const nrhs, mpf_class *d, mpf_class *e, mpf_class *x, mplapackint const ldx, mpf_class *b, mplapackint const ldb, mpf_class &resid);
void Rptt05(mplapackint const n, mplapackint const nrhs, mpf_class *d, mpf_class *e, mpf_class *b, mplapackint const ldb, mpf_class *x, mplapackint const ldx, mpf_class *xact, mplapackint const ldxact, mpf_class *ferr, mpf_class *berr, mpf_class *reslts);
void Rqlt01(mplapackint const m, mplapackint const n, mpf_class *a, mpf_class *af, mpf_class *q, mpf_class *l, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Rqlt02(mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *a, mpf_class *af, mpf_class *q, mpf_class *l, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Rqlt03(mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *af, mpf_class *c, mpf_class *cc, mpf_class *q, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Rqrt01(mplapackint const m, mplapackint const n, mpf_class *a, mpf_class *af, mpf_class *q, mpf_class *r, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Rqrt01p(mplapackint const m, mplapackint const n, mpf_class *a, mpf_class *af, mpf_class *q, mpf_class *r, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Rqrt02(mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *a, mpf_class *af, mpf_class *q, mpf_class *r, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Rqrt03(mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *af, mpf_class *c, mpf_class *cc, mpf_class *q, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Rqrt04(mplapackint const m, mplapackint const n, mplapackint const nb, mpf_class *result);
void Rqrt05(mplapackint const m, mplapackint const n, mplapackint const l, mplapackint const nb, mpf_class *result);
void Rqrt13(mplapackint const scale, mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class &norma, mplapackint (&iseed)[4]);
void Rqrt15(mplapackint const scale, mplapackint const rksel, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *b, mplapackint const ldb, mpf_class *s, mplapackint &rank, mpf_class &norma, mpf_class &normb, mplapackint (&iseed)[4], mpf_class *work, mplapackint const lwork);
void Rqrt16(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *x, mplapackint const ldx, mpf_class *b, mplapackint const ldb, mpf_class *rwork, mpf_class &resid);
void Rrqt01(mplapackint const m, mplapackint const n, mpf_class *a, mpf_class *af, mpf_class *q, mpf_class *r, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Rrqt02(mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *a, mpf_class *af, mpf_class *q, mpf_class *r, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Rrqt03(mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *af, mpf_class *c, mpf_class *cc, mpf_class *q, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork, mpf_class *rwork, mpf_class *result);
void Rspt01(fem::str_cref uplo, mplapackint const n, mpf_class *a, mpf_class *afac, mplapackint *ipiv, mpf_class *c, mplapackint const ldc, mpf_class *rwork, mpf_class &resid);
void Rsyt01(fem::str_cref uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpf_class *c, mplapackint const ldc, mpf_class *rwork, mpf_class &resid);
void Rsyt01_3(fem::str_cref uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *afac, mplapackint const ldafac, mpf_class *e, mplapackint *ipiv, mpf_class *c, mplapackint const ldc, mpf_class *rwork, mpf_class &resid);
void Rsyt01_aa(fem::str_cref uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpf_class *c, mplapackint const ldc, mpf_class *rwork, mpf_class &resid);
void Rsyt01_rook(fem::str_cref uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpf_class *c, mplapackint const ldc, mpf_class *rwork, mpf_class &resid);
void Rtbt02(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpf_class *ab, mplapackint const ldab, mpf_class *x, mplapackint const ldx, mpf_class *b, mplapackint const ldb, mpf_class *work, mpf_class &resid);
void Rtbt03(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpf_class *ab, mplapackint const ldab, mpf_class const scale, mpf_class *cnorm, mpf_class const tscal, mpf_class *x, mplapackint const ldx, mpf_class *b, mplapackint const ldb, mpf_class *work, mpf_class &resid);
void Rtbt05(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpf_class *ab, mplapackint const ldab, mpf_class *b, mplapackint const ldb, mpf_class *x, mplapackint const ldx, mpf_class *xact, mplapackint const ldxact, mpf_class *ferr, mpf_class *berr, mpf_class *reslts);
void Rtbt06(mpf_class const rcond, mpf_class const rcondc, fem::str_cref uplo, fem::str_cref diag, mplapackint const n, mplapackint const kd, mpf_class *ab, mplapackint const ldab, mpf_class *work, mpf_class &rat);
void Rtplqt(mplapackint const m, mplapackint const n, mplapackint const l, mplapackint const mb, mpf_class *a, mplapackint const lda, mpf_class *b, mplapackint const ldb, mpf_class *t, mplapackint const ldt, mpf_class *work, mplapackint &info);
void Rtpt01(fem::str_cref uplo, fem::str_cref diag, mplapackint const n, mpf_class *ap, mpf_class *ainvp, mpf_class &rcond, mpf_class *work, mpf_class &resid);
void Rtpt02(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpf_class *ap, mpf_class *x, mplapackint const ldx, mpf_class *b, mplapackint const ldb, mpf_class *work, mpf_class &resid);
void Rtpt03(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpf_class *ap, mpf_class const scale, mpf_class *cnorm, mpf_class const tscal, mpf_class *x, mplapackint const ldx, mpf_class *b, mplapackint const ldb, mpf_class *work, mpf_class &resid);
void Rtpt05(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpf_class *ap, mpf_class *b, mplapackint const ldb, mpf_class *x, mplapackint const ldx, mpf_class *xact, mplapackint const ldxact, mpf_class *ferr, mpf_class *berr, mpf_class *reslts);
void Rtpt06(mpf_class const rcond, mpf_class const rcondc, fem::str_cref uplo, fem::str_cref diag, mplapackint const n, mpf_class *ap, mpf_class *work, mpf_class &rat);
void Rtrt01(fem::str_cref uplo, fem::str_cref diag, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *ainv, mplapackint const ldainv, mpf_class &rcond, mpf_class *work, mpf_class &resid);
void Rtrt02(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *x, mplapackint const ldx, mpf_class *b, mplapackint const ldb, mpf_class *work, mpf_class &resid);
void Rtrt03(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class const scale, mpf_class *cnorm, mpf_class const tscal, mpf_class *x, mplapackint const ldx, mpf_class *b, mplapackint const ldb, mpf_class *work, mpf_class &resid);
void Rtrt05(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *b, mplapackint const ldb, mpf_class *x, mplapackint const ldx, mpf_class *xact, mplapackint const ldxact, mpf_class *ferr, mpf_class *berr, mpf_class *reslts);
void Rtrt06(mpf_class const rcond, mpf_class const rcondc, fem::str_cref uplo, fem::str_cref diag, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *work, mpf_class &rat);
void Rtsqr01(fem::str_cref tssw, mplapackint const m, mplapackint const n, mplapackint const mb, mplapackint const nb, mpf_class *result);
void icopy(mplapackint const n, mplapackint *sx, mplapackint const incx, mplapackint *sy, mplapackint const incy);
#endif
