/*
 * Copyright (c) 2008-2021
 *	Nakata, Maho
 * 	All rights reserved.
 *
 * $Id: mplapack_gmp.h,v 1.34 2010/08/07 03:15:46 nakatamaho Exp $
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 */

#ifndef _MPLAPACK_GMP_H_
#define _MPLAPACK_GMP_H_

#include "mplapack_config.h"
#include "gmpxx.h"
#include "mpc_class.h"

bool Risnan(mpf_class const din);
bool Rlaisnan(mpf_class const din1, mpf_class const din2);
mpc_class Cladiv(mpc_class const x, mpc_class const y);
mpf_class Clangt(const char *norm, mplapackint const n, mpc_class *dl, mpc_class *d, mpc_class *du);
mpf_class Clanhe(const char *norm, const char *uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpf_class *work);
mpf_class Clanht(const char *norm, mplapackint const n, mpf_class *d, mpc_class *e);
mpf_class Clansy(const char *norm, const char *uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpf_class *work);
mpf_class RCsum1(mplapackint const n, mpc_class *cx, mplapackint const incx);
mpf_class Rla_gerpvgrw(mplapackint const n, mplapackint const ncols, mpf_class *a, mplapackint const lda, mpf_class *af, mplapackint const ldaf);
mpf_class Rladiv2(mpf_class const &a, mpf_class const &b, mpf_class const &c, mpf_class const &d, mpf_class const &r, mpf_class const &t);
mpf_class Rladiv2(mpf_class const &a, mpf_class const &b, mpf_class const &c, mpf_class const &d, mpf_class const &r, mpf_class const &t);
mpf_class Rlamch_gmp(const char *cmach);
mpf_class Rlangt(const char *norm, mplapackint const n, mpf_class *dl, mpf_class *d, mpf_class *du);
mpf_class Rlanst(const char *norm, mplapackint const n, mpf_class *d, mpf_class *e);
mpf_class Rlansy(const char *norm, const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *work);
mpf_class Rlapy2(mpf_class const x, mpf_class const y);
mpf_class Rlapy3(mpf_class const x, mpf_class const y, mpf_class const z);
mpf_class abs1(mpc_class ff);
mpf_class abs1(mpc_class ff);
mpf_class abs1(mpc_class ff);
mpf_class abssq(mpc_class ff);
mpf_class abssq(mpc_class ff);
mplapackint Rlaneg(mplapackint const n, mpf_class *d, mpf_class *lld, mpf_class const sigma, mpf_class const, mplapackint const r);
mplapackint iCmax1(mplapackint const n, mpc_class *zx, mplapackint const incx);
mplapackint iMladlc(mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda);
mplapackint iMladlr(mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda);
mplapackint iMlaenv_gmp(mplapackint ispec, const char *name, const char *opts, mplapackint n1, mplapackint n2, mplapackint n3, mplapackint n4);
mplapackint iMlazlc(mplapackint const m, mplapackint const n, mpc_class *a, mplapackint const lda);
mplapackint iMlazlr(mplapackint const m, mplapackint const n, mpc_class *a, mplapackint const lda);
void CRrscl(mplapackint const n, mpf_class const sa, mpc_class *sx, mplapackint const incx);
void Cgebak(const char *job, const char *side, mplapackint const n, mplapackint const ilo, mplapackint const ihi, mpf_class *scale, mplapackint const m, mpc_class *v, mplapackint const ldv, mplapackint &info);
void Cgelq(mplapackint const m, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *t, mplapackint const tsize, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Cgelqt(mplapackint const m, mplapackint const n, mplapackint const mb, mpc_class *a, mplapackint const lda, mpc_class *t, mplapackint const ldt, mpc_class *work, mplapackint &info);
void Cgemlqt(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const mb, mpc_class *v, mplapackint const ldv, mpc_class *t, mplapackint const ldt, mpc_class *c, mplapackint const ldc, mpc_class *work, mplapackint &info);
void Cgemqrt(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const nb, mpc_class *v, mplapackint const ldv, mpc_class *t, mplapackint const ldt, mpc_class *c, mplapackint const ldc, mpc_class *work, mplapackint &info);
void Cgeqr(mplapackint const m, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *t, mplapackint const tsize, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Cgeqrt(mplapackint const m, mplapackint const n, mplapackint const nb, mpc_class *a, mplapackint const lda, mpc_class *t, mplapackint const ldt, mpc_class *work, mplapackint &info);
void Cgesv(mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Cgetc2(mplapackint const n, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mplapackint *jpiv, mplapackint &info);
void Cgetf2(mplapackint const m, mplapackint const n, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mplapackint &info);
void Cgetrf(mplapackint const m, mplapackint const n, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mplapackint &info);
void Cgetrf2(mplapackint const m, mplapackint const n, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mplapackint &info);
void Cgetri(mplapackint const n, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Cgetrs(const char *trans, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Cggbak(const char *job, const char *side, mplapackint const n, mplapackint const ilo, mplapackint const ihi, mpf_class *lscale, mpf_class *rscale, mplapackint const m, mpc_class *v, mplapackint const ldv, mplapackint &info);
void Cgtts2(mplapackint const itrans, mplapackint const n, mplapackint const nrhs, mpc_class *dl, mpc_class *d, mpc_class *du, mpc_class *du2, mplapackint *ipiv, mpc_class *b, mplapackint const ldb);
void Cheev(const char *jobz, const char *uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpf_class *w, mpc_class *work, mplapackint const lwork, mpf_class *rwork, mplapackint &info);
void Chegst(mplapackint const itype, const char *uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Chesv(const char *uplo, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Chesv_rook(const char *uplo, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Chetd2(const char *uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpf_class *d, mpf_class *e, mpc_class *tau, mplapackint &info);
void Chetrd(const char *uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpf_class *d, mpf_class *e, mpc_class *tau, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Chetri(const char *uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *work, mplapackint &info);
void Chetri2(const char *uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Chetri_3(const char *uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *e, mplapackint *ipiv, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Chetri_rook(const char *uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *work, mplapackint &info);
void Chetrs(const char *uplo, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Chetrs2(const char *uplo, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mpc_class *work, mplapackint &info);
void Chetrs_3(const char *uplo, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *e, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Chetrs_aa(const char *uplo, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Chetrs_rook(const char *uplo, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Chfrk(const char *transr, const char *uplo, const char *trans, mplapackint const n, mplapackint const k, mpf_class const alpha, mpc_class *a, mplapackint const lda, mpf_class const beta, mpc_class *c);
void Chpsv(const char *uplo, mplapackint const n, mplapackint const nrhs, mpc_class *ap, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Cla_wwaddw(mplapackint const n, mpc_class *x, mpc_class *y, mpc_class *w);
void Clacgv(mplapackint const n, mpc_class *x, mplapackint const incx);
void Clacp2(const char *uplo, mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb);
void Clacpy(const char *uplo, mplapackint const m, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb);
void Clacrm(mplapackint const m, mplapackint const n, mpc_class *a, mplapackint const lda, mpf_class *b, mplapackint const ldb, mpc_class *c, mplapackint const ldc, mpf_class *rwork);
void Clacrt(mplapackint const n, mpc_class *cx, mplapackint const incx, mpc_class *cy, mplapackint const incy, mpc_class const c, mpc_class const s);
void Claesy(mpc_class const a, mpc_class const b, mpc_class const c, mpc_class &rt1, mpc_class &rt2, mpc_class &evscal, mpc_class &cs1, mpc_class &sn1);
void Claev2(mpc_class const a, mpc_class const b, mpc_class const c, mpf_class &rt1, mpf_class &rt2, mpf_class &cs1, mpc_class &sn1);
void Clagtm(const char *trans, mplapackint const n, mplapackint const nrhs, mpf_class const alpha, mpc_class *dl, mpc_class *d, mpc_class *du, mpc_class *x, mplapackint const ldx, mpf_class const beta, mpc_class *b, mplapackint const ldb);
void Clahef(const char *uplo, mplapackint const n, mplapackint const nb, mplapackint &kb, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *w, mplapackint const ldw, mplapackint &info);
void Clapmr(bool const forwrd, mplapackint const m, mplapackint const n, mpc_class *x, mplapackint const ldx, mplapackint *k);
void Clapmt(bool const forwrd, mplapackint const m, mplapackint const n, mpc_class *x, mplapackint const ldx, mplapackint *k);
void Claqgb(mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mpc_class *ab, mplapackint const ldab, mpf_class *r, mpf_class *c, mpf_class const rowcnd, mpf_class const colcnd, mpf_class const amax, char *equed);
void Claqge(mplapackint const m, mplapackint const n, mpc_class *a, mplapackint const lda, mpf_class *r, mpf_class *c, mpf_class const rowcnd, mpf_class const colcnd, mpf_class const amax, char *equed);
void Claqhb(const char *uplo, mplapackint const n, mplapackint const kd, mpc_class *ab, mplapackint const ldab, mpf_class *s, mpf_class const scond, mpf_class const amax, char *equed);
void Claqhe(const char *uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpf_class *s, mpf_class const scond, mpf_class const amax, char *equed);
void Claqhp(const char *uplo, mplapackint const n, mpc_class *ap, mpf_class *s, mpf_class const scond, mpf_class const amax, char *equed);
void Claqsb(const char *uplo, mplapackint const n, mplapackint const kd, mpc_class *ab, mplapackint const ldab, mpf_class *s, mpf_class const scond, mpf_class const amax, char *equed);
void Claqsp(const char *uplo, mplapackint const n, mpc_class *ap, mpf_class *s, mpf_class const scond, mpf_class const amax, char *equed);
void Claqsy(const char *uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpf_class *s, mpf_class const scond, mpf_class const amax, char *equed);
void Clar2v(mplapackint const n, mpc_class *x, mpc_class *y, mpc_class *z, mplapackint const incx, mpf_class *c, mpc_class *s, mplapackint const incc);
void Clarf(const char *side, mplapackint const m, mplapackint const n, mpc_class *v, mplapackint const incv, mpc_class const tau, mpc_class *c, mplapackint const ldc, mpc_class *work);
void Clarfb(const char *side, const char *trans, const char *direct, const char *storev, mplapackint const m, mplapackint const n, mplapackint const k, mpc_class *v, mplapackint const ldv, mpc_class *t, mplapackint const ldt, mpc_class *c, mplapackint const ldc, mpc_class *work, mplapackint const ldwork);
void Clarfb_gett(const char *ident, mplapackint const m, mplapackint const n, mplapackint const k, mpc_class *t, mplapackint const ldt, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mpc_class *work, mplapackint const ldwork);
void Clarfg(mplapackint const n, mpc_class &alpha, mpc_class *x, mplapackint const incx, mpc_class &tau);
void Clarft(const char *direct, const char *storev, mplapackint const n, mplapackint const k, mpc_class *v, mplapackint const ldv, mpc_class *tau, mpc_class *t, mplapackint const ldt);
void Clarfx(const char *side, mplapackint const m, mplapackint const n, mpc_class *v, mpc_class const tau, mpc_class *c, mplapackint const ldc, mpc_class *work);
void Clarfy(const char *uplo, mplapackint const n, mpc_class *v, mplapackint const incv, mpc_class const tau, mpc_class *c, mplapackint const ldc, mpc_class *work);
void Clarscl2(mplapackint const m, mplapackint const n, mpf_class *d, mpc_class *x, mplapackint const ldx);
void Clartg(mpc_class const f, mpc_class const g, mpf_class &cs, mpc_class &sn, mpc_class &r);
void Clartv(mplapackint const n, mpc_class *x, mplapackint const incx, mpc_class *y, mplapackint const incy, mpf_class *c, mpc_class *s, mplapackint const incc);
void Clarz(const char *side, mplapackint const m, mplapackint const n, mplapackint const l, mpc_class *v, mplapackint const incv, mpc_class const tau, mpc_class *c, mplapackint const ldc, mpc_class *work);
void Clarzt(const char *direct, const char *storev, mplapackint const n, mplapackint const k, mpc_class *v, mplapackint const ldv, mpc_class *tau, mpc_class *t, mplapackint const ldt);
void Clascl(const char *type, mplapackint const kl, mplapackint const ku, mpf_class const cfrom, mpf_class const cto, mplapackint const m, mplapackint const n, mpc_class *a, mplapackint const lda, mplapackint &info);
void Clascl2(mplapackint const m, mplapackint const n, mpf_class *d, mpc_class *x, mplapackint const ldx);
void Claset(const char *uplo, mplapackint const m, mplapackint const n, mpc_class const alpha, mpc_class const beta, mpc_class *a, mplapackint const lda);
void Clasr(const char *side, const char *pivot, const char *direct, mplapackint const m, mplapackint const n, mpf_class *c, mpf_class *s, mpc_class *a, mplapackint const lda);
void Classq(mplapackint const n, mpc_class *x, mplapackint const incx, mpf_class &scale, mpf_class &sumsq);
void Claswlq(mplapackint const m, mplapackint const n, mplapackint const mb, mplapackint const nb, mpc_class *a, mplapackint const lda, mpc_class *t, mplapackint const ldt, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Claswp(mplapackint const n, mpc_class *a, mplapackint const lda, mplapackint const k1, mplapackint const k2, mplapackint *ipiv, mplapackint const incx);
void Clasyf(const char *uplo, mplapackint const n, mplapackint const nb, mplapackint &kb, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *w, mplapackint const ldw, mplapackint &info);
void Clatrd(const char *uplo, mplapackint const n, mplapackint const nb, mpc_class *a, mplapackint const lda, mpf_class *e, mpc_class *tau, mpc_class *w, mplapackint const ldw);
void Clatsqr(mplapackint const m, mplapackint const n, mplapackint const mb, mplapackint const nb, mpc_class *a, mplapackint const lda, mpc_class *t, mplapackint const ldt, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Claunhr_col_getrfnp(mplapackint const m, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *d, mplapackint &info);
void Clauum(const char *uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mplapackint &info);
void Cpbequ(const char *uplo, mplapackint const n, mplapackint const kd, mpc_class *ab, mplapackint const ldab, mpf_class *s, mpf_class &scond, mpf_class &amax, mplapackint &info);
void Cpbsv(const char *uplo, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpc_class *ab, mplapackint const ldab, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Cpbtrs(const char *uplo, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpc_class *ab, mplapackint const ldab, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Cpoequ(mplapackint const n, mpc_class *a, mplapackint const lda, mpf_class *s, mpf_class &scond, mpf_class &amax, mplapackint &info);
void Cposv(const char *uplo, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Cpotf2(const char *uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mplapackint &info);
void Cpotrf(const char *uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mplapackint &info);
void Cpotrf2(const char *uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mplapackint &info);
void Cpotri(const char *uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mplapackint &info);
void Cpotrs(const char *uplo, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Cppequ(const char *uplo, mplapackint const n, mpc_class *ap, mpf_class *s, mpf_class &scond, mpf_class &amax, mplapackint &info);
void Cppsv(const char *uplo, mplapackint const n, mplapackint const nrhs, mpc_class *ap, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Cpptrs(const char *uplo, mplapackint const n, mplapackint const nrhs, mpc_class *ap, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Cptcon(mplapackint const n, mpf_class *d, mpc_class *e, mpf_class const anorm, mpf_class &rcond, mpf_class *rwork, mplapackint &info);
void Cptsv(mplapackint const n, mplapackint const nrhs, mpf_class *d, mpc_class *e, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Cpttrf(mplapackint const n, mpf_class *d, mpc_class *e, mplapackint &info);
void Cpttrs(const char *uplo, mplapackint const n, mplapackint const nrhs, mpf_class *d, mpc_class *e, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Cptts2(mplapackint const iuplo, mplapackint const n, mplapackint const nrhs, mpf_class *d, mpc_class *e, mpc_class *b, mplapackint const ldb);
void Crot(mplapackint const n, mpc_class *cx, mplapackint const incx, mpc_class *cy, mplapackint const incy, mpf_class const c, mpc_class const s);
void Cspmv(const char *uplo, mplapackint const n, mpc_class const alpha, mpc_class *ap, mpc_class *x, mplapackint const incx, mpc_class const beta, mpc_class *y, mplapackint const incy);
void Cspr(const char *uplo, mplapackint const n, mpc_class const alpha, mpc_class *x, mplapackint const incx, mpc_class *ap);
void Cspsv(const char *uplo, mplapackint const n, mplapackint const nrhs, mpc_class *ap, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Csteqr(const char *compz, mplapackint const n, mpf_class *d, mpf_class *e, mpc_class *z, mplapackint const ldz, mpf_class *work, mplapackint &info);
void Csyconv(const char *uplo, const char *way, mplapackint const n, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *e, mplapackint &info);
void Csyconvf(const char *uplo, const char *way, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *e, mplapackint *ipiv, mplapackint &info);
void Csyconvf_rook(const char *uplo, const char *way, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *e, mplapackint *ipiv, mplapackint &info);
void Csymv(const char *uplo, mplapackint const n, mpc_class const alpha, mpc_class *a, mplapackint const lda, mpc_class *x, mplapackint const incx, mpc_class const beta, mpc_class *y, mplapackint const incy);
void Csyr(const char *uplo, mplapackint const n, mpc_class const alpha, mpc_class *x, mplapackint const incx, mpc_class *a, mplapackint const lda);
void Csytri2(const char *uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Csytri_3(const char *uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *e, mplapackint *ipiv, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Csytrs(const char *uplo, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Csytrs2(const char *uplo, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mpc_class *work, mplapackint &info);
void Csytrs_3(const char *uplo, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *e, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Csytrs_aa(const char *uplo, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Csytrs_rook(const char *uplo, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Ctbtrs(const char *uplo, const char *trans, const char *diag, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpc_class *ab, mplapackint const ldab, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Ctgexc(bool const wantq, bool const wantz, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mpc_class *q, mplapackint const ldq, mpc_class *z, mplapackint const ldz, mplapackint const ifst, mplapackint &ilst, mplapackint &info);
void Ctplqt(mplapackint const m, mplapackint const n, mplapackint const l, mplapackint const mb, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mpc_class *t, mplapackint const ldt, mpc_class *work, mplapackint &info);
void Ctpmlqt(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const l, mplapackint const mb, mpc_class *v, mplapackint const ldv, mpc_class *t, mplapackint const ldt, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mpc_class *work, mplapackint &info);
void Ctpmqrt(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const l, mplapackint const nb, mpc_class *v, mplapackint const ldv, mpc_class *t, mplapackint const ldt, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mpc_class *work, mplapackint &info);
void Ctpqrt(mplapackint const m, mplapackint const n, mplapackint const l, mplapackint const nb, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mpc_class *t, mplapackint const ldt, mpc_class *work, mplapackint &info);
void Ctprfb(const char *side, const char *trans, const char *direct, const char *storev, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const l, mpc_class *v, mplapackint const ldv, mpc_class *t, mplapackint const ldt, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mpc_class *work, mplapackint const ldwork);
void Ctptrs(const char *uplo, const char *trans, const char *diag, mplapackint const n, mplapackint const nrhs, mpc_class *ap, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Ctpttr(const char *uplo, mplapackint const n, mpc_class *ap, mpc_class *a, mplapackint const lda, mplapackint &info);
void Ctrti2(const char *uplo, const char *diag, mplapackint const n, mpc_class *a, mplapackint const lda, mplapackint &info);
void Ctrtri(const char *uplo, const char *diag, mplapackint const n, mpc_class *a, mplapackint const lda, mplapackint &info);
void Ctrtrs(const char *uplo, const char *trans, const char *diag, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Ctrttp(const char *uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *ap, mplapackint &info);
void Cunbdb5(mplapackint const m1, mplapackint const m2, mplapackint const n, mpc_class *x1, mplapackint const incx1, mpc_class *x2, mplapackint const incx2, mpc_class *q1, mplapackint const ldq1, mpc_class *q2, mplapackint const ldq2, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Cunbdb6(mplapackint const m1, mplapackint const m2, mplapackint const n, mpc_class *x1, mplapackint const incx1, mpc_class *x2, mplapackint const incx2, mpc_class *q1, mplapackint const ldq1, mpc_class *q2, mplapackint const ldq2, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Cung2l(mplapackint const m, mplapackint const n, mplapackint const k, mpc_class *a, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint &info);
void Cung2r(mplapackint const m, mplapackint const n, mplapackint const k, mpc_class *a, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint &info);
void Cunghr(mplapackint const n, mplapackint const ilo, mplapackint const ihi, mpc_class *a, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Cungl2(mplapackint const m, mplapackint const n, mplapackint const k, mpc_class *a, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint &info);
void Cungql(mplapackint const m, mplapackint const n, mplapackint const k, mpc_class *a, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Cungqr(mplapackint const m, mplapackint const n, mplapackint const k, mpc_class *a, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Cungr2(mplapackint const m, mplapackint const n, mplapackint const k, mpc_class *a, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint &info);
void Cungtr(const char *uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Cungtsqr(mplapackint const m, mplapackint const n, mplapackint const mb, mplapackint const nb, mpc_class *a, mplapackint const lda, mpc_class *t, mplapackint const ldt, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Cunhr_col(mplapackint const m, mplapackint const n, mplapackint const nb, mpc_class *a, mplapackint const lda, mpc_class *t, mplapackint const ldt, mpc_class *d, mplapackint &info);
void Cunm2l(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mpc_class *a, mplapackint const lda, mpc_class *tau, mpc_class *c, mplapackint const ldc, mpc_class *work, mplapackint &info);
void Cunm2r(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mpc_class *a, mplapackint const lda, mpc_class *tau, mpc_class *c, mplapackint const ldc, mpc_class *work, mplapackint &info);
void Cunml2(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mpc_class *a, mplapackint const lda, mpc_class *tau, mpc_class *c, mplapackint const ldc, mpc_class *work, mplapackint &info);
void Cunmr2(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mpc_class *a, mplapackint const lda, mpc_class *tau, mpc_class *c, mplapackint const ldc, mpc_class *work, mplapackint &info);
void Cunmr3(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const l, mpc_class *a, mplapackint const lda, mpc_class *tau, mpc_class *c, mplapackint const ldc, mpc_class *work, mplapackint &info);
void Rbdsqr(const char *uplo, mplapackint const n, mplapackint const ncvt, mplapackint const nru, mplapackint const ncc, mpf_class *d, mpf_class *e, mpf_class *vt, mplapackint const ldvt, mpf_class *u, mplapackint const ldu, mpf_class *c, mplapackint const ldc, mpf_class *work, mplapackint &info);
void Rcombssq(mpf_class *v1, mpf_class *v2);
void Rgebak(const char *job, const char *side, mplapackint const n, mplapackint const ilo, mplapackint const ihi, mpf_class *scale, mplapackint const m, mpf_class *v, mplapackint const ldv, mplapackint &info);
void Rgebd2(mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *d, mpf_class *e, mpf_class *tauq, mpf_class *taup, mpf_class *work, mplapackint &info);
void Rgebrd(mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *d, mpf_class *e, mpf_class *tauq, mpf_class *taup, mpf_class *work, mplapackint const lwork, int &info);
void Rgelq(mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *t, mplapackint const tsize, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rgelq2(mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint &info);
void Rgelqf(mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rgelqt(mplapackint const m, mplapackint const n, mplapackint const mb, mpf_class *a, mplapackint const lda, mpf_class *t, mplapackint const ldt, mpf_class *work, mplapackint &info);
void Rgemlqt(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const mb, mpf_class *v, mplapackint const ldv, mpf_class *t, mplapackint const ldt, mpf_class *c, mplapackint const ldc, mpf_class *work, mplapackint &info);
void Rgemqrt(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const nb, mpf_class *v, mplapackint const ldv, mpf_class *t, mplapackint const ldt, mpf_class *c, mplapackint const ldc, mpf_class *work, mplapackint &info);
void Rgeqr(mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *t, mplapackint const tsize, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rgeqr2(mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint &info);
void Rgeqrf(mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rgeqrt(mplapackint const m, mplapackint const n, mplapackint const nb, mpf_class *a, mplapackint const lda, mpf_class *t, mplapackint const ldt, mpf_class *work, mplapackint &info);
void Rgesv(mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rgesvd(const char *jobu, const char *jobvt, mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *s, mpf_class *u, mplapackint const ldu, mpf_class *vt, mplapackint const ldvt, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rgetc2(mplapackint const n, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mplapackint *jpiv, mplapackint &info);
void Rgetf2(mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mplapackint &info);
void Rgetrf(mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mplapackint &info);
void Rgetrf2(mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mplapackint &info);
void Rgetri(mplapackint const n, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rgetrs(const char *trans, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rggbak(const char *job, const char *side, mplapackint const n, mplapackint const ilo, mplapackint const ihi, mpf_class *lscale, mpf_class *rscale, mplapackint const m, mpf_class *v, mplapackint const ldv, mplapackint &info);
void Rgtsv(mplapackint const n, mplapackint const nrhs, mpf_class *dl, mpf_class *d, mpf_class *du, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rgttrf(mplapackint const n, mpf_class *dl, mpf_class *d, mpf_class *du, mpf_class *du2, mplapackint *ipiv, mplapackint &info);
void Rgtts2(mplapackint const itrans, mplapackint const n, mplapackint const nrhs, mpf_class *dl, mpf_class *d, mpf_class *du, mpf_class *du2, mplapackint *ipiv, mpf_class *b, mplapackint const ldb);
void Rla_wwaddw(mplapackint const n, mpf_class *x, mpf_class *y, mpf_class *w);
void Rlabad(mpf_class &small, mpf_class &large);
void Rlabrd(mplapackint const m, mplapackint const n, mplapackint const nb, mpf_class *a, mplapackint const lda, mpf_class *d, mpf_class *e, mpf_class *tauq, mpf_class *taup, mpf_class *x, mplapackint const ldx, mpf_class *y, mplapackint const ldy);
void Rlacpy(const char *uplo, mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *b, mplapackint const ldb);
void Rladiv(mpf_class const &a, mpf_class const &b, mpf_class const &c, mpf_class const &d, mpf_class &p, mpf_class &q);
void Rladiv(mpf_class const &a, mpf_class const &b, mpf_class const &c, mpf_class const &d, mpf_class &p, mpf_class &q);
void Rladiv1(mpf_class &a, mpf_class const &b, mpf_class const &c, mpf_class const &d, mpf_class &p, mpf_class &q);
void Rladiv1(mpf_class &a, mpf_class const &b, mpf_class const &c, mpf_class const &d, mpf_class &p, mpf_class &q);
void Rlae2(mpf_class const a, mpf_class const b, mpf_class const c, mpf_class &rt1, mpf_class &rt2);
void Rlaed5(mplapackint const i, mpf_class *d, mpf_class *z, mpf_class *delta, mpf_class const rho, mpf_class &dlam);
void Rlaev2(mpf_class const a, mpf_class const b, mpf_class const c, mpf_class &rt1, mpf_class &rt2, mpf_class &cs1, mpf_class &sn1);
void Rlagtf(mplapackint const n, mpf_class *a, mpf_class const lambda, mpf_class *b, mpf_class *c, mpf_class const tol, mpf_class *d, mplapackint *in, mplapackint &info);
void Rlagtm(const char *trans, mplapackint const n, mplapackint const nrhs, mpf_class const alpha, mpf_class *dl, mpf_class *d, mpf_class *du, mpf_class *x, mplapackint const ldx, mpf_class const beta, mpf_class *b, mplapackint const ldb);
void Rlaic1(mplapackint const job, mplapackint const j, mpf_class *x, mpf_class const sest, mpf_class *w, mpf_class const gamma, mpf_class &sestpr, mpf_class &s, mpf_class &c);
void Rlamrg(mplapackint const n1, mplapackint const n2, mpf_class *a, mplapackint const dtrd1, mplapackint const dtrd2, mplapackint *index);
void Rlanv2(mpf_class &a, mpf_class &b, mpf_class &c, mpf_class &d, mpf_class &rt1r, mpf_class &rt1i, mpf_class &rt2r, mpf_class &rt2i, mpf_class &cs, mpf_class &sn);
void Rlaorhr_col_getrfnp(mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *d, mplapackint &info);
void Rlaorhr_col_getrfnp2(mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *d, mplapackint &info);
void Rlapmr(bool const forwrd, mplapackint const m, mplapackint const n, mpf_class *x, mplapackint const ldx, mplapackint *k);
void Rlapmt(bool const forwrd, mplapackint const m, mplapackint const n, mpf_class *x, mplapackint const ldx, mplapackint *k);
void Rlaqgb(mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mpf_class *ab, mplapackint const ldab, mpf_class *r, mpf_class *c, mpf_class const rowcnd, mpf_class const colcnd, mpf_class const amax, char *equed);
void Rlaqge(mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *r, mpf_class *c, mpf_class const rowcnd, mpf_class const colcnd, mpf_class const amax, char *equed);
void Rlaqr1(mplapackint const n, mpf_class *h, mplapackint const ldh, mpf_class const sr1, mpf_class const si1, mpf_class const sr2, mpf_class const si2, mpf_class *v);
void Rlaqsb(const char *uplo, mplapackint const n, mplapackint const kd, mpf_class *ab, mplapackint const ldab, mpf_class *s, mpf_class const scond, mpf_class const amax, char *equed);
void Rlaqsp(const char *uplo, mplapackint const n, mpf_class *ap, mpf_class *s, mpf_class const scond, mpf_class const amax, char *equed);
void Rlaqsy(const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *s, mpf_class const scond, mpf_class const amax, char *equed);
void Rlar1v(mplapackint const n, mplapackint const b1, mplapackint const bn, mpf_class const lambda, mpf_class *d, mpf_class *l, mpf_class *ld, mpf_class *lld, mpf_class const pivmin, mpf_class const gaptol, mpf_class *z, bool const wantnc, mplapackint &negcnt, mpf_class &ztz, mpf_class &mingma, mplapackint &r, mplapackint *isuppz, mpf_class &nrminv, mpf_class &resid, mpf_class &rqcorr, mpf_class *work);
void Rlar2v(mplapackint const n, mpf_class *x, mpf_class *y, mpf_class *z, mplapackint const incx, mpf_class *c, mpf_class *s, mplapackint const incc);
void Rlarf(const char *side, mplapackint const m, mplapackint const n, mpf_class *v, mplapackint const incv, mpf_class const tau, mpf_class *c, mplapackint const ldc, mpf_class *work);
void Rlarfb(const char *side, const char *trans, const char *direct, const char *storev, mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *v, mplapackint const ldv, mpf_class *t, mplapackint const ldt, mpf_class *c, mplapackint const ldc, mpf_class *work, mplapackint const ldwork);
void Rlarfb_gett(const char *ident, mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *t, mplapackint const ldt, mpf_class *a, mplapackint const lda, mpf_class *b, mplapackint const ldb, mpf_class *work, mplapackint const ldwork);
void Rlarfg(mplapackint const n, mpf_class &alpha, mpf_class *x, mplapackint const incx, mpf_class &tau);
void Rlarfgp(mplapackint const n, mpf_class &alpha, mpf_class *x, mplapackint const incx, mpf_class &tau);
void Rlarft(const char *direct, const char *storev, mplapackint const n, mplapackint const k, mpf_class *v, mplapackint const ldv, mpf_class *tau, mpf_class *t, mplapackint const ldt);
void Rlarfx(const char *side, mplapackint const m, mplapackint const n, mpf_class *v, mpf_class const tau, mpf_class *c, mplapackint const ldc, mpf_class *work);
void Rlarfy(const char *uplo, mplapackint const n, mpf_class *v, mplapackint const incv, mpf_class const tau, mpf_class *c, mplapackint const ldc, mpf_class *work);
void Rlargv(mplapackint const n, mpf_class *x, mplapackint const incx, mpf_class *y, mplapackint const incy, mpf_class *c, mplapackint const incc);
void Rlarra(mplapackint const n, mpf_class *d, mpf_class *e, mpf_class *e2, mpf_class const spltol, mpf_class const tnrm, mplapackint &nsplit, mplapackint *isplit, mplapackint &info);
void Rlarrc(const char *jobt, mplapackint const n, mpf_class const vl, mpf_class const vu, mpf_class *d, mpf_class *e, mpf_class const, mplapackint &eigcnt, mplapackint &lcnt, mplapackint &rcnt, mplapackint &info);
void Rlarrj(mplapackint const n, mpf_class *d, mpf_class *e2, mplapackint const ifirst, mplapackint const ilast, mpf_class const rtol, mplapackint const offset, mpf_class *w, mpf_class *werr, mpf_class *work, mplapackint *iwork, mpf_class const pivmin, mpf_class const spdiam, mplapackint &info);
void Rlarrr(mplapackint const n, mpf_class *d, mpf_class *e, mplapackint &info);
void Rlarscl2(mplapackint const m, mplapackint const n, mpf_class *d, mpf_class *x, mplapackint const ldx);
void Rlartg(mpf_class const f, mpf_class const g, mpf_class &cs, mpf_class &sn, mpf_class &r);
void Rlartgp(mpf_class const f, mpf_class const g, mpf_class &cs, mpf_class &sn, mpf_class &r);
void Rlartgs(mpf_class const x, mpf_class const y, mpf_class const sigma, mpf_class cs, mpf_class sn);
void Rlartv(mplapackint const n, mpf_class *x, mplapackint const incx, mpf_class *y, mplapackint const incy, mpf_class *c, mpf_class *s, mplapackint const incc);
void Rlarz(const char *side, mplapackint const m, mplapackint const n, mplapackint const l, mpf_class *v, mplapackint const incv, mpf_class const tau, mpf_class *c, mplapackint const ldc, mpf_class *work);
void Rlarzt(const char *direct, const char *storev, mplapackint const n, mplapackint const k, mpf_class *v, mplapackint const ldv, mpf_class *tau, mpf_class *t, mplapackint const ldt);
void Rlas2(mpf_class const f, mpf_class const g, mpf_class const h, mpf_class &ssmin, mpf_class &ssmax);
void Rlascl(const char *type, mplapackint const kl, mplapackint const ku, mpf_class const cfrom, mpf_class const cto, mplapackint const m, mplapackint const n, mpf_class *a, mplapackint const lda, mplapackint &info);
void Rlascl2(mplapackint const m, mplapackint const n, mpf_class *d, mpf_class *x, mplapackint const ldx);
void Rlasd5(mplapackint const i, mpf_class *d, mpf_class *z, mpf_class *delta, mpf_class const rho, mpf_class &dsigma, mpf_class *work);
void Rlaset(const char *uplo, mplapackint const m, mplapackint const n, mpf_class const alpha, mpf_class const beta, mpf_class *a, mplapackint const lda);
void Rlasq1(mplapackint const n, mpf_class *d, mpf_class *e, mpf_class *work, mplapackint &info);
void Rlasq2(mplapackint const n, mpf_class *z, mplapackint &info);
void Rlasq3(mplapackint const i0, mplapackint &n0, mpf_class *z, mplapackint &pp, mpf_class &dmin, mpf_class &sigma, mpf_class &desig, mpf_class &qmax, mplapackint &nfail, mplapackint &iter, mplapackint &ndiv, bool const ieee, mplapackint &ttype, mpf_class const dmin1, mpf_class &dmin2, mpf_class const dn, mpf_class const dn1, mpf_class const dn2, mpf_class const g, mpf_class &tau);
void Rlasq4(mplapackint const i0, mplapackint const n0, mpf_class *z, mplapackint const pp, mplapackint const n0in, mpf_class const dmin, mpf_class const dmin1, mpf_class const dmin2, mpf_class const dn, mpf_class const dn1, mpf_class const dn2, mpf_class &tau, mplapackint &ttype, mpf_class &g);
void Rlasq6(mplapackint const i0, mplapackint const n0, mpf_class *z, mplapackint const pp, mpf_class &dmin, mpf_class &dmin1, mpf_class &dmin2, mpf_class &dn, mpf_class &dnm1, mpf_class &dnm2);
void Rlasr(const char *side, const char *pivot, const char *direct, mplapackint const m, mplapackint const n, mpf_class *c, mpf_class *s, mpf_class *a, mplapackint const lda);
void Rlasrt(const char *id, mplapackint const n, mpf_class *d, mplapackint &info);
void Rlassq(mplapackint const n, mpf_class *x, mplapackint const incx, mpf_class &scale, mpf_class &sumsq);
void Rlasv2(mpf_class const f, mpf_class const g, mpf_class const h, mpf_class &ssmin, mpf_class &ssmax, mpf_class &snr, mpf_class &csr, mpf_class &snl, mpf_class &csl);
void Rlaswlq(mplapackint const m, mplapackint const n, mplapackint const mb, mplapackint const nb, mpf_class *a, mplapackint const lda, mpf_class *t, mplapackint const ldt, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rlaswp(mplapackint const n, mpf_class *a, mplapackint const lda, mplapackint const k1, mplapackint const k2, mplapackint *ipiv, mplapackint const incx);
void Rlasyf(const char *uplo, mplapackint const n, mplapackint const nb, mplapackint &kb, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mpf_class *w, mplapackint const ldw, mplapackint &info);
void Rlasyf_aa(const char *uplo, mplapackint const j1, mplapackint const m, mplapackint const nb, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mpf_class *h, mplapackint const ldh, mpf_class *work);
void Rlasyf_rk(const char *uplo, mplapackint const n, mplapackint const nb, mplapackint &kb, mpf_class *a, mplapackint const lda, mpf_class *e, mplapackint *ipiv, mpf_class *w, mplapackint const ldw, mplapackint &info);
void Rlasyf_rook(const char *uplo, mplapackint const n, mplapackint const nb, mplapackint &kb, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mpf_class *w, mplapackint const ldw, mplapackint &info);
void Rlatrd(const char *uplo, mplapackint const n, mplapackint const nb, mpf_class *a, mplapackint const lda, mpf_class *e, mpf_class *tau, mpf_class *w, mplapackint const ldw);
void Rlatsqr(mplapackint const m, mplapackint const n, mplapackint const mb, mplapackint const nb, mpf_class *a, mplapackint const lda, mpf_class *t, mplapackint const ldt, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rlauu2(const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mplapackint &info);
void Rlauum(const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mplapackint &info);
void Rorbdb5(mplapackint const m1, mplapackint const m2, mplapackint const n, mpf_class *x1, mplapackint const incx1, mpf_class *x2, mplapackint const incx2, mpf_class *q1, mplapackint const ldq1, mpf_class *q2, mplapackint const ldq2, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rorbdb6(mplapackint const m1, mplapackint const m2, mplapackint const n, mpf_class *x1, mplapackint const incx1, mpf_class *x2, mplapackint const incx2, mpf_class *q1, mplapackint const ldq1, mpf_class *q2, mplapackint const ldq2, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rorg2l(mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint &info);
void Rorg2r(mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint &info);
void Rorgbr(const char *vect, mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rorghr(mplapackint const n, mplapackint const ilo, mplapackint const ihi, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rorgl2(mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint &info);
void Rorglq(mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rorgql(mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rorgqr(mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rorgtr(const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rorhr_col(mplapackint const m, mplapackint const n, mplapackint const nb, mpf_class *a, mplapackint const lda, mpf_class *t, mplapackint const ldt, mpf_class *d, mplapackint &info);
void Rorm2r(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *c, mplapackint const ldc, mpf_class *work, mplapackint &info);
void Rormbr(const char *vect, const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *c, mplapackint const ldc, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rorml2(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *c, mplapackint const ldc, mpf_class *work, mplapackint &info);
void Rormlq(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *c, mplapackint const ldc, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rormql(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *c, mplapackint const ldc, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rormql(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *c, mplapackint const ldc, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rormqr(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mpf_class *a, mplapackint const lda, mpf_class *tau, mpf_class *c, mplapackint const ldc, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rpbequ(const char *uplo, mplapackint const n, mplapackint const kd, mpf_class *ab, mplapackint const ldab, mpf_class *s, mpf_class &scond, mpf_class &amax, mplapackint &info);
void Rpbsv(const char *uplo, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpf_class *ab, mplapackint const ldab, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rpbtrs(const char *uplo, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpf_class *ab, mplapackint const ldab, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rpoequ(mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *s, mpf_class &scond, mpf_class &amax, mplapackint &info);
void Rpoequb(mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *s, mpf_class &scond, mpf_class &amax, mplapackint &info);
void Rposv(const char *uplo, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rposvx(const char *fact, const char *uplo, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *af, mplapackint const ldaf, char *equed, mpf_class *s, mpf_class *b, mplapackint const ldb, mpf_class *x, mplapackint const ldx, mpf_class &rcond, mpf_class *ferr, mpf_class *berr, mpf_class *work, mplapackint *iwork, mplapackint &info);
void Rpotf2(const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mplapackint &info);
void Rpotrf(const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mplapackint &info);
void Rpotrf2(const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mplapackint &info);
void Rpotri(const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mplapackint &info);
void Rpotrs(const char *uplo, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rppequ(const char *uplo, mplapackint const n, mpf_class *ap, mpf_class *s, mpf_class &scond, mpf_class &amax, mplapackint &info);
void Rppsv(const char *uplo, mplapackint const n, mplapackint const nrhs, mpf_class *ap, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rpptrs(const char *uplo, mplapackint const n, mplapackint const nrhs, mpf_class *ap, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rptcon(mplapackint const n, mpf_class *d, mpf_class *e, mpf_class const anorm, mpf_class &rcond, mpf_class *work, mplapackint &info);
void Rptsv(mplapackint const n, mplapackint const nrhs, mpf_class *d, mpf_class *e, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rptsvx(const char *fact, mplapackint const n, mplapackint const nrhs, mpf_class *d, mpf_class *e, mpf_class *df, mpf_class *ef, mpf_class *b, mplapackint const ldb, mpf_class *x, mplapackint const ldx, mpf_class &rcond, mpf_class *ferr, mpf_class *berr, mpf_class *work, mplapackint &info);
void Rpttrf(mplapackint const n, mpf_class *d, mpf_class *e, mplapackint &info);
void Rpttrs(mplapackint const n, mplapackint const nrhs, mpf_class *d, mpf_class *e, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rptts2(mplapackint const n, mplapackint const nrhs, mpf_class *d, mpf_class *e, mpf_class *b, mplapackint const ldb);
void Rrscl(mplapackint const n, mpf_class const sa, mpf_class *sx, mplapackint const incx);
void Rsfrk(const char *transr, const char *uplo, const char *trans, mplapackint const n, mplapackint const k, mpf_class const alpha, mpf_class *a, mplapackint const lda, mpf_class const beta, mpf_class *c);
void Rspsv(const char *uplo, mplapackint const n, mplapackint const nrhs, mpf_class *ap, mplapackint *ipiv, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rsteqr(const char *compz, mplapackint const n, mpf_class *d, mpf_class *e, mpf_class *z, mplapackint const ldz, mpf_class *work, mplapackint &info);
void Rsterf(mplapackint const n, mpf_class *d, mpf_class *e, mplapackint &info);
void Rstev(const char *jobz, mplapackint const n, mpf_class *d, mpf_class *e, mpf_class *z, mplapackint const ldz, mpf_class *work, mplapackint &info);
void Rstevd(const char *jobz, mplapackint const n, mpf_class *d, mpf_class *e, mpf_class *z, mplapackint const ldz, mpf_class *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, mplapackint &info);
void Rsyconv(const char *uplo, const char *way, mplapackint const n, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mpf_class *e, mplapackint &info);
void Rsyconvf(const char *uplo, const char *way, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *e, mplapackint *ipiv, mplapackint &info);
void Rsyconvf_rook(const char *uplo, const char *way, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *e, mplapackint *ipiv, mplapackint &info);
void Rsyequb(const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *s, mpf_class &scond, mpf_class &amax, mpf_class *work, mplapackint &info);
void Rsyev(const char *jobz, const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *w, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rsyevd(const char *jobz, const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *w, mpf_class *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, mplapackint &info);
void Rsygs2(mplapackint const itype, const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rsygst(mplapackint const itype, const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rsysv(const char *uplo, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mpf_class *b, mplapackint const ldb, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rsysv_aa(const char *uplo, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mpf_class *b, mplapackint const ldb, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rsysv_aa_2stage(const char *uplo, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *tb, mplapackint const ltb, mplapackint *ipiv, mplapackint *ipiv2, mpf_class *b, mplapackint const ldb, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rsysv_rk(const char *uplo, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *e, mplapackint *ipiv, mpf_class *b, mplapackint const ldb, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rsysv_rook(const char *uplo, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mpf_class *b, mplapackint const ldb, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rsysvx(const char *fact, const char *uplo, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *af, mplapackint const ldaf, mplapackint *ipiv, mpf_class *b, mplapackint const ldb, mpf_class *x, mplapackint const ldx, mpf_class &rcond, mpf_class *ferr, mpf_class *berr, mpf_class *work, mplapackint const lwork, mplapackint *iwork, mplapackint &info);
void Rsytd2(const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *d, mpf_class *e, mpf_class *tau, mplapackint &info);
void Rsytf2(const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mplapackint &info);
void Rsytf2_rk(const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *e, mplapackint *ipiv, mplapackint &info);
void Rsytf2_rook(const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mplapackint &info);
void Rsytrd(const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *d, mpf_class *e, mpf_class *tau, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rsytri(const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mpf_class *work, mplapackint &info);
void Rsytri2(const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rsytri_3(const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *e, mplapackint *ipiv, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rsytri_rook(const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mpf_class *work, mplapackint &info);
void Rsytrs(const char *uplo, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rsytrs2(const char *uplo, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mpf_class *b, mplapackint const ldb, mpf_class *work, mplapackint &info);
void Rsytrs_3(const char *uplo, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *e, mplapackint *ipiv, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rsytrs_aa(const char *uplo, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mpf_class *b, mplapackint const ldb, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rsytrs_aa_2stage(const char *uplo, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *tb, mplapackint const ltb, mplapackint *ipiv, mplapackint *ipiv2, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rsytrs_rook(const char *uplo, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mplapackint *ipiv, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rtbtrs(const char *uplo, const char *trans, const char *diag, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpf_class *ab, mplapackint const ldab, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rtgexc(bool const wantq, bool const wantz, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *b, mplapackint const ldb, mpf_class *q, mplapackint const ldq, mpf_class *z, mplapackint const ldz, mplapackint &ifst, mplapackint &ilst, mpf_class *work, mplapackint const lwork, mplapackint &info);
void Rtplqt(mplapackint const m, mplapackint const n, mplapackint const l, mplapackint const mb, mpf_class *a, mplapackint const lda, mpf_class *b, mplapackint const ldb, mpf_class *t, mplapackint const ldt, mpf_class *work, mplapackint &info);
void Rtpmlqt(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const l, mplapackint const mb, mpf_class *v, mplapackint const ldv, mpf_class *t, mplapackint const ldt, mpf_class *a, mplapackint const lda, mpf_class *b, mplapackint const ldb, mpf_class *work, mplapackint &info);
void Rtpmqrt(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const l, mplapackint const nb, mpf_class *v, mplapackint const ldv, mpf_class *t, mplapackint const ldt, mpf_class *a, mplapackint const lda, mpf_class *b, mplapackint const ldb, mpf_class *work, mplapackint &info);
void Rtpqrt(mplapackint const m, mplapackint const n, mplapackint const l, mplapackint const nb, mpf_class *a, mplapackint const lda, mpf_class *b, mplapackint const ldb, mpf_class *t, mplapackint const ldt, mpf_class *work, mplapackint &info);
void Rtprfb(const char *side, const char *trans, const char *direct, const char *storev, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const l, mpf_class *v, mplapackint const ldv, mpf_class *t, mplapackint const ldt, mpf_class *a, mplapackint const lda, mpf_class *b, mplapackint const ldb, mpf_class *work, mplapackint const ldwork);
void Rtptrs(const char *uplo, const char *trans, const char *diag, mplapackint const n, mplapackint const nrhs, mpf_class *ap, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rtpttr(const char *uplo, mplapackint const n, mpf_class *ap, mpf_class *a, mplapackint const lda, mplapackint &info);
void Rtrexc(const char *compq, mplapackint const n, mpf_class *t, mplapackint const ldt, mpf_class *q, mplapackint const ldq, mplapackint &ifst, mplapackint &ilst, mpf_class *work, mplapackint &info);
void Rtrti2(const char *uplo, const char *diag, mplapackint const n, mpf_class *a, mplapackint const lda, mplapackint &info);
void Rtrtri(const char *uplo, const char *diag, mplapackint const n, mpf_class *a, mplapackint const lda, mplapackint &info);
void Rtrtrs(const char *uplo, const char *trans, const char *diag, mplapackint const n, mplapackint const nrhs, mpf_class *a, mplapackint const lda, mpf_class *b, mplapackint const ldb, mplapackint &info);
void Rtrttp(const char *uplo, mplapackint const n, mpf_class *a, mplapackint const lda, mpf_class *ap, mplapackint &info);
#endif
