/*
 * Copyright (c) 2008-2025
 *	Nakata, Maho
 * 	All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 */

#ifndef MPLAPACK_EIG_TD_H
#define MPLAPACK_EIG_TD_H

#include "mplapack_config.h"
#include "qd/td_real.h"
#include <qd/td_complex.h>

#include <mpblas.h>
#include <mplapack.h>

#include <fem.hpp> // Fortran EMulation library of fable module
using namespace fem::major_types;
using fem::common;

#include <mplapack_matgen.h>
#include <mplapack_debug.h>
bool Clctes(td_complex const z, td_complex const d);
bool Clctsx(td_complex const, td_complex const);
bool Cslect(td_complex const z);
bool Rlctes(td_real const zr, td_real const, td_real const d);
bool Rlctsx(td_real const, td_real const, td_real const);
bool Rslect(td_real const zr, td_real const zi);
mplapackint iMlaenv2stage_td(mplapackint const ispec, const char *name, const char *opts, mplapackint const n1, mplapackint const n2, mplapackint const n3, mplapackint const n4);
mplapackint iMlaenv_td(mplapackint const ispec, const char *name, const char *opts, mplapackint const n1, mplapackint const n2, mplapackint const n3, mplapackint const n4);
td_real Rlamch_td(const char *cmach);
td_real Rsxt1(mplapackint const ijob, td_real *d1, mplapackint const n1, td_real *d2, mplapackint const n2, td_real const abstol, td_real const ulp, td_real const unfl);
void Alahdg(mplapackint const iounit, fem::str_cref path);
void Alareq(fem::str_cref path, mplapackint const nmats, bool *dotype, mplapackint const ntypes, mplapackint const nin, mplapackint const nout);
void Alarqg(fem::str_cref path, mplapackint const nmats, bool *dotype, mplapackint const ntypes, mplapackint const nin, mplapackint const nout);
void Alasmg(fem::str_cref type, mplapackint const nout, mplapackint const nfail, mplapackint const nrun, mplapackint const nerrs);
void Alasum(fem::str_cref type, mplapackint const nout, mplapackint const nfail, mplapackint const nrun, mplapackint const nerrs);
void Alasvm(fem::str_cref type, mplapackint const nout, mplapackint const nfail, mplapackint const nrun, mplapackint const nerrs);
void Cbdt01(mplapackint const m, mplapackint const n, mplapackint const kd, td_complex *a, mplapackint const lda, td_complex *q, mplapackint const ldq, td_real *d, td_real *e, td_complex *pt, mplapackint const ldpt, td_complex *work, td_real *rwork, td_real &resid);
void Cbdt02(mplapackint const m, mplapackint const n, td_complex *b, mplapackint const ldb, td_complex *c, mplapackint const ldc, td_complex *u, mplapackint const ldu, td_complex *work, td_real *rwork, td_real &resid);
void Cbdt03(fem::str_cref uplo, mplapackint const n, mplapackint const kd, td_real *d, td_real *e, td_complex *u, mplapackint const ldu, td_real *s, td_complex *vt, mplapackint const ldvt, td_complex *work, td_real &resid);
void Cbdt05(mplapackint const m, mplapackint const n, td_complex *a, mplapackint const lda, td_real *s, mplapackint const ns, td_complex *u, mplapackint const ldu, td_complex *vt, mplapackint const ldvt, td_complex *work, td_real &resid);
void Cchkbb(mplapackint const nsizes, mplapackint *mval, mplapackint *nval, mplapackint const nwdths, mplapackint *kk, mplapackint const ntypes, bool *dotype, mplapackint const nrhs, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_complex *a, mplapackint const lda, td_complex *ab, mplapackint const ldab, td_real *bd, td_real *be, td_complex *q, mplapackint const ldq, td_complex *p, mplapackint const ldp, td_complex *c, mplapackint const ldc, td_complex *cc, td_complex *work, mplapackint const lwork, td_real *rwork, td_real *result, mplapackint &info);
void Cchkbd(mplapackint const nsizes, mplapackint *mval, mplapackint *nval, mplapackint const ntypes, bool *dotype, mplapackint const nrhs, mplapackint (&iseed)[4], td_real const thresh, td_complex *a, mplapackint const lda, td_real *bd, td_real *be, td_real *s1, td_real *s2, td_complex *x, mplapackint const ldx, td_complex *y, td_complex *z, td_complex *q, mplapackint const ldq, td_complex *pt, mplapackint const ldpt, td_complex *u, td_complex *vt, td_complex *work, mplapackint const lwork, td_real *rwork, mplapackint const nout, mplapackint &info);
void Cchkbk(mplapackint const nin, mplapackint const nout);
void Cchkbl(mplapackint const nin, mplapackint const nout);
void Cchkec(td_real const thresh, bool const tsterr, mplapackint const nin, mplapackint const nout);
void Cchkgg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, bool const tstdif, td_real const thrshn, mplapackint const nounit, td_complex *a, mplapackint const lda, td_complex *b, td_complex *h, td_complex *t, td_complex *s1, td_complex *s2, td_complex *p1, td_complex *p2, td_complex *u, mplapackint const ldu, td_complex *v, td_complex *q, td_complex *z, td_complex *alpha1, td_complex *beta1, td_complex *alpha3, td_complex *beta3, td_complex *evectl, td_complex *evectr, td_complex *work, mplapackint const lwork, td_real *rwork, bool *llwork, td_real *result, mplapackint &info);
void Cchkgk(mplapackint const nin, mplapackint const nout);
void Cchkgl(mplapackint const nin, mplapackint const nout);
void Cchkhb(mplapackint const nsizes, mplapackint *nn, mplapackint const nwdths, mplapackint *kk, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_complex *a, mplapackint const lda, td_real *sd, td_real *se, td_complex *u, mplapackint const ldu, td_complex *work, mplapackint const lwork, td_real *rwork, td_real *result, mplapackint &info);
void Cchkhb2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const nwdths, mplapackint *kk, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_complex *a, mplapackint const lda, td_real *sd, td_real *se, td_real *d1, td_real *d2, td_real *d3, td_complex *u, mplapackint const ldu, td_complex *work, mplapackint const lwork, td_real *rwork, td_real *result, mplapackint &info);
void Cchkhs(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_complex *a, mplapackint const lda, td_complex *h, td_complex *t1, td_complex *t2, td_complex *u, mplapackint const ldu, td_complex *z, td_complex *uz, td_complex *w1, td_complex *w3, td_complex *evectl, td_complex *evectr, td_complex *evecty, td_complex *evectx, td_complex *uu, td_complex *tau, td_complex *work, mplapackint const nwork, td_real *rwork, mplapackint *iwork, bool *select, td_real *result, mplapackint &info);
void Cchkst(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_complex *a, mplapackint const lda, td_complex *ap, td_real *sd, td_real *se, td_real *d1, td_real *d2, td_real *d3, td_real *d4, td_real *d5, td_real *wa1, td_real *wa2, td_real *wa3, td_real *wr, td_complex *u, mplapackint const ldu, td_complex *v, td_complex *vp, td_complex *tau, td_complex *z, td_complex *work, mplapackint const lwork, td_real *rwork, mplapackint const lrwork, mplapackint *iwork, mplapackint const liwork, td_real *result, mplapackint &info);
void Cchkst2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_complex *a, mplapackint const lda, td_complex *ap, td_real *sd, td_real *se, td_real *d1, td_real *d2, td_real *d3, td_real *d4, td_real *d5, td_real *wa1, td_real *wa2, td_real *wa3, td_real *wr, td_complex *u, mplapackint const ldu, td_complex *v, td_complex *vp, td_complex *tau, td_complex *z, td_complex *work, mplapackint const lwork, td_real *rwork, mplapackint const lrwork, mplapackint *iwork, mplapackint const liwork, td_real *result, mplapackint &info);
void Cckcsd(mplapackint const nm, mplapackint *mval, mplapackint *pval, mplapackint *qval, mplapackint const nmats, mplapackint (&iseed)[4], td_real const thresh, mplapackint const mmax, td_complex *x, td_complex *xf, td_complex *u1, td_complex *u2, td_complex *v1t, td_complex *v2t, td_real *theta, mplapackint *iwork, td_complex *work, td_real *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Cckglm(mplapackint const nn, mplapackint *nval, mplapackint *mval, mplapackint *pval, mplapackint const nmats, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nmax, td_complex *a, td_complex *af, td_complex *b, td_complex *bf, td_complex *x, td_complex *work, td_real *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Cckgqr(mplapackint const nm, mplapackint *mval, mplapackint const np, mplapackint *pval, mplapackint const nn, mplapackint *nval, mplapackint const nmats, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nmax, td_complex *a, td_complex *af, td_complex *aq, td_complex *ar, td_complex *taua, td_complex *b, td_complex *bf, td_complex *bz, td_complex *bt, td_complex *bwk, td_complex *taub, td_complex *work, td_real *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Cckgsv(mplapackint const nm, mplapackint *mval, mplapackint *pval, mplapackint *nval, mplapackint const nmats, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nmax, td_complex *a, td_complex *af, td_complex *b, td_complex *bf, td_complex *u, td_complex *v, td_complex *q, td_real *alpha, td_real *beta, td_complex *r, mplapackint *iwork, td_complex *work, td_real *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Ccklse(mplapackint const nn, mplapackint *mval, mplapackint *pval, mplapackint *nval, mplapackint const nmats, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nmax, td_complex *a, td_complex *af, td_complex *b, td_complex *bf, td_complex *x, td_complex *work, td_real *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Ccsdts(mplapackint const m, mplapackint const p, mplapackint const q, td_complex *x, td_complex *xf, mplapackint const ldx, td_complex *u1, mplapackint const ldu1, td_complex *u2, mplapackint const ldu2, td_complex *v1t, mplapackint const ldv1t, td_complex *v2t, mplapackint const ldv2t, td_real *theta, mplapackint *iwork, td_complex *work, mplapackint const lwork, td_real *rwork, td_real *result);
void Cdrges(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_complex *a, mplapackint const lda, td_complex *b, td_complex *s, td_complex *t, td_complex *q, mplapackint const ldq, td_complex *z, td_complex *alpha, td_complex *beta, td_complex *work, mplapackint const lwork, td_real *rwork, td_real *result, bool *bwork, mplapackint &info);
void Cdrges3(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_complex *a, mplapackint const lda, td_complex *b, td_complex *s, td_complex *t, td_complex *q, mplapackint const ldq, td_complex *z, td_complex *alpha, td_complex *beta, td_complex *work, mplapackint const lwork, td_real *rwork, td_real *result, bool *bwork, mplapackint &info);
void Cdrgev(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_complex *a, mplapackint const lda, td_complex *b, td_complex *s, td_complex *t, td_complex *q, mplapackint const ldq, td_complex *z, td_complex *qe, mplapackint const ldqe, td_complex *alpha, td_complex *beta, td_complex *alpha1, td_complex *beta1, td_complex *work, mplapackint const lwork, td_real *rwork, td_real *result, mplapackint &info);
void Cdrgev3(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_complex *a, mplapackint const lda, td_complex *b, td_complex *s, td_complex *t, td_complex *q, mplapackint const ldq, td_complex *z, td_complex *qe, mplapackint const ldqe, td_complex *alpha, td_complex *beta, td_complex *alpha1, td_complex *beta1, td_complex *work, mplapackint const lwork, td_real *rwork, td_real *result, mplapackint &info);
void Cdrgsx(mplapackint const nsize, mplapackint const ncmax, td_real const thresh, mplapackint const nin, mplapackint const nout, td_complex *a, mplapackint const lda, td_complex *b, td_complex *ai, td_complex *bi, td_complex *z, td_complex *q, td_complex *alpha, td_complex *beta, td_complex *c, mplapackint const ldc, td_real *s, td_complex *work, mplapackint const lwork, td_real *rwork, mplapackint *iwork, mplapackint const liwork, bool *bwork, mplapackint &info);
void Cdrgvx(mplapackint const nsize, td_real const thresh, mplapackint const nin, mplapackint const nout, td_complex *a, mplapackint const lda, td_complex *b, td_complex *ai, td_complex *bi, td_complex *alpha, td_complex *beta, td_complex *vl, td_complex *vr, mplapackint &ilo, mplapackint &ihi, td_real *lscale, td_real *rscale, td_real *s, td_real *dtru, td_real *dif, td_real *diftru, td_complex *work, mplapackint const lwork, td_real *rwork, mplapackint *iwork, mplapackint const liwork, td_real *result, bool *bwork, mplapackint &info);
void Cdrvbd(mplapackint const nsizes, mplapackint *mm, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, td_complex *a, mplapackint const lda, td_complex *u, mplapackint const ldu, td_complex *vt, mplapackint const ldvt, td_complex *asav, td_complex *usav, td_complex *vtsav, td_real *s, td_real *ssav, td_real *e, td_complex *work, mplapackint const lwork, td_real *rwork, mplapackint *iwork, mplapackint const nounit, mplapackint &info);
void Cdrves(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_complex *a, mplapackint const lda, td_complex *h, td_complex *ht, td_complex *w, td_complex *wt, td_complex *vs, mplapackint const ldvs, td_real *result, td_complex *work, mplapackint const nwork, td_real *rwork, mplapackint *iwork, bool *bwork, mplapackint &info);
void Cdrvev(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_complex *a, mplapackint const lda, td_complex *h, td_complex *w, td_complex *w1, td_complex *vl, mplapackint const ldvl, td_complex *vr, mplapackint const ldvr, td_complex *lre, mplapackint const ldlre, td_real *result, td_complex *work, mplapackint const nwork, td_real *rwork, mplapackint *iwork, mplapackint &info);
void Cdrvsg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_complex *a, mplapackint const lda, td_complex *b, mplapackint const ldb, td_real *d, td_complex *z, mplapackint const ldz, td_complex *ab, td_complex *bb, td_complex *ap, td_complex *bp, td_complex *work, mplapackint const nwork, td_real *rwork, mplapackint const lrwork, mplapackint *iwork, mplapackint const liwork, td_real *result, mplapackint &info);
void Cdrvsg2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_complex *a, mplapackint const lda, td_complex *b, mplapackint const ldb, td_real *d, td_real *d2, td_complex *z, mplapackint const ldz, td_complex *ab, td_complex *bb, td_complex *ap, td_complex *bp, td_complex *work, mplapackint const nwork, td_real *rwork, mplapackint const lrwork, mplapackint *iwork, mplapackint const liwork, td_real *result, mplapackint &info);
void Cdrvst(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_complex *a, mplapackint const lda, td_real *d1, td_real *d2, td_real *d3, td_real *wa1, td_real *wa2, td_real *wa3, td_complex *u, mplapackint const ldu, td_complex *v, td_complex *tau, td_complex *z, td_complex *work, mplapackint const lwork, td_real *rwork, mplapackint const lrwork, mplapackint *iwork, mplapackint const liwork, td_real *result, mplapackint &info);
void Cdrvst2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_complex *a, mplapackint const lda, td_real *d1, td_real *d2, td_real *d3, td_real *wa1, td_real *wa2, td_real *wa3, td_complex *u, mplapackint const ldu, td_complex *v, td_complex *tau, td_complex *z, td_complex *work, mplapackint const lwork, td_real *rwork, mplapackint const lrwork, mplapackint *iwork, mplapackint const liwork, td_real *result, mplapackint &info);
void Cdrvsx(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const niunit, mplapackint const nounit, td_complex *a, mplapackint const lda, td_complex *h, td_complex *ht, td_complex *w, td_complex *wt, td_complex *wtmp, td_complex *vs, mplapackint const ldvs, td_complex *vs1, td_real *result, td_complex *work, mplapackint const lwork, td_real *rwork, bool *bwork, mplapackint &info);
void Cdrvvx(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const niunit, mplapackint const nounit, td_complex *a, mplapackint const lda, td_complex *h, td_complex *w, td_complex *w1, td_complex *vl, mplapackint const ldvl, td_complex *vr, mplapackint const ldvr, td_complex *lre, mplapackint const ldlre, td_real *rcondv, td_real *rcndv1, td_real *rcdvin, td_real *rconde, td_real *rcnde1, td_real *rcdein, td_real *scale, td_real *scale1, td_real *result, td_complex *work, mplapackint const nwork, td_real *rwork, mplapackint &info);
void Cerrbd(fem::str_cref path, mplapackint const nunit);
void Cerrec(fem::str_cref path, mplapackint const nunit);
void Cerred(fem::str_cref path, mplapackint const nunit);
void Cerrgg(fem::str_cref path, mplapackint const nunit);
void Cerrhs(fem::str_cref path, mplapackint const nunit);
void Cerrst(fem::str_cref path, mplapackint const nunit);
void Cget02(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, td_complex *a, mplapackint const lda, td_complex *x, mplapackint const ldx, td_complex *b, mplapackint const ldb, td_real *rwork, td_real &resid);
void Cget10(mplapackint const m, mplapackint const n, td_complex *a, mplapackint const lda, td_complex *b, mplapackint const ldb, td_complex *work, td_real *rwork, td_real &result);
void Cget22(fem::str_cref transa, fem::str_cref transe, fem::str_cref transw, mplapackint const n, td_complex *a, mplapackint const lda, td_complex *e, mplapackint const lde, td_complex *w, td_complex *work, td_real *rwork, td_real *result);
void Cget23(bool const comp, mplapackint const isrt, fem::str_cref balanc, mplapackint const jtype, td_real const thresh, mplapackint (&iseed)[4], mplapackint const nounit, mplapackint const n, td_complex *a, mplapackint const lda, td_complex *h, td_complex *w, td_complex *w1, td_complex *vl, mplapackint const ldvl, td_complex *vr, mplapackint const ldvr, td_complex *lre, mplapackint const ldlre, td_real *rcondv, td_real *rcndv1, td_real *rcdvin, td_real *rconde, td_real *rcnde1, td_real *rcdein, td_real *scale, td_real *scale1, td_real *result, td_complex *work, mplapackint const lwork, td_real *rwork, mplapackint &info);
void Cget24(bool const comp, mplapackint const jtype, td_real const thresh, mplapackint (&iseed)[4], mplapackint const nounit, mplapackint const n, td_complex *a, mplapackint const lda, td_complex *h, td_complex *ht, td_complex *w, td_complex *wt, td_complex *wtmp, td_complex *vs, mplapackint const ldvs, td_complex *vs1, td_real const rcdein, td_real const rcdvin, mplapackint const nslct, mplapackint *islct, mplapackint const isrt, td_real *result, td_complex *work, mplapackint const lwork, td_real *rwork, bool *bwork, mplapackint &info);
void Cget35(td_real &rmax, mplapackint &lmax, mplapackint &ninfo, mplapackint &knt, mplapackint const nin);
void Cget36(td_real &rmax, mplapackint &lmax, mplapackint &ninfo, mplapackint &knt, mplapackint const nin);
void Cget37(td_real *rmax, mplapackint *lmax, mplapackint *ninfo, mplapackint &knt, mplapackint const nin);
void Cget38(td_real *rmax, mplapackint *lmax, mplapackint *ninfo, mplapackint &knt, mplapackint const nin);
void Cget51(mplapackint const itype, mplapackint const n, td_complex *a, mplapackint const lda, td_complex *b, mplapackint const ldb, td_complex *u, mplapackint const ldu, td_complex *v, mplapackint const ldv, td_complex *work, td_real *rwork, td_real &result);
void Cget52(bool const left, mplapackint const n, td_complex *a, mplapackint const lda, td_complex *b, mplapackint const ldb, td_complex *e, mplapackint const lde, td_complex *alpha, td_complex *beta, td_complex *work, td_real *rwork, td_real *result);
void Cget54(mplapackint const n, td_complex *a, mplapackint const lda, td_complex *b, mplapackint const ldb, td_complex *s, mplapackint const lds, td_complex *t, mplapackint const ldt, td_complex *u, mplapackint const ldu, td_complex *v, mplapackint const ldv, td_complex *work, td_real &result);
void Cglmts(mplapackint const n, mplapackint const m, mplapackint const p, td_complex *a, td_complex *af, mplapackint const lda, td_complex *b, td_complex *bf, mplapackint const ldb, td_complex *d, td_complex *df, td_complex *x, td_complex *u, td_complex *work, mplapackint const lwork, td_real *rwork, td_real &result);
void Cgqrts(mplapackint const n, mplapackint const m, mplapackint const p, td_complex *a, td_complex *af, td_complex *q, td_complex *r, mplapackint const lda, td_complex *taua, td_complex *b, td_complex *bf, td_complex *z, td_complex *t, td_complex *bwk, mplapackint const ldb, td_complex *taub, td_complex *work, mplapackint const lwork, td_real *rwork, td_real *result);
void Cgrqts(mplapackint const m, mplapackint const p, mplapackint const n, td_complex *a, td_complex *af, td_complex *q, td_complex *r, mplapackint const lda, td_complex *taua, td_complex *b, td_complex *bf, td_complex *z, td_complex *t, td_complex *bwk, mplapackint const ldb, td_complex *taub, td_complex *work, mplapackint const lwork, td_real *rwork, td_real *result);
void Cgsvts3(mplapackint const m, mplapackint const p, mplapackint const n, td_complex *a, td_complex *af, mplapackint const lda, td_complex *b, td_complex *bf, mplapackint const ldb, td_complex *u, mplapackint const ldu, td_complex *v, mplapackint const ldv, td_complex *q, mplapackint const ldq, td_real *alpha, td_real *beta, td_complex *r, mplapackint const ldr, mplapackint *iwork, td_complex *work, mplapackint const lwork, td_real *rwork, td_real *result);
void Chbt21(fem::str_cref uplo, mplapackint const n, mplapackint const ka, mplapackint const ks, td_complex *a, mplapackint const lda, td_real *d, td_real *e, td_complex *u, mplapackint const ldu, td_complex *work, td_real *rwork, td_real *result);
void Chet21(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const kband, td_complex *a, mplapackint const lda, td_real *d, td_real *e, td_complex *u, mplapackint const ldu, td_complex *v, mplapackint const ldv, td_complex *tau, td_complex *work, td_real *rwork, td_real *result);
void Chet22(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const m, mplapackint const kband, td_complex *a, mplapackint const lda, td_real *d, td_real *e, td_complex *u, mplapackint const ldu, td_complex *, mplapackint const ldv, td_complex *, td_complex *work, td_real *rwork, td_real *result);
void Chkxer(fem::str_cref srnamt, mplapackint const infot, mplapackint const nout, bool &lerr, bool &ok);
void Chpt21(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const kband, td_complex *ap, td_real *d, td_real *e, td_complex *u, mplapackint const ldu, td_complex *vp, td_complex *tau, td_complex *work, td_real *rwork, td_real *result);
void Chst01(mplapackint const n, mplapackint const, mplapackint const, td_complex *a, mplapackint const lda, td_complex *h, mplapackint const ldh, td_complex *q, mplapackint const ldq, td_complex *work, mplapackint const lwork, td_real *rwork, td_real *result);
void Clacsg(mplapackint const m, mplapackint const p, mplapackint const q, td_real *theta, mplapackint (&iseed)[4], td_complex *x, mplapackint const ldx, td_complex *work);
void Clarfy(fem::str_cref uplo, mplapackint const n, td_complex *v, mplapackint const incv, td_complex const tau, td_complex *c, mplapackint const ldc, td_complex *work);
void Clarhs(fem::str_cref path, fem::str_cref xtype, fem::str_cref uplo, fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mplapackint const nrhs, td_complex *a, mplapackint const lda, td_complex *x, mplapackint const ldx, td_complex *b, mplapackint const ldb, mplapackint (&iseed)[4], mplapackint &info);
void Clatm4(mplapackint const itype, mplapackint const n, mplapackint const nz1, mplapackint const nz2, bool const rsign, td_real const amagn, td_real const rcond, td_real const triang, mplapackint const idist, mplapackint (&iseed)[4], td_complex *a, mplapackint const lda);
void Clsets(mplapackint const m, mplapackint const p, mplapackint const n, td_complex *a, td_complex *af, mplapackint const lda, td_complex *b, td_complex *bf, mplapackint const ldb, td_complex *c, td_complex *cf, td_complex *d, td_complex *df, td_complex *x, td_complex *work, mplapackint const lwork, td_real *rwork, td_real *result);
void Csbmv(fem::str_cref uplo, mplapackint const n, mplapackint const k, td_complex const alpha, td_complex *a, mplapackint const lda, td_complex *x, mplapackint const incx, td_complex const beta, td_complex *y, mplapackint const incy);
void Csgt01(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const m, td_complex *a, mplapackint const lda, td_complex *b, mplapackint const ldb, td_complex *z, mplapackint const ldz, td_real *d, td_complex *work, td_real *rwork, td_real *result);
void Cstt21(mplapackint const n, mplapackint const kband, td_real *ad, td_real *ae, td_real *sd, td_real *se, td_complex *u, mplapackint const ldu, td_complex *work, td_real *rwork, td_real *result);
void Cstt22(mplapackint const n, mplapackint const m, mplapackint const kband, td_real *ad, td_real *ae, td_real *sd, td_real *se, td_complex *u, mplapackint const ldu, td_complex *work, mplapackint const ldwork, td_real *rwork, td_real *result);
void Csyl01(td_real const thresh, mplapackint *nfail, td_real *rmax, mplapackint *ninfo, mplapackint &knt);
void Cunt01(fem::str_cref rowcol, mplapackint const m, mplapackint const n, td_complex *u, mplapackint const ldu, td_complex *work, mplapackint const lwork, td_real *rwork, td_real &resid);
void Cunt03(fem::str_cref rc, mplapackint const mu, mplapackint const mv, mplapackint const n, mplapackint const k, td_complex *u, mplapackint const ldu, td_complex *v, mplapackint const ldv, td_complex *work, mplapackint const lwork, td_real *rwork, td_real &result, mplapackint &info);
void Mxerbla_td(const char *srname, int info);
void Mxlaenv(mplapackint const ispec, mplapackint const nvalue);
void Rbdt01(mplapackint const m, mplapackint const n, mplapackint const kd, td_real *a, mplapackint const lda, td_real *q, mplapackint const ldq, td_real *d, td_real *e, td_real *pt, mplapackint const ldpt, td_real *work, td_real &resid);
void Rbdt02(mplapackint const m, mplapackint const n, td_real *b, mplapackint const ldb, td_real *c, mplapackint const ldc, td_real *u, mplapackint const ldu, td_real *work, td_real &resid);
void Rbdt03(fem::str_cref uplo, mplapackint const n, mplapackint const kd, td_real *d, td_real *e, td_real *u, mplapackint const ldu, td_real *s, td_real *vt, mplapackint const ldvt, td_real *work, td_real &resid);
void Rbdt04(fem::str_cref uplo, mplapackint const n, td_real *d, td_real *e, td_real *s, mplapackint const ns, td_real *u, mplapackint const ldu, td_real *vt, mplapackint const ldvt, td_real *work, td_real &resid);
void Rbdt05(mplapackint const m, mplapackint const n, td_real *a, mplapackint const lda, td_real *s, mplapackint const ns, td_real *u, mplapackint const ldu, td_real *vt, mplapackint const ldvt, td_real *work, td_real &resid);
void Rchkbb(mplapackint const nsizes, mplapackint *mval, mplapackint *nval, mplapackint const nwdths, mplapackint *kk, mplapackint const ntypes, bool *dotype, mplapackint const nrhs, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_real *a, mplapackint const lda, td_real *ab, mplapackint const ldab, td_real *bd, td_real *be, td_real *q, mplapackint const ldq, td_real *p, mplapackint const ldp, td_real *c, mplapackint const ldc, td_real *cc, td_real *work, mplapackint const lwork, td_real *result, mplapackint &info);
void Rchkbd(mplapackint const nsizes, mplapackint *mval, mplapackint *nval, mplapackint const ntypes, bool *dotype, mplapackint const nrhs, mplapackint (&iseed)[4], td_real const thresh, td_real *a, mplapackint const lda, td_real *bd, td_real *be, td_real *s1, td_real *s2, td_real *x, mplapackint const ldx, td_real *y, td_real *z, td_real *q, mplapackint const ldq, td_real *pt, mplapackint const ldpt, td_real *u, td_real *vt, td_real *work, mplapackint const lwork, mplapackint *iwork, mplapackint const nout, mplapackint &info);
void Rchkbk(mplapackint const nin, mplapackint const nout);
void Rchkbl(mplapackint const nin, mplapackint const nout);
void Rchkec(td_real const thresh, bool const tsterr, mplapackint const nin, mplapackint const nout);
void Rchkgg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, bool const tstdif, td_real const thrshn, mplapackint const nounit, td_real *a, mplapackint const lda, td_real *b, td_real *h, td_real *t, td_real *s1, td_real *s2, td_real *p1, td_real *p2, td_real *u, mplapackint const ldu, td_real *v, td_real *q, td_real *z, td_real *alphr1, td_real *alphi1, td_real *beta1, td_real *alphr3, td_real *alphi3, td_real *beta3, td_real *evectl, td_real *evectr, td_real *work, mplapackint const lwork, bool *llwork, td_real *result, mplapackint &info);
void Rchkgk(mplapackint const nin, mplapackint const nout);
void Rchkgl(mplapackint const nin, mplapackint const nout);
void Rchkhs(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_real *a, mplapackint const lda, td_real *h, td_real *t1, td_real *t2, td_real *u, mplapackint const ldu, td_real *z, td_real *uz, td_real *wr1, td_real *wi1, td_real *wr2, td_real *wi2, td_real *wr3, td_real *wi3, td_real *evectl, td_real *evectr, td_real *evecty, td_real *evectx, td_real *uu, td_real *tau, td_real *work, mplapackint const nwork, mplapackint *iwork, bool *select, td_real *result, mplapackint &info);
void Rchksb(mplapackint const nsizes, mplapackint *nn, mplapackint const nwdths, mplapackint *kk, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_real *a, mplapackint const lda, td_real *sd, td_real *se, td_real *u, mplapackint const ldu, td_real *work, mplapackint const lwork, td_real *result, mplapackint &info);
void Rchksb2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const nwdths, mplapackint *kk, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_real *a, mplapackint const lda, td_real *sd, td_real *se, td_real *d1, td_real *d2, td_real *d3, td_real *u, mplapackint const ldu, td_real *work, mplapackint const lwork, td_real *result, mplapackint &info);
void Rchkst(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_real *a, mplapackint const lda, td_real *ap, td_real *sd, td_real *se, td_real *d1, td_real *d2, td_real *d3, td_real *d4, td_real *d5, td_real *wa1, td_real *wa2, td_real *wa3, td_real *wr, td_real *u, mplapackint const ldu, td_real *v, td_real *vp, td_real *tau, td_real *z, td_real *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, td_real *result, mplapackint &info);
void Rchkst2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_real *a, mplapackint const lda, td_real *ap, td_real *sd, td_real *se, td_real *d1, td_real *d2, td_real *d3, td_real *d4, td_real *d5, td_real *wa1, td_real *wa2, td_real *wa3, td_real *wr, td_real *u, mplapackint const ldu, td_real *v, td_real *vp, td_real *tau, td_real *z, td_real *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, td_real *result, mplapackint &info);
void Rckcsd(mplapackint const nm, mplapackint *mval, mplapackint *pval, mplapackint *qval, mplapackint const nmats, mplapackint (&iseed)[4], td_real const thresh, mplapackint const mmax, td_real *x, td_real *xf, td_real *u1, td_real *u2, td_real *v1t, td_real *v2t, td_real *theta, mplapackint *iwork, td_real *work, td_real *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Rckglm(mplapackint const nn, mplapackint *mval, mplapackint *pval, mplapackint *nval, mplapackint const nmats, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nmax, td_real *a, td_real *af, td_real *b, td_real *bf, td_real *x, td_real *work, td_real *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Rckgqr(mplapackint const nm, mplapackint *mval, mplapackint const np, mplapackint *pval, mplapackint const nn, mplapackint *nval, mplapackint const nmats, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nmax, td_real *a, td_real *af, td_real *aq, td_real *ar, td_real *taua, td_real *b, td_real *bf, td_real *bz, td_real *bt, td_real *bwk, td_real *taub, td_real *work, td_real *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Rckgsv(mplapackint const nm, mplapackint *mval, mplapackint *pval, mplapackint *nval, mplapackint const nmats, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nmax, td_real *a, td_real *af, td_real *b, td_real *bf, td_real *u, td_real *v, td_real *q, td_real *alpha, td_real *beta, td_real *r, mplapackint *iwork, td_real *work, td_real *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Rcklse(mplapackint const nn, mplapackint *mval, mplapackint *pval, mplapackint *nval, mplapackint const nmats, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nmax, td_real *a, td_real *af, td_real *b, td_real *bf, td_real *x, td_real *work, td_real *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Rcsdts(mplapackint const m, mplapackint const p, mplapackint const q, td_real *x, td_real *xf, mplapackint const ldx, td_real *u1, mplapackint const ldu1, td_real *u2, mplapackint const ldu2, td_real *v1t, mplapackint const ldv1t, td_real *v2t, mplapackint const ldv2t, td_real *theta, mplapackint *iwork, td_real *work, mplapackint const lwork, td_real *rwork, td_real *result);
void Rdrges(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_real *a, mplapackint const lda, td_real *b, td_real *s, td_real *t, td_real *q, mplapackint const ldq, td_real *z, td_real *alphar, td_real *alphai, td_real *beta, td_real *work, mplapackint const lwork, td_real *result, bool *bwork, mplapackint &info);
void Rdrges3(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_real *a, mplapackint const lda, td_real *b, td_real *s, td_real *t, td_real *q, mplapackint const ldq, td_real *z, td_real *alphar, td_real *alphai, td_real *beta, td_real *work, mplapackint const lwork, td_real *result, bool *bwork, mplapackint &info);
void Rdrgev(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_real *a, mplapackint const lda, td_real *b, td_real *s, td_real *t, td_real *q, mplapackint const ldq, td_real *z, td_real *qe, mplapackint const ldqe, td_real *alphar, td_real *alphai, td_real *beta, td_real *alphr1, td_real *alphi1, td_real *beta1, td_real *work, mplapackint const lwork, td_real *result, mplapackint &info);
void Rdrgev3(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_real *a, mplapackint const lda, td_real *b, td_real *s, td_real *t, td_real *q, mplapackint const ldq, td_real *z, td_real *qe, mplapackint const ldqe, td_real *alphar, td_real *alphai, td_real *beta, td_real *alphr1, td_real *alphi1, td_real *beta1, td_real *work, mplapackint const lwork, td_real *result, mplapackint &info);
void Rdrgsx(mplapackint const nsize, mplapackint const ncmax, td_real const thresh, mplapackint const nin, mplapackint const nout, td_real *a, mplapackint const lda, td_real *b, td_real *ai, td_real *bi, td_real *z, td_real *q, td_real *alphar, td_real *alphai, td_real *beta, td_real *c, mplapackint const ldc, td_real *s, td_real *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, bool *bwork, mplapackint &info);
void Rdrgvx(mplapackint const nsize, td_real const thresh, mplapackint const nin, mplapackint const nout, td_real *a, mplapackint const lda, td_real *b, td_real *ai, td_real *bi, td_real *alphar, td_real *alphai, td_real *beta, td_real *vl, td_real *vr, mplapackint &ilo, mplapackint &ihi, td_real *lscale, td_real *rscale, td_real *s, td_real *dtru, td_real *dif, td_real *diftru, td_real *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, td_real *result, bool *bwork, mplapackint &info);
void Rdrvbd(mplapackint const nsizes, mplapackint *mm, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, td_real *a, mplapackint const lda, td_real *u, mplapackint const ldu, td_real *vt, mplapackint const ldvt, td_real *asav, td_real *usav, td_real *vtsav, td_real *s, td_real *ssav, td_real *e, td_real *work, mplapackint const lwork, mplapackint *iwork, mplapackint const nout, mplapackint &info);
void Rdrves(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_real *a, mplapackint const lda, td_real *h, td_real *ht, td_real *wr, td_real *wi, td_real *wrt, td_real *wit, td_real *vs, mplapackint const ldvs, td_real *result, td_real *work, mplapackint const nwork, mplapackint *iwork, bool *bwork, mplapackint &info);
void Rdrvev(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_real *a, mplapackint const lda, td_real *h, td_real *wr, td_real *wi, td_real *wr1, td_real *wi1, td_real *vl, mplapackint const ldvl, td_real *vr, mplapackint const ldvr, td_real *lre, mplapackint const ldlre, td_real *result, td_real *work, mplapackint const nwork, mplapackint *iwork, mplapackint &info);
void Rdrvsg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_real *a, mplapackint const lda, td_real *b, mplapackint const ldb, td_real *d, td_real *z, mplapackint const ldz, td_real *ab, td_real *bb, td_real *ap, td_real *bp, td_real *work, mplapackint const nwork, mplapackint *iwork, mplapackint const liwork, td_real *result, mplapackint &info);
void Rdrvsg2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_real *a, mplapackint const lda, td_real *b, mplapackint const ldb, td_real *d, td_real *d2, td_real *z, mplapackint const ldz, td_real *ab, td_real *bb, td_real *ap, td_real *bp, td_real *work, mplapackint const nwork, mplapackint *iwork, mplapackint const liwork, td_real *result, mplapackint &info);
void Rdrvst(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_real *a, mplapackint const lda, td_real *d1, td_real *d2, td_real *d3, td_real *d4, td_real *eveigs, td_real *wa1, td_real *wa2, td_real *wa3, td_real *u, mplapackint const ldu, td_real *v, td_real *tau, td_real *z, td_real *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, td_real *result, mplapackint &info);
void Rdrvst2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const nounit, td_real *a, mplapackint const lda, td_real *d1, td_real *d2, td_real *d3, td_real *d4, td_real *eveigs, td_real *wa1, td_real *wa2, td_real *wa3, td_real *u, mplapackint const ldu, td_real *v, td_real *tau, td_real *z, td_real *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, td_real *result, mplapackint &info);
void Rdrvsx(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const niunit, mplapackint const nounit, td_real *a, mplapackint const lda, td_real *h, td_real *ht, td_real *wr, td_real *wi, td_real *wrt, td_real *wit, td_real *wrtmp, td_real *witmp, td_real *vs, mplapackint const ldvs, td_real *vs1, td_real *result, td_real *work, mplapackint const lwork, mplapackint *iwork, bool *bwork, mplapackint &info);
void Rdrvvx(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], td_real const thresh, mplapackint const niunit, mplapackint const nounit, td_real *a, mplapackint const lda, td_real *h, td_real *wr, td_real *wi, td_real *wr1, td_real *wi1, td_real *vl, mplapackint const ldvl, td_real *vr, mplapackint const ldvr, td_real *lre, mplapackint const ldlre, td_real *rcondv, td_real *rcndv1, td_real *rcdvin, td_real *rconde, td_real *rcnde1, td_real *rcdein, td_real *scale, td_real *scale1, td_real *result, td_real *work, mplapackint const nwork, mplapackint *iwork, mplapackint &info);
void Rerrbd(fem::str_cref path, mplapackint const nunit);
void Rerrec(fem::str_cref path, mplapackint const nunit);
void Rerred(fem::str_cref path, mplapackint const nunit);
void Rerrgg(fem::str_cref path, mplapackint const nunit);
void Rerrhs(fem::str_cref path, mplapackint const nunit);
void Rerrst(fem::str_cref path, mplapackint const nunit);
void Rget02(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, td_real *a, mplapackint const lda, td_real *x, mplapackint const ldx, td_real *b, mplapackint const ldb, td_real *rwork, td_real &resid);
void Rget10(mplapackint const m, mplapackint const n, td_real *a, mplapackint const lda, td_real *b, mplapackint const ldb, td_real *work, td_real &result);
void Rget22(fem::str_cref transa, fem::str_cref transe, fem::str_cref transw, mplapackint const n, td_real *a, mplapackint const lda, td_real *e, mplapackint const lde, td_real *wr, td_real *wi, td_real *work, td_real *result);
void Rget23(bool const comp, fem::str_cref balanc, mplapackint const jtype, td_real const thresh, mplapackint (&iseed)[4], mplapackint const nounit, mplapackint const n, td_real *a, mplapackint const lda, td_real *h, td_real *wr, td_real *wi, td_real *wr1, td_real *wi1, td_real *vl, mplapackint const ldvl, td_real *vr, mplapackint const ldvr, td_real *lre, mplapackint const ldlre, td_real *rcondv, td_real *rcndv1, td_real *rcdvin, td_real *rconde, td_real *rcnde1, td_real *rcdein, td_real *scale, td_real *scale1, td_real *result, td_real *work, mplapackint const lwork, mplapackint *iwork, mplapackint &info);
void Rget24(bool const comp, mplapackint const jtype, td_real const thresh, mplapackint (&iseed)[4], mplapackint const nounit, mplapackint const n, td_real *a, mplapackint const lda, td_real *h, td_real *ht, td_real *wr, td_real *wi, td_real *wrt, td_real *wit, td_real *wrtmp, td_real *witmp, td_real *vs, mplapackint const ldvs, td_real *vs1, td_real const rcdein, td_real const rcdvin, mplapackint const nslct, mplapackint *islct, td_real *result, td_real *work, mplapackint const lwork, mplapackint *iwork, bool *bwork, mplapackint &info);
void Rget31(td_real &rmax, mplapackint &lmax, mplapackint *ninfo, mplapackint &knt);
void Rget32(td_real &rmax, mplapackint &lmax, mplapackint &ninfo, mplapackint &knt);
void Rget33(td_real &rmax, mplapackint &lmax, mplapackint &ninfo, mplapackint &knt);
void Rget34(td_real &rmax, mplapackint &lmax, mplapackint *ninfo, mplapackint &knt);
void Rget35(td_real &rmax, mplapackint &lmax, mplapackint &ninfo, mplapackint &knt);
void Rget36(td_real &rmax, mplapackint &lmax, mplapackint *ninfo, mplapackint &knt, mplapackint const nin);
void Rget37(td_real *rmax, mplapackint *lmax, mplapackint *ninfo, mplapackint &knt, mplapackint const nin);
void Rget38(td_real *rmax, mplapackint *lmax, mplapackint *ninfo, mplapackint &knt, mplapackint const nin);
void Rget39(td_real &rmax, mplapackint &lmax, mplapackint &ninfo, mplapackint &knt);
void Rget40(td_real &rmax, mplapackint &lmax, mplapackint *ninfo, mplapackint &knt, mplapackint const nin);
void Rget51(mplapackint const itype, mplapackint const n, td_real *a, mplapackint const lda, td_real *b, mplapackint const ldb, td_real *u, mplapackint const ldu, td_real *v, mplapackint const ldv, td_real *work, td_real &result);
void Rget52(bool const left, mplapackint const n, td_real *a, mplapackint const lda, td_real *b, mplapackint const ldb, td_real *e, mplapackint const lde, td_real *alphar, td_real *alphai, td_real *beta, td_real *work, td_real *result);
void Rget53(td_real *a, mplapackint const lda, td_real *b, mplapackint const ldb, td_real const scale, td_real const wr, td_real const wi, td_real &result, mplapackint &info);
void Rget54(mplapackint const n, td_real *a, mplapackint const lda, td_real *b, mplapackint const ldb, td_real *s, mplapackint const lds, td_real *t, mplapackint const ldt, td_real *u, mplapackint const ldu, td_real *v, mplapackint const ldv, td_real *work, td_real &result);
void Rglmts(mplapackint const n, mplapackint const m, mplapackint const p, td_real *a, td_real *af, mplapackint const lda, td_real *b, td_real *bf, mplapackint const ldb, td_real *d, td_real *df, td_real *x, td_real *u, td_real *work, mplapackint const lwork, td_real *rwork, td_real &result);
void Rgqrts(mplapackint const n, mplapackint const m, mplapackint const p, td_real *a, td_real *af, td_real *q, td_real *r, mplapackint const lda, td_real *taua, td_real *b, td_real *bf, td_real *z, td_real *t, td_real *bwk, mplapackint const ldb, td_real *taub, td_real *work, mplapackint const lwork, td_real *rwork, td_real *result);
void Rgrqts(mplapackint const m, mplapackint const p, mplapackint const n, td_real *a, td_real *af, td_real *q, td_real *r, mplapackint const lda, td_real *taua, td_real *b, td_real *bf, td_real *z, td_real *t, td_real *bwk, mplapackint const ldb, td_real *taub, td_real *work, mplapackint const lwork, td_real *rwork, td_real *result);
void Rgsvts3(mplapackint const m, mplapackint const p, mplapackint const n, td_real *a, td_real *af, mplapackint const lda, td_real *b, td_real *bf, mplapackint const ldb, td_real *u, mplapackint const ldu, td_real *v, mplapackint const ldv, td_real *q, mplapackint const ldq, td_real *alpha, td_real *beta, td_real *r, mplapackint const ldr, mplapackint *iwork, td_real *work, mplapackint const lwork, td_real *rwork, td_real *result);
void Rhst01(mplapackint const n, mplapackint const, mplapackint const, td_real *a, mplapackint const lda, td_real *h, mplapackint const ldh, td_real *q, mplapackint const ldq, td_real *work, mplapackint const lwork, td_real *result);
void Rlacsg(mplapackint const m, mplapackint const p, mplapackint const q, td_real *theta, mplapackint (&iseed)[4], td_real *x, mplapackint const ldx, td_real *work);
void Rlafts(fem::str_cref type, mplapackint const m, mplapackint const n, mplapackint const imat, mplapackint const ntests, td_real *result, mplapackint (&iseed)[4], td_real const thresh, mplapackint const iounit, mplapackint &ie);
void Rlahd2(mplapackint const iounit, fem::str_cref path);
void Rlarfy(fem::str_cref uplo, mplapackint const n, td_real *v, mplapackint const incv, td_real const tau, td_real *c, mplapackint const ldc, td_real *work);
void Rlarhs(fem::str_cref path, fem::str_cref xtype, fem::str_cref uplo, fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mplapackint const nrhs, td_real *a, mplapackint const lda, td_real *x, mplapackint const ldx, td_real *b, mplapackint const ldb, mplapackint (&iseed)[4], mplapackint &info);
void Rlasum(fem::str_cref type, mplapackint const iounit, mplapackint const ie, mplapackint const nrun);
void Rlatb9(fem::str_cref path, mplapackint const imat, mplapackint const m, mplapackint const p, mplapackint const n, fem::str_ref type, mplapackint &kla, mplapackint &kua, mplapackint &klb, mplapackint &kub, td_real &anorm, td_real &bnorm, mplapackint &modea, mplapackint &modeb, td_real &cndnma, td_real &cndnmb, fem::str_ref dista, fem::str_ref distb);
void Rlatm4(mplapackint const itype, mplapackint const n, mplapackint const nz1, mplapackint const nz2, mplapackint const isign, td_real const amagn, td_real const rcond, td_real const triang, mplapackint const idist, mplapackint (&iseed)[4], td_real *a, mplapackint const lda);
void Rlsets(mplapackint const m, mplapackint const p, mplapackint const n, td_real *a, td_real *af, mplapackint const lda, td_real *b, td_real *bf, mplapackint const ldb, td_real *c, td_real *cf, td_real *d, td_real *df, td_real *x, td_real *work, mplapackint const lwork, td_real *rwork, td_real *result);
void Rort01(fem::str_cref rowcol, mplapackint const m, mplapackint const n, td_real *u, mplapackint const ldu, td_real *work, mplapackint const lwork, td_real &resid);
void Rort03(fem::str_cref rc, mplapackint const mu, mplapackint const mv, mplapackint const n, mplapackint const k, td_real *u, mplapackint const ldu, td_real *v, mplapackint const ldv, td_real *work, mplapackint const lwork, td_real &result, mplapackint &info);
void Rsbt21(fem::str_cref uplo, mplapackint const n, mplapackint const ka, mplapackint const ks, td_real *a, mplapackint const lda, td_real *d, td_real *e, td_real *u, mplapackint const ldu, td_real *work, td_real *result);
void Rsgt01(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const m, td_real *a, mplapackint const lda, td_real *b, mplapackint const ldb, td_real *z, mplapackint const ldz, td_real *d, td_real *work, td_real *result);
void Rspt21(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const kband, td_real *ap, td_real *d, td_real *e, td_real *u, mplapackint const ldu, td_real *vp, td_real *tau, td_real *work, td_real *result);
void Rstech(mplapackint const n, td_real *a, td_real *b, td_real *eig, td_real const tol, td_real *work, mplapackint &info);
void Rstect(mplapackint const n, td_real *a, td_real *b, td_real const shift, mplapackint &num);
void Rstt21(mplapackint const n, mplapackint const kband, td_real *ad, td_real *ae, td_real *sd, td_real *se, td_real *u, mplapackint const ldu, td_real *work, td_real *result);
void Rstt22(mplapackint const n, mplapackint const m, mplapackint const kband, td_real *ad, td_real *ae, td_real *sd, td_real *se, td_real *u, mplapackint const ldu, td_real *work, mplapackint const ldwork, td_real *result);
void Rsvdch(mplapackint const n, td_real *s, td_real *e, td_real *svd, td_real const tol, mplapackint &info);
void Rsvdct(mplapackint const n, td_real *s, td_real *e, td_real const shift, mplapackint &num);
void Rsyl01(td_real const thresh, mplapackint *nfail, td_real *rmax, mplapackint *ninfo, mplapackint &knt);
void Rsyt21(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const kband, td_real *a, mplapackint const lda, td_real *d, td_real *e, td_real *u, mplapackint const ldu, td_real *v, mplapackint const ldv, td_real *tau, td_real *work, td_real *result);
void Rsyt22(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const m, mplapackint const kband, td_real *a, mplapackint const lda, td_real *d, td_real *e, td_real *u, mplapackint const ldu, td_real *, mplapackint const ldv, td_real *, td_real *work, td_real *result);
#endif
