/*
 * Copyright (c) 2008-2025
 *	Nakata, Maho
 * 	All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 */

#ifndef _MPLAPACK_LIN_MPFR_H_
#define _MPLAPACK_LIN_MPFR_H_

#include "mplapack_config.h"

#include <mpfrxx_mkII.h>
#include <mpcxx_mkII.h>
using namespace mpfrxx;


#include <mpblas.h>
#include <mplapack.h>

#include <fem.hpp> // Fortran EMulation library of fable module
using namespace fem::major_types;
using fem::common;

#include <mplapack_matgen.h>
#include <mplapack_lin.h>
#include <mplapack_debug.h>
bool Cgennd(mplapackint const m, mplapackint const n, mpc_class *a, mplapackint const lda);
bool Rgennd(mplapackint const m, mplapackint const n, mpfr_class *a, mplapackint const lda);
mplapackint iMlaenv2stage_mpfr(mplapackint const ispec, const char *name, const char *opts, mplapackint const n1, mplapackint const n2, mplapackint const n3, mplapackint const n4);
mplapackint iMlaenv_mpfr(mplapackint const ispec, const char *name, const char *opts, mplapackint const n1, mplapackint const n2, mplapackint const n3, mplapackint const n4);
mpfr_class Cqpt01(mplapackint const m, mplapackint const n, mplapackint const k, mpc_class *a, mpc_class *af, mplapackint const lda, mpc_class *tau, mplapackint *jpvt, mpc_class *work, mplapackint const lwork);
mpfr_class Cqrt11(mplapackint const m, mplapackint const k, mpc_class *a, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint const lwork);
mpfr_class Cqrt12(mplapackint const m, mplapackint const n, mpc_class *a, mplapackint const lda, mpfr_class *s, mpc_class *work, mplapackint const lwork, mpfr_class *rwork);
mpfr_class Cqrt14(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *x, mplapackint const ldx, mpc_class *work, mplapackint const lwork);
mpfr_class Cqrt17(fem::str_cref trans, mplapackint const iresid, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mpc_class *c, mpc_class *work, mplapackint const lwork);
mpfr_class Crzt01(mplapackint const m, mplapackint const n, mpc_class *a, mpc_class *af, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint const lwork);
mpfr_class Crzt02(mplapackint const m, mplapackint const n, mpc_class *af, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint const lwork);
mpfr_class Rget06(mpfr_class const rcond, mpfr_class const rcondc);
mpfr_class Rlamch_mpfr(const char *cmach);
mpfr_class Rqpt01(mplapackint const m, mplapackint const n, mplapackint const k, mpfr_class *a, mpfr_class *af, mplapackint const lda, mpfr_class *tau, mplapackint *jpvt, mpfr_class *work, mplapackint const lwork);
mpfr_class Rqrt11(mplapackint const m, mplapackint const k, mpfr_class *a, mplapackint const lda, mpfr_class *tau, mpfr_class *work, mplapackint const lwork);
mpfr_class Rqrt12(mplapackint const m, mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class *s, mpfr_class *work, mplapackint const lwork);
mpfr_class Rqrt14(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mpfr_class *x, mplapackint const ldx, mpfr_class *work, mplapackint const lwork);
mpfr_class Rqrt17(fem::str_cref trans, mplapackint const iresid, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mpfr_class *x, mplapackint const ldx, mpfr_class *b, mplapackint const ldb, mpfr_class *c, mpfr_class *work, mplapackint const lwork);
mpfr_class Rrzt01(mplapackint const m, mplapackint const n, mpfr_class *a, mpfr_class *af, mplapackint const lda, mpfr_class *tau, mpfr_class *work, mplapackint const lwork);
mpfr_class Rrzt02(mplapackint const m, mplapackint const n, mpfr_class *af, mplapackint const lda, mpfr_class *tau, mpfr_class *work, mplapackint const lwork);
void Aladhd(mplapackint const iounit, fem::str_cref path);
void Alaerh(fem::str_cref path, fem::str_cref subnam, mplapackint const info, mplapackint const infoe, fem::str_cref opts, mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mplapackint const n5, mplapackint const imat, mplapackint const nfail, mplapackint &nerrs, mplapackint const nout);
void Alaesm(fem::str_cref path, bool const ok, mplapackint const nout);
void Alahd(mplapackint const iounit, fem::str_cref path);
void Alareq(fem::str_cref path, mplapackint const nmats, bool *dotype, mplapackint const ntypes, mplapackint const nin, mplapackint const nout);
void Alasum(fem::str_cref type, mplapackint const nout, mplapackint const nfail, mplapackint const nrun, mplapackint const nerrs);
void Alasvm(fem::str_cref type, mplapackint const nout, mplapackint const nfail, mplapackint const nrun, mplapackint const nerrs);
void Cchkeq(mpfr_class const thresh, mplapackint const nout);
void Cchkgb(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mpc_class *a, mplapackint const la, mpc_class *afac, mplapackint const lafac, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchkge(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchkgt(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mpc_class *a, mpc_class *af, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchkhe(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchkhe_aa(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchkhe_aa_2stage(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchkhe_rk(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpc_class *a, mpc_class *afac, mpc_class *e, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchkhe_rook(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchkhp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchklq(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpc_class *a, mpc_class *af, mpc_class *aq, mpc_class *al, mpc_class *ac, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *tau, mpc_class *work, mpfr_class *rwork, mplapackint const nout);
void Cchklqt(mpfr_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Cchklqtp(mpfr_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Cchkpb(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint const nout);
void Cchkpo(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint const nout);
void Cchkpp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint const nout);
void Cchkps(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nrank, mplapackint *rankval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpc_class *a, mpc_class *afac, mpc_class *perm, mplapackint *piv, mpc_class *work, mpfr_class *rwork, mplapackint const nout);
void Cchkpt(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mpc_class *a, mpfr_class *d, mpc_class *e, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint const nout);
void Cchkq3(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mpfr_class const thresh, mpc_class *a, mpc_class *copya, mpfr_class *s, mpc_class *tau, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchkql(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpc_class *a, mpc_class *af, mpc_class *aq, mpc_class *al, mpc_class *ac, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *tau, mpc_class *work, mpfr_class *rwork, mplapackint const nout);
void Cchkqp3rk(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mpfr_class const thresh, mpc_class *a, mpc_class *copya, mpc_class *b, mpc_class *copyb, mpfr_class *s, mpc_class *tau, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchkqr(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpc_class *a, mpc_class *af, mpc_class *aq, mpc_class *ar, mpc_class *ac, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *tau, mpc_class *work, mpfr_class *rwork, mplapackint *, mplapackint const nout);
void Cchkqrt(mpfr_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Cchkqrtp(mpfr_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Cchkrq(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpc_class *a, mpc_class *af, mpc_class *aq, mpc_class *ar, mpc_class *ac, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *tau, mpc_class *work, mpfr_class *rwork, mplapackint *, mplapackint const nout);
void Cchksp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchksy(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchksy_aa(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchksy_aa_2stage(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchksy_rk(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpc_class *a, mpc_class *afac, mpc_class *e, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchksy_rook(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cchktb(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpc_class *ab, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint const nout);
void Cchktp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpc_class *ap, mpc_class *ainvp, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint const nout);
void Cchktr(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpc_class *a, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint const nout);
void Cchktsqr(mpfr_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Cchktz(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mpfr_class const thresh, bool const tsterr, mpc_class *a, mpc_class *copya, mpfr_class *s, mpc_class *tau, mpc_class *work, mpfr_class *rwork, mplapackint const nout);
void Cchkunhr_col(mpfr_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Cdrvgb(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mpc_class *a, mplapackint const la, mpc_class *afb, mplapackint const lafb, mpc_class *asav, mpc_class *b, mpc_class *bsav, mpc_class *x, mpc_class *xact, mpfr_class *s, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvge(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpc_class *a, mpc_class *afac, mpc_class *asav, mpc_class *b, mpc_class *bsav, mpc_class *x, mpc_class *xact, mpfr_class *s, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvgt(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mpc_class *a, mpc_class *af, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvhe(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvhe_aa(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvhe_aa_2stage(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvhe_rk(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpc_class *a, mpc_class *afac, mpc_class *e, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvhe_rook(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvhp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvls(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mpfr_class const thresh, bool const tsterr, mpc_class *a, mpc_class *copya, mpc_class *b, mpc_class *copyb, mpc_class *c, mpfr_class *s, mpfr_class *copys, mplapackint const nout);
void Cdrvpb(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const, mpc_class *a, mpc_class *afac, mpc_class *asav, mpc_class *b, mpc_class *bsav, mpc_class *x, mpc_class *xact, mpfr_class *s, mpc_class *work, mpfr_class *rwork, mplapackint const nout);
void Cdrvpo(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const, mpc_class *a, mpc_class *afac, mpc_class *asav, mpc_class *b, mpc_class *bsav, mpc_class *x, mpc_class *xact, mpfr_class *s, mpc_class *work, mpfr_class *rwork, mplapackint const nout);
void Cdrvpp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const, mpc_class *a, mpc_class *afac, mpc_class *asav, mpc_class *b, mpc_class *bsav, mpc_class *x, mpc_class *xact, mpfr_class *s, mpc_class *work, mpfr_class *rwork, mplapackint const nout);
void Cdrvpt(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mpc_class *a, mpfr_class *d, mpc_class *e, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint const nout);
void Cdrvrf1(mplapackint const nout, mplapackint const nn, mplapackint *nval, mpfr_class const thresh, mpc_class *a, mplapackint const lda, mpc_class *arf, mpfr_class *work);
void Cdrvrf2(mplapackint const nout, mplapackint const nn, mplapackint *nval, mpc_class *a, mplapackint const lda, mpc_class *arf, mpc_class *ap, mpc_class *asav);
void Cdrvrf3(mplapackint const nout, mplapackint const nn, mplapackint *nval, mpfr_class const thresh, mpc_class *a, mplapackint const lda, mpc_class *arf, mpc_class *b1, mpc_class *b2, mpfr_class *d_work_zlange, mpc_class *z_work_zgeqrf, mpc_class *tau);
void Cdrvrf4(mplapackint const nout, mplapackint const nn, mplapackint *nval, mpfr_class const thresh, mpc_class *c1, mpc_class *c2, mplapackint const ldc, mpc_class *crf, mpc_class *a, mplapackint const lda, mpfr_class *d_work_zlange);
void Cdrvrfp(mplapackint const nout, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mplapackint const nnt, mplapackint *ntval, mpfr_class const thresh, mpc_class *a, mpc_class *asav, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *bsav, mpc_class *xact, mpc_class *x, mpc_class *arf, mpc_class *arfinv, mpc_class *z_work_zlatms, mpc_class *z_work_zpot02, mpc_class *z_work_zpot03, mpfr_class *d_work_zlatms, mpfr_class *d_work_zlanhe, mpfr_class *d_work_zpot01, mpfr_class *d_work_zpot02, mpfr_class *d_work_zpot03);
void Cdrvsp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvsy(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvsy_aa(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvsy_aa_2stage(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvsy_rk(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpc_class *a, mpc_class *afac, mpc_class *e, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cdrvsy_rook(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpc_class *a, mpc_class *afac, mpc_class *ainv, mpc_class *b, mpc_class *x, mpc_class *xact, mpc_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Cerrge(fem::str_cref path, mplapackint const nunit);
void Cerrgt(fem::str_cref path, mplapackint const nunit);
void Cerrhe(fem::str_cref path, mplapackint const nunit);
void Cerrlq(fem::str_cref path, mplapackint const nunit);
void Cerrlqt(fem::str_cref path, mplapackint const nunit);
void Cerrlqtp(fem::str_cref path, mplapackint const nunit);
void Cerrls(fem::str_cref path, mplapackint const nunit);
void Cerrpo(fem::str_cref path, mplapackint const nunit);
void Cerrps(fem::str_cref path, mplapackint const nunit);
void Cerrql(fem::str_cref path, mplapackint const nunit);
void Cerrqp(fem::str_cref path, mplapackint const nunit);
void Cerrqr(fem::str_cref path, mplapackint const nunit);
void Cerrqrt(fem::str_cref path, mplapackint const nunit);
void Cerrqrtp(fem::str_cref path, mplapackint const nunit);
void Cerrrfp(mplapackint const nunit);
void Cerrrq(fem::str_cref path, mplapackint const nunit);
void Cerrsy(fem::str_cref path, mplapackint const nunit);
void Cerrtr(fem::str_cref path, mplapackint const nunit);
void Cerrtsqr(fem::str_cref path, mplapackint const nunit);
void Cerrtz(fem::str_cref path, mplapackint const nunit);
void Cerrunhr_col(fem::str_cref path, mplapackint const nunit);
void Cerrvx(fem::str_cref path, mplapackint const nunit);
void Cgbt01(mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mpc_class *a, mplapackint const lda, mpc_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpc_class *work, mpfr_class &resid);
void Cgbt02(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mpfr_class *rwork, mpfr_class &resid);
void Cgbt05(fem::str_cref trans, mplapackint const n, mplapackint const kl, mplapackint const ku, mplapackint const nrhs, mpc_class *ab, mplapackint const ldab, mpc_class *b, mplapackint const ldb, mpc_class *x, mplapackint const ldx, mpc_class *xact, mplapackint const ldxact, mpfr_class *ferr, mpfr_class *berr, mpfr_class *reslts);
void Cgeqls(mplapackint const m, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *tau, mpc_class *b, mplapackint const ldb, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Cgerqs(mplapackint const m, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *tau, mpc_class *b, mplapackint const ldb, mpc_class *work, mplapackint const lwork, mplapackint &info);
void Cget01(mplapackint const m, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpfr_class *rwork, mpfr_class &resid);
void Cget02(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mpfr_class *rwork, mpfr_class &resid);
void Cget03(mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *ainv, mplapackint const ldainv, mpc_class *work, mplapackint const ldwork, mpfr_class *rwork, mpfr_class &rcond, mpfr_class &resid);
void Cget04(mplapackint const n, mplapackint const nrhs, mpc_class *x, mplapackint const ldx, mpc_class *xact, mplapackint const ldxact, mpfr_class const rcond, mpfr_class &resid);
void Cget07(fem::str_cref trans, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mpc_class *x, mplapackint const ldx, mpc_class *xact, mplapackint const ldxact, mpfr_class *ferr, bool const chkferr, mpfr_class *berr, mpfr_class *reslts);
void Cget08(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mpfr_class *rwork, mpfr_class &resid);
void Cgtt01(mplapackint const n, mpc_class *dl, mpc_class *d, mpc_class *du, mpc_class *dlf, mpc_class *df, mpc_class *duf, mpc_class *du2, mplapackint *ipiv, mpc_class *work, mplapackint const ldwork, mpfr_class *rwork, mpfr_class &resid);
void Cgtt02(fem::str_cref trans, mplapackint const n, mplapackint const nrhs, mpc_class *dl, mpc_class *d, mpc_class *du, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mpfr_class &resid);
void Cgtt05(fem::str_cref trans, mplapackint const n, mplapackint const nrhs, mpc_class *dl, mpc_class *d, mpc_class *du, mpc_class *b, mplapackint const ldb, mpc_class *x, mplapackint const ldx, mpc_class *xact, mplapackint const ldxact, mpfr_class *ferr, mpfr_class *berr, mpfr_class *reslts);
void Chet01(fem::str_cref uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpc_class *c, mplapackint const ldc, mpfr_class *rwork, mpfr_class &resid);
void Chet01_3(fem::str_cref uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *afac, mplapackint const ldafac, mpc_class *e, mplapackint *ipiv, mpc_class *c, mplapackint const ldc, mpfr_class *rwork, mpfr_class &resid);
void Chet01_aa(fem::str_cref uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpc_class *c, mplapackint const ldc, mpfr_class *rwork, mpfr_class &resid);
void Chet01_rook(fem::str_cref uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpc_class *c, mplapackint const ldc, mpfr_class *rwork, mpfr_class &resid);
void Chkxer(fem::str_cref srnamt, mplapackint const infot, mplapackint const nout, bool &lerr, bool &ok);
void Chpt01(fem::str_cref uplo, mplapackint const n, mpc_class *a, mpc_class *afac, mplapackint *ipiv, mpc_class *c, mplapackint const ldc, mpfr_class *rwork, mpfr_class &resid);
void Clahilb(mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mpfr_class *work, mplapackint &info, fem::str_cref path);
void Claipd(mplapackint const n, mpc_class *a, mplapackint const inda, mplapackint const vinda);
void Claptm(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpfr_class const alpha, mpfr_class *d, mpc_class *e, mpc_class *x, mplapackint const ldx, mpfr_class const beta, mpc_class *b, mplapackint const ldb);
void Clarhs(fem::str_cref path, fem::str_cref xtype, fem::str_cref uplo, fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mplapackint (&iseed)[4], mplapackint &info);
void Clatb4(fem::str_cref path, mplapackint const imat, mplapackint const m, mplapackint const n, fem::str_ref type, mplapackint &kl, mplapackint &ku, mpfr_class &anorm, mplapackint &mode, mpfr_class &cndnum, fem::str_ref dist);
void Clatb5(fem::str_cref path, mplapackint const imat, mplapackint const n, fem::str_ref type, mplapackint &kl, mplapackint &ku, mpfr_class &anorm, mplapackint &mode, mpfr_class &cndnum, fem::str_ref dist);
void Clatsp(fem::str_cref uplo, mplapackint const n, mpc_class *x, mplapackint (&iseed)[4]);
void Clatsy(fem::str_cref uplo, mplapackint const n, mpc_class *x, mplapackint const ldx, mplapackint (&iseed)[4]);
void Clattb(mplapackint const imat, fem::str_cref uplo, fem::str_cref trans, fem::str_ref diag, mplapackint (&iseed)[4], mplapackint const n, mplapackint const kd, mpc_class *ab, mplapackint const ldab, mpc_class *b, mpc_class *work, mpfr_class *rwork, mplapackint &info);
void Clattp(mplapackint const imat, fem::str_cref uplo, fem::str_cref trans, fem::str_ref diag, mplapackint (&iseed)[4], mplapackint const n, mpc_class *ap, mpc_class *b, mpc_class *work, mpfr_class *rwork, mplapackint &info);
void Clattr(mplapackint const imat, fem::str_cref uplo, fem::str_cref trans, fem::str_ref diag, mplapackint (&iseed)[4], mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *b, mpc_class *work, mpfr_class *rwork, mplapackint &info);
void Clavhe(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Clavhe_rook(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Clavhp(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Clavsp(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Clavsy(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Clavsy_rook(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mplapackint *ipiv, mpc_class *b, mplapackint const ldb, mplapackint &info);
void Clqt01(mplapackint const m, mplapackint const n, mpc_class *a, mpc_class *af, mpc_class *q, mpc_class *l, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Clqt02(mplapackint const m, mplapackint const n, mplapackint const k, mpc_class *a, mpc_class *af, mpc_class *q, mpc_class *l, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Clqt03(mplapackint const m, mplapackint const n, mplapackint const k, mpc_class *af, mpc_class *c, mpc_class *cc, mpc_class *q, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Clqt04(mplapackint const m, mplapackint const n, mplapackint const nb, mpfr_class *result);
void Clqt05(mplapackint const m, mplapackint const n, mplapackint const l, mplapackint const nb, mpfr_class *result);
void Cpbt01(fem::str_cref uplo, mplapackint const n, mplapackint const kd, mpc_class *a, mplapackint const lda, mpc_class *afac, mplapackint const ldafac, mpfr_class *rwork, mpfr_class &resid);
void Cpbt02(fem::str_cref uplo, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mpfr_class *rwork, mpfr_class &resid);
void Cpbt05(fem::str_cref uplo, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpc_class *ab, mplapackint const ldab, mpc_class *b, mplapackint const ldb, mpc_class *x, mplapackint const ldx, mpc_class *xact, mplapackint const ldxact, mpfr_class *ferr, mpfr_class *berr, mpfr_class *reslts);
void Cpot01(fem::str_cref uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *afac, mplapackint const ldafac, mpfr_class *rwork, mpfr_class &resid);
void Cpot02(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mpfr_class *rwork, mpfr_class &resid);
void Cpot03(fem::str_cref uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *ainv, mplapackint const ldainv, mpc_class *work, mplapackint const ldwork, mpfr_class *rwork, mpfr_class &rcond, mpfr_class &resid);
void Cpot05(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mpc_class *x, mplapackint const ldx, mpc_class *xact, mplapackint const ldxact, mpfr_class *ferr, mpfr_class *berr, mpfr_class *reslts);
void Cpot06(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mpfr_class *rwork, mpfr_class &resid);
void Cppt01(fem::str_cref uplo, mplapackint const n, mpc_class *a, mpc_class *afac, mpfr_class *rwork, mpfr_class &resid);
void Cppt02(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpc_class *a, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mpfr_class *rwork, mpfr_class &resid);
void Cppt03(fem::str_cref uplo, mplapackint const n, mpc_class *a, mpc_class *ainv, mpc_class *work, mplapackint const ldwork, mpfr_class *rwork, mpfr_class &rcond, mpfr_class &resid);
void Cppt05(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpc_class *ap, mpc_class *b, mplapackint const ldb, mpc_class *x, mplapackint const ldx, mpc_class *xact, mplapackint const ldxact, mpfr_class *ferr, mpfr_class *berr, mpfr_class *reslts);
void Cpst01(fem::str_cref uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *afac, mplapackint const ldafac, mpc_class *perm, mplapackint const ldperm, mplapackint *piv, mpfr_class *rwork, mpfr_class &resid, mplapackint const rank);
void Cptt01(mplapackint const n, mpfr_class *d, mpc_class *e, mpfr_class *df, mpc_class *ef, mpc_class *work, mpfr_class &resid);
void Cptt02(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpfr_class *d, mpc_class *e, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mpfr_class &resid);
void Cptt05(mplapackint const n, mplapackint const nrhs, mpfr_class *d, mpc_class *e, mpc_class *b, mplapackint const ldb, mpc_class *x, mplapackint const ldx, mpc_class *xact, mplapackint const ldxact, mpfr_class *ferr, mpfr_class *berr, mpfr_class *reslts);
void Cqlt01(mplapackint const m, mplapackint const n, mpc_class *a, mpc_class *af, mpc_class *q, mpc_class *l, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Cqlt02(mplapackint const m, mplapackint const n, mplapackint const k, mpc_class *a, mpc_class *af, mpc_class *q, mpc_class *l, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Cqlt03(mplapackint const m, mplapackint const n, mplapackint const k, mpc_class *af, mpc_class *c, mpc_class *cc, mpc_class *q, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Cqrt01(mplapackint const m, mplapackint const n, mpc_class *a, mpc_class *af, mpc_class *q, mpc_class *r, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Cqrt01p(mplapackint const m, mplapackint const n, mpc_class *a, mpc_class *af, mpc_class *q, mpc_class *r, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Cqrt02(mplapackint const m, mplapackint const n, mplapackint const k, mpc_class *a, mpc_class *af, mpc_class *q, mpc_class *r, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Cqrt03(mplapackint const m, mplapackint const n, mplapackint const k, mpc_class *af, mpc_class *c, mpc_class *cc, mpc_class *q, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Cqrt04(mplapackint const m, mplapackint const n, mplapackint const nb, mpfr_class *result);
void Cqrt05(mplapackint const m, mplapackint const n, mplapackint const l, mplapackint const nb, mpfr_class *result);
void Cqrt13(mplapackint const scale, mplapackint const m, mplapackint const n, mpc_class *a, mplapackint const lda, mpfr_class &norma, mplapackint (&iseed)[4]);
void Cqrt15(mplapackint const scale, mplapackint const rksel, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mpfr_class *s, mplapackint &rank, mpfr_class &norma, mpfr_class &normb, mplapackint (&iseed)[4], mpc_class *work, mplapackint const lwork);
void Cqrt16(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mpfr_class *rwork, mpfr_class &resid);
void Crqt01(mplapackint const m, mplapackint const n, mpc_class *a, mpc_class *af, mpc_class *q, mpc_class *r, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Crqt02(mplapackint const m, mplapackint const n, mplapackint const k, mpc_class *a, mpc_class *af, mpc_class *q, mpc_class *r, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Crqt03(mplapackint const m, mplapackint const n, mplapackint const k, mpc_class *af, mpc_class *c, mpc_class *cc, mpc_class *q, mplapackint const lda, mpc_class *tau, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Csbmv(fem::str_cref uplo, mplapackint const n, mplapackint const k, mpc_class const alpha, mpc_class *a, mplapackint const lda, mpc_class *x, mplapackint const incx, mpc_class const beta, mpc_class *y, mplapackint const incy);
void Cspt01(fem::str_cref uplo, mplapackint const n, mpc_class *a, mpc_class *afac, mplapackint *ipiv, mpc_class *c, mplapackint const ldc, mpfr_class *rwork, mpfr_class &resid);
void Cspt02(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpc_class *a, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mpfr_class *rwork, mpfr_class &resid);
void Cspt03(fem::str_cref uplo, mplapackint const n, mpc_class *a, mpc_class *ainv, mpc_class *work, mplapackint const ldw, mpfr_class *rwork, mpfr_class &rcond, mpfr_class &resid);
void Csyt01(fem::str_cref uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpc_class *c, mplapackint const ldc, mpfr_class *rwork, mpfr_class &resid);
void Csyt01_3(fem::str_cref uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *afac, mplapackint const ldafac, mpc_class *e, mplapackint *ipiv, mpc_class *c, mplapackint const ldc, mpfr_class *rwork, mpfr_class &resid);
void Csyt01_aa(fem::str_cref uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpc_class *c, mplapackint const ldc, mpfr_class *rwork, mpfr_class &resid);
void Csyt01_rook(fem::str_cref uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpc_class *c, mplapackint const ldc, mpfr_class *rwork, mpfr_class &resid);
void Csyt02(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mpfr_class *rwork, mpfr_class &resid);
void Csyt03(fem::str_cref uplo, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *ainv, mplapackint const ldainv, mpc_class *work, mplapackint const ldwork, mpfr_class *rwork, mpfr_class &rcond, mpfr_class &resid);
void Ctbt02(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpc_class *ab, mplapackint const ldab, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mpc_class *work, mpfr_class *rwork, mpfr_class &resid);
void Ctbt03(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpc_class *ab, mplapackint const ldab, mpfr_class const scale, mpfr_class *cnorm, mpfr_class const tscal, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mpc_class *work, mpfr_class &resid);
void Ctbt05(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpc_class *ab, mplapackint const ldab, mpc_class *b, mplapackint const ldb, mpc_class *x, mplapackint const ldx, mpc_class *xact, mplapackint const ldxact, mpfr_class *ferr, mpfr_class *berr, mpfr_class *reslts);
void Ctbt06(mpfr_class const rcond, mpfr_class const rcondc, fem::str_cref uplo, fem::str_cref diag, mplapackint const n, mplapackint const kd, mpc_class *ab, mplapackint const ldab, mpfr_class *rwork, mpfr_class &rat);
void Ctpt01(fem::str_cref uplo, fem::str_cref diag, mplapackint const n, mpc_class *ap, mpc_class *ainvp, mpfr_class &rcond, mpfr_class *rwork, mpfr_class &resid);
void Ctpt02(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpc_class *ap, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mpc_class *work, mpfr_class *rwork, mpfr_class &resid);
void Ctpt03(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpc_class *ap, mpfr_class const scale, mpfr_class *cnorm, mpfr_class const tscal, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mpc_class *work, mpfr_class &resid);
void Ctpt05(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpc_class *ap, mpc_class *b, mplapackint const ldb, mpc_class *x, mplapackint const ldx, mpc_class *xact, mplapackint const ldxact, mpfr_class *ferr, mpfr_class *berr, mpfr_class *reslts);
void Ctpt06(mpfr_class const rcond, mpfr_class const rcondc, fem::str_cref uplo, fem::str_cref diag, mplapackint const n, mpc_class *ap, mpfr_class *rwork, mpfr_class &rat);
void Ctrt01(fem::str_cref uplo, fem::str_cref diag, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *ainv, mplapackint const ldainv, mpfr_class &rcond, mpfr_class *rwork, mpfr_class &resid);
void Ctrt02(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mpc_class *work, mpfr_class *rwork, mpfr_class &resid);
void Ctrt03(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpfr_class const scale, mpfr_class *cnorm, mpfr_class const tscal, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mpc_class *work, mpfr_class &resid);
void Ctrt05(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mpc_class *x, mplapackint const ldx, mpc_class *xact, mplapackint const ldxact, mpfr_class *ferr, mpfr_class *berr, mpfr_class *reslts);
void Ctrt06(mpfr_class const rcond, mpfr_class const rcondc, fem::str_cref uplo, fem::str_cref diag, mplapackint const n, mpc_class *a, mplapackint const lda, mpfr_class *rwork, mpfr_class &rat);
void Ctsqr01(fem::str_cref tssw, mplapackint const m, mplapackint const n, mplapackint const mb, mplapackint const nb, mpfr_class *result);
void Cunhr_col01(mplapackint const m, mplapackint const n, mplapackint const mb1, mplapackint const nb1, mplapackint const nb2, mpfr_class *result);
void Cunhr_col02(mplapackint const m, mplapackint const n, mplapackint const mb1, mplapackint const nb1, mplapackint const nb2, mpfr_class *result);
void Mxerbla_mpfr(const char *srname, int info);
void Mxlaenv(mplapackint const ispec, mplapackint const nvalue);
void Rchkeq(mpfr_class const thresh, mplapackint const nout);
void Rchkgb(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mpfr_class *a, mplapackint const la, mpfr_class *afac, mplapackint const lafac, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchkge(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpfr_class *a, mpfr_class *afac, mpfr_class *ainv, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchkgt(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mpfr_class *a, mpfr_class *af, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchklq(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpfr_class *a, mpfr_class *af, mpfr_class *aq, mpfr_class *al, mpfr_class *ac, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *tau, mpfr_class *work, mpfr_class *rwork, mplapackint const nout);
void Rchklqt(mpfr_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Rchklqtp(mpfr_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Rchkorhr_col(mpfr_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Rchkpb(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpfr_class *a, mpfr_class *afac, mpfr_class *ainv, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchkpo(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpfr_class *a, mpfr_class *afac, mpfr_class *ainv, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchkpp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpfr_class *a, mpfr_class *afac, mpfr_class *ainv, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchkps(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nrank, mplapackint *rankval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpfr_class *a, mpfr_class *afac, mpfr_class *perm, mplapackint *piv, mpfr_class *work, mpfr_class *rwork, mplapackint const nout);
void Rchkpt(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mpfr_class *a, mpfr_class *d, mpfr_class *e, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint const nout);
void Rchkq3(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mpfr_class const thresh, mpfr_class *a, mpfr_class *copya, mpfr_class *s, mpfr_class *tau, mpfr_class *work, mplapackint *iwork, mplapackint const nout);
void Rchkql(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpfr_class *a, mpfr_class *af, mpfr_class *aq, mpfr_class *al, mpfr_class *ac, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *tau, mpfr_class *work, mpfr_class *rwork, mplapackint const nout);
void Rchkqp3rk(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mpfr_class const thresh, mpfr_class *a, mpfr_class *copya, mpfr_class *b, mpfr_class *copyb, mpfr_class *s, mpfr_class *tau, mpfr_class *work, mplapackint *iwork, mplapackint const nout);
void Rchkqr(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpfr_class *a, mpfr_class *af, mpfr_class *aq, mpfr_class *ar, mpfr_class *ac, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *tau, mpfr_class *work, mpfr_class *rwork, mplapackint *, mplapackint const nout);
void Rchkqrt(mpfr_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Rchkqrtp(mpfr_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Rchkrq(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpfr_class *a, mpfr_class *af, mpfr_class *aq, mpfr_class *ar, mpfr_class *ac, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *tau, mpfr_class *work, mpfr_class *rwork, mplapackint *, mplapackint const nout);
void Rchksp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpfr_class *a, mpfr_class *afac, mpfr_class *ainv, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchksy(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpfr_class *a, mpfr_class *afac, mpfr_class *ainv, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchksy_aa(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpfr_class *a, mpfr_class *afac, mpfr_class *ainv, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchksy_aa_2stage(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpfr_class *a, mpfr_class *afac, mpfr_class *ainv, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchksy_rk(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpfr_class *a, mpfr_class *afac, mpfr_class *e, mpfr_class *ainv, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchksy_rook(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpfr_class *a, mpfr_class *afac, mpfr_class *ainv, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchktb(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpfr_class *ab, mpfr_class *ainv, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchktp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const, mpfr_class *ap, mpfr_class *ainvp, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchktr(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nns, mplapackint *nsval, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpfr_class *a, mpfr_class *ainv, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rchktsqr(mpfr_class const thresh, bool const tsterr, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nnb, mplapackint *nbval, mplapackint const nout);
void Rchktz(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mpfr_class const thresh, bool const tsterr, mpfr_class *a, mpfr_class *copya, mpfr_class *s, mpfr_class *tau, mpfr_class *work, mplapackint const nout);
void Rdrvgb(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mpfr_class *a, mplapackint const la, mpfr_class *afb, mplapackint const lafb, mpfr_class *asav, mpfr_class *b, mpfr_class *bsav, mpfr_class *x, mpfr_class *xact, mpfr_class *s, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvge(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpfr_class *a, mpfr_class *afac, mpfr_class *asav, mpfr_class *b, mpfr_class *bsav, mpfr_class *x, mpfr_class *xact, mpfr_class *s, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvgt(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mpfr_class *a, mpfr_class *af, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvls(bool *dotype, mplapackint const nm, mplapackint *mval, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mplapackint const nnb, mplapackint *nbval, mplapackint *nxval, mpfr_class const thresh, bool const tsterr, mpfr_class *a, mpfr_class *copya, mpfr_class *b, mpfr_class *copyb, mpfr_class *c, mpfr_class *s, mpfr_class *copys, mplapackint const nout);
void Rdrvpb(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const, mpfr_class *a, mpfr_class *afac, mpfr_class *asav, mpfr_class *b, mpfr_class *bsav, mpfr_class *x, mpfr_class *xact, mpfr_class *s, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvpo(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const, mpfr_class *a, mpfr_class *afac, mpfr_class *asav, mpfr_class *b, mpfr_class *bsav, mpfr_class *x, mpfr_class *xact, mpfr_class *s, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvpp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const, mpfr_class *a, mpfr_class *afac, mpfr_class *asav, mpfr_class *b, mpfr_class *bsav, mpfr_class *x, mpfr_class *xact, mpfr_class *s, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvpt(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mpfr_class *a, mpfr_class *d, mpfr_class *e, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint const nout);
void Rdrvrf1(mplapackint const nout, mplapackint const nn, mplapackint *nval, mpfr_class const thresh, mpfr_class *a, mplapackint const lda, mpfr_class *arf, mpfr_class *work);
void Rdrvrf2(mplapackint const nout, mplapackint const nn, mplapackint *nval, mpfr_class *a, mplapackint const lda, mpfr_class *arf, mpfr_class *ap, mpfr_class *asav);
void Rdrvrf3(mplapackint const nout, mplapackint const nn, mplapackint *nval, mpfr_class const thresh, mpfr_class *a, mplapackint const lda, mpfr_class *arf, mpfr_class *b1, mpfr_class *b2, mpfr_class *d_work_dlange, mpfr_class *d_work_dgeqrf, mpfr_class *tau);
void Rdrvrf4(mplapackint const nout, mplapackint const nn, mplapackint *nval, mpfr_class const thresh, mpfr_class *c1, mpfr_class *c2, mplapackint const ldc, mpfr_class *crf, mpfr_class *a, mplapackint const lda, mpfr_class *d_work_dlange);
void Rdrvrfp(mplapackint const nout, mplapackint const nn, mplapackint *nval, mplapackint const nns, mplapackint *nsval, mplapackint const nnt, mplapackint *ntval, mpfr_class const thresh, mpfr_class *a, mpfr_class *asav, mpfr_class *afac, mpfr_class *ainv, mpfr_class *b, mpfr_class *bsav, mpfr_class *xact, mpfr_class *x, mpfr_class *arf, mpfr_class *arfinv, mpfr_class *d_work_dlatms, mpfr_class *d_work_dpot01, mpfr_class *d_temp_dpot02, mpfr_class *d_temp_dpot03, mpfr_class *d_work_dlansy, mpfr_class *d_work_dpot02, mpfr_class *d_work_dpot03);
void Rdrvsp(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpfr_class *a, mpfr_class *afac, mpfr_class *ainv, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvsy(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpfr_class *a, mpfr_class *afac, mpfr_class *ainv, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvsy_aa(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const, mpfr_class *a, mpfr_class *afac, mpfr_class *ainv, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvsy_aa_2stage(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpfr_class *a, mpfr_class *afac, mpfr_class *ainv, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvsy_rk(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpfr_class *a, mpfr_class *afac, mpfr_class *e, mpfr_class *ainv, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rdrvsy_rook(bool *dotype, mplapackint const nn, mplapackint *nval, mplapackint const nrhs, mpfr_class const thresh, bool const tsterr, mplapackint const nmax, mpfr_class *a, mpfr_class *afac, mpfr_class *ainv, mpfr_class *b, mpfr_class *x, mpfr_class *xact, mpfr_class *work, mpfr_class *rwork, mplapackint *iwork, mplapackint const nout);
void Rerrge(fem::str_cref path, mplapackint const nunit);
void Rerrgt(fem::str_cref path, mplapackint const nunit);
void Rerrlq(fem::str_cref path, mplapackint const nunit);
void Rerrlqt(fem::str_cref path, mplapackint const nunit);
void Rerrlqtp(fem::str_cref path, mplapackint const nunit);
void Rerrls(fem::str_cref path, mplapackint const nunit);
void Rerrorhr_col(fem::str_cref path, mplapackint const nunit);
void Rerrpo(fem::str_cref path, mplapackint const nunit);
void Rerrps(fem::str_cref path, mplapackint const nunit);
void Rerrql(fem::str_cref path, mplapackint const nunit);
void Rerrqp(fem::str_cref path, mplapackint const nunit);
void Rerrqr(fem::str_cref path, mplapackint const nunit);
void Rerrqrt(fem::str_cref path, mplapackint const nunit);
void Rerrqrtp(fem::str_cref path, mplapackint const nunit);
void Rerrrfp(mplapackint const nunit);
void Rerrrq(fem::str_cref path, mplapackint const nunit);
void Rerrsy(fem::str_cref path, mplapackint const nunit);
void Rerrtr(fem::str_cref path, mplapackint const nunit);
void Rerrtsqr(fem::str_cref path, mplapackint const nunit);
void Rerrtz(fem::str_cref path, mplapackint const nunit);
void Rerrvx(fem::str_cref path, mplapackint const nunit);
void Rgbt01(mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mpfr_class *a, mplapackint const lda, mpfr_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpfr_class *work, mpfr_class &resid);
void Rgbt02(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mpfr_class *x, mplapackint const ldx, mpfr_class *b, mplapackint const ldb, mpfr_class *rwork, mpfr_class &resid);
void Rgbt05(fem::str_cref trans, mplapackint const n, mplapackint const kl, mplapackint const ku, mplapackint const nrhs, mpfr_class *ab, mplapackint const ldab, mpfr_class *b, mplapackint const ldb, mpfr_class *x, mplapackint const ldx, mpfr_class *xact, mplapackint const ldxact, mpfr_class *ferr, mpfr_class *berr, mpfr_class *reslts);
void Rgeqls(mplapackint const m, mplapackint const n, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mpfr_class *tau, mpfr_class *b, mplapackint const ldb, mpfr_class *work, mplapackint const lwork, mplapackint &info);
void Rgerqs(mplapackint const m, mplapackint const n, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mpfr_class *tau, mpfr_class *b, mplapackint const ldb, mpfr_class *work, mplapackint const lwork, mplapackint &info);
void Rget01(mplapackint const m, mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpfr_class *rwork, mpfr_class &resid);
void Rget02(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mpfr_class *x, mplapackint const ldx, mpfr_class *b, mplapackint const ldb, mpfr_class *rwork, mpfr_class &resid);
void Rget03(mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class *ainv, mplapackint const ldainv, mpfr_class *work, mplapackint const ldwork, mpfr_class *rwork, mpfr_class &rcond, mpfr_class &resid);
void Rget04(mplapackint const n, mplapackint const nrhs, mpfr_class *x, mplapackint const ldx, mpfr_class *xact, mplapackint const ldxact, mpfr_class const rcond, mpfr_class &resid);
void Rget07(fem::str_cref trans, mplapackint const n, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mpfr_class *b, mplapackint const ldb, mpfr_class *x, mplapackint const ldx, mpfr_class *xact, mplapackint const ldxact, mpfr_class *ferr, bool const chkferr, mpfr_class *berr, mpfr_class *reslts);
void Rget08(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mpfr_class *x, mplapackint const ldx, mpfr_class *b, mplapackint const ldb, mpfr_class *rwork, mpfr_class &resid);
void Rgtt01(mplapackint const n, mpfr_class *dl, mpfr_class *d, mpfr_class *du, mpfr_class *dlf, mpfr_class *df, mpfr_class *duf, mpfr_class *du2, mplapackint *ipiv, mpfr_class *work, mplapackint const ldwork, mpfr_class *rwork, mpfr_class &resid);
void Rgtt02(fem::str_cref trans, mplapackint const n, mplapackint const nrhs, mpfr_class *dl, mpfr_class *d, mpfr_class *du, mpfr_class *x, mplapackint const ldx, mpfr_class *b, mplapackint const ldb, mpfr_class &resid);
void Rgtt05(fem::str_cref trans, mplapackint const n, mplapackint const nrhs, mpfr_class *dl, mpfr_class *d, mpfr_class *du, mpfr_class *b, mplapackint const ldb, mpfr_class *x, mplapackint const ldx, mpfr_class *xact, mplapackint const ldxact, mpfr_class *ferr, mpfr_class *berr, mpfr_class *reslts);
void Rlahilb(mplapackint const n, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mpfr_class *x, mplapackint const ldx, mpfr_class *b, mplapackint const ldb, mpfr_class *work, mplapackint &info);
void Rlaord(fem::str_cref job, mplapackint const n, mpfr_class *x, mplapackint const incx);
void Rlaptm(mplapackint const n, mplapackint const nrhs, mpfr_class const alpha, mpfr_class *d, mpfr_class *e, mpfr_class *x, mplapackint const ldx, mpfr_class const beta, mpfr_class *b, mplapackint const ldb);
void Rlarhs(fem::str_cref path, fem::str_cref xtype, fem::str_cref uplo, fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mpfr_class *x, mplapackint const ldx, mpfr_class *b, mplapackint const ldb, mplapackint (&iseed)[4], mplapackint &info);
void Rlatb4(fem::str_cref path, mplapackint const imat, mplapackint const m, mplapackint const n, fem::str_ref type, mplapackint &kl, mplapackint &ku, mpfr_class &anorm, mplapackint &mode, mpfr_class &cndnum, fem::str_ref dist);
void Rlatb5(fem::str_cref path, mplapackint const imat, mplapackint const n, fem::str_ref type, mplapackint &kl, mplapackint &ku, mpfr_class &anorm, mplapackint &mode, mpfr_class &cndnum, fem::str_ref dist);
void Rlattb(mplapackint const imat, fem::str_cref uplo, fem::str_cref trans, fem::str_ref diag, mplapackint (&iseed)[4], mplapackint const n, mplapackint const kd, mpfr_class *ab, mplapackint const ldab, mpfr_class *b, mpfr_class *work, mplapackint &info);
void Rlattp(mplapackint const imat, fem::str_cref uplo, fem::str_cref trans, fem::str_ref diag, mplapackint (&iseed)[4], mplapackint const n, mpfr_class *a, mpfr_class *b, mpfr_class *work, mplapackint &info);
void Rlattr(mplapackint const imat, fem::str_cref uplo, fem::str_cref trans, fem::str_ref diag, mplapackint (&iseed)[4], mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class *b, mpfr_class *work, mplapackint &info);
void Rlavsp(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpfr_class *a, mplapackint *ipiv, mpfr_class *b, mplapackint const ldb, mplapackint &info);
void Rlavsy(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mplapackint *ipiv, mpfr_class *b, mplapackint const ldb, mplapackint &info);
void Rlavsy_rook(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mplapackint *ipiv, mpfr_class *b, mplapackint const ldb, mplapackint &info);
void Rlqt01(mplapackint const m, mplapackint const n, mpfr_class *a, mpfr_class *af, mpfr_class *q, mpfr_class *l, mplapackint const lda, mpfr_class *tau, mpfr_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Rlqt02(mplapackint const m, mplapackint const n, mplapackint const k, mpfr_class *a, mpfr_class *af, mpfr_class *q, mpfr_class *l, mplapackint const lda, mpfr_class *tau, mpfr_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Rlqt03(mplapackint const m, mplapackint const n, mplapackint const k, mpfr_class *af, mpfr_class *c, mpfr_class *cc, mpfr_class *q, mplapackint const lda, mpfr_class *tau, mpfr_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Rlqt04(mplapackint const m, mplapackint const n, mplapackint const nb, mpfr_class *result);
void Rlqt05(mplapackint const m, mplapackint const n, mplapackint const l, mplapackint const nb, mpfr_class *result);
void Rorhr_col01(mplapackint const m, mplapackint const n, mplapackint const mb1, mplapackint const nb1, mplapackint const nb2, mpfr_class *result);
void Rorhr_col02(mplapackint const m, mplapackint const n, mplapackint const mb1, mplapackint const nb1, mplapackint const nb2, mpfr_class *result);
void Rpbt01(fem::str_cref uplo, mplapackint const n, mplapackint const kd, mpfr_class *a, mplapackint const lda, mpfr_class *afac, mplapackint const ldafac, mpfr_class *rwork, mpfr_class &resid);
void Rpbt02(fem::str_cref uplo, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mpfr_class *x, mplapackint const ldx, mpfr_class *b, mplapackint const ldb, mpfr_class *rwork, mpfr_class &resid);
void Rpbt05(fem::str_cref uplo, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpfr_class *ab, mplapackint const ldab, mpfr_class *b, mplapackint const ldb, mpfr_class *x, mplapackint const ldx, mpfr_class *xact, mplapackint const ldxact, mpfr_class *ferr, mpfr_class *berr, mpfr_class *reslts);
void Rpot01(fem::str_cref uplo, mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class *afac, mplapackint const ldafac, mpfr_class *rwork, mpfr_class &resid);
void Rpot02(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mpfr_class *x, mplapackint const ldx, mpfr_class *b, mplapackint const ldb, mpfr_class *rwork, mpfr_class &resid);
void Rpot03(fem::str_cref uplo, mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class *ainv, mplapackint const ldainv, mpfr_class *work, mplapackint const ldwork, mpfr_class *rwork, mpfr_class &rcond, mpfr_class &resid);
void Rpot05(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mpfr_class *b, mplapackint const ldb, mpfr_class *x, mplapackint const ldx, mpfr_class *xact, mplapackint const ldxact, mpfr_class *ferr, mpfr_class *berr, mpfr_class *reslts);
void Rpot06(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mpfr_class *x, mplapackint const ldx, mpfr_class *b, mplapackint const ldb, mpfr_class *rwork, mpfr_class &resid);
void Rppt01(fem::str_cref uplo, mplapackint const n, mpfr_class *a, mpfr_class *afac, mpfr_class *rwork, mpfr_class &resid);
void Rppt02(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpfr_class *a, mpfr_class *x, mplapackint const ldx, mpfr_class *b, mplapackint const ldb, mpfr_class *rwork, mpfr_class &resid);
void Rppt03(fem::str_cref uplo, mplapackint const n, mpfr_class *a, mpfr_class *ainv, mpfr_class *work, mplapackint const ldwork, mpfr_class *rwork, mpfr_class &rcond, mpfr_class &resid);
void Rppt05(fem::str_cref uplo, mplapackint const n, mplapackint const nrhs, mpfr_class *ap, mpfr_class *b, mplapackint const ldb, mpfr_class *x, mplapackint const ldx, mpfr_class *xact, mplapackint const ldxact, mpfr_class *ferr, mpfr_class *berr, mpfr_class *reslts);
void Rpst01(fem::str_cref uplo, mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class *afac, mplapackint const ldafac, mpfr_class *perm, mplapackint const ldperm, mplapackint *piv, mpfr_class *rwork, mpfr_class &resid, mplapackint const rank);
void Rptt01(mplapackint const n, mpfr_class *d, mpfr_class *e, mpfr_class *df, mpfr_class *ef, mpfr_class *work, mpfr_class &resid);
void Rptt02(mplapackint const n, mplapackint const nrhs, mpfr_class *d, mpfr_class *e, mpfr_class *x, mplapackint const ldx, mpfr_class *b, mplapackint const ldb, mpfr_class &resid);
void Rptt05(mplapackint const n, mplapackint const nrhs, mpfr_class *d, mpfr_class *e, mpfr_class *b, mplapackint const ldb, mpfr_class *x, mplapackint const ldx, mpfr_class *xact, mplapackint const ldxact, mpfr_class *ferr, mpfr_class *berr, mpfr_class *reslts);
void Rqlt01(mplapackint const m, mplapackint const n, mpfr_class *a, mpfr_class *af, mpfr_class *q, mpfr_class *l, mplapackint const lda, mpfr_class *tau, mpfr_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Rqlt02(mplapackint const m, mplapackint const n, mplapackint const k, mpfr_class *a, mpfr_class *af, mpfr_class *q, mpfr_class *l, mplapackint const lda, mpfr_class *tau, mpfr_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Rqlt03(mplapackint const m, mplapackint const n, mplapackint const k, mpfr_class *af, mpfr_class *c, mpfr_class *cc, mpfr_class *q, mplapackint const lda, mpfr_class *tau, mpfr_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Rqrt01(mplapackint const m, mplapackint const n, mpfr_class *a, mpfr_class *af, mpfr_class *q, mpfr_class *r, mplapackint const lda, mpfr_class *tau, mpfr_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Rqrt01p(mplapackint const m, mplapackint const n, mpfr_class *a, mpfr_class *af, mpfr_class *q, mpfr_class *r, mplapackint const lda, mpfr_class *tau, mpfr_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Rqrt02(mplapackint const m, mplapackint const n, mplapackint const k, mpfr_class *a, mpfr_class *af, mpfr_class *q, mpfr_class *r, mplapackint const lda, mpfr_class *tau, mpfr_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Rqrt03(mplapackint const m, mplapackint const n, mplapackint const k, mpfr_class *af, mpfr_class *c, mpfr_class *cc, mpfr_class *q, mplapackint const lda, mpfr_class *tau, mpfr_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Rqrt04(mplapackint const m, mplapackint const n, mplapackint const nb, mpfr_class *result);
void Rqrt05(mplapackint const m, mplapackint const n, mplapackint const l, mplapackint const nb, mpfr_class *result);
void Rqrt13(mplapackint const scale, mplapackint const m, mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class &norma, mplapackint (&iseed)[4]);
void Rqrt15(mplapackint const scale, mplapackint const rksel, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mpfr_class *b, mplapackint const ldb, mpfr_class *s, mplapackint &rank, mpfr_class &norma, mpfr_class &normb, mplapackint (&iseed)[4], mpfr_class *work, mplapackint const lwork);
void Rqrt16(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mpfr_class *x, mplapackint const ldx, mpfr_class *b, mplapackint const ldb, mpfr_class *rwork, mpfr_class &resid);
void Rrqt01(mplapackint const m, mplapackint const n, mpfr_class *a, mpfr_class *af, mpfr_class *q, mpfr_class *r, mplapackint const lda, mpfr_class *tau, mpfr_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Rrqt02(mplapackint const m, mplapackint const n, mplapackint const k, mpfr_class *a, mpfr_class *af, mpfr_class *q, mpfr_class *r, mplapackint const lda, mpfr_class *tau, mpfr_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Rrqt03(mplapackint const m, mplapackint const n, mplapackint const k, mpfr_class *af, mpfr_class *c, mpfr_class *cc, mpfr_class *q, mplapackint const lda, mpfr_class *tau, mpfr_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Rspt01(fem::str_cref uplo, mplapackint const n, mpfr_class *a, mpfr_class *afac, mplapackint *ipiv, mpfr_class *c, mplapackint const ldc, mpfr_class *rwork, mpfr_class &resid);
void Rsyt01(fem::str_cref uplo, mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpfr_class *c, mplapackint const ldc, mpfr_class *rwork, mpfr_class &resid);
void Rsyt01_3(fem::str_cref uplo, mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class *afac, mplapackint const ldafac, mpfr_class *e, mplapackint *ipiv, mpfr_class *c, mplapackint const ldc, mpfr_class *rwork, mpfr_class &resid);
void Rsyt01_aa(fem::str_cref uplo, mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpfr_class *c, mplapackint const ldc, mpfr_class *rwork, mpfr_class &resid);
void Rsyt01_rook(fem::str_cref uplo, mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class *afac, mplapackint const ldafac, mplapackint *ipiv, mpfr_class *c, mplapackint const ldc, mpfr_class *rwork, mpfr_class &resid);
void Rtbt02(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpfr_class *ab, mplapackint const ldab, mpfr_class *x, mplapackint const ldx, mpfr_class *b, mplapackint const ldb, mpfr_class *work, mpfr_class &resid);
void Rtbt03(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpfr_class *ab, mplapackint const ldab, mpfr_class const scale, mpfr_class *cnorm, mpfr_class const tscal, mpfr_class *x, mplapackint const ldx, mpfr_class *b, mplapackint const ldb, mpfr_class *work, mpfr_class &resid);
void Rtbt05(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const kd, mplapackint const nrhs, mpfr_class *ab, mplapackint const ldab, mpfr_class *b, mplapackint const ldb, mpfr_class *x, mplapackint const ldx, mpfr_class *xact, mplapackint const ldxact, mpfr_class *ferr, mpfr_class *berr, mpfr_class *reslts);
void Rtbt06(mpfr_class const rcond, mpfr_class const rcondc, fem::str_cref uplo, fem::str_cref diag, mplapackint const n, mplapackint const kd, mpfr_class *ab, mplapackint const ldab, mpfr_class *work, mpfr_class &rat);
void Rtplqt(mplapackint const m, mplapackint const n, mplapackint const l, mplapackint const mb, mpfr_class *a, mplapackint const lda, mpfr_class *b, mplapackint const ldb, mpfr_class *t, mplapackint const ldt, mpfr_class *work, mplapackint &info);
void Rtpt01(fem::str_cref uplo, fem::str_cref diag, mplapackint const n, mpfr_class *ap, mpfr_class *ainvp, mpfr_class &rcond, mpfr_class *work, mpfr_class &resid);
void Rtpt02(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpfr_class *ap, mpfr_class *x, mplapackint const ldx, mpfr_class *b, mplapackint const ldb, mpfr_class *work, mpfr_class &resid);
void Rtpt03(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpfr_class *ap, mpfr_class const scale, mpfr_class *cnorm, mpfr_class const tscal, mpfr_class *x, mplapackint const ldx, mpfr_class *b, mplapackint const ldb, mpfr_class *work, mpfr_class &resid);
void Rtpt05(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpfr_class *ap, mpfr_class *b, mplapackint const ldb, mpfr_class *x, mplapackint const ldx, mpfr_class *xact, mplapackint const ldxact, mpfr_class *ferr, mpfr_class *berr, mpfr_class *reslts);
void Rtpt06(mpfr_class const rcond, mpfr_class const rcondc, fem::str_cref uplo, fem::str_cref diag, mplapackint const n, mpfr_class *ap, mpfr_class *work, mpfr_class &rat);
void Rtrt01(fem::str_cref uplo, fem::str_cref diag, mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class *ainv, mplapackint const ldainv, mpfr_class &rcond, mpfr_class *work, mpfr_class &resid);
void Rtrt02(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mpfr_class *x, mplapackint const ldx, mpfr_class *b, mplapackint const ldb, mpfr_class *work, mpfr_class &resid);
void Rtrt03(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mpfr_class const scale, mpfr_class *cnorm, mpfr_class const tscal, mpfr_class *x, mplapackint const ldx, mpfr_class *b, mplapackint const ldb, mpfr_class *work, mpfr_class &resid);
void Rtrt05(fem::str_cref uplo, fem::str_cref trans, fem::str_cref diag, mplapackint const n, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mpfr_class *b, mplapackint const ldb, mpfr_class *x, mplapackint const ldx, mpfr_class *xact, mplapackint const ldxact, mpfr_class *ferr, mpfr_class *berr, mpfr_class *reslts);
void Rtrt06(mpfr_class const rcond, mpfr_class const rcondc, fem::str_cref uplo, fem::str_cref diag, mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class *work, mpfr_class &rat);
void Rtsqr01(fem::str_cref tssw, mplapackint const m, mplapackint const n, mplapackint const mb, mplapackint const nb, mpfr_class *result);
void icopy(mplapackint const n, mplapackint *sx, mplapackint const incx, mplapackint *sy, mplapackint const incy);
#endif
