/*
 * Copyright (c) 2008-2025
 *	Nakata, Maho
 * 	All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 */

#ifndef MPLAPACK_EIG_MPFR_H
#define MPLAPACK_EIG_MPFR_H

#include "mplapack_config.h"
#include <mplapack_gmpfrxx_mkII_config.h>
#include <mpfrxx_mkII.h>
#include <mpcxx_mkII.h>
using namespace mpfrxx;


#include <mpblas.h>
#include <mplapack.h>

#include <fem.hpp> // Fortran EMulation library of fable module
using namespace fem::major_types;
using fem::common;

#include <mplapack_matgen.h>
#include <mplapack_debug.h>

bool Clctes(mpc_class const z, mpc_class const d);
bool Clctsx(mpc_class const, mpc_class const);
bool Cslect(mpc_class const z);
bool Rlctes(mpfr_class const zr, mpfr_class const, mpfr_class const d);
bool Rlctsx(mpfr_class const, mpfr_class const, mpfr_class const);
bool Rslect(mpfr_class const zr, mpfr_class const zi);
mplapackint iMlaenv2stage_mpfr(mplapackint const ispec, const char *name, const char *opts, mplapackint const n1, mplapackint const n2, mplapackint const n3, mplapackint const n4);
mplapackint iMlaenv_mpfr(mplapackint const ispec, const char *name, const char *opts, mplapackint const n1, mplapackint const n2, mplapackint const n3, mplapackint const n4);
mpfr_class Rlamch_mpfr(const char *cmach);
mpfr_class Rsxt1(mplapackint const ijob, mpfr_class *d1, mplapackint const n1, mpfr_class *d2, mplapackint const n2, mpfr_class const abstol, mpfr_class const ulp, mpfr_class const unfl);
void Alahdg(mplapackint const iounit, fem::str_cref path);
void Alareq(fem::str_cref path, mplapackint const nmats, bool *dotype, mplapackint const ntypes, mplapackint const nin, mplapackint const nout);
void Alarqg(fem::str_cref path, mplapackint const nmats, bool *dotype, mplapackint const ntypes, mplapackint const nin, mplapackint const nout);
void Alasmg(fem::str_cref type, mplapackint const nout, mplapackint const nfail, mplapackint const nrun, mplapackint const nerrs);
void Alasum(fem::str_cref type, mplapackint const nout, mplapackint const nfail, mplapackint const nrun, mplapackint const nerrs);
void Alasvm(fem::str_cref type, mplapackint const nout, mplapackint const nfail, mplapackint const nrun, mplapackint const nerrs);
void Cbdt01(mplapackint const m, mplapackint const n, mplapackint const kd, mpc_class *a, mplapackint const lda, mpc_class *q, mplapackint const ldq, mpfr_class *d, mpfr_class *e, mpc_class *pt, mplapackint const ldpt, mpc_class *work, mpfr_class *rwork, mpfr_class &resid);
void Cbdt02(mplapackint const m, mplapackint const n, mpc_class *b, mplapackint const ldb, mpc_class *c, mplapackint const ldc, mpc_class *u, mplapackint const ldu, mpc_class *work, mpfr_class *rwork, mpfr_class &resid);
void Cbdt03(fem::str_cref uplo, mplapackint const n, mplapackint const kd, mpfr_class *d, mpfr_class *e, mpc_class *u, mplapackint const ldu, mpfr_class *s, mpc_class *vt, mplapackint const ldvt, mpc_class *work, mpfr_class &resid);
void Cbdt05(mplapackint const m, mplapackint const n, mpc_class *a, mplapackint const lda, mpfr_class *s, mplapackint const ns, mpc_class *u, mplapackint const ldu, mpc_class *vt, mplapackint const ldvt, mpc_class *work, mpfr_class &resid);
void Cchkbb(mplapackint const nsizes, mplapackint *mval, mplapackint *nval, mplapackint const nwdths, mplapackint *kk, mplapackint const ntypes, bool *dotype, mplapackint const nrhs, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpc_class *a, mplapackint const lda, mpc_class *ab, mplapackint const ldab, mpfr_class *bd, mpfr_class *be, mpc_class *q, mplapackint const ldq, mpc_class *p, mplapackint const ldp, mpc_class *c, mplapackint const ldc, mpc_class *cc, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result, mplapackint &info);
void Cchkbd(mplapackint const nsizes, mplapackint *mval, mplapackint *nval, mplapackint const ntypes, bool *dotype, mplapackint const nrhs, mplapackint (&iseed)[4], mpfr_class const thresh, mpc_class *a, mplapackint const lda, mpfr_class *bd, mpfr_class *be, mpfr_class *s1, mpfr_class *s2, mpc_class *x, mplapackint const ldx, mpc_class *y, mpc_class *z, mpc_class *q, mplapackint const ldq, mpc_class *pt, mplapackint const ldpt, mpc_class *u, mpc_class *vt, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mplapackint const nout, mplapackint &info);
void Cchkbk(mplapackint const nin, mplapackint const nout);
void Cchkbl(mplapackint const nin, mplapackint const nout);
void Cchkec(mpfr_class const thresh, bool const tsterr, mplapackint const nin, mplapackint const nout);
void Cchkgg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, bool const tstdif, mpfr_class const thrshn, mplapackint const nounit, mpc_class *a, mplapackint const lda, mpc_class *b, mpc_class *h, mpc_class *t, mpc_class *s1, mpc_class *s2, mpc_class *p1, mpc_class *p2, mpc_class *u, mplapackint const ldu, mpc_class *v, mpc_class *q, mpc_class *z, mpc_class *alpha1, mpc_class *beta1, mpc_class *alpha3, mpc_class *beta3, mpc_class *evectl, mpc_class *evectr, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, bool *llwork, mpfr_class *result, mplapackint &info);
void Cchkgk(mplapackint const nin, mplapackint const nout);
void Cchkgl(mplapackint const nin, mplapackint const nout);
void Cchkhb(mplapackint const nsizes, mplapackint *nn, mplapackint const nwdths, mplapackint *kk, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpc_class *a, mplapackint const lda, mpfr_class *sd, mpfr_class *se, mpc_class *u, mplapackint const ldu, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result, mplapackint &info);
void Cchkhb2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const nwdths, mplapackint *kk, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpc_class *a, mplapackint const lda, mpfr_class *sd, mpfr_class *se, mpfr_class *d1, mpfr_class *d2, mpfr_class *d3, mpc_class *u, mplapackint const ldu, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result, mplapackint &info);
void Cchkhs(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpc_class *a, mplapackint const lda, mpc_class *h, mpc_class *t1, mpc_class *t2, mpc_class *u, mplapackint const ldu, mpc_class *z, mpc_class *uz, mpc_class *w1, mpc_class *w3, mpc_class *evectl, mpc_class *evectr, mpc_class *evecty, mpc_class *evectx, mpc_class *uu, mpc_class *tau, mpc_class *work, mplapackint const nwork, mpfr_class *rwork, mplapackint *iwork, bool *select, mpfr_class *result, mplapackint &info);
void Cchkst(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpc_class *a, mplapackint const lda, mpc_class *ap, mpfr_class *sd, mpfr_class *se, mpfr_class *d1, mpfr_class *d2, mpfr_class *d3, mpfr_class *d4, mpfr_class *d5, mpfr_class *wa1, mpfr_class *wa2, mpfr_class *wa3, mpfr_class *wr, mpc_class *u, mplapackint const ldu, mpc_class *v, mpc_class *vp, mpc_class *tau, mpc_class *z, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mplapackint const lrwork, mplapackint *iwork, mplapackint const liwork, mpfr_class *result, mplapackint &info);
void Cchkst2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpc_class *a, mplapackint const lda, mpc_class *ap, mpfr_class *sd, mpfr_class *se, mpfr_class *d1, mpfr_class *d2, mpfr_class *d3, mpfr_class *d4, mpfr_class *d5, mpfr_class *wa1, mpfr_class *wa2, mpfr_class *wa3, mpfr_class *wr, mpc_class *u, mplapackint const ldu, mpc_class *v, mpc_class *vp, mpc_class *tau, mpc_class *z, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mplapackint const lrwork, mplapackint *iwork, mplapackint const liwork, mpfr_class *result, mplapackint &info);
void Cckcsd(mplapackint const nm, mplapackint *mval, mplapackint *pval, mplapackint *qval, mplapackint const nmats, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const mmax, mpc_class *x, mpc_class *xf, mpc_class *u1, mpc_class *u2, mpc_class *v1t, mpc_class *v2t, mpfr_class *theta, mplapackint *iwork, mpc_class *work, mpfr_class *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Cckglm(mplapackint const nn, mplapackint *nval, mplapackint *mval, mplapackint *pval, mplapackint const nmats, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nmax, mpc_class *a, mpc_class *af, mpc_class *b, mpc_class *bf, mpc_class *x, mpc_class *work, mpfr_class *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Cckgqr(mplapackint const nm, mplapackint *mval, mplapackint const np, mplapackint *pval, mplapackint const nn, mplapackint *nval, mplapackint const nmats, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nmax, mpc_class *a, mpc_class *af, mpc_class *aq, mpc_class *ar, mpc_class *taua, mpc_class *b, mpc_class *bf, mpc_class *bz, mpc_class *bt, mpc_class *bwk, mpc_class *taub, mpc_class *work, mpfr_class *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Cckgsv(mplapackint const nm, mplapackint *mval, mplapackint *pval, mplapackint *nval, mplapackint const nmats, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nmax, mpc_class *a, mpc_class *af, mpc_class *b, mpc_class *bf, mpc_class *u, mpc_class *v, mpc_class *q, mpfr_class *alpha, mpfr_class *beta, mpc_class *r, mplapackint *iwork, mpc_class *work, mpfr_class *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Ccklse(mplapackint const nn, mplapackint *mval, mplapackint *pval, mplapackint *nval, mplapackint const nmats, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nmax, mpc_class *a, mpc_class *af, mpc_class *b, mpc_class *bf, mpc_class *x, mpc_class *work, mpfr_class *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Ccsdts(mplapackint const m, mplapackint const p, mplapackint const q, mpc_class *x, mpc_class *xf, mplapackint const ldx, mpc_class *u1, mplapackint const ldu1, mpc_class *u2, mplapackint const ldu2, mpc_class *v1t, mplapackint const ldv1t, mpc_class *v2t, mplapackint const ldv2t, mpfr_class *theta, mplapackint *iwork, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Cdrges(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpc_class *a, mplapackint const lda, mpc_class *b, mpc_class *s, mpc_class *t, mpc_class *q, mplapackint const ldq, mpc_class *z, mpc_class *alpha, mpc_class *beta, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result, bool *bwork, mplapackint &info);
void Cdrges3(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpc_class *a, mplapackint const lda, mpc_class *b, mpc_class *s, mpc_class *t, mpc_class *q, mplapackint const ldq, mpc_class *z, mpc_class *alpha, mpc_class *beta, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result, bool *bwork, mplapackint &info);
void Cdrgev(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpc_class *a, mplapackint const lda, mpc_class *b, mpc_class *s, mpc_class *t, mpc_class *q, mplapackint const ldq, mpc_class *z, mpc_class *qe, mplapackint const ldqe, mpc_class *alpha, mpc_class *beta, mpc_class *alpha1, mpc_class *beta1, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result, mplapackint &info);
void Cdrgev3(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpc_class *a, mplapackint const lda, mpc_class *b, mpc_class *s, mpc_class *t, mpc_class *q, mplapackint const ldq, mpc_class *z, mpc_class *qe, mplapackint const ldqe, mpc_class *alpha, mpc_class *beta, mpc_class *alpha1, mpc_class *beta1, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result, mplapackint &info);
void Cdrgsx(mplapackint const nsize, mplapackint const ncmax, mpfr_class const thresh, mplapackint const nin, mplapackint const nout, mpc_class *a, mplapackint const lda, mpc_class *b, mpc_class *ai, mpc_class *bi, mpc_class *z, mpc_class *q, mpc_class *alpha, mpc_class *beta, mpc_class *c, mplapackint const ldc, mpfr_class *s, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mplapackint *iwork, mplapackint const liwork, bool *bwork, mplapackint &info);
void Cdrgvx(mplapackint const nsize, mpfr_class const thresh, mplapackint const nin, mplapackint const nout, mpc_class *a, mplapackint const lda, mpc_class *b, mpc_class *ai, mpc_class *bi, mpc_class *alpha, mpc_class *beta, mpc_class *vl, mpc_class *vr, mplapackint &ilo, mplapackint &ihi, mpfr_class *lscale, mpfr_class *rscale, mpfr_class *s, mpfr_class *dtru, mpfr_class *dif, mpfr_class *diftru, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mplapackint *iwork, mplapackint const liwork, mpfr_class *result, bool *bwork, mplapackint &info);
void Cdrvbd(mplapackint const nsizes, mplapackint *mm, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mpc_class *a, mplapackint const lda, mpc_class *u, mplapackint const ldu, mpc_class *vt, mplapackint const ldvt, mpc_class *asav, mpc_class *usav, mpc_class *vtsav, mpfr_class *s, mpfr_class *ssav, mpfr_class *e, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mplapackint *iwork, mplapackint const nounit, mplapackint &info);
void Cdrves(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpc_class *a, mplapackint const lda, mpc_class *h, mpc_class *ht, mpc_class *w, mpc_class *wt, mpc_class *vs, mplapackint const ldvs, mpfr_class *result, mpc_class *work, mplapackint const nwork, mpfr_class *rwork, mplapackint *iwork, bool *bwork, mplapackint &info);
void Cdrvev(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpc_class *a, mplapackint const lda, mpc_class *h, mpc_class *w, mpc_class *w1, mpc_class *vl, mplapackint const ldvl, mpc_class *vr, mplapackint const ldvr, mpc_class *lre, mplapackint const ldlre, mpfr_class *result, mpc_class *work, mplapackint const nwork, mpfr_class *rwork, mplapackint *iwork, mplapackint &info);
void Cdrvsg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mpfr_class *d, mpc_class *z, mplapackint const ldz, mpc_class *ab, mpc_class *bb, mpc_class *ap, mpc_class *bp, mpc_class *work, mplapackint const nwork, mpfr_class *rwork, mplapackint const lrwork, mplapackint *iwork, mplapackint const liwork, mpfr_class *result, mplapackint &info);
void Cdrvsg2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mpfr_class *d, mpfr_class *d2, mpc_class *z, mplapackint const ldz, mpc_class *ab, mpc_class *bb, mpc_class *ap, mpc_class *bp, mpc_class *work, mplapackint const nwork, mpfr_class *rwork, mplapackint const lrwork, mplapackint *iwork, mplapackint const liwork, mpfr_class *result, mplapackint &info);
void Cdrvst(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpc_class *a, mplapackint const lda, mpfr_class *d1, mpfr_class *d2, mpfr_class *d3, mpfr_class *wa1, mpfr_class *wa2, mpfr_class *wa3, mpc_class *u, mplapackint const ldu, mpc_class *v, mpc_class *tau, mpc_class *z, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mplapackint const lrwork, mplapackint *iwork, mplapackint const liwork, mpfr_class *result, mplapackint &info);
void Cdrvst2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpc_class *a, mplapackint const lda, mpfr_class *d1, mpfr_class *d2, mpfr_class *d3, mpfr_class *wa1, mpfr_class *wa2, mpfr_class *wa3, mpc_class *u, mplapackint const ldu, mpc_class *v, mpc_class *tau, mpc_class *z, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mplapackint const lrwork, mplapackint *iwork, mplapackint const liwork, mpfr_class *result, mplapackint &info);
void Cdrvsx(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const niunit, mplapackint const nounit, mpc_class *a, mplapackint const lda, mpc_class *h, mpc_class *ht, mpc_class *w, mpc_class *wt, mpc_class *wtmp, mpc_class *vs, mplapackint const ldvs, mpc_class *vs1, mpfr_class *result, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, bool *bwork, mplapackint &info);
void Cdrvvx(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const niunit, mplapackint const nounit, mpc_class *a, mplapackint const lda, mpc_class *h, mpc_class *w, mpc_class *w1, mpc_class *vl, mplapackint const ldvl, mpc_class *vr, mplapackint const ldvr, mpc_class *lre, mplapackint const ldlre, mpfr_class *rcondv, mpfr_class *rcndv1, mpfr_class *rcdvin, mpfr_class *rconde, mpfr_class *rcnde1, mpfr_class *rcdein, mpfr_class *scale, mpfr_class *scale1, mpfr_class *result, mpc_class *work, mplapackint const nwork, mpfr_class *rwork, mplapackint &info);
void Cerrbd(fem::str_cref path, mplapackint const nunit);
void Cerrec(fem::str_cref path, mplapackint const nunit);
void Cerred(fem::str_cref path, mplapackint const nunit);
void Cerrgg(fem::str_cref path, mplapackint const nunit);
void Cerrhs(fem::str_cref path, mplapackint const nunit);
void Cerrst(fem::str_cref path, mplapackint const nunit);
void Cget02(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mpfr_class *rwork, mpfr_class &resid);
void Cget10(mplapackint const m, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mpc_class *work, mpfr_class *rwork, mpfr_class &result);
void Cget22(fem::str_cref transa, fem::str_cref transe, fem::str_cref transw, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *e, mplapackint const lde, mpc_class *w, mpc_class *work, mpfr_class *rwork, mpfr_class *result);
void Cget23(bool const comp, mplapackint const isrt, fem::str_cref balanc, mplapackint const jtype, mpfr_class const thresh, mplapackint (&iseed)[4], mplapackint const nounit, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *h, mpc_class *w, mpc_class *w1, mpc_class *vl, mplapackint const ldvl, mpc_class *vr, mplapackint const ldvr, mpc_class *lre, mplapackint const ldlre, mpfr_class *rcondv, mpfr_class *rcndv1, mpfr_class *rcdvin, mpfr_class *rconde, mpfr_class *rcnde1, mpfr_class *rcdein, mpfr_class *scale, mpfr_class *scale1, mpfr_class *result, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mplapackint &info);
void Cget24(bool const comp, mplapackint const jtype, mpfr_class const thresh, mplapackint (&iseed)[4], mplapackint const nounit, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *h, mpc_class *ht, mpc_class *w, mpc_class *wt, mpc_class *wtmp, mpc_class *vs, mplapackint const ldvs, mpc_class *vs1, mpfr_class const rcdein, mpfr_class const rcdvin, mplapackint const nslct, mplapackint *islct, mplapackint const isrt, mpfr_class *result, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, bool *bwork, mplapackint &info);
void Cget35(mpfr_class &rmax, mplapackint &lmax, mplapackint &ninfo, mplapackint &knt, mplapackint const nin);
void Cget36(mpfr_class &rmax, mplapackint &lmax, mplapackint &ninfo, mplapackint &knt, mplapackint const nin);
void Cget37(mpfr_class *rmax, mplapackint *lmax, mplapackint *ninfo, mplapackint &knt, mplapackint const nin);
void Cget38(mpfr_class *rmax, mplapackint *lmax, mplapackint *ninfo, mplapackint &knt, mplapackint const nin);
void Cget51(mplapackint const itype, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mpc_class *u, mplapackint const ldu, mpc_class *v, mplapackint const ldv, mpc_class *work, mpfr_class *rwork, mpfr_class &result);
void Cget52(bool const left, mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mpc_class *e, mplapackint const lde, mpc_class *alpha, mpc_class *beta, mpc_class *work, mpfr_class *rwork, mpfr_class *result);
void Cget54(mplapackint const n, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mpc_class *s, mplapackint const lds, mpc_class *t, mplapackint const ldt, mpc_class *u, mplapackint const ldu, mpc_class *v, mplapackint const ldv, mpc_class *work, mpfr_class &result);
void Cglmts(mplapackint const n, mplapackint const m, mplapackint const p, mpc_class *a, mpc_class *af, mplapackint const lda, mpc_class *b, mpc_class *bf, mplapackint const ldb, mpc_class *d, mpc_class *df, mpc_class *x, mpc_class *u, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class &result);
void Cgqrts(mplapackint const n, mplapackint const m, mplapackint const p, mpc_class *a, mpc_class *af, mpc_class *q, mpc_class *r, mplapackint const lda, mpc_class *taua, mpc_class *b, mpc_class *bf, mpc_class *z, mpc_class *t, mpc_class *bwk, mplapackint const ldb, mpc_class *taub, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Cgrqts(mplapackint const m, mplapackint const p, mplapackint const n, mpc_class *a, mpc_class *af, mpc_class *q, mpc_class *r, mplapackint const lda, mpc_class *taua, mpc_class *b, mpc_class *bf, mpc_class *z, mpc_class *t, mpc_class *bwk, mplapackint const ldb, mpc_class *taub, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Cgsvts3(mplapackint const m, mplapackint const p, mplapackint const n, mpc_class *a, mpc_class *af, mplapackint const lda, mpc_class *b, mpc_class *bf, mplapackint const ldb, mpc_class *u, mplapackint const ldu, mpc_class *v, mplapackint const ldv, mpc_class *q, mplapackint const ldq, mpfr_class *alpha, mpfr_class *beta, mpc_class *r, mplapackint const ldr, mplapackint *iwork, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Chbt21(fem::str_cref uplo, mplapackint const n, mplapackint const ka, mplapackint const ks, mpc_class *a, mplapackint const lda, mpfr_class *d, mpfr_class *e, mpc_class *u, mplapackint const ldu, mpc_class *work, mpfr_class *rwork, mpfr_class *result);
void Chet21(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const kband, mpc_class *a, mplapackint const lda, mpfr_class *d, mpfr_class *e, mpc_class *u, mplapackint const ldu, mpc_class *v, mplapackint const ldv, mpc_class *tau, mpc_class *work, mpfr_class *rwork, mpfr_class *result);
void Chet22(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const m, mplapackint const kband, mpc_class *a, mplapackint const lda, mpfr_class *d, mpfr_class *e, mpc_class *u, mplapackint const ldu, mpc_class *, mplapackint const ldv, mpc_class *, mpc_class *work, mpfr_class *rwork, mpfr_class *result);
void Chkxer(fem::str_cref srnamt, mplapackint const infot, mplapackint const nout, bool &lerr, bool &ok);
void Chpt21(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const kband, mpc_class *ap, mpfr_class *d, mpfr_class *e, mpc_class *u, mplapackint const ldu, mpc_class *vp, mpc_class *tau, mpc_class *work, mpfr_class *rwork, mpfr_class *result);
void Chst01(mplapackint const n, mplapackint const, mplapackint const, mpc_class *a, mplapackint const lda, mpc_class *h, mplapackint const ldh, mpc_class *q, mplapackint const ldq, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Clacsg(mplapackint const m, mplapackint const p, mplapackint const q, mpfr_class *theta, mplapackint (&iseed)[4], mpc_class *x, mplapackint const ldx, mpc_class *work);
void Clarfy(fem::str_cref uplo, mplapackint const n, mpc_class *v, mplapackint const incv, mpc_class const tau, mpc_class *c, mplapackint const ldc, mpc_class *work);
void Clarhs(fem::str_cref path, fem::str_cref xtype, fem::str_cref uplo, fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mplapackint const nrhs, mpc_class *a, mplapackint const lda, mpc_class *x, mplapackint const ldx, mpc_class *b, mplapackint const ldb, mplapackint (&iseed)[4], mplapackint &info);
void Clatm4(mplapackint const itype, mplapackint const n, mplapackint const nz1, mplapackint const nz2, bool const rsign, mpfr_class const amagn, mpfr_class const rcond, mpfr_class const triang, mplapackint const idist, mplapackint (&iseed)[4], mpc_class *a, mplapackint const lda);
void Clsets(mplapackint const m, mplapackint const p, mplapackint const n, mpc_class *a, mpc_class *af, mplapackint const lda, mpc_class *b, mpc_class *bf, mplapackint const ldb, mpc_class *c, mpc_class *cf, mpc_class *d, mpc_class *df, mpc_class *x, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Csbmv(fem::str_cref uplo, mplapackint const n, mplapackint const k, mpc_class const alpha, mpc_class *a, mplapackint const lda, mpc_class *x, mplapackint const incx, mpc_class const beta, mpc_class *y, mplapackint const incy);
void Csgt01(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const m, mpc_class *a, mplapackint const lda, mpc_class *b, mplapackint const ldb, mpc_class *z, mplapackint const ldz, mpfr_class *d, mpc_class *work, mpfr_class *rwork, mpfr_class *result);
void Cstt21(mplapackint const n, mplapackint const kband, mpfr_class *ad, mpfr_class *ae, mpfr_class *sd, mpfr_class *se, mpc_class *u, mplapackint const ldu, mpc_class *work, mpfr_class *rwork, mpfr_class *result);
void Cstt22(mplapackint const n, mplapackint const m, mplapackint const kband, mpfr_class *ad, mpfr_class *ae, mpfr_class *sd, mpfr_class *se, mpc_class *u, mplapackint const ldu, mpc_class *work, mplapackint const ldwork, mpfr_class *rwork, mpfr_class *result);
void Csyl01(mpfr_class const thresh, mplapackint *nfail, mpfr_class *rmax, mplapackint *ninfo, mplapackint &knt);
void Cunt01(fem::str_cref rowcol, mplapackint const m, mplapackint const n, mpc_class *u, mplapackint const ldu, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class &resid);
void Cunt03(fem::str_cref rc, mplapackint const mu, mplapackint const mv, mplapackint const n, mplapackint const k, mpc_class *u, mplapackint const ldu, mpc_class *v, mplapackint const ldv, mpc_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class &result, mplapackint &info);
void Mxerbla_mpfr(const char *srname, int info);
void Mxlaenv(mplapackint const ispec, mplapackint const nvalue);
void Rbdt01(mplapackint const m, mplapackint const n, mplapackint const kd, mpfr_class *a, mplapackint const lda, mpfr_class *q, mplapackint const ldq, mpfr_class *d, mpfr_class *e, mpfr_class *pt, mplapackint const ldpt, mpfr_class *work, mpfr_class &resid);
void Rbdt02(mplapackint const m, mplapackint const n, mpfr_class *b, mplapackint const ldb, mpfr_class *c, mplapackint const ldc, mpfr_class *u, mplapackint const ldu, mpfr_class *work, mpfr_class &resid);
void Rbdt03(fem::str_cref uplo, mplapackint const n, mplapackint const kd, mpfr_class *d, mpfr_class *e, mpfr_class *u, mplapackint const ldu, mpfr_class *s, mpfr_class *vt, mplapackint const ldvt, mpfr_class *work, mpfr_class &resid);
void Rbdt04(fem::str_cref uplo, mplapackint const n, mpfr_class *d, mpfr_class *e, mpfr_class *s, mplapackint const ns, mpfr_class *u, mplapackint const ldu, mpfr_class *vt, mplapackint const ldvt, mpfr_class *work, mpfr_class &resid);
void Rbdt05(mplapackint const m, mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class *s, mplapackint const ns, mpfr_class *u, mplapackint const ldu, mpfr_class *vt, mplapackint const ldvt, mpfr_class *work, mpfr_class &resid);
void Rchkbb(mplapackint const nsizes, mplapackint *mval, mplapackint *nval, mplapackint const nwdths, mplapackint *kk, mplapackint const ntypes, bool *dotype, mplapackint const nrhs, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpfr_class *a, mplapackint const lda, mpfr_class *ab, mplapackint const ldab, mpfr_class *bd, mpfr_class *be, mpfr_class *q, mplapackint const ldq, mpfr_class *p, mplapackint const ldp, mpfr_class *c, mplapackint const ldc, mpfr_class *cc, mpfr_class *work, mplapackint const lwork, mpfr_class *result, mplapackint &info);
void Rchkbd(mplapackint const nsizes, mplapackint *mval, mplapackint *nval, mplapackint const ntypes, bool *dotype, mplapackint const nrhs, mplapackint (&iseed)[4], mpfr_class const thresh, mpfr_class *a, mplapackint const lda, mpfr_class *bd, mpfr_class *be, mpfr_class *s1, mpfr_class *s2, mpfr_class *x, mplapackint const ldx, mpfr_class *y, mpfr_class *z, mpfr_class *q, mplapackint const ldq, mpfr_class *pt, mplapackint const ldpt, mpfr_class *u, mpfr_class *vt, mpfr_class *work, mplapackint const lwork, mplapackint *iwork, mplapackint const nout, mplapackint &info);
void Rchkbk(mplapackint const nin, mplapackint const nout);
void Rchkbl(mplapackint const nin, mplapackint const nout);
void Rchkec(mpfr_class const thresh, bool const tsterr, mplapackint const nin, mplapackint const nout);
void Rchkgg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, bool const tstdif, mpfr_class const thrshn, mplapackint const nounit, mpfr_class *a, mplapackint const lda, mpfr_class *b, mpfr_class *h, mpfr_class *t, mpfr_class *s1, mpfr_class *s2, mpfr_class *p1, mpfr_class *p2, mpfr_class *u, mplapackint const ldu, mpfr_class *v, mpfr_class *q, mpfr_class *z, mpfr_class *alphr1, mpfr_class *alphi1, mpfr_class *beta1, mpfr_class *alphr3, mpfr_class *alphi3, mpfr_class *beta3, mpfr_class *evectl, mpfr_class *evectr, mpfr_class *work, mplapackint const lwork, bool *llwork, mpfr_class *result, mplapackint &info);
void Rchkgk(mplapackint const nin, mplapackint const nout);
void Rchkgl(mplapackint const nin, mplapackint const nout);
void Rchkhs(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpfr_class *a, mplapackint const lda, mpfr_class *h, mpfr_class *t1, mpfr_class *t2, mpfr_class *u, mplapackint const ldu, mpfr_class *z, mpfr_class *uz, mpfr_class *wr1, mpfr_class *wi1, mpfr_class *wr2, mpfr_class *wi2, mpfr_class *wr3, mpfr_class *wi3, mpfr_class *evectl, mpfr_class *evectr, mpfr_class *evecty, mpfr_class *evectx, mpfr_class *uu, mpfr_class *tau, mpfr_class *work, mplapackint const nwork, mplapackint *iwork, bool *select, mpfr_class *result, mplapackint &info);
void Rchksb(mplapackint const nsizes, mplapackint *nn, mplapackint const nwdths, mplapackint *kk, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpfr_class *a, mplapackint const lda, mpfr_class *sd, mpfr_class *se, mpfr_class *u, mplapackint const ldu, mpfr_class *work, mplapackint const lwork, mpfr_class *result, mplapackint &info);
void Rchksb2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const nwdths, mplapackint *kk, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpfr_class *a, mplapackint const lda, mpfr_class *sd, mpfr_class *se, mpfr_class *d1, mpfr_class *d2, mpfr_class *d3, mpfr_class *u, mplapackint const ldu, mpfr_class *work, mplapackint const lwork, mpfr_class *result, mplapackint &info);
void Rchkst(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpfr_class *a, mplapackint const lda, mpfr_class *ap, mpfr_class *sd, mpfr_class *se, mpfr_class *d1, mpfr_class *d2, mpfr_class *d3, mpfr_class *d4, mpfr_class *d5, mpfr_class *wa1, mpfr_class *wa2, mpfr_class *wa3, mpfr_class *wr, mpfr_class *u, mplapackint const ldu, mpfr_class *v, mpfr_class *vp, mpfr_class *tau, mpfr_class *z, mpfr_class *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, mpfr_class *result, mplapackint &info);
void Rchkst2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpfr_class *a, mplapackint const lda, mpfr_class *ap, mpfr_class *sd, mpfr_class *se, mpfr_class *d1, mpfr_class *d2, mpfr_class *d3, mpfr_class *d4, mpfr_class *d5, mpfr_class *wa1, mpfr_class *wa2, mpfr_class *wa3, mpfr_class *wr, mpfr_class *u, mplapackint const ldu, mpfr_class *v, mpfr_class *vp, mpfr_class *tau, mpfr_class *z, mpfr_class *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, mpfr_class *result, mplapackint &info);
void Rckcsd(mplapackint const nm, mplapackint *mval, mplapackint *pval, mplapackint *qval, mplapackint const nmats, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const mmax, mpfr_class *x, mpfr_class *xf, mpfr_class *u1, mpfr_class *u2, mpfr_class *v1t, mpfr_class *v2t, mpfr_class *theta, mplapackint *iwork, mpfr_class *work, mpfr_class *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Rckglm(mplapackint const nn, mplapackint *mval, mplapackint *pval, mplapackint *nval, mplapackint const nmats, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nmax, mpfr_class *a, mpfr_class *af, mpfr_class *b, mpfr_class *bf, mpfr_class *x, mpfr_class *work, mpfr_class *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Rckgqr(mplapackint const nm, mplapackint *mval, mplapackint const np, mplapackint *pval, mplapackint const nn, mplapackint *nval, mplapackint const nmats, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nmax, mpfr_class *a, mpfr_class *af, mpfr_class *aq, mpfr_class *ar, mpfr_class *taua, mpfr_class *b, mpfr_class *bf, mpfr_class *bz, mpfr_class *bt, mpfr_class *bwk, mpfr_class *taub, mpfr_class *work, mpfr_class *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Rckgsv(mplapackint const nm, mplapackint *mval, mplapackint *pval, mplapackint *nval, mplapackint const nmats, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nmax, mpfr_class *a, mpfr_class *af, mpfr_class *b, mpfr_class *bf, mpfr_class *u, mpfr_class *v, mpfr_class *q, mpfr_class *alpha, mpfr_class *beta, mpfr_class *r, mplapackint *iwork, mpfr_class *work, mpfr_class *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Rcklse(mplapackint const nn, mplapackint *mval, mplapackint *pval, mplapackint *nval, mplapackint const nmats, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nmax, mpfr_class *a, mpfr_class *af, mpfr_class *b, mpfr_class *bf, mpfr_class *x, mpfr_class *work, mpfr_class *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Rcsdts(mplapackint const m, mplapackint const p, mplapackint const q, mpfr_class *x, mpfr_class *xf, mplapackint const ldx, mpfr_class *u1, mplapackint const ldu1, mpfr_class *u2, mplapackint const ldu2, mpfr_class *v1t, mplapackint const ldv1t, mpfr_class *v2t, mplapackint const ldv2t, mpfr_class *theta, mplapackint *iwork, mpfr_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Rdrges(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpfr_class *a, mplapackint const lda, mpfr_class *b, mpfr_class *s, mpfr_class *t, mpfr_class *q, mplapackint const ldq, mpfr_class *z, mpfr_class *alphar, mpfr_class *alphai, mpfr_class *beta, mpfr_class *work, mplapackint const lwork, mpfr_class *result, bool *bwork, mplapackint &info);
void Rdrges3(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpfr_class *a, mplapackint const lda, mpfr_class *b, mpfr_class *s, mpfr_class *t, mpfr_class *q, mplapackint const ldq, mpfr_class *z, mpfr_class *alphar, mpfr_class *alphai, mpfr_class *beta, mpfr_class *work, mplapackint const lwork, mpfr_class *result, bool *bwork, mplapackint &info);
void Rdrgev(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpfr_class *a, mplapackint const lda, mpfr_class *b, mpfr_class *s, mpfr_class *t, mpfr_class *q, mplapackint const ldq, mpfr_class *z, mpfr_class *qe, mplapackint const ldqe, mpfr_class *alphar, mpfr_class *alphai, mpfr_class *beta, mpfr_class *alphr1, mpfr_class *alphi1, mpfr_class *beta1, mpfr_class *work, mplapackint const lwork, mpfr_class *result, mplapackint &info);
void Rdrgev3(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpfr_class *a, mplapackint const lda, mpfr_class *b, mpfr_class *s, mpfr_class *t, mpfr_class *q, mplapackint const ldq, mpfr_class *z, mpfr_class *qe, mplapackint const ldqe, mpfr_class *alphar, mpfr_class *alphai, mpfr_class *beta, mpfr_class *alphr1, mpfr_class *alphi1, mpfr_class *beta1, mpfr_class *work, mplapackint const lwork, mpfr_class *result, mplapackint &info);
void Rdrgsx(mplapackint const nsize, mplapackint const ncmax, mpfr_class const thresh, mplapackint const nin, mplapackint const nout, mpfr_class *a, mplapackint const lda, mpfr_class *b, mpfr_class *ai, mpfr_class *bi, mpfr_class *z, mpfr_class *q, mpfr_class *alphar, mpfr_class *alphai, mpfr_class *beta, mpfr_class *c, mplapackint const ldc, mpfr_class *s, mpfr_class *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, bool *bwork, mplapackint &info);
void Rdrgvx(mplapackint const nsize, mpfr_class const thresh, mplapackint const nin, mplapackint const nout, mpfr_class *a, mplapackint const lda, mpfr_class *b, mpfr_class *ai, mpfr_class *bi, mpfr_class *alphar, mpfr_class *alphai, mpfr_class *beta, mpfr_class *vl, mpfr_class *vr, mplapackint &ilo, mplapackint &ihi, mpfr_class *lscale, mpfr_class *rscale, mpfr_class *s, mpfr_class *dtru, mpfr_class *dif, mpfr_class *diftru, mpfr_class *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, mpfr_class *result, bool *bwork, mplapackint &info);
void Rdrvbd(mplapackint const nsizes, mplapackint *mm, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mpfr_class *a, mplapackint const lda, mpfr_class *u, mplapackint const ldu, mpfr_class *vt, mplapackint const ldvt, mpfr_class *asav, mpfr_class *usav, mpfr_class *vtsav, mpfr_class *s, mpfr_class *ssav, mpfr_class *e, mpfr_class *work, mplapackint const lwork, mplapackint *iwork, mplapackint const nout, mplapackint &info);
void Rdrves(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpfr_class *a, mplapackint const lda, mpfr_class *h, mpfr_class *ht, mpfr_class *wr, mpfr_class *wi, mpfr_class *wrt, mpfr_class *wit, mpfr_class *vs, mplapackint const ldvs, mpfr_class *result, mpfr_class *work, mplapackint const nwork, mplapackint *iwork, bool *bwork, mplapackint &info);
void Rdrvev(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpfr_class *a, mplapackint const lda, mpfr_class *h, mpfr_class *wr, mpfr_class *wi, mpfr_class *wr1, mpfr_class *wi1, mpfr_class *vl, mplapackint const ldvl, mpfr_class *vr, mplapackint const ldvr, mpfr_class *lre, mplapackint const ldlre, mpfr_class *result, mpfr_class *work, mplapackint const nwork, mplapackint *iwork, mplapackint &info);
void Rdrvsg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpfr_class *a, mplapackint const lda, mpfr_class *b, mplapackint const ldb, mpfr_class *d, mpfr_class *z, mplapackint const ldz, mpfr_class *ab, mpfr_class *bb, mpfr_class *ap, mpfr_class *bp, mpfr_class *work, mplapackint const nwork, mplapackint *iwork, mplapackint const liwork, mpfr_class *result, mplapackint &info);
void Rdrvsg2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpfr_class *a, mplapackint const lda, mpfr_class *b, mplapackint const ldb, mpfr_class *d, mpfr_class *d2, mpfr_class *z, mplapackint const ldz, mpfr_class *ab, mpfr_class *bb, mpfr_class *ap, mpfr_class *bp, mpfr_class *work, mplapackint const nwork, mplapackint *iwork, mplapackint const liwork, mpfr_class *result, mplapackint &info);
void Rdrvst(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpfr_class *a, mplapackint const lda, mpfr_class *d1, mpfr_class *d2, mpfr_class *d3, mpfr_class *d4, mpfr_class *eveigs, mpfr_class *wa1, mpfr_class *wa2, mpfr_class *wa3, mpfr_class *u, mplapackint const ldu, mpfr_class *v, mpfr_class *tau, mpfr_class *z, mpfr_class *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, mpfr_class *result, mplapackint &info);
void Rdrvst2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const nounit, mpfr_class *a, mplapackint const lda, mpfr_class *d1, mpfr_class *d2, mpfr_class *d3, mpfr_class *d4, mpfr_class *eveigs, mpfr_class *wa1, mpfr_class *wa2, mpfr_class *wa3, mpfr_class *u, mplapackint const ldu, mpfr_class *v, mpfr_class *tau, mpfr_class *z, mpfr_class *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, mpfr_class *result, mplapackint &info);
void Rdrvsx(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const niunit, mplapackint const nounit, mpfr_class *a, mplapackint const lda, mpfr_class *h, mpfr_class *ht, mpfr_class *wr, mpfr_class *wi, mpfr_class *wrt, mpfr_class *wit, mpfr_class *wrtmp, mpfr_class *witmp, mpfr_class *vs, mplapackint const ldvs, mpfr_class *vs1, mpfr_class *result, mpfr_class *work, mplapackint const lwork, mplapackint *iwork, bool *bwork, mplapackint &info);
void Rdrvvx(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const niunit, mplapackint const nounit, mpfr_class *a, mplapackint const lda, mpfr_class *h, mpfr_class *wr, mpfr_class *wi, mpfr_class *wr1, mpfr_class *wi1, mpfr_class *vl, mplapackint const ldvl, mpfr_class *vr, mplapackint const ldvr, mpfr_class *lre, mplapackint const ldlre, mpfr_class *rcondv, mpfr_class *rcndv1, mpfr_class *rcdvin, mpfr_class *rconde, mpfr_class *rcnde1, mpfr_class *rcdein, mpfr_class *scale, mpfr_class *scale1, mpfr_class *result, mpfr_class *work, mplapackint const nwork, mplapackint *iwork, mplapackint &info);
void Rerrbd(fem::str_cref path, mplapackint const nunit);
void Rerrec(fem::str_cref path, mplapackint const nunit);
void Rerred(fem::str_cref path, mplapackint const nunit);
void Rerrgg(fem::str_cref path, mplapackint const nunit);
void Rerrhs(fem::str_cref path, mplapackint const nunit);
void Rerrst(fem::str_cref path, mplapackint const nunit);
void Rget02(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mpfr_class *x, mplapackint const ldx, mpfr_class *b, mplapackint const ldb, mpfr_class *rwork, mpfr_class &resid);
void Rget10(mplapackint const m, mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class *b, mplapackint const ldb, mpfr_class *work, mpfr_class &result);
void Rget22(fem::str_cref transa, fem::str_cref transe, fem::str_cref transw, mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class *e, mplapackint const lde, mpfr_class *wr, mpfr_class *wi, mpfr_class *work, mpfr_class *result);
void Rget23(bool const comp, fem::str_cref balanc, mplapackint const jtype, mpfr_class const thresh, mplapackint (&iseed)[4], mplapackint const nounit, mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class *h, mpfr_class *wr, mpfr_class *wi, mpfr_class *wr1, mpfr_class *wi1, mpfr_class *vl, mplapackint const ldvl, mpfr_class *vr, mplapackint const ldvr, mpfr_class *lre, mplapackint const ldlre, mpfr_class *rcondv, mpfr_class *rcndv1, mpfr_class *rcdvin, mpfr_class *rconde, mpfr_class *rcnde1, mpfr_class *rcdein, mpfr_class *scale, mpfr_class *scale1, mpfr_class *result, mpfr_class *work, mplapackint const lwork, mplapackint *iwork, mplapackint &info);
void Rget24(bool const comp, mplapackint const jtype, mpfr_class const thresh, mplapackint (&iseed)[4], mplapackint const nounit, mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class *h, mpfr_class *ht, mpfr_class *wr, mpfr_class *wi, mpfr_class *wrt, mpfr_class *wit, mpfr_class *wrtmp, mpfr_class *witmp, mpfr_class *vs, mplapackint const ldvs, mpfr_class *vs1, mpfr_class const rcdein, mpfr_class const rcdvin, mplapackint const nslct, mplapackint *islct, mpfr_class *result, mpfr_class *work, mplapackint const lwork, mplapackint *iwork, bool *bwork, mplapackint &info);
void Rget31(mpfr_class &rmax, mplapackint &lmax, mplapackint *ninfo, mplapackint &knt);
void Rget32(mpfr_class &rmax, mplapackint &lmax, mplapackint &ninfo, mplapackint &knt);
void Rget33(mpfr_class &rmax, mplapackint &lmax, mplapackint &ninfo, mplapackint &knt);
void Rget34(mpfr_class &rmax, mplapackint &lmax, mplapackint *ninfo, mplapackint &knt);
void Rget35(mpfr_class &rmax, mplapackint &lmax, mplapackint &ninfo, mplapackint &knt);
void Rget36(mpfr_class &rmax, mplapackint &lmax, mplapackint *ninfo, mplapackint &knt, mplapackint const nin);
void Rget37(mpfr_class *rmax, mplapackint *lmax, mplapackint *ninfo, mplapackint &knt, mplapackint const nin);
void Rget38(mpfr_class *rmax, mplapackint *lmax, mplapackint *ninfo, mplapackint &knt, mplapackint const nin);
void Rget39(mpfr_class &rmax, mplapackint &lmax, mplapackint &ninfo, mplapackint &knt);
void Rget40(mpfr_class &rmax, mplapackint &lmax, mplapackint *ninfo, mplapackint &knt, mplapackint const nin);
void Rget51(mplapackint const itype, mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class *b, mplapackint const ldb, mpfr_class *u, mplapackint const ldu, mpfr_class *v, mplapackint const ldv, mpfr_class *work, mpfr_class &result);
void Rget52(bool const left, mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class *b, mplapackint const ldb, mpfr_class *e, mplapackint const lde, mpfr_class *alphar, mpfr_class *alphai, mpfr_class *beta, mpfr_class *work, mpfr_class *result);
void Rget53(mpfr_class *a, mplapackint const lda, mpfr_class *b, mplapackint const ldb, mpfr_class const scale, mpfr_class const wr, mpfr_class const wi, mpfr_class &result, mplapackint &info);
void Rget54(mplapackint const n, mpfr_class *a, mplapackint const lda, mpfr_class *b, mplapackint const ldb, mpfr_class *s, mplapackint const lds, mpfr_class *t, mplapackint const ldt, mpfr_class *u, mplapackint const ldu, mpfr_class *v, mplapackint const ldv, mpfr_class *work, mpfr_class &result);
void Rglmts(mplapackint const n, mplapackint const m, mplapackint const p, mpfr_class *a, mpfr_class *af, mplapackint const lda, mpfr_class *b, mpfr_class *bf, mplapackint const ldb, mpfr_class *d, mpfr_class *df, mpfr_class *x, mpfr_class *u, mpfr_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class &result);
void Rgqrts(mplapackint const n, mplapackint const m, mplapackint const p, mpfr_class *a, mpfr_class *af, mpfr_class *q, mpfr_class *r, mplapackint const lda, mpfr_class *taua, mpfr_class *b, mpfr_class *bf, mpfr_class *z, mpfr_class *t, mpfr_class *bwk, mplapackint const ldb, mpfr_class *taub, mpfr_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Rgrqts(mplapackint const m, mplapackint const p, mplapackint const n, mpfr_class *a, mpfr_class *af, mpfr_class *q, mpfr_class *r, mplapackint const lda, mpfr_class *taua, mpfr_class *b, mpfr_class *bf, mpfr_class *z, mpfr_class *t, mpfr_class *bwk, mplapackint const ldb, mpfr_class *taub, mpfr_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Rgsvts3(mplapackint const m, mplapackint const p, mplapackint const n, mpfr_class *a, mpfr_class *af, mplapackint const lda, mpfr_class *b, mpfr_class *bf, mplapackint const ldb, mpfr_class *u, mplapackint const ldu, mpfr_class *v, mplapackint const ldv, mpfr_class *q, mplapackint const ldq, mpfr_class *alpha, mpfr_class *beta, mpfr_class *r, mplapackint const ldr, mplapackint *iwork, mpfr_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Rhst01(mplapackint const n, mplapackint const, mplapackint const, mpfr_class *a, mplapackint const lda, mpfr_class *h, mplapackint const ldh, mpfr_class *q, mplapackint const ldq, mpfr_class *work, mplapackint const lwork, mpfr_class *result);
void Rlacsg(mplapackint const m, mplapackint const p, mplapackint const q, mpfr_class *theta, mplapackint (&iseed)[4], mpfr_class *x, mplapackint const ldx, mpfr_class *work);
void Rlafts(fem::str_cref type, mplapackint const m, mplapackint const n, mplapackint const imat, mplapackint const ntests, mpfr_class *result, mplapackint (&iseed)[4], mpfr_class const thresh, mplapackint const iounit, mplapackint &ie);
void Rlahd2(mplapackint const iounit, fem::str_cref path);
void Rlarfy(fem::str_cref uplo, mplapackint const n, mpfr_class *v, mplapackint const incv, mpfr_class const tau, mpfr_class *c, mplapackint const ldc, mpfr_class *work);
void Rlarhs(fem::str_cref path, fem::str_cref xtype, fem::str_cref uplo, fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mplapackint const nrhs, mpfr_class *a, mplapackint const lda, mpfr_class *x, mplapackint const ldx, mpfr_class *b, mplapackint const ldb, mplapackint (&iseed)[4], mplapackint &info);
void Rlasum(fem::str_cref type, mplapackint const iounit, mplapackint const ie, mplapackint const nrun);
void Rlatb9(fem::str_cref path, mplapackint const imat, mplapackint const m, mplapackint const p, mplapackint const n, fem::str_ref type, mplapackint &kla, mplapackint &kua, mplapackint &klb, mplapackint &kub, mpfr_class &anorm, mpfr_class &bnorm, mplapackint &modea, mplapackint &modeb, mpfr_class &cndnma, mpfr_class &cndnmb, fem::str_ref dista, fem::str_ref distb);
void Rlatm4(mplapackint const itype, mplapackint const n, mplapackint const nz1, mplapackint const nz2, mplapackint const isign, mpfr_class const amagn, mpfr_class const rcond, mpfr_class const triang, mplapackint const idist, mplapackint (&iseed)[4], mpfr_class *a, mplapackint const lda);
void Rlsets(mplapackint const m, mplapackint const p, mplapackint const n, mpfr_class *a, mpfr_class *af, mplapackint const lda, mpfr_class *b, mpfr_class *bf, mplapackint const ldb, mpfr_class *c, mpfr_class *cf, mpfr_class *d, mpfr_class *df, mpfr_class *x, mpfr_class *work, mplapackint const lwork, mpfr_class *rwork, mpfr_class *result);
void Rort01(fem::str_cref rowcol, mplapackint const m, mplapackint const n, mpfr_class *u, mplapackint const ldu, mpfr_class *work, mplapackint const lwork, mpfr_class &resid);
void Rort03(fem::str_cref rc, mplapackint const mu, mplapackint const mv, mplapackint const n, mplapackint const k, mpfr_class *u, mplapackint const ldu, mpfr_class *v, mplapackint const ldv, mpfr_class *work, mplapackint const lwork, mpfr_class &result, mplapackint &info);
void Rsbt21(fem::str_cref uplo, mplapackint const n, mplapackint const ka, mplapackint const ks, mpfr_class *a, mplapackint const lda, mpfr_class *d, mpfr_class *e, mpfr_class *u, mplapackint const ldu, mpfr_class *work, mpfr_class *result);
void Rsgt01(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const m, mpfr_class *a, mplapackint const lda, mpfr_class *b, mplapackint const ldb, mpfr_class *z, mplapackint const ldz, mpfr_class *d, mpfr_class *work, mpfr_class *result);
void Rspt21(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const kband, mpfr_class *ap, mpfr_class *d, mpfr_class *e, mpfr_class *u, mplapackint const ldu, mpfr_class *vp, mpfr_class *tau, mpfr_class *work, mpfr_class *result);
void Rstech(mplapackint const n, mpfr_class *a, mpfr_class *b, mpfr_class *eig, mpfr_class const tol, mpfr_class *work, mplapackint &info);
void Rstect(mplapackint const n, mpfr_class *a, mpfr_class *b, mpfr_class const shift, mplapackint &num);
void Rstt21(mplapackint const n, mplapackint const kband, mpfr_class *ad, mpfr_class *ae, mpfr_class *sd, mpfr_class *se, mpfr_class *u, mplapackint const ldu, mpfr_class *work, mpfr_class *result);
void Rstt22(mplapackint const n, mplapackint const m, mplapackint const kband, mpfr_class *ad, mpfr_class *ae, mpfr_class *sd, mpfr_class *se, mpfr_class *u, mplapackint const ldu, mpfr_class *work, mplapackint const ldwork, mpfr_class *result);
void Rsvdch(mplapackint const n, mpfr_class *s, mpfr_class *e, mpfr_class *svd, mpfr_class const tol, mplapackint &info);
void Rsvdct(mplapackint const n, mpfr_class *s, mpfr_class *e, mpfr_class const shift, mplapackint &num);
void Rsyl01(mpfr_class const thresh, mplapackint *nfail, mpfr_class *rmax, mplapackint *ninfo, mplapackint &knt);
void Rsyt21(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const kband, mpfr_class *a, mplapackint const lda, mpfr_class *d, mpfr_class *e, mpfr_class *u, mplapackint const ldu, mpfr_class *v, mplapackint const ldv, mpfr_class *tau, mpfr_class *work, mpfr_class *result);
void Rsyt22(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const m, mplapackint const kband, mpfr_class *a, mplapackint const lda, mpfr_class *d, mpfr_class *e, mpfr_class *u, mplapackint const ldu, mpfr_class *, mplapackint const ldv, mpfr_class *, mpfr_class *work, mpfr_class *result);
#endif
