/*
 * Copyright (c) 2012-2025
 *	Nakata, Maho
 * 	All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 */

#ifndef MPLAPACK_EIG_BINARY80_H
#define MPLAPACK_EIG_BINARY80_H

#include "mplapack_config.h"

#include <mpblas.h>
#include <mplapack.h>

#include <fem.hpp> // Fortran EMulation library of fable module
using namespace fem::major_types;
using fem::common;

#include <mplapack_matgen.h>
#include <mplapack_debug.h>

bool Clctes(std::complex<mplapack_binary80_t> const z, std::complex<mplapack_binary80_t> const d);
bool Clctsx(std::complex<mplapack_binary80_t> const, std::complex<mplapack_binary80_t> const);
bool Cslect(std::complex<mplapack_binary80_t> const z);
bool Rlctes(mplapack_binary80_t const zr, mplapack_binary80_t const, mplapack_binary80_t const d);
bool Rlctsx(mplapack_binary80_t const, mplapack_binary80_t const, mplapack_binary80_t const);
bool Rslect(mplapack_binary80_t const zr, mplapack_binary80_t const zi);
mplapack_binary80_t Rlamch_binary80(const char *cmach);
mplapack_binary80_t Rsxt1(mplapackint const ijob, mplapack_binary80_t *d1, mplapackint const n1, mplapack_binary80_t *d2, mplapackint const n2, mplapack_binary80_t const abstol, mplapack_binary80_t const ulp, mplapack_binary80_t const unfl);
mplapackint iMlaenv2stage_binary80(mplapackint const ispec, const char *name, const char *opts, mplapackint const n1, mplapackint const n2, mplapackint const n3, mplapackint const n4);
mplapackint iMlaenv_binary80(mplapackint const ispec, const char *name, const char *opts, mplapackint const n1, mplapackint const n2, mplapackint const n3, mplapackint const n4);
void Alahdg(mplapackint const iounit, fem::str_cref path);
void Alareq(fem::str_cref path, mplapackint const nmats, bool *dotype, mplapackint const ntypes, mplapackint const nin, mplapackint const nout);
void Alarqg(fem::str_cref path, mplapackint const nmats, bool *dotype, mplapackint const ntypes, mplapackint const nin, mplapackint const nout);
void Alasmg(fem::str_cref type, mplapackint const nout, mplapackint const nfail, mplapackint const nrun, mplapackint const nerrs);
void Alasum(fem::str_cref type, mplapackint const nout, mplapackint const nfail, mplapackint const nrun, mplapackint const nerrs);
void Alasvm(fem::str_cref type, mplapackint const nout, mplapackint const nfail, mplapackint const nrun, mplapackint const nerrs);
void Cbdt01(mplapackint const m, mplapackint const n, mplapackint const kd, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *q, mplapackint const ldq, mplapack_binary80_t *d, mplapack_binary80_t *e, std::complex<mplapack_binary80_t> *pt, mplapackint const ldpt, std::complex<mplapack_binary80_t> *work, mplapack_binary80_t *rwork, mplapack_binary80_t &resid);
void Cbdt02(mplapackint const m, mplapackint const n, std::complex<mplapack_binary80_t> *b, mplapackint const ldb, std::complex<mplapack_binary80_t> *c, mplapackint const ldc, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *work, mplapack_binary80_t *rwork, mplapack_binary80_t &resid);
void Cbdt03(fem::str_cref uplo, mplapackint const n, mplapackint const kd, mplapack_binary80_t *d, mplapack_binary80_t *e, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, mplapack_binary80_t *s, std::complex<mplapack_binary80_t> *vt, mplapackint const ldvt, std::complex<mplapack_binary80_t> *work, mplapack_binary80_t &resid);
void Cbdt05(mplapackint const m, mplapackint const n, std::complex<mplapack_binary80_t> *a, mplapackint const lda, mplapack_binary80_t *s, mplapackint const ns, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *vt, mplapackint const ldvt, std::complex<mplapack_binary80_t> *work, mplapack_binary80_t &resid);
void Cchkbb(mplapackint const nsizes, mplapackint *mval, mplapackint *nval, mplapackint const nwdths, mplapackint *kk, mplapackint const ntypes, bool *dotype, mplapackint const nrhs, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *ab, mplapackint const ldab, mplapack_binary80_t *bd, mplapack_binary80_t *be, std::complex<mplapack_binary80_t> *q, mplapackint const ldq, std::complex<mplapack_binary80_t> *p, mplapackint const ldp, std::complex<mplapack_binary80_t> *c, mplapackint const ldc, std::complex<mplapack_binary80_t> *cc, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t *result, mplapackint &info);
void Cchkbd(mplapackint const nsizes, mplapackint *mval, mplapackint *nval, mplapackint const ntypes, bool *dotype, mplapackint const nrhs, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, std::complex<mplapack_binary80_t> *a, mplapackint const lda, mplapack_binary80_t *bd, mplapack_binary80_t *be, mplapack_binary80_t *s1, mplapack_binary80_t *s2, std::complex<mplapack_binary80_t> *x, mplapackint const ldx, std::complex<mplapack_binary80_t> *y, std::complex<mplapack_binary80_t> *z, std::complex<mplapack_binary80_t> *q, mplapackint const ldq, std::complex<mplapack_binary80_t> *pt, mplapackint const ldpt, std::complex<mplapack_binary80_t> *u, std::complex<mplapack_binary80_t> *vt, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapackint const nout, mplapackint &info);
void Cchkbk(mplapackint const nin, mplapackint const nout);
void Cchkbl(mplapackint const nin, mplapackint const nout);
void Cchkec(mplapack_binary80_t const thresh, bool const tsterr, mplapackint const nin, mplapackint const nout);
void Cchkgg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, bool const tstdif, mplapack_binary80_t const thrshn, mplapackint const nounit, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *b, std::complex<mplapack_binary80_t> *h, std::complex<mplapack_binary80_t> *t, std::complex<mplapack_binary80_t> *s1, std::complex<mplapack_binary80_t> *s2, std::complex<mplapack_binary80_t> *p1, std::complex<mplapack_binary80_t> *p2, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *v, std::complex<mplapack_binary80_t> *q, std::complex<mplapack_binary80_t> *z, std::complex<mplapack_binary80_t> *alpha1, std::complex<mplapack_binary80_t> *beta1, std::complex<mplapack_binary80_t> *alpha3, std::complex<mplapack_binary80_t> *beta3, std::complex<mplapack_binary80_t> *evectl, std::complex<mplapack_binary80_t> *evectr, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, bool *llwork, mplapack_binary80_t *result, mplapackint &info);
void Cchkgk(mplapackint const nin, mplapackint const nout);
void Cchkgl(mplapackint const nin, mplapackint const nout);
void Cchkhb(mplapackint const nsizes, mplapackint *nn, mplapackint const nwdths, mplapackint *kk, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, std::complex<mplapack_binary80_t> *a, mplapackint const lda, mplapack_binary80_t *sd, mplapack_binary80_t *se, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t *result, mplapackint &info);
void Cchkhb2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const nwdths, mplapackint *kk, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, std::complex<mplapack_binary80_t> *a, mplapackint const lda, mplapack_binary80_t *sd, mplapack_binary80_t *se, mplapack_binary80_t *d1, mplapack_binary80_t *d2, mplapack_binary80_t *d3, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t *result, mplapackint &info);
void Cchkhs(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *h, std::complex<mplapack_binary80_t> *t1, std::complex<mplapack_binary80_t> *t2, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *z, std::complex<mplapack_binary80_t> *uz, std::complex<mplapack_binary80_t> *w1, std::complex<mplapack_binary80_t> *w3, std::complex<mplapack_binary80_t> *evectl, std::complex<mplapack_binary80_t> *evectr, std::complex<mplapack_binary80_t> *evecty, std::complex<mplapack_binary80_t> *evectx, std::complex<mplapack_binary80_t> *uu, std::complex<mplapack_binary80_t> *tau, std::complex<mplapack_binary80_t> *work, mplapackint const nwork, mplapack_binary80_t *rwork, mplapackint *iwork, bool *select, mplapack_binary80_t *result, mplapackint &info);
void Cchkst(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *ap, mplapack_binary80_t *sd, mplapack_binary80_t *se, mplapack_binary80_t *d1, mplapack_binary80_t *d2, mplapack_binary80_t *d3, mplapack_binary80_t *d4, mplapack_binary80_t *d5, mplapack_binary80_t *wa1, mplapack_binary80_t *wa2, mplapack_binary80_t *wa3, mplapack_binary80_t *wr, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *v, std::complex<mplapack_binary80_t> *vp, std::complex<mplapack_binary80_t> *tau, std::complex<mplapack_binary80_t> *z, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapackint const lrwork, mplapackint *iwork, mplapackint const liwork, mplapack_binary80_t *result, mplapackint &info);
void Cchkst2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *ap, mplapack_binary80_t *sd, mplapack_binary80_t *se, mplapack_binary80_t *d1, mplapack_binary80_t *d2, mplapack_binary80_t *d3, mplapack_binary80_t *d4, mplapack_binary80_t *d5, mplapack_binary80_t *wa1, mplapack_binary80_t *wa2, mplapack_binary80_t *wa3, mplapack_binary80_t *wr, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *v, std::complex<mplapack_binary80_t> *vp, std::complex<mplapack_binary80_t> *tau, std::complex<mplapack_binary80_t> *z, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapackint const lrwork, mplapackint *iwork, mplapackint const liwork, mplapack_binary80_t *result, mplapackint &info);
void Cckcsd(mplapackint const nm, mplapackint *mval, mplapackint *pval, mplapackint *qval, mplapackint const nmats, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const mmax, std::complex<mplapack_binary80_t> *x, std::complex<mplapack_binary80_t> *xf, std::complex<mplapack_binary80_t> *u1, std::complex<mplapack_binary80_t> *u2, std::complex<mplapack_binary80_t> *v1t, std::complex<mplapack_binary80_t> *v2t, mplapack_binary80_t *theta, mplapackint *iwork, std::complex<mplapack_binary80_t> *work, mplapack_binary80_t *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Cckglm(mplapackint const nn, mplapackint *nval, mplapackint *mval, mplapackint *pval, mplapackint const nmats, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nmax, std::complex<mplapack_binary80_t> *a, std::complex<mplapack_binary80_t> *af, std::complex<mplapack_binary80_t> *b, std::complex<mplapack_binary80_t> *bf, std::complex<mplapack_binary80_t> *x, std::complex<mplapack_binary80_t> *work, mplapack_binary80_t *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Cckgqr(mplapackint const nm, mplapackint *mval, mplapackint const np, mplapackint *pval, mplapackint const nn, mplapackint *nval, mplapackint const nmats, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nmax, std::complex<mplapack_binary80_t> *a, std::complex<mplapack_binary80_t> *af, std::complex<mplapack_binary80_t> *aq, std::complex<mplapack_binary80_t> *ar, std::complex<mplapack_binary80_t> *taua, std::complex<mplapack_binary80_t> *b, std::complex<mplapack_binary80_t> *bf, std::complex<mplapack_binary80_t> *bz, std::complex<mplapack_binary80_t> *bt, std::complex<mplapack_binary80_t> *bwk, std::complex<mplapack_binary80_t> *taub, std::complex<mplapack_binary80_t> *work, mplapack_binary80_t *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Cckgsv(mplapackint const nm, mplapackint *mval, mplapackint *pval, mplapackint *nval, mplapackint const nmats, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nmax, std::complex<mplapack_binary80_t> *a, std::complex<mplapack_binary80_t> *af, std::complex<mplapack_binary80_t> *b, std::complex<mplapack_binary80_t> *bf, std::complex<mplapack_binary80_t> *u, std::complex<mplapack_binary80_t> *v, std::complex<mplapack_binary80_t> *q, mplapack_binary80_t *alpha, mplapack_binary80_t *beta, std::complex<mplapack_binary80_t> *r, mplapackint *iwork, std::complex<mplapack_binary80_t> *work, mplapack_binary80_t *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Ccklse(mplapackint const nn, mplapackint *mval, mplapackint *pval, mplapackint *nval, mplapackint const nmats, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nmax, std::complex<mplapack_binary80_t> *a, std::complex<mplapack_binary80_t> *af, std::complex<mplapack_binary80_t> *b, std::complex<mplapack_binary80_t> *bf, std::complex<mplapack_binary80_t> *x, std::complex<mplapack_binary80_t> *work, mplapack_binary80_t *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Ccsdts(mplapackint const m, mplapackint const p, mplapackint const q, std::complex<mplapack_binary80_t> *x, std::complex<mplapack_binary80_t> *xf, mplapackint const ldx, std::complex<mplapack_binary80_t> *u1, mplapackint const ldu1, std::complex<mplapack_binary80_t> *u2, mplapackint const ldu2, std::complex<mplapack_binary80_t> *v1t, mplapackint const ldv1t, std::complex<mplapack_binary80_t> *v2t, mplapackint const ldv2t, mplapack_binary80_t *theta, mplapackint *iwork, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t *result);
void Cdrges(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *b, std::complex<mplapack_binary80_t> *s, std::complex<mplapack_binary80_t> *t, std::complex<mplapack_binary80_t> *q, mplapackint const ldq, std::complex<mplapack_binary80_t> *z, std::complex<mplapack_binary80_t> *alpha, std::complex<mplapack_binary80_t> *beta, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t *result, bool *bwork, mplapackint &info);
void Cdrges3(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *b, std::complex<mplapack_binary80_t> *s, std::complex<mplapack_binary80_t> *t, std::complex<mplapack_binary80_t> *q, mplapackint const ldq, std::complex<mplapack_binary80_t> *z, std::complex<mplapack_binary80_t> *alpha, std::complex<mplapack_binary80_t> *beta, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t *result, bool *bwork, mplapackint &info);
void Cdrgev(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *b, std::complex<mplapack_binary80_t> *s, std::complex<mplapack_binary80_t> *t, std::complex<mplapack_binary80_t> *q, mplapackint const ldq, std::complex<mplapack_binary80_t> *z, std::complex<mplapack_binary80_t> *qe, mplapackint const ldqe, std::complex<mplapack_binary80_t> *alpha, std::complex<mplapack_binary80_t> *beta, std::complex<mplapack_binary80_t> *alpha1, std::complex<mplapack_binary80_t> *beta1, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t *result, mplapackint &info);
void Cdrgev3(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *b, std::complex<mplapack_binary80_t> *s, std::complex<mplapack_binary80_t> *t, std::complex<mplapack_binary80_t> *q, mplapackint const ldq, std::complex<mplapack_binary80_t> *z, std::complex<mplapack_binary80_t> *qe, mplapackint const ldqe, std::complex<mplapack_binary80_t> *alpha, std::complex<mplapack_binary80_t> *beta, std::complex<mplapack_binary80_t> *alpha1, std::complex<mplapack_binary80_t> *beta1, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t *result, mplapackint &info);
void Cdrgsx(mplapackint const nsize, mplapackint const ncmax, mplapack_binary80_t const thresh, mplapackint const nin, mplapackint const nout, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *b, std::complex<mplapack_binary80_t> *ai, std::complex<mplapack_binary80_t> *bi, std::complex<mplapack_binary80_t> *z, std::complex<mplapack_binary80_t> *q, std::complex<mplapack_binary80_t> *alpha, std::complex<mplapack_binary80_t> *beta, std::complex<mplapack_binary80_t> *c, mplapackint const ldc, mplapack_binary80_t *s, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapackint *iwork, mplapackint const liwork, bool *bwork, mplapackint &info);
void Cdrgvx(mplapackint const nsize, mplapack_binary80_t const thresh, mplapackint const nin, mplapackint const nout, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *b, std::complex<mplapack_binary80_t> *ai, std::complex<mplapack_binary80_t> *bi, std::complex<mplapack_binary80_t> *alpha, std::complex<mplapack_binary80_t> *beta, std::complex<mplapack_binary80_t> *vl, std::complex<mplapack_binary80_t> *vr, mplapackint &ilo, mplapackint &ihi, mplapack_binary80_t *lscale, mplapack_binary80_t *rscale, mplapack_binary80_t *s, mplapack_binary80_t *dtru, mplapack_binary80_t *dif, mplapack_binary80_t *diftru, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapackint *iwork, mplapackint const liwork, mplapack_binary80_t *result, bool *bwork, mplapackint &info);
void Cdrvbd(mplapackint const nsizes, mplapackint *mm, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *vt, mplapackint const ldvt, std::complex<mplapack_binary80_t> *asav, std::complex<mplapack_binary80_t> *usav, std::complex<mplapack_binary80_t> *vtsav, mplapack_binary80_t *s, mplapack_binary80_t *ssav, mplapack_binary80_t *e, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapackint *iwork, mplapackint const nounit, mplapackint &info);
void Cdrves(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *h, std::complex<mplapack_binary80_t> *ht, std::complex<mplapack_binary80_t> *w, std::complex<mplapack_binary80_t> *wt, std::complex<mplapack_binary80_t> *vs, mplapackint const ldvs, mplapack_binary80_t *result, std::complex<mplapack_binary80_t> *work, mplapackint const nwork, mplapack_binary80_t *rwork, mplapackint *iwork, bool *bwork, mplapackint &info);
void Cdrvev(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *h, std::complex<mplapack_binary80_t> *w, std::complex<mplapack_binary80_t> *w1, std::complex<mplapack_binary80_t> *vl, mplapackint const ldvl, std::complex<mplapack_binary80_t> *vr, mplapackint const ldvr, std::complex<mplapack_binary80_t> *lre, mplapackint const ldlre, mplapack_binary80_t *result, std::complex<mplapack_binary80_t> *work, mplapackint const nwork, mplapack_binary80_t *rwork, mplapackint *iwork, mplapackint &info);
void Cdrvsg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *b, mplapackint const ldb, mplapack_binary80_t *d, std::complex<mplapack_binary80_t> *z, mplapackint const ldz, std::complex<mplapack_binary80_t> *ab, std::complex<mplapack_binary80_t> *bb, std::complex<mplapack_binary80_t> *ap, std::complex<mplapack_binary80_t> *bp, std::complex<mplapack_binary80_t> *work, mplapackint const nwork, mplapack_binary80_t *rwork, mplapackint const lrwork, mplapackint *iwork, mplapackint const liwork, mplapack_binary80_t *result, mplapackint &info);
void Cdrvsg2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *b, mplapackint const ldb, mplapack_binary80_t *d, mplapack_binary80_t *d2, std::complex<mplapack_binary80_t> *z, mplapackint const ldz, std::complex<mplapack_binary80_t> *ab, std::complex<mplapack_binary80_t> *bb, std::complex<mplapack_binary80_t> *ap, std::complex<mplapack_binary80_t> *bp, std::complex<mplapack_binary80_t> *work, mplapackint const nwork, mplapack_binary80_t *rwork, mplapackint const lrwork, mplapackint *iwork, mplapackint const liwork, mplapack_binary80_t *result, mplapackint &info);
void Cdrvst(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, std::complex<mplapack_binary80_t> *a, mplapackint const lda, mplapack_binary80_t *d1, mplapack_binary80_t *d2, mplapack_binary80_t *d3, mplapack_binary80_t *wa1, mplapack_binary80_t *wa2, mplapack_binary80_t *wa3, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *v, std::complex<mplapack_binary80_t> *tau, std::complex<mplapack_binary80_t> *z, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapackint const lrwork, mplapackint *iwork, mplapackint const liwork, mplapack_binary80_t *result, mplapackint &info);
void Cdrvst2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, std::complex<mplapack_binary80_t> *a, mplapackint const lda, mplapack_binary80_t *d1, mplapack_binary80_t *d2, mplapack_binary80_t *d3, mplapack_binary80_t *wa1, mplapack_binary80_t *wa2, mplapack_binary80_t *wa3, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *v, std::complex<mplapack_binary80_t> *tau, std::complex<mplapack_binary80_t> *z, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapackint const lrwork, mplapackint *iwork, mplapackint const liwork, mplapack_binary80_t *result, mplapackint &info);
void Cdrvsx(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const niunit, mplapackint const nounit, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *h, std::complex<mplapack_binary80_t> *ht, std::complex<mplapack_binary80_t> *w, std::complex<mplapack_binary80_t> *wt, std::complex<mplapack_binary80_t> *wtmp, std::complex<mplapack_binary80_t> *vs, mplapackint const ldvs, std::complex<mplapack_binary80_t> *vs1, mplapack_binary80_t *result, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, bool *bwork, mplapackint &info);
void Cdrvvx(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const niunit, mplapackint const nounit, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *h, std::complex<mplapack_binary80_t> *w, std::complex<mplapack_binary80_t> *w1, std::complex<mplapack_binary80_t> *vl, mplapackint const ldvl, std::complex<mplapack_binary80_t> *vr, mplapackint const ldvr, std::complex<mplapack_binary80_t> *lre, mplapackint const ldlre, mplapack_binary80_t *rcondv, mplapack_binary80_t *rcndv1, mplapack_binary80_t *rcdvin, mplapack_binary80_t *rconde, mplapack_binary80_t *rcnde1, mplapack_binary80_t *rcdein, mplapack_binary80_t *scale, mplapack_binary80_t *scale1, mplapack_binary80_t *result, std::complex<mplapack_binary80_t> *work, mplapackint const nwork, mplapack_binary80_t *rwork, mplapackint &info);
void Cerrbd(fem::str_cref path, mplapackint const nunit);
void Cerrec(fem::str_cref path, mplapackint const nunit);
void Cerred(fem::str_cref path, mplapackint const nunit);
void Cerrgg(fem::str_cref path, mplapackint const nunit);
void Cerrhs(fem::str_cref path, mplapackint const nunit);
void Cerrst(fem::str_cref path, mplapackint const nunit);
void Cget02(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *x, mplapackint const ldx, std::complex<mplapack_binary80_t> *b, mplapackint const ldb, mplapack_binary80_t *rwork, mplapack_binary80_t &resid);
void Cget10(mplapackint const m, mplapackint const n, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *b, mplapackint const ldb, std::complex<mplapack_binary80_t> *work, mplapack_binary80_t *rwork, mplapack_binary80_t &result);
void Cget22(fem::str_cref transa, fem::str_cref transe, fem::str_cref transw, mplapackint const n, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *e, mplapackint const lde, std::complex<mplapack_binary80_t> *w, std::complex<mplapack_binary80_t> *work, mplapack_binary80_t *rwork, mplapack_binary80_t *result);
void Cget23(bool const comp, mplapackint const isrt, fem::str_cref balanc, mplapackint const jtype, mplapack_binary80_t const thresh, mplapackint (&iseed)[4], mplapackint const nounit, mplapackint const n, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *h, std::complex<mplapack_binary80_t> *w, std::complex<mplapack_binary80_t> *w1, std::complex<mplapack_binary80_t> *vl, mplapackint const ldvl, std::complex<mplapack_binary80_t> *vr, mplapackint const ldvr, std::complex<mplapack_binary80_t> *lre, mplapackint const ldlre, mplapack_binary80_t *rcondv, mplapack_binary80_t *rcndv1, mplapack_binary80_t *rcdvin, mplapack_binary80_t *rconde, mplapack_binary80_t *rcnde1, mplapack_binary80_t *rcdein, mplapack_binary80_t *scale, mplapack_binary80_t *scale1, mplapack_binary80_t *result, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapackint &info);
void Cget24(bool const comp, mplapackint const jtype, mplapack_binary80_t const thresh, mplapackint (&iseed)[4], mplapackint const nounit, mplapackint const n, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *h, std::complex<mplapack_binary80_t> *ht, std::complex<mplapack_binary80_t> *w, std::complex<mplapack_binary80_t> *wt, std::complex<mplapack_binary80_t> *wtmp, std::complex<mplapack_binary80_t> *vs, mplapackint const ldvs, std::complex<mplapack_binary80_t> *vs1, mplapack_binary80_t const rcdein, mplapack_binary80_t const rcdvin, mplapackint const nslct, mplapackint *islct, mplapackint const isrt, mplapack_binary80_t *result, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, bool *bwork, mplapackint &info);
void Cget35(mplapack_binary80_t &rmax, mplapackint &lmax, mplapackint &ninfo, mplapackint &knt, mplapackint const nin);
void Cget36(mplapack_binary80_t &rmax, mplapackint &lmax, mplapackint &ninfo, mplapackint &knt, mplapackint const nin);
void Cget37(mplapack_binary80_t *rmax, mplapackint *lmax, mplapackint *ninfo, mplapackint &knt, mplapackint const nin);
void Cget38(mplapack_binary80_t *rmax, mplapackint *lmax, mplapackint *ninfo, mplapackint &knt, mplapackint const nin);
void Cget51(mplapackint const itype, mplapackint const n, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *b, mplapackint const ldb, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *v, mplapackint const ldv, std::complex<mplapack_binary80_t> *work, mplapack_binary80_t *rwork, mplapack_binary80_t &result);
void Cget52(bool const left, mplapackint const n, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *b, mplapackint const ldb, std::complex<mplapack_binary80_t> *e, mplapackint const lde, std::complex<mplapack_binary80_t> *alpha, std::complex<mplapack_binary80_t> *beta, std::complex<mplapack_binary80_t> *work, mplapack_binary80_t *rwork, mplapack_binary80_t *result);
void Cget54(mplapackint const n, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *b, mplapackint const ldb, std::complex<mplapack_binary80_t> *s, mplapackint const lds, std::complex<mplapack_binary80_t> *t, mplapackint const ldt, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *v, mplapackint const ldv, std::complex<mplapack_binary80_t> *work, mplapack_binary80_t &result);
void Cglmts(mplapackint const n, mplapackint const m, mplapackint const p, std::complex<mplapack_binary80_t> *a, std::complex<mplapack_binary80_t> *af, mplapackint const lda, std::complex<mplapack_binary80_t> *b, std::complex<mplapack_binary80_t> *bf, mplapackint const ldb, std::complex<mplapack_binary80_t> *d, std::complex<mplapack_binary80_t> *df, std::complex<mplapack_binary80_t> *x, std::complex<mplapack_binary80_t> *u, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t &result);
void Cgqrts(mplapackint const n, mplapackint const m, mplapackint const p, std::complex<mplapack_binary80_t> *a, std::complex<mplapack_binary80_t> *af, std::complex<mplapack_binary80_t> *q, std::complex<mplapack_binary80_t> *r, mplapackint const lda, std::complex<mplapack_binary80_t> *taua, std::complex<mplapack_binary80_t> *b, std::complex<mplapack_binary80_t> *bf, std::complex<mplapack_binary80_t> *z, std::complex<mplapack_binary80_t> *t, std::complex<mplapack_binary80_t> *bwk, mplapackint const ldb, std::complex<mplapack_binary80_t> *taub, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t *result);
void Cgrqts(mplapackint const m, mplapackint const p, mplapackint const n, std::complex<mplapack_binary80_t> *a, std::complex<mplapack_binary80_t> *af, std::complex<mplapack_binary80_t> *q, std::complex<mplapack_binary80_t> *r, mplapackint const lda, std::complex<mplapack_binary80_t> *taua, std::complex<mplapack_binary80_t> *b, std::complex<mplapack_binary80_t> *bf, std::complex<mplapack_binary80_t> *z, std::complex<mplapack_binary80_t> *t, std::complex<mplapack_binary80_t> *bwk, mplapackint const ldb, std::complex<mplapack_binary80_t> *taub, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t *result);
void Cgsvts3(mplapackint const m, mplapackint const p, mplapackint const n, std::complex<mplapack_binary80_t> *a, std::complex<mplapack_binary80_t> *af, mplapackint const lda, std::complex<mplapack_binary80_t> *b, std::complex<mplapack_binary80_t> *bf, mplapackint const ldb, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *v, mplapackint const ldv, std::complex<mplapack_binary80_t> *q, mplapackint const ldq, mplapack_binary80_t *alpha, mplapack_binary80_t *beta, std::complex<mplapack_binary80_t> *r, mplapackint const ldr, mplapackint *iwork, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t *result);
void Chbt21(fem::str_cref uplo, mplapackint const n, mplapackint const ka, mplapackint const ks, std::complex<mplapack_binary80_t> *a, mplapackint const lda, mplapack_binary80_t *d, mplapack_binary80_t *e, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *work, mplapack_binary80_t *rwork, mplapack_binary80_t *result);
void Chet21(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const kband, std::complex<mplapack_binary80_t> *a, mplapackint const lda, mplapack_binary80_t *d, mplapack_binary80_t *e, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *v, mplapackint const ldv, std::complex<mplapack_binary80_t> *tau, std::complex<mplapack_binary80_t> *work, mplapack_binary80_t *rwork, mplapack_binary80_t *result);
void Chet22(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const m, mplapackint const kband, std::complex<mplapack_binary80_t> *a, mplapackint const lda, mplapack_binary80_t *d, mplapack_binary80_t *e, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *, mplapackint const ldv, std::complex<mplapack_binary80_t> *, std::complex<mplapack_binary80_t> *work, mplapack_binary80_t *rwork, mplapack_binary80_t *result);
void Chkxer(fem::str_cref srnamt, mplapackint const infot, mplapackint const nout, bool &lerr, bool &ok);
void Chpt21(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const kband, std::complex<mplapack_binary80_t> *ap, mplapack_binary80_t *d, mplapack_binary80_t *e, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *vp, std::complex<mplapack_binary80_t> *tau, std::complex<mplapack_binary80_t> *work, mplapack_binary80_t *rwork, mplapack_binary80_t *result);
void Chst01(mplapackint const n, mplapackint const, mplapackint const, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *h, mplapackint const ldh, std::complex<mplapack_binary80_t> *q, mplapackint const ldq, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t *result);
void Clacsg(mplapackint const m, mplapackint const p, mplapackint const q, mplapack_binary80_t *theta, mplapackint (&iseed)[4], std::complex<mplapack_binary80_t> *x, mplapackint const ldx, std::complex<mplapack_binary80_t> *work);
void Clarfy(fem::str_cref uplo, mplapackint const n, std::complex<mplapack_binary80_t> *v, mplapackint const incv, std::complex<mplapack_binary80_t> const tau, std::complex<mplapack_binary80_t> *c, mplapackint const ldc, std::complex<mplapack_binary80_t> *work);
void Clarhs(fem::str_cref path, fem::str_cref xtype, fem::str_cref uplo, fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mplapackint const nrhs, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *x, mplapackint const ldx, std::complex<mplapack_binary80_t> *b, mplapackint const ldb, mplapackint (&iseed)[4], mplapackint &info);
void Clatm4(mplapackint const itype, mplapackint const n, mplapackint const nz1, mplapackint const nz2, bool const rsign, mplapack_binary80_t const amagn, mplapack_binary80_t const rcond, mplapack_binary80_t const triang, mplapackint const idist, mplapackint (&iseed)[4], std::complex<mplapack_binary80_t> *a, mplapackint const lda);
void Clsets(mplapackint const m, mplapackint const p, mplapackint const n, std::complex<mplapack_binary80_t> *a, std::complex<mplapack_binary80_t> *af, mplapackint const lda, std::complex<mplapack_binary80_t> *b, std::complex<mplapack_binary80_t> *bf, mplapackint const ldb, std::complex<mplapack_binary80_t> *c, std::complex<mplapack_binary80_t> *cf, std::complex<mplapack_binary80_t> *d, std::complex<mplapack_binary80_t> *df, std::complex<mplapack_binary80_t> *x, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t *result);
void Csbmv(fem::str_cref uplo, mplapackint const n, mplapackint const k, std::complex<mplapack_binary80_t> const alpha, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *x, mplapackint const incx, std::complex<mplapack_binary80_t> const beta, std::complex<mplapack_binary80_t> *y, mplapackint const incy);
void Csgt01(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const m, std::complex<mplapack_binary80_t> *a, mplapackint const lda, std::complex<mplapack_binary80_t> *b, mplapackint const ldb, std::complex<mplapack_binary80_t> *z, mplapackint const ldz, mplapack_binary80_t *d, std::complex<mplapack_binary80_t> *work, mplapack_binary80_t *rwork, mplapack_binary80_t *result);
void Cstt21(mplapackint const n, mplapackint const kband, mplapack_binary80_t *ad, mplapack_binary80_t *ae, mplapack_binary80_t *sd, mplapack_binary80_t *se, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *work, mplapack_binary80_t *rwork, mplapack_binary80_t *result);
void Cstt22(mplapackint const n, mplapackint const m, mplapackint const kband, mplapack_binary80_t *ad, mplapack_binary80_t *ae, mplapack_binary80_t *sd, mplapack_binary80_t *se, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *work, mplapackint const ldwork, mplapack_binary80_t *rwork, mplapack_binary80_t *result);
void Csyl01(mplapack_binary80_t const thresh, mplapackint *nfail, mplapack_binary80_t *rmax, mplapackint *ninfo, mplapackint &knt);
void Cunt01(fem::str_cref rowcol, mplapackint const m, mplapackint const n, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t &resid);
void Cunt03(fem::str_cref rc, mplapackint const mu, mplapackint const mv, mplapackint const n, mplapackint const k, std::complex<mplapack_binary80_t> *u, mplapackint const ldu, std::complex<mplapack_binary80_t> *v, mplapackint const ldv, std::complex<mplapack_binary80_t> *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t &result, mplapackint &info);
void Mxerbla_binary80(const char *srname, int info);
void Mxlaenv(mplapackint const ispec, mplapackint const nvalue);
void Rbdt01(mplapackint const m, mplapackint const n, mplapackint const kd, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *q, mplapackint const ldq, mplapack_binary80_t *d, mplapack_binary80_t *e, mplapack_binary80_t *pt, mplapackint const ldpt, mplapack_binary80_t *work, mplapack_binary80_t &resid);
void Rbdt02(mplapackint const m, mplapackint const n, mplapack_binary80_t *b, mplapackint const ldb, mplapack_binary80_t *c, mplapackint const ldc, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *work, mplapack_binary80_t &resid);
void Rbdt03(fem::str_cref uplo, mplapackint const n, mplapackint const kd, mplapack_binary80_t *d, mplapack_binary80_t *e, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *s, mplapack_binary80_t *vt, mplapackint const ldvt, mplapack_binary80_t *work, mplapack_binary80_t &resid);
void Rbdt04(fem::str_cref uplo, mplapackint const n, mplapack_binary80_t *d, mplapack_binary80_t *e, mplapack_binary80_t *s, mplapackint const ns, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *vt, mplapackint const ldvt, mplapack_binary80_t *work, mplapack_binary80_t &resid);
void Rbdt05(mplapackint const m, mplapackint const n, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *s, mplapackint const ns, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *vt, mplapackint const ldvt, mplapack_binary80_t *work, mplapack_binary80_t &resid);
void Rchkbb(mplapackint const nsizes, mplapackint *mval, mplapackint *nval, mplapackint const nwdths, mplapackint *kk, mplapackint const ntypes, bool *dotype, mplapackint const nrhs, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *ab, mplapackint const ldab, mplapack_binary80_t *bd, mplapack_binary80_t *be, mplapack_binary80_t *q, mplapackint const ldq, mplapack_binary80_t *p, mplapackint const ldp, mplapack_binary80_t *c, mplapackint const ldc, mplapack_binary80_t *cc, mplapack_binary80_t *work, mplapackint const lwork, mplapack_binary80_t *result, mplapackint &info);
void Rchkbd(mplapackint const nsizes, mplapackint *mval, mplapackint *nval, mplapackint const ntypes, bool *dotype, mplapackint const nrhs, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *bd, mplapack_binary80_t *be, mplapack_binary80_t *s1, mplapack_binary80_t *s2, mplapack_binary80_t *x, mplapackint const ldx, mplapack_binary80_t *y, mplapack_binary80_t *z, mplapack_binary80_t *q, mplapackint const ldq, mplapack_binary80_t *pt, mplapackint const ldpt, mplapack_binary80_t *u, mplapack_binary80_t *vt, mplapack_binary80_t *work, mplapackint const lwork, mplapackint *iwork, mplapackint const nout, mplapackint &info);
void Rchkbk(mplapackint const nin, mplapackint const nout);
void Rchkbl(mplapackint const nin, mplapackint const nout);
void Rchkec(mplapack_binary80_t const thresh, bool const tsterr, mplapackint const nin, mplapackint const nout);
void Rchkgg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, bool const tstdif, mplapack_binary80_t const thrshn, mplapackint const nounit, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *b, mplapack_binary80_t *h, mplapack_binary80_t *t, mplapack_binary80_t *s1, mplapack_binary80_t *s2, mplapack_binary80_t *p1, mplapack_binary80_t *p2, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *v, mplapack_binary80_t *q, mplapack_binary80_t *z, mplapack_binary80_t *alphr1, mplapack_binary80_t *alphi1, mplapack_binary80_t *beta1, mplapack_binary80_t *alphr3, mplapack_binary80_t *alphi3, mplapack_binary80_t *beta3, mplapack_binary80_t *evectl, mplapack_binary80_t *evectr, mplapack_binary80_t *work, mplapackint const lwork, bool *llwork, mplapack_binary80_t *result, mplapackint &info);
void Rchkgk(mplapackint const nin, mplapackint const nout);
void Rchkgl(mplapackint const nin, mplapackint const nout);
void Rchkhs(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *h, mplapack_binary80_t *t1, mplapack_binary80_t *t2, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *z, mplapack_binary80_t *uz, mplapack_binary80_t *wr1, mplapack_binary80_t *wi1, mplapack_binary80_t *wr2, mplapack_binary80_t *wi2, mplapack_binary80_t *wr3, mplapack_binary80_t *wi3, mplapack_binary80_t *evectl, mplapack_binary80_t *evectr, mplapack_binary80_t *evecty, mplapack_binary80_t *evectx, mplapack_binary80_t *uu, mplapack_binary80_t *tau, mplapack_binary80_t *work, mplapackint const nwork, mplapackint *iwork, bool *select, mplapack_binary80_t *result, mplapackint &info);
void Rchksb(mplapackint const nsizes, mplapackint *nn, mplapackint const nwdths, mplapackint *kk, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *sd, mplapack_binary80_t *se, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *work, mplapackint const lwork, mplapack_binary80_t *result, mplapackint &info);
void Rchksb2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const nwdths, mplapackint *kk, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *sd, mplapack_binary80_t *se, mplapack_binary80_t *d1, mplapack_binary80_t *d2, mplapack_binary80_t *d3, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *work, mplapackint const lwork, mplapack_binary80_t *result, mplapackint &info);
void Rchkst(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *ap, mplapack_binary80_t *sd, mplapack_binary80_t *se, mplapack_binary80_t *d1, mplapack_binary80_t *d2, mplapack_binary80_t *d3, mplapack_binary80_t *d4, mplapack_binary80_t *d5, mplapack_binary80_t *wa1, mplapack_binary80_t *wa2, mplapack_binary80_t *wa3, mplapack_binary80_t *wr, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *v, mplapack_binary80_t *vp, mplapack_binary80_t *tau, mplapack_binary80_t *z, mplapack_binary80_t *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, mplapack_binary80_t *result, mplapackint &info);
void Rchkst2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *ap, mplapack_binary80_t *sd, mplapack_binary80_t *se, mplapack_binary80_t *d1, mplapack_binary80_t *d2, mplapack_binary80_t *d3, mplapack_binary80_t *d4, mplapack_binary80_t *d5, mplapack_binary80_t *wa1, mplapack_binary80_t *wa2, mplapack_binary80_t *wa3, mplapack_binary80_t *wr, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *v, mplapack_binary80_t *vp, mplapack_binary80_t *tau, mplapack_binary80_t *z, mplapack_binary80_t *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, mplapack_binary80_t *result, mplapackint &info);
void Rckcsd(mplapackint const nm, mplapackint *mval, mplapackint *pval, mplapackint *qval, mplapackint const nmats, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const mmax, mplapack_binary80_t *x, mplapack_binary80_t *xf, mplapack_binary80_t *u1, mplapack_binary80_t *u2, mplapack_binary80_t *v1t, mplapack_binary80_t *v2t, mplapack_binary80_t *theta, mplapackint *iwork, mplapack_binary80_t *work, mplapack_binary80_t *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Rckglm(mplapackint const nn, mplapackint *mval, mplapackint *pval, mplapackint *nval, mplapackint const nmats, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nmax, mplapack_binary80_t *a, mplapack_binary80_t *af, mplapack_binary80_t *b, mplapack_binary80_t *bf, mplapack_binary80_t *x, mplapack_binary80_t *work, mplapack_binary80_t *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Rckgqr(mplapackint const nm, mplapackint *mval, mplapackint const np, mplapackint *pval, mplapackint const nn, mplapackint *nval, mplapackint const nmats, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nmax, mplapack_binary80_t *a, mplapack_binary80_t *af, mplapack_binary80_t *aq, mplapack_binary80_t *ar, mplapack_binary80_t *taua, mplapack_binary80_t *b, mplapack_binary80_t *bf, mplapack_binary80_t *bz, mplapack_binary80_t *bt, mplapack_binary80_t *bwk, mplapack_binary80_t *taub, mplapack_binary80_t *work, mplapack_binary80_t *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Rckgsv(mplapackint const nm, mplapackint *mval, mplapackint *pval, mplapackint *nval, mplapackint const nmats, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nmax, mplapack_binary80_t *a, mplapack_binary80_t *af, mplapack_binary80_t *b, mplapack_binary80_t *bf, mplapack_binary80_t *u, mplapack_binary80_t *v, mplapack_binary80_t *q, mplapack_binary80_t *alpha, mplapack_binary80_t *beta, mplapack_binary80_t *r, mplapackint *iwork, mplapack_binary80_t *work, mplapack_binary80_t *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Rcklse(mplapackint const nn, mplapackint *mval, mplapackint *pval, mplapackint *nval, mplapackint const nmats, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nmax, mplapack_binary80_t *a, mplapack_binary80_t *af, mplapack_binary80_t *b, mplapack_binary80_t *bf, mplapack_binary80_t *x, mplapack_binary80_t *work, mplapack_binary80_t *rwork, mplapackint const nin, mplapackint const nout, mplapackint &info);
void Rcsdts(mplapackint const m, mplapackint const p, mplapackint const q, mplapack_binary80_t *x, mplapack_binary80_t *xf, mplapackint const ldx, mplapack_binary80_t *u1, mplapackint const ldu1, mplapack_binary80_t *u2, mplapackint const ldu2, mplapack_binary80_t *v1t, mplapackint const ldv1t, mplapack_binary80_t *v2t, mplapackint const ldv2t, mplapack_binary80_t *theta, mplapackint *iwork, mplapack_binary80_t *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t *result);
void Rdrges(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *b, mplapack_binary80_t *s, mplapack_binary80_t *t, mplapack_binary80_t *q, mplapackint const ldq, mplapack_binary80_t *z, mplapack_binary80_t *alphar, mplapack_binary80_t *alphai, mplapack_binary80_t *beta, mplapack_binary80_t *work, mplapackint const lwork, mplapack_binary80_t *result, bool *bwork, mplapackint &info);
void Rdrges3(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *b, mplapack_binary80_t *s, mplapack_binary80_t *t, mplapack_binary80_t *q, mplapackint const ldq, mplapack_binary80_t *z, mplapack_binary80_t *alphar, mplapack_binary80_t *alphai, mplapack_binary80_t *beta, mplapack_binary80_t *work, mplapackint const lwork, mplapack_binary80_t *result, bool *bwork, mplapackint &info);
void Rdrgev(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *b, mplapack_binary80_t *s, mplapack_binary80_t *t, mplapack_binary80_t *q, mplapackint const ldq, mplapack_binary80_t *z, mplapack_binary80_t *qe, mplapackint const ldqe, mplapack_binary80_t *alphar, mplapack_binary80_t *alphai, mplapack_binary80_t *beta, mplapack_binary80_t *alphr1, mplapack_binary80_t *alphi1, mplapack_binary80_t *beta1, mplapack_binary80_t *work, mplapackint const lwork, mplapack_binary80_t *result, mplapackint &info);
void Rdrgev3(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *b, mplapack_binary80_t *s, mplapack_binary80_t *t, mplapack_binary80_t *q, mplapackint const ldq, mplapack_binary80_t *z, mplapack_binary80_t *qe, mplapackint const ldqe, mplapack_binary80_t *alphar, mplapack_binary80_t *alphai, mplapack_binary80_t *beta, mplapack_binary80_t *alphr1, mplapack_binary80_t *alphi1, mplapack_binary80_t *beta1, mplapack_binary80_t *work, mplapackint const lwork, mplapack_binary80_t *result, mplapackint &info);
void Rdrgsx(mplapackint const nsize, mplapackint const ncmax, mplapack_binary80_t const thresh, mplapackint const nin, mplapackint const nout, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *b, mplapack_binary80_t *ai, mplapack_binary80_t *bi, mplapack_binary80_t *z, mplapack_binary80_t *q, mplapack_binary80_t *alphar, mplapack_binary80_t *alphai, mplapack_binary80_t *beta, mplapack_binary80_t *c, mplapackint const ldc, mplapack_binary80_t *s, mplapack_binary80_t *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, bool *bwork, mplapackint &info);
void Rdrgvx(mplapackint const nsize, mplapack_binary80_t const thresh, mplapackint const nin, mplapackint const nout, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *b, mplapack_binary80_t *ai, mplapack_binary80_t *bi, mplapack_binary80_t *alphar, mplapack_binary80_t *alphai, mplapack_binary80_t *beta, mplapack_binary80_t *vl, mplapack_binary80_t *vr, mplapackint &ilo, mplapackint &ihi, mplapack_binary80_t *lscale, mplapack_binary80_t *rscale, mplapack_binary80_t *s, mplapack_binary80_t *dtru, mplapack_binary80_t *dif, mplapack_binary80_t *diftru, mplapack_binary80_t *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, mplapack_binary80_t *result, bool *bwork, mplapackint &info);
void Rdrvbd(mplapackint const nsizes, mplapackint *mm, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *vt, mplapackint const ldvt, mplapack_binary80_t *asav, mplapack_binary80_t *usav, mplapack_binary80_t *vtsav, mplapack_binary80_t *s, mplapack_binary80_t *ssav, mplapack_binary80_t *e, mplapack_binary80_t *work, mplapackint const lwork, mplapackint *iwork, mplapackint const nout, mplapackint &info);
void Rdrves(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *h, mplapack_binary80_t *ht, mplapack_binary80_t *wr, mplapack_binary80_t *wi, mplapack_binary80_t *wrt, mplapack_binary80_t *wit, mplapack_binary80_t *vs, mplapackint const ldvs, mplapack_binary80_t *result, mplapack_binary80_t *work, mplapackint const nwork, mplapackint *iwork, bool *bwork, mplapackint &info);
void Rdrvev(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *h, mplapack_binary80_t *wr, mplapack_binary80_t *wi, mplapack_binary80_t *wr1, mplapack_binary80_t *wi1, mplapack_binary80_t *vl, mplapackint const ldvl, mplapack_binary80_t *vr, mplapackint const ldvr, mplapack_binary80_t *lre, mplapackint const ldlre, mplapack_binary80_t *result, mplapack_binary80_t *work, mplapackint const nwork, mplapackint *iwork, mplapackint &info);
void Rdrvsg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *b, mplapackint const ldb, mplapack_binary80_t *d, mplapack_binary80_t *z, mplapackint const ldz, mplapack_binary80_t *ab, mplapack_binary80_t *bb, mplapack_binary80_t *ap, mplapack_binary80_t *bp, mplapack_binary80_t *work, mplapackint const nwork, mplapackint *iwork, mplapackint const liwork, mplapack_binary80_t *result, mplapackint &info);
void Rdrvsg2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *b, mplapackint const ldb, mplapack_binary80_t *d, mplapack_binary80_t *d2, mplapack_binary80_t *z, mplapackint const ldz, mplapack_binary80_t *ab, mplapack_binary80_t *bb, mplapack_binary80_t *ap, mplapack_binary80_t *bp, mplapack_binary80_t *work, mplapackint const nwork, mplapackint *iwork, mplapackint const liwork, mplapack_binary80_t *result, mplapackint &info);
void Rdrvst(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *d1, mplapack_binary80_t *d2, mplapack_binary80_t *d3, mplapack_binary80_t *d4, mplapack_binary80_t *eveigs, mplapack_binary80_t *wa1, mplapack_binary80_t *wa2, mplapack_binary80_t *wa3, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *v, mplapack_binary80_t *tau, mplapack_binary80_t *z, mplapack_binary80_t *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, mplapack_binary80_t *result, mplapackint &info);
void Rdrvst2stg(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const nounit, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *d1, mplapack_binary80_t *d2, mplapack_binary80_t *d3, mplapack_binary80_t *d4, mplapack_binary80_t *eveigs, mplapack_binary80_t *wa1, mplapack_binary80_t *wa2, mplapack_binary80_t *wa3, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *v, mplapack_binary80_t *tau, mplapack_binary80_t *z, mplapack_binary80_t *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, mplapack_binary80_t *result, mplapackint &info);
void Rdrvsx(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const niunit, mplapackint const nounit, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *h, mplapack_binary80_t *ht, mplapack_binary80_t *wr, mplapack_binary80_t *wi, mplapack_binary80_t *wrt, mplapack_binary80_t *wit, mplapack_binary80_t *wrtmp, mplapack_binary80_t *witmp, mplapack_binary80_t *vs, mplapackint const ldvs, mplapack_binary80_t *vs1, mplapack_binary80_t *result, mplapack_binary80_t *work, mplapackint const lwork, mplapackint *iwork, bool *bwork, mplapackint &info);
void Rdrvvx(mplapackint const nsizes, mplapackint *nn, mplapackint const ntypes, bool *dotype, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const niunit, mplapackint const nounit, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *h, mplapack_binary80_t *wr, mplapack_binary80_t *wi, mplapack_binary80_t *wr1, mplapack_binary80_t *wi1, mplapack_binary80_t *vl, mplapackint const ldvl, mplapack_binary80_t *vr, mplapackint const ldvr, mplapack_binary80_t *lre, mplapackint const ldlre, mplapack_binary80_t *rcondv, mplapack_binary80_t *rcndv1, mplapack_binary80_t *rcdvin, mplapack_binary80_t *rconde, mplapack_binary80_t *rcnde1, mplapack_binary80_t *rcdein, mplapack_binary80_t *scale, mplapack_binary80_t *scale1, mplapack_binary80_t *result, mplapack_binary80_t *work, mplapackint const nwork, mplapackint *iwork, mplapackint &info);
void Rerrbd(fem::str_cref path, mplapackint const nunit);
void Rerrec(fem::str_cref path, mplapackint const nunit);
void Rerred(fem::str_cref path, mplapackint const nunit);
void Rerrgg(fem::str_cref path, mplapackint const nunit);
void Rerrhs(fem::str_cref path, mplapackint const nunit);
void Rerrst(fem::str_cref path, mplapackint const nunit);
void Rget02(fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const nrhs, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *x, mplapackint const ldx, mplapack_binary80_t *b, mplapackint const ldb, mplapack_binary80_t *rwork, mplapack_binary80_t &resid);
void Rget10(mplapackint const m, mplapackint const n, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *b, mplapackint const ldb, mplapack_binary80_t *work, mplapack_binary80_t &result);
void Rget22(fem::str_cref transa, fem::str_cref transe, fem::str_cref transw, mplapackint const n, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *e, mplapackint const lde, mplapack_binary80_t *wr, mplapack_binary80_t *wi, mplapack_binary80_t *work, mplapack_binary80_t *result);
void Rget23(bool const comp, fem::str_cref balanc, mplapackint const jtype, mplapack_binary80_t const thresh, mplapackint (&iseed)[4], mplapackint const nounit, mplapackint const n, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *h, mplapack_binary80_t *wr, mplapack_binary80_t *wi, mplapack_binary80_t *wr1, mplapack_binary80_t *wi1, mplapack_binary80_t *vl, mplapackint const ldvl, mplapack_binary80_t *vr, mplapackint const ldvr, mplapack_binary80_t *lre, mplapackint const ldlre, mplapack_binary80_t *rcondv, mplapack_binary80_t *rcndv1, mplapack_binary80_t *rcdvin, mplapack_binary80_t *rconde, mplapack_binary80_t *rcnde1, mplapack_binary80_t *rcdein, mplapack_binary80_t *scale, mplapack_binary80_t *scale1, mplapack_binary80_t *result, mplapack_binary80_t *work, mplapackint const lwork, mplapackint *iwork, mplapackint &info);
void Rget24(bool const comp, mplapackint const jtype, mplapack_binary80_t const thresh, mplapackint (&iseed)[4], mplapackint const nounit, mplapackint const n, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *h, mplapack_binary80_t *ht, mplapack_binary80_t *wr, mplapack_binary80_t *wi, mplapack_binary80_t *wrt, mplapack_binary80_t *wit, mplapack_binary80_t *wrtmp, mplapack_binary80_t *witmp, mplapack_binary80_t *vs, mplapackint const ldvs, mplapack_binary80_t *vs1, mplapack_binary80_t const rcdein, mplapack_binary80_t const rcdvin, mplapackint const nslct, mplapackint *islct, mplapack_binary80_t *result, mplapack_binary80_t *work, mplapackint const lwork, mplapackint *iwork, bool *bwork, mplapackint &info);
void Rget31(mplapack_binary80_t &rmax, mplapackint &lmax, mplapackint *ninfo, mplapackint &knt);
void Rget32(mplapack_binary80_t &rmax, mplapackint &lmax, mplapackint &ninfo, mplapackint &knt);
void Rget33(mplapack_binary80_t &rmax, mplapackint &lmax, mplapackint &ninfo, mplapackint &knt);
void Rget34(mplapack_binary80_t &rmax, mplapackint &lmax, mplapackint *ninfo, mplapackint &knt);
void Rget35(mplapack_binary80_t &rmax, mplapackint &lmax, mplapackint &ninfo, mplapackint &knt);
void Rget36(mplapack_binary80_t &rmax, mplapackint &lmax, mplapackint *ninfo, mplapackint &knt, mplapackint const nin);
void Rget37(mplapack_binary80_t *rmax, mplapackint *lmax, mplapackint *ninfo, mplapackint &knt, mplapackint const nin);
void Rget38(mplapack_binary80_t *rmax, mplapackint *lmax, mplapackint *ninfo, mplapackint &knt, mplapackint const nin);
void Rget39(mplapack_binary80_t &rmax, mplapackint &lmax, mplapackint &ninfo, mplapackint &knt);
void Rget40(mplapack_binary80_t &rmax, mplapackint &lmax, mplapackint *ninfo, mplapackint &knt, mplapackint const nin);
void Rget51(mplapackint const itype, mplapackint const n, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *b, mplapackint const ldb, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *v, mplapackint const ldv, mplapack_binary80_t *work, mplapack_binary80_t &result);
void Rget52(bool const left, mplapackint const n, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *b, mplapackint const ldb, mplapack_binary80_t *e, mplapackint const lde, mplapack_binary80_t *alphar, mplapack_binary80_t *alphai, mplapack_binary80_t *beta, mplapack_binary80_t *work, mplapack_binary80_t *result);
void Rget53(mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *b, mplapackint const ldb, mplapack_binary80_t const scale, mplapack_binary80_t const wr, mplapack_binary80_t const wi, mplapack_binary80_t &result, mplapackint &info);
void Rget54(mplapackint const n, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *b, mplapackint const ldb, mplapack_binary80_t *s, mplapackint const lds, mplapack_binary80_t *t, mplapackint const ldt, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *v, mplapackint const ldv, mplapack_binary80_t *work, mplapack_binary80_t &result);
void Rglmts(mplapackint const n, mplapackint const m, mplapackint const p, mplapack_binary80_t *a, mplapack_binary80_t *af, mplapackint const lda, mplapack_binary80_t *b, mplapack_binary80_t *bf, mplapackint const ldb, mplapack_binary80_t *d, mplapack_binary80_t *df, mplapack_binary80_t *x, mplapack_binary80_t *u, mplapack_binary80_t *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t &result);
void Rgqrts(mplapackint const n, mplapackint const m, mplapackint const p, mplapack_binary80_t *a, mplapack_binary80_t *af, mplapack_binary80_t *q, mplapack_binary80_t *r, mplapackint const lda, mplapack_binary80_t *taua, mplapack_binary80_t *b, mplapack_binary80_t *bf, mplapack_binary80_t *z, mplapack_binary80_t *t, mplapack_binary80_t *bwk, mplapackint const ldb, mplapack_binary80_t *taub, mplapack_binary80_t *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t *result);
void Rgrqts(mplapackint const m, mplapackint const p, mplapackint const n, mplapack_binary80_t *a, mplapack_binary80_t *af, mplapack_binary80_t *q, mplapack_binary80_t *r, mplapackint const lda, mplapack_binary80_t *taua, mplapack_binary80_t *b, mplapack_binary80_t *bf, mplapack_binary80_t *z, mplapack_binary80_t *t, mplapack_binary80_t *bwk, mplapackint const ldb, mplapack_binary80_t *taub, mplapack_binary80_t *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t *result);
void Rgsvts3(mplapackint const m, mplapackint const p, mplapackint const n, mplapack_binary80_t *a, mplapack_binary80_t *af, mplapackint const lda, mplapack_binary80_t *b, mplapack_binary80_t *bf, mplapackint const ldb, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *v, mplapackint const ldv, mplapack_binary80_t *q, mplapackint const ldq, mplapack_binary80_t *alpha, mplapack_binary80_t *beta, mplapack_binary80_t *r, mplapackint const ldr, mplapackint *iwork, mplapack_binary80_t *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t *result);
void Rhst01(mplapackint const n, mplapackint const, mplapackint const, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *h, mplapackint const ldh, mplapack_binary80_t *q, mplapackint const ldq, mplapack_binary80_t *work, mplapackint const lwork, mplapack_binary80_t *result);
void Rlacsg(mplapackint const m, mplapackint const p, mplapackint const q, mplapack_binary80_t *theta, mplapackint (&iseed)[4], mplapack_binary80_t *x, mplapackint const ldx, mplapack_binary80_t *work);
void Rlafts(fem::str_cref type, mplapackint const m, mplapackint const n, mplapackint const imat, mplapackint const ntests, mplapack_binary80_t *result, mplapackint (&iseed)[4], mplapack_binary80_t const thresh, mplapackint const iounit, mplapackint &ie);
void Rlahd2(mplapackint const iounit, fem::str_cref path);
void Rlarfy(fem::str_cref uplo, mplapackint const n, mplapack_binary80_t *v, mplapackint const incv, mplapack_binary80_t const tau, mplapack_binary80_t *c, mplapackint const ldc, mplapack_binary80_t *work);
void Rlarhs(fem::str_cref path, fem::str_cref xtype, fem::str_cref uplo, fem::str_cref trans, mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, mplapackint const nrhs, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *x, mplapackint const ldx, mplapack_binary80_t *b, mplapackint const ldb, mplapackint (&iseed)[4], mplapackint &info);
void Rlasum(fem::str_cref type, mplapackint const iounit, mplapackint const ie, mplapackint const nrun);
void Rlatb9(fem::str_cref path, mplapackint const imat, mplapackint const m, mplapackint const p, mplapackint const n, fem::str_ref type, mplapackint &kla, mplapackint &kua, mplapackint &klb, mplapackint &kub, mplapack_binary80_t &anorm, mplapack_binary80_t &bnorm, mplapackint &modea, mplapackint &modeb, mplapack_binary80_t &cndnma, mplapack_binary80_t &cndnmb, fem::str_ref dista, fem::str_ref distb);
void Rlatm4(mplapackint const itype, mplapackint const n, mplapackint const nz1, mplapackint const nz2, mplapackint const isign, mplapack_binary80_t const amagn, mplapack_binary80_t const rcond, mplapack_binary80_t const triang, mplapackint const idist, mplapackint (&iseed)[4], mplapack_binary80_t *a, mplapackint const lda);
void Rlsets(mplapackint const m, mplapackint const p, mplapackint const n, mplapack_binary80_t *a, mplapack_binary80_t *af, mplapackint const lda, mplapack_binary80_t *b, mplapack_binary80_t *bf, mplapackint const ldb, mplapack_binary80_t *c, mplapack_binary80_t *cf, mplapack_binary80_t *d, mplapack_binary80_t *df, mplapack_binary80_t *x, mplapack_binary80_t *work, mplapackint const lwork, mplapack_binary80_t *rwork, mplapack_binary80_t *result);
void Rort01(fem::str_cref rowcol, mplapackint const m, mplapackint const n, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *work, mplapackint const lwork, mplapack_binary80_t &resid);
void Rort03(fem::str_cref rc, mplapackint const mu, mplapackint const mv, mplapackint const n, mplapackint const k, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *v, mplapackint const ldv, mplapack_binary80_t *work, mplapackint const lwork, mplapack_binary80_t &result, mplapackint &info);
void Rsbt21(fem::str_cref uplo, mplapackint const n, mplapackint const ka, mplapackint const ks, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *d, mplapack_binary80_t *e, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *work, mplapack_binary80_t *result);
void Rsgt01(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const m, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *b, mplapackint const ldb, mplapack_binary80_t *z, mplapackint const ldz, mplapack_binary80_t *d, mplapack_binary80_t *work, mplapack_binary80_t *result);
void Rspt21(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const kband, mplapack_binary80_t *ap, mplapack_binary80_t *d, mplapack_binary80_t *e, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *vp, mplapack_binary80_t *tau, mplapack_binary80_t *work, mplapack_binary80_t *result);
void Rstech(mplapackint const n, mplapack_binary80_t *a, mplapack_binary80_t *b, mplapack_binary80_t *eig, mplapack_binary80_t const tol, mplapack_binary80_t *work, mplapackint &info);
void Rstect(mplapackint const n, mplapack_binary80_t *a, mplapack_binary80_t *b, mplapack_binary80_t const shift, mplapackint &num);
void Rstt21(mplapackint const n, mplapackint const kband, mplapack_binary80_t *ad, mplapack_binary80_t *ae, mplapack_binary80_t *sd, mplapack_binary80_t *se, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *work, mplapack_binary80_t *result);
void Rstt22(mplapackint const n, mplapackint const m, mplapackint const kband, mplapack_binary80_t *ad, mplapack_binary80_t *ae, mplapack_binary80_t *sd, mplapack_binary80_t *se, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *work, mplapackint const ldwork, mplapack_binary80_t *result);
void Rsvdch(mplapackint const n, mplapack_binary80_t *s, mplapack_binary80_t *e, mplapack_binary80_t *svd, mplapack_binary80_t const tol, mplapackint &info);
void Rsvdct(mplapackint const n, mplapack_binary80_t *s, mplapack_binary80_t *e, mplapack_binary80_t const shift, mplapackint &num);
void Rsyl01(mplapack_binary80_t const thresh, mplapackint *nfail, mplapack_binary80_t *rmax, mplapackint *ninfo, mplapackint &knt);
void Rsyt21(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const kband, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *d, mplapack_binary80_t *e, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *v, mplapackint const ldv, mplapack_binary80_t *tau, mplapack_binary80_t *work, mplapack_binary80_t *result);
void Rsyt22(mplapackint const itype, fem::str_cref uplo, mplapackint const n, mplapackint const m, mplapackint const kband, mplapack_binary80_t *a, mplapackint const lda, mplapack_binary80_t *d, mplapack_binary80_t *e, mplapack_binary80_t *u, mplapackint const ldu, mplapack_binary80_t *, mplapackint const ldv, mplapack_binary80_t *, mplapack_binary80_t *work, mplapack_binary80_t *result);
#endif
