/*
 * Copyright (c) 2008-2021
 *	Nakata, Maho
 * 	All rights reserved.
 *
 * $Id: mplapack_qd.h,v 1.31 2010/08/07 03:15:46 nakatamaho Exp $
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 */

#ifndef _MPLAPACK_QD_H_
#define _MPLAPACK_QD_H_

#include "mplapack_config.h"
#include <qd/qd_real.h>
#include "qd_complex.h"

bool Risnan(qd_real const din);
bool Rlaisnan(qd_real const din1, qd_real const din2);
mplapackint Rlaneg(mplapackint const n, qd_real *d, qd_real *lld, qd_real const sigma, qd_real const, mplapackint const r);
mplapackint iCmax1(mplapackint const n, qd_complex *zx, mplapackint const incx);
mplapackint iMladlc(mplapackint const m, mplapackint const n, qd_real *a, mplapackint const lda);
mplapackint iMladlr(mplapackint const m, mplapackint const n, qd_real *a, mplapackint const lda);
mplapackint iMlaenv_qd(mplapackint ispec, const char *name, const char *opts, mplapackint n1, mplapackint n2, mplapackint n3, mplapackint n4);
mplapackint iMlazlc(mplapackint const m, mplapackint const n, qd_complex *a, mplapackint const lda);
mplapackint iMlazlr(mplapackint const m, mplapackint const n, qd_complex *a, mplapackint const lda);
qd_complex Cladiv(qd_complex const x, qd_complex const y);
qd_real Clangt(const char *norm, mplapackint const n, qd_complex *dl, qd_complex *d, qd_complex *du);
qd_real Clanhe(const char *norm, const char *uplo, mplapackint const n, qd_complex *a, mplapackint const lda, qd_real *work);
qd_real Clanht(const char *norm, mplapackint const n, qd_real *d, qd_complex *e);
qd_real Clansy(const char *norm, const char *uplo, mplapackint const n, qd_complex *a, mplapackint const lda, qd_real *work);
qd_real RCsum1(mplapackint const n, qd_complex *cx, mplapackint const incx);
qd_real Rla_gerpvgrw(mplapackint const n, mplapackint const ncols, qd_real *a, mplapackint const lda, qd_real *af, mplapackint const ldaf);
qd_real Rladiv2(qd_real const &a, qd_real const &b, qd_real const &c, qd_real const &d, qd_real const &r, qd_real const &t);
qd_real Rladiv2(qd_real const &a, qd_real const &b, qd_real const &c, qd_real const &d, qd_real const &r, qd_real const &t);
qd_real Rlamch_qd(const char *cmach);
qd_real Rlangt(const char *norm, mplapackint const n, qd_real *dl, qd_real *d, qd_real *du);
qd_real Rlanst(const char *norm, mplapackint const n, qd_real *d, qd_real *e);
qd_real Rlansy(const char *norm, const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *work);
qd_real Rlapy2(qd_real const x, qd_real const y);
qd_real Rlapy3(qd_real const x, qd_real const y, qd_real const z);
qd_real abs1(qd_complex ff);
qd_real abs1(qd_complex ff);
qd_real abs1(qd_complex ff);
qd_real abssq(qd_complex ff);
qd_real abssq(qd_complex ff);
void CRrscl(mplapackint const n, qd_real const sa, qd_complex *sx, mplapackint const incx);
void Cgebak(const char *job, const char *side, mplapackint const n, mplapackint const ilo, mplapackint const ihi, qd_real *scale, mplapackint const m, qd_complex *v, mplapackint const ldv, mplapackint &info);
void Cgelq(mplapackint const m, mplapackint const n, qd_complex *a, mplapackint const lda, qd_complex *t, mplapackint const tsize, qd_complex *work, mplapackint const lwork, mplapackint &info);
void Cgelqt(mplapackint const m, mplapackint const n, mplapackint const mb, qd_complex *a, mplapackint const lda, qd_complex *t, mplapackint const ldt, qd_complex *work, mplapackint &info);
void Cgemlqt(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const mb, qd_complex *v, mplapackint const ldv, qd_complex *t, mplapackint const ldt, qd_complex *c, mplapackint const ldc, qd_complex *work, mplapackint &info);
void Cgemqrt(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const nb, qd_complex *v, mplapackint const ldv, qd_complex *t, mplapackint const ldt, qd_complex *c, mplapackint const ldc, qd_complex *work, mplapackint &info);
void Cgeqr(mplapackint const m, mplapackint const n, qd_complex *a, mplapackint const lda, qd_complex *t, mplapackint const tsize, qd_complex *work, mplapackint const lwork, mplapackint &info);
void Cgeqrt(mplapackint const m, mplapackint const n, mplapackint const nb, qd_complex *a, mplapackint const lda, qd_complex *t, mplapackint const ldt, qd_complex *work, mplapackint &info);
void Cgesv(mplapackint const n, mplapackint const nrhs, qd_complex *a, mplapackint const lda, mplapackint *ipiv, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Cgetc2(mplapackint const n, qd_complex *a, mplapackint const lda, mplapackint *ipiv, mplapackint *jpiv, mplapackint &info);
void Cgetf2(mplapackint const m, mplapackint const n, qd_complex *a, mplapackint const lda, mplapackint *ipiv, mplapackint &info);
void Cgetrf(mplapackint const m, mplapackint const n, qd_complex *a, mplapackint const lda, mplapackint *ipiv, mplapackint &info);
void Cgetrf2(mplapackint const m, mplapackint const n, qd_complex *a, mplapackint const lda, mplapackint *ipiv, mplapackint &info);
void Cgetri(mplapackint const n, qd_complex *a, mplapackint const lda, mplapackint *ipiv, qd_complex *work, mplapackint const lwork, mplapackint &info);
void Cgetrs(const char *trans, mplapackint const n, mplapackint const nrhs, qd_complex *a, mplapackint const lda, mplapackint *ipiv, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Cggbak(const char *job, const char *side, mplapackint const n, mplapackint const ilo, mplapackint const ihi, qd_real *lscale, qd_real *rscale, mplapackint const m, qd_complex *v, mplapackint const ldv, mplapackint &info);
void Cgtts2(mplapackint const itrans, mplapackint const n, mplapackint const nrhs, qd_complex *dl, qd_complex *d, qd_complex *du, qd_complex *du2, mplapackint *ipiv, qd_complex *b, mplapackint const ldb);
void Cheev(const char *jobz, const char *uplo, mplapackint const n, qd_complex *a, mplapackint const lda, qd_real *w, qd_complex *work, mplapackint const lwork, qd_real *rwork, mplapackint &info);
void Chegst(mplapackint const itype, const char *uplo, mplapackint const n, qd_complex *a, mplapackint const lda, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Chesv(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_complex *a, mplapackint const lda, mplapackint *ipiv, qd_complex *b, mplapackint const ldb, qd_complex *work, mplapackint const lwork, mplapackint &info);
void Chesv_rook(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_complex *a, mplapackint const lda, mplapackint *ipiv, qd_complex *b, mplapackint const ldb, qd_complex *work, mplapackint const lwork, mplapackint &info);
void Chetd2(const char *uplo, mplapackint const n, qd_complex *a, mplapackint const lda, qd_real *d, qd_real *e, qd_complex *tau, mplapackint &info);
void Chetrd(const char *uplo, mplapackint const n, qd_complex *a, mplapackint const lda, qd_real *d, qd_real *e, qd_complex *tau, qd_complex *work, mplapackint const lwork, mplapackint &info);
void Chetri(const char *uplo, mplapackint const n, qd_complex *a, mplapackint const lda, mplapackint *ipiv, qd_complex *work, mplapackint &info);
void Chetri2(const char *uplo, mplapackint const n, qd_complex *a, mplapackint const lda, mplapackint *ipiv, qd_complex *work, mplapackint const lwork, mplapackint &info);
void Chetri_3(const char *uplo, mplapackint const n, qd_complex *a, mplapackint const lda, qd_complex *e, mplapackint *ipiv, qd_complex *work, mplapackint const lwork, mplapackint &info);
void Chetri_rook(const char *uplo, mplapackint const n, qd_complex *a, mplapackint const lda, mplapackint *ipiv, qd_complex *work, mplapackint &info);
void Chetrs(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_complex *a, mplapackint const lda, mplapackint *ipiv, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Chetrs2(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_complex *a, mplapackint const lda, mplapackint *ipiv, qd_complex *b, mplapackint const ldb, qd_complex *work, mplapackint &info);
void Chetrs_3(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_complex *a, mplapackint const lda, qd_complex *e, mplapackint *ipiv, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Chetrs_aa(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_complex *a, mplapackint const lda, mplapackint *ipiv, qd_complex *b, mplapackint const ldb, qd_complex *work, mplapackint const lwork, mplapackint &info);
void Chetrs_rook(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_complex *a, mplapackint const lda, mplapackint *ipiv, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Chfrk(const char *transr, const char *uplo, const char *trans, mplapackint const n, mplapackint const k, qd_real const alpha, qd_complex *a, mplapackint const lda, qd_real const beta, qd_complex *c);
void Chpsv(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_complex *ap, mplapackint *ipiv, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Cla_wwaddw(mplapackint const n, qd_complex *x, qd_complex *y, qd_complex *w);
void Clacgv(mplapackint const n, qd_complex *x, mplapackint const incx);
void Clacp2(const char *uplo, mplapackint const m, mplapackint const n, qd_real *a, mplapackint const lda, qd_complex *b, mplapackint const ldb);
void Clacpy(const char *uplo, mplapackint const m, mplapackint const n, qd_complex *a, mplapackint const lda, qd_complex *b, mplapackint const ldb);
void Clacrm(mplapackint const m, mplapackint const n, qd_complex *a, mplapackint const lda, qd_real *b, mplapackint const ldb, qd_complex *c, mplapackint const ldc, qd_real *rwork);
void Clacrt(mplapackint const n, qd_complex *cx, mplapackint const incx, qd_complex *cy, mplapackint const incy, qd_complex const c, qd_complex const s);
void Claesy(qd_complex const a, qd_complex const b, qd_complex const c, qd_complex &rt1, qd_complex &rt2, qd_complex &evscal, qd_complex &cs1, qd_complex &sn1);
void Claev2(qd_complex const a, qd_complex const b, qd_complex const c, qd_real &rt1, qd_real &rt2, qd_real &cs1, qd_complex &sn1);
void Clagtm(const char *trans, mplapackint const n, mplapackint const nrhs, qd_real const alpha, qd_complex *dl, qd_complex *d, qd_complex *du, qd_complex *x, mplapackint const ldx, qd_real const beta, qd_complex *b, mplapackint const ldb);
void Clahef(const char *uplo, mplapackint const n, mplapackint const nb, mplapackint &kb, qd_complex *a, mplapackint const lda, mplapackint *ipiv, qd_complex *w, mplapackint const ldw, mplapackint &info);
void Clapmr(bool const forwrd, mplapackint const m, mplapackint const n, qd_complex *x, mplapackint const ldx, mplapackint *k);
void Clapmt(bool const forwrd, mplapackint const m, mplapackint const n, qd_complex *x, mplapackint const ldx, mplapackint *k);
void Claqgb(mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, qd_complex *ab, mplapackint const ldab, qd_real *r, qd_real *c, qd_real const rowcnd, qd_real const colcnd, qd_real const amax, char *equed);
void Claqge(mplapackint const m, mplapackint const n, qd_complex *a, mplapackint const lda, qd_real *r, qd_real *c, qd_real const rowcnd, qd_real const colcnd, qd_real const amax, char *equed);
void Claqhb(const char *uplo, mplapackint const n, mplapackint const kd, qd_complex *ab, mplapackint const ldab, qd_real *s, qd_real const scond, qd_real const amax, char *equed);
void Claqhe(const char *uplo, mplapackint const n, qd_complex *a, mplapackint const lda, qd_real *s, qd_real const scond, qd_real const amax, char *equed);
void Claqhp(const char *uplo, mplapackint const n, qd_complex *ap, qd_real *s, qd_real const scond, qd_real const amax, char *equed);
void Claqsb(const char *uplo, mplapackint const n, mplapackint const kd, qd_complex *ab, mplapackint const ldab, qd_real *s, qd_real const scond, qd_real const amax, char *equed);
void Claqsp(const char *uplo, mplapackint const n, qd_complex *ap, qd_real *s, qd_real const scond, qd_real const amax, char *equed);
void Claqsy(const char *uplo, mplapackint const n, qd_complex *a, mplapackint const lda, qd_real *s, qd_real const scond, qd_real const amax, char *equed);
void Clar2v(mplapackint const n, qd_complex *x, qd_complex *y, qd_complex *z, mplapackint const incx, qd_real *c, qd_complex *s, mplapackint const incc);
void Clarf(const char *side, mplapackint const m, mplapackint const n, qd_complex *v, mplapackint const incv, qd_complex const tau, qd_complex *c, mplapackint const ldc, qd_complex *work);
void Clarfb(const char *side, const char *trans, const char *direct, const char *storev, mplapackint const m, mplapackint const n, mplapackint const k, qd_complex *v, mplapackint const ldv, qd_complex *t, mplapackint const ldt, qd_complex *c, mplapackint const ldc, qd_complex *work, mplapackint const ldwork);
void Clarfb_gett(const char *ident, mplapackint const m, mplapackint const n, mplapackint const k, qd_complex *t, mplapackint const ldt, qd_complex *a, mplapackint const lda, qd_complex *b, mplapackint const ldb, qd_complex *work, mplapackint const ldwork);
void Clarfg(mplapackint const n, qd_complex &alpha, qd_complex *x, mplapackint const incx, qd_complex &tau);
void Clarft(const char *direct, const char *storev, mplapackint const n, mplapackint const k, qd_complex *v, mplapackint const ldv, qd_complex *tau, qd_complex *t, mplapackint const ldt);
void Clarfx(const char *side, mplapackint const m, mplapackint const n, qd_complex *v, qd_complex const tau, qd_complex *c, mplapackint const ldc, qd_complex *work);
void Clarfy(const char *uplo, mplapackint const n, qd_complex *v, mplapackint const incv, qd_complex const tau, qd_complex *c, mplapackint const ldc, qd_complex *work);
void Clarscl2(mplapackint const m, mplapackint const n, qd_real *d, qd_complex *x, mplapackint const ldx);
void Clartg(qd_complex const f, qd_complex const g, qd_real &cs, qd_complex &sn, qd_complex &r);
void Clartv(mplapackint const n, qd_complex *x, mplapackint const incx, qd_complex *y, mplapackint const incy, qd_real *c, qd_complex *s, mplapackint const incc);
void Clarz(const char *side, mplapackint const m, mplapackint const n, mplapackint const l, qd_complex *v, mplapackint const incv, qd_complex const tau, qd_complex *c, mplapackint const ldc, qd_complex *work);
void Clarzt(const char *direct, const char *storev, mplapackint const n, mplapackint const k, qd_complex *v, mplapackint const ldv, qd_complex *tau, qd_complex *t, mplapackint const ldt);
void Clascl(const char *type, mplapackint const kl, mplapackint const ku, qd_real const cfrom, qd_real const cto, mplapackint const m, mplapackint const n, qd_complex *a, mplapackint const lda, mplapackint &info);
void Clascl2(mplapackint const m, mplapackint const n, qd_real *d, qd_complex *x, mplapackint const ldx);
void Claset(const char *uplo, mplapackint const m, mplapackint const n, qd_complex const alpha, qd_complex const beta, qd_complex *a, mplapackint const lda);
void Clasr(const char *side, const char *pivot, const char *direct, mplapackint const m, mplapackint const n, qd_real *c, qd_real *s, qd_complex *a, mplapackint const lda);
void Classq(mplapackint const n, qd_complex *x, mplapackint const incx, qd_real &scale, qd_real &sumsq);
void Claswlq(mplapackint const m, mplapackint const n, mplapackint const mb, mplapackint const nb, qd_complex *a, mplapackint const lda, qd_complex *t, mplapackint const ldt, qd_complex *work, mplapackint const lwork, mplapackint &info);
void Claswp(mplapackint const n, qd_complex *a, mplapackint const lda, mplapackint const k1, mplapackint const k2, mplapackint *ipiv, mplapackint const incx);
void Clasyf(const char *uplo, mplapackint const n, mplapackint const nb, mplapackint &kb, qd_complex *a, mplapackint const lda, mplapackint *ipiv, qd_complex *w, mplapackint const ldw, mplapackint &info);
void Clatrd(const char *uplo, mplapackint const n, mplapackint const nb, qd_complex *a, mplapackint const lda, qd_real *e, qd_complex *tau, qd_complex *w, mplapackint const ldw);
void Clatsqr(mplapackint const m, mplapackint const n, mplapackint const mb, mplapackint const nb, qd_complex *a, mplapackint const lda, qd_complex *t, mplapackint const ldt, qd_complex *work, mplapackint const lwork, mplapackint &info);
void Claunhr_col_getrfnp(mplapackint const m, mplapackint const n, qd_complex *a, mplapackint const lda, qd_complex *d, mplapackint &info);
void Clauum(const char *uplo, mplapackint const n, qd_complex *a, mplapackint const lda, mplapackint &info);
void Cpbequ(const char *uplo, mplapackint const n, mplapackint const kd, qd_complex *ab, mplapackint const ldab, qd_real *s, qd_real &scond, qd_real &amax, mplapackint &info);
void Cpbsv(const char *uplo, mplapackint const n, mplapackint const kd, mplapackint const nrhs, qd_complex *ab, mplapackint const ldab, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Cpbtrs(const char *uplo, mplapackint const n, mplapackint const kd, mplapackint const nrhs, qd_complex *ab, mplapackint const ldab, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Cpoequ(mplapackint const n, qd_complex *a, mplapackint const lda, qd_real *s, qd_real &scond, qd_real &amax, mplapackint &info);
void Cposv(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_complex *a, mplapackint const lda, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Cpotf2(const char *uplo, mplapackint const n, qd_complex *a, mplapackint const lda, mplapackint &info);
void Cpotrf(const char *uplo, mplapackint const n, qd_complex *a, mplapackint const lda, mplapackint &info);
void Cpotrf2(const char *uplo, mplapackint const n, qd_complex *a, mplapackint const lda, mplapackint &info);
void Cpotri(const char *uplo, mplapackint const n, qd_complex *a, mplapackint const lda, mplapackint &info);
void Cpotrs(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_complex *a, mplapackint const lda, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Cppequ(const char *uplo, mplapackint const n, qd_complex *ap, qd_real *s, qd_real &scond, qd_real &amax, mplapackint &info);
void Cppsv(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_complex *ap, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Cpptrs(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_complex *ap, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Cptcon(mplapackint const n, qd_real *d, qd_complex *e, qd_real const anorm, qd_real &rcond, qd_real *rwork, mplapackint &info);
void Cptsv(mplapackint const n, mplapackint const nrhs, qd_real *d, qd_complex *e, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Cpttrf(mplapackint const n, qd_real *d, qd_complex *e, mplapackint &info);
void Cpttrs(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_real *d, qd_complex *e, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Cptts2(mplapackint const iuplo, mplapackint const n, mplapackint const nrhs, qd_real *d, qd_complex *e, qd_complex *b, mplapackint const ldb);
void Crot(mplapackint const n, qd_complex *cx, mplapackint const incx, qd_complex *cy, mplapackint const incy, qd_real const c, qd_complex const s);
void Cspmv(const char *uplo, mplapackint const n, qd_complex const alpha, qd_complex *ap, qd_complex *x, mplapackint const incx, qd_complex const beta, qd_complex *y, mplapackint const incy);
void Cspr(const char *uplo, mplapackint const n, qd_complex const alpha, qd_complex *x, mplapackint const incx, qd_complex *ap);
void Cspsv(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_complex *ap, mplapackint *ipiv, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Csteqr(const char *compz, mplapackint const n, qd_real *d, qd_real *e, qd_complex *z, mplapackint const ldz, qd_real *work, mplapackint &info);
void Csyconv(const char *uplo, const char *way, mplapackint const n, qd_complex *a, mplapackint const lda, mplapackint *ipiv, qd_complex *e, mplapackint &info);
void Csyconvf(const char *uplo, const char *way, mplapackint const n, qd_complex *a, mplapackint const lda, qd_complex *e, mplapackint *ipiv, mplapackint &info);
void Csyconvf_rook(const char *uplo, const char *way, mplapackint const n, qd_complex *a, mplapackint const lda, qd_complex *e, mplapackint *ipiv, mplapackint &info);
void Csymv(const char *uplo, mplapackint const n, qd_complex const alpha, qd_complex *a, mplapackint const lda, qd_complex *x, mplapackint const incx, qd_complex const beta, qd_complex *y, mplapackint const incy);
void Csyr(const char *uplo, mplapackint const n, qd_complex const alpha, qd_complex *x, mplapackint const incx, qd_complex *a, mplapackint const lda);
void Csytri2(const char *uplo, mplapackint const n, qd_complex *a, mplapackint const lda, mplapackint *ipiv, qd_complex *work, mplapackint const lwork, mplapackint &info);
void Csytri_3(const char *uplo, mplapackint const n, qd_complex *a, mplapackint const lda, qd_complex *e, mplapackint *ipiv, qd_complex *work, mplapackint const lwork, mplapackint &info);
void Csytrs(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_complex *a, mplapackint const lda, mplapackint *ipiv, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Csytrs2(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_complex *a, mplapackint const lda, mplapackint *ipiv, qd_complex *b, mplapackint const ldb, qd_complex *work, mplapackint &info);
void Csytrs_3(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_complex *a, mplapackint const lda, qd_complex *e, mplapackint *ipiv, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Csytrs_aa(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_complex *a, mplapackint const lda, mplapackint *ipiv, qd_complex *b, mplapackint const ldb, qd_complex *work, mplapackint const lwork, mplapackint &info);
void Csytrs_rook(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_complex *a, mplapackint const lda, mplapackint *ipiv, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Ctbtrs(const char *uplo, const char *trans, const char *diag, mplapackint const n, mplapackint const kd, mplapackint const nrhs, qd_complex *ab, mplapackint const ldab, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Ctgexc(bool const wantq, bool const wantz, mplapackint const n, qd_complex *a, mplapackint const lda, qd_complex *b, mplapackint const ldb, qd_complex *q, mplapackint const ldq, qd_complex *z, mplapackint const ldz, mplapackint const ifst, mplapackint &ilst, mplapackint &info);
void Ctplqt(mplapackint const m, mplapackint const n, mplapackint const l, mplapackint const mb, qd_complex *a, mplapackint const lda, qd_complex *b, mplapackint const ldb, qd_complex *t, mplapackint const ldt, qd_complex *work, mplapackint &info);
void Ctpmlqt(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const l, mplapackint const mb, qd_complex *v, mplapackint const ldv, qd_complex *t, mplapackint const ldt, qd_complex *a, mplapackint const lda, qd_complex *b, mplapackint const ldb, qd_complex *work, mplapackint &info);
void Ctpmqrt(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const l, mplapackint const nb, qd_complex *v, mplapackint const ldv, qd_complex *t, mplapackint const ldt, qd_complex *a, mplapackint const lda, qd_complex *b, mplapackint const ldb, qd_complex *work, mplapackint &info);
void Ctpqrt(mplapackint const m, mplapackint const n, mplapackint const l, mplapackint const nb, qd_complex *a, mplapackint const lda, qd_complex *b, mplapackint const ldb, qd_complex *t, mplapackint const ldt, qd_complex *work, mplapackint &info);
void Ctprfb(const char *side, const char *trans, const char *direct, const char *storev, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const l, qd_complex *v, mplapackint const ldv, qd_complex *t, mplapackint const ldt, qd_complex *a, mplapackint const lda, qd_complex *b, mplapackint const ldb, qd_complex *work, mplapackint const ldwork);
void Ctptrs(const char *uplo, const char *trans, const char *diag, mplapackint const n, mplapackint const nrhs, qd_complex *ap, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Ctpttr(const char *uplo, mplapackint const n, qd_complex *ap, qd_complex *a, mplapackint const lda, mplapackint &info);
void Ctrti2(const char *uplo, const char *diag, mplapackint const n, qd_complex *a, mplapackint const lda, mplapackint &info);
void Ctrtri(const char *uplo, const char *diag, mplapackint const n, qd_complex *a, mplapackint const lda, mplapackint &info);
void Ctrtrs(const char *uplo, const char *trans, const char *diag, mplapackint const n, mplapackint const nrhs, qd_complex *a, mplapackint const lda, qd_complex *b, mplapackint const ldb, mplapackint &info);
void Ctrttp(const char *uplo, mplapackint const n, qd_complex *a, mplapackint const lda, qd_complex *ap, mplapackint &info);
void Cunbdb5(mplapackint const m1, mplapackint const m2, mplapackint const n, qd_complex *x1, mplapackint const incx1, qd_complex *x2, mplapackint const incx2, qd_complex *q1, mplapackint const ldq1, qd_complex *q2, mplapackint const ldq2, qd_complex *work, mplapackint const lwork, mplapackint &info);
void Cunbdb6(mplapackint const m1, mplapackint const m2, mplapackint const n, qd_complex *x1, mplapackint const incx1, qd_complex *x2, mplapackint const incx2, qd_complex *q1, mplapackint const ldq1, qd_complex *q2, mplapackint const ldq2, qd_complex *work, mplapackint const lwork, mplapackint &info);
void Cung2l(mplapackint const m, mplapackint const n, mplapackint const k, qd_complex *a, mplapackint const lda, qd_complex *tau, qd_complex *work, mplapackint &info);
void Cung2r(mplapackint const m, mplapackint const n, mplapackint const k, qd_complex *a, mplapackint const lda, qd_complex *tau, qd_complex *work, mplapackint &info);
void Cunghr(mplapackint const n, mplapackint const ilo, mplapackint const ihi, qd_complex *a, mplapackint const lda, qd_complex *tau, qd_complex *work, mplapackint const lwork, mplapackint &info);
void Cungl2(mplapackint const m, mplapackint const n, mplapackint const k, qd_complex *a, mplapackint const lda, qd_complex *tau, qd_complex *work, mplapackint &info);
void Cungql(mplapackint const m, mplapackint const n, mplapackint const k, qd_complex *a, mplapackint const lda, qd_complex *tau, qd_complex *work, mplapackint const lwork, mplapackint &info);
void Cungqr(mplapackint const m, mplapackint const n, mplapackint const k, qd_complex *a, mplapackint const lda, qd_complex *tau, qd_complex *work, mplapackint const lwork, mplapackint &info);
void Cungr2(mplapackint const m, mplapackint const n, mplapackint const k, qd_complex *a, mplapackint const lda, qd_complex *tau, qd_complex *work, mplapackint &info);
void Cungtr(const char *uplo, mplapackint const n, qd_complex *a, mplapackint const lda, qd_complex *tau, qd_complex *work, mplapackint const lwork, mplapackint &info);
void Cungtsqr(mplapackint const m, mplapackint const n, mplapackint const mb, mplapackint const nb, qd_complex *a, mplapackint const lda, qd_complex *t, mplapackint const ldt, qd_complex *work, mplapackint const lwork, mplapackint &info);
void Cunhr_col(mplapackint const m, mplapackint const n, mplapackint const nb, qd_complex *a, mplapackint const lda, qd_complex *t, mplapackint const ldt, qd_complex *d, mplapackint &info);
void Cunm2l(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, qd_complex *a, mplapackint const lda, qd_complex *tau, qd_complex *c, mplapackint const ldc, qd_complex *work, mplapackint &info);
void Cunm2r(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, qd_complex *a, mplapackint const lda, qd_complex *tau, qd_complex *c, mplapackint const ldc, qd_complex *work, mplapackint &info);
void Cunml2(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, qd_complex *a, mplapackint const lda, qd_complex *tau, qd_complex *c, mplapackint const ldc, qd_complex *work, mplapackint &info);
void Cunmr2(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, qd_complex *a, mplapackint const lda, qd_complex *tau, qd_complex *c, mplapackint const ldc, qd_complex *work, mplapackint &info);
void Cunmr3(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const l, qd_complex *a, mplapackint const lda, qd_complex *tau, qd_complex *c, mplapackint const ldc, qd_complex *work, mplapackint &info);
void Rbdsqr(const char *uplo, mplapackint const n, mplapackint const ncvt, mplapackint const nru, mplapackint const ncc, qd_real *d, qd_real *e, qd_real *vt, mplapackint const ldvt, qd_real *u, mplapackint const ldu, qd_real *c, mplapackint const ldc, qd_real *work, mplapackint &info);
void Rcombssq(qd_real *v1, qd_real *v2);
void Rgebak(const char *job, const char *side, mplapackint const n, mplapackint const ilo, mplapackint const ihi, qd_real *scale, mplapackint const m, qd_real *v, mplapackint const ldv, mplapackint &info);
void Rgebd2(mplapackint const m, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *d, qd_real *e, qd_real *tauq, qd_real *taup, qd_real *work, mplapackint &info);
void Rgebrd(mplapackint const m, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *d, qd_real *e, qd_real *tauq, qd_real *taup, qd_real *work, mplapackint const lwork, int &info);
void Rgelq(mplapackint const m, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *t, mplapackint const tsize, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rgelq2(mplapackint const m, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *tau, qd_real *work, mplapackint &info);
void Rgelqf(mplapackint const m, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *tau, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rgelqt(mplapackint const m, mplapackint const n, mplapackint const mb, qd_real *a, mplapackint const lda, qd_real *t, mplapackint const ldt, qd_real *work, mplapackint &info);
void Rgemlqt(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const mb, qd_real *v, mplapackint const ldv, qd_real *t, mplapackint const ldt, qd_real *c, mplapackint const ldc, qd_real *work, mplapackint &info);
void Rgemqrt(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const nb, qd_real *v, mplapackint const ldv, qd_real *t, mplapackint const ldt, qd_real *c, mplapackint const ldc, qd_real *work, mplapackint &info);
void Rgeqr(mplapackint const m, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *t, mplapackint const tsize, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rgeqr2(mplapackint const m, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *tau, qd_real *work, mplapackint &info);
void Rgeqrf(mplapackint const m, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *tau, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rgeqrt(mplapackint const m, mplapackint const n, mplapackint const nb, qd_real *a, mplapackint const lda, qd_real *t, mplapackint const ldt, qd_real *work, mplapackint &info);
void Rgesv(mplapackint const n, mplapackint const nrhs, qd_real *a, mplapackint const lda, mplapackint *ipiv, qd_real *b, mplapackint const ldb, mplapackint &info);
void Rgesvd(const char *jobu, const char *jobvt, mplapackint const m, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *s, qd_real *u, mplapackint const ldu, qd_real *vt, mplapackint const ldvt, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rgetc2(mplapackint const n, qd_real *a, mplapackint const lda, mplapackint *ipiv, mplapackint *jpiv, mplapackint &info);
void Rgetf2(mplapackint const m, mplapackint const n, qd_real *a, mplapackint const lda, mplapackint *ipiv, mplapackint &info);
void Rgetrf(mplapackint const m, mplapackint const n, qd_real *a, mplapackint const lda, mplapackint *ipiv, mplapackint &info);
void Rgetrf2(mplapackint const m, mplapackint const n, qd_real *a, mplapackint const lda, mplapackint *ipiv, mplapackint &info);
void Rgetri(mplapackint const n, qd_real *a, mplapackint const lda, mplapackint *ipiv, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rgetrs(const char *trans, mplapackint const n, mplapackint const nrhs, qd_real *a, mplapackint const lda, mplapackint *ipiv, qd_real *b, mplapackint const ldb, mplapackint &info);
void Rggbak(const char *job, const char *side, mplapackint const n, mplapackint const ilo, mplapackint const ihi, qd_real *lscale, qd_real *rscale, mplapackint const m, qd_real *v, mplapackint const ldv, mplapackint &info);
void Rgtsv(mplapackint const n, mplapackint const nrhs, qd_real *dl, qd_real *d, qd_real *du, qd_real *b, mplapackint const ldb, mplapackint &info);
void Rgttrf(mplapackint const n, qd_real *dl, qd_real *d, qd_real *du, qd_real *du2, mplapackint *ipiv, mplapackint &info);
void Rgtts2(mplapackint const itrans, mplapackint const n, mplapackint const nrhs, qd_real *dl, qd_real *d, qd_real *du, qd_real *du2, mplapackint *ipiv, qd_real *b, mplapackint const ldb);
void Rla_wwaddw(mplapackint const n, qd_real *x, qd_real *y, qd_real *w);
void Rlabad(qd_real &small, qd_real &large);
void Rlabrd(mplapackint const m, mplapackint const n, mplapackint const nb, qd_real *a, mplapackint const lda, qd_real *d, qd_real *e, qd_real *tauq, qd_real *taup, qd_real *x, mplapackint const ldx, qd_real *y, mplapackint const ldy);
void Rlacpy(const char *uplo, mplapackint const m, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *b, mplapackint const ldb);
void Rladiv(qd_real const &a, qd_real const &b, qd_real const &c, qd_real const &d, qd_real &p, qd_real &q);
void Rladiv(qd_real const &a, qd_real const &b, qd_real const &c, qd_real const &d, qd_real &p, qd_real &q);
void Rladiv1(qd_real &a, qd_real const &b, qd_real const &c, qd_real const &d, qd_real &p, qd_real &q);
void Rladiv1(qd_real &a, qd_real const &b, qd_real const &c, qd_real const &d, qd_real &p, qd_real &q);
void Rlae2(qd_real const a, qd_real const b, qd_real const c, qd_real &rt1, qd_real &rt2);
void Rlaed5(mplapackint const i, qd_real *d, qd_real *z, qd_real *delta, qd_real const rho, qd_real &dlam);
void Rlaev2(qd_real const a, qd_real const b, qd_real const c, qd_real &rt1, qd_real &rt2, qd_real &cs1, qd_real &sn1);
void Rlagtf(mplapackint const n, qd_real *a, qd_real const lambda, qd_real *b, qd_real *c, qd_real const tol, qd_real *d, mplapackint *in, mplapackint &info);
void Rlagtm(const char *trans, mplapackint const n, mplapackint const nrhs, qd_real const alpha, qd_real *dl, qd_real *d, qd_real *du, qd_real *x, mplapackint const ldx, qd_real const beta, qd_real *b, mplapackint const ldb);
void Rlaic1(mplapackint const job, mplapackint const j, qd_real *x, qd_real const sest, qd_real *w, qd_real const gamma, qd_real &sestpr, qd_real &s, qd_real &c);
void Rlamrg(mplapackint const n1, mplapackint const n2, qd_real *a, mplapackint const dtrd1, mplapackint const dtrd2, mplapackint *index);
void Rlanv2(qd_real &a, qd_real &b, qd_real &c, qd_real &d, qd_real &rt1r, qd_real &rt1i, qd_real &rt2r, qd_real &rt2i, qd_real &cs, qd_real &sn);
void Rlaorhr_col_getrfnp(mplapackint const m, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *d, mplapackint &info);
void Rlaorhr_col_getrfnp2(mplapackint const m, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *d, mplapackint &info);
void Rlapmr(bool const forwrd, mplapackint const m, mplapackint const n, qd_real *x, mplapackint const ldx, mplapackint *k);
void Rlapmt(bool const forwrd, mplapackint const m, mplapackint const n, qd_real *x, mplapackint const ldx, mplapackint *k);
void Rlaqgb(mplapackint const m, mplapackint const n, mplapackint const kl, mplapackint const ku, qd_real *ab, mplapackint const ldab, qd_real *r, qd_real *c, qd_real const rowcnd, qd_real const colcnd, qd_real const amax, char *equed);
void Rlaqge(mplapackint const m, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *r, qd_real *c, qd_real const rowcnd, qd_real const colcnd, qd_real const amax, char *equed);
void Rlaqr1(mplapackint const n, qd_real *h, mplapackint const ldh, qd_real const sr1, qd_real const si1, qd_real const sr2, qd_real const si2, qd_real *v);
void Rlaqsb(const char *uplo, mplapackint const n, mplapackint const kd, qd_real *ab, mplapackint const ldab, qd_real *s, qd_real const scond, qd_real const amax, char *equed);
void Rlaqsp(const char *uplo, mplapackint const n, qd_real *ap, qd_real *s, qd_real const scond, qd_real const amax, char *equed);
void Rlaqsy(const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *s, qd_real const scond, qd_real const amax, char *equed);
void Rlar1v(mplapackint const n, mplapackint const b1, mplapackint const bn, qd_real const lambda, qd_real *d, qd_real *l, qd_real *ld, qd_real *lld, qd_real const pivmin, qd_real const gaptol, qd_real *z, bool const wantnc, mplapackint &negcnt, qd_real &ztz, qd_real &mingma, mplapackint &r, mplapackint *isuppz, qd_real &nrminv, qd_real &resid, qd_real &rqcorr, qd_real *work);
void Rlar2v(mplapackint const n, qd_real *x, qd_real *y, qd_real *z, mplapackint const incx, qd_real *c, qd_real *s, mplapackint const incc);
void Rlarf(const char *side, mplapackint const m, mplapackint const n, qd_real *v, mplapackint const incv, qd_real const tau, qd_real *c, mplapackint const ldc, qd_real *work);
void Rlarfb(const char *side, const char *trans, const char *direct, const char *storev, mplapackint const m, mplapackint const n, mplapackint const k, qd_real *v, mplapackint const ldv, qd_real *t, mplapackint const ldt, qd_real *c, mplapackint const ldc, qd_real *work, mplapackint const ldwork);
void Rlarfb_gett(const char *ident, mplapackint const m, mplapackint const n, mplapackint const k, qd_real *t, mplapackint const ldt, qd_real *a, mplapackint const lda, qd_real *b, mplapackint const ldb, qd_real *work, mplapackint const ldwork);
void Rlarfg(mplapackint const n, qd_real &alpha, qd_real *x, mplapackint const incx, qd_real &tau);
void Rlarfgp(mplapackint const n, qd_real &alpha, qd_real *x, mplapackint const incx, qd_real &tau);
void Rlarft(const char *direct, const char *storev, mplapackint const n, mplapackint const k, qd_real *v, mplapackint const ldv, qd_real *tau, qd_real *t, mplapackint const ldt);
void Rlarfx(const char *side, mplapackint const m, mplapackint const n, qd_real *v, qd_real const tau, qd_real *c, mplapackint const ldc, qd_real *work);
void Rlarfy(const char *uplo, mplapackint const n, qd_real *v, mplapackint const incv, qd_real const tau, qd_real *c, mplapackint const ldc, qd_real *work);
void Rlargv(mplapackint const n, qd_real *x, mplapackint const incx, qd_real *y, mplapackint const incy, qd_real *c, mplapackint const incc);
void Rlarra(mplapackint const n, qd_real *d, qd_real *e, qd_real *e2, qd_real const spltol, qd_real const tnrm, mplapackint &nsplit, mplapackint *isplit, mplapackint &info);
void Rlarrc(const char *jobt, mplapackint const n, qd_real const vl, qd_real const vu, qd_real *d, qd_real *e, qd_real const, mplapackint &eigcnt, mplapackint &lcnt, mplapackint &rcnt, mplapackint &info);
void Rlarrj(mplapackint const n, qd_real *d, qd_real *e2, mplapackint const ifirst, mplapackint const ilast, qd_real const rtol, mplapackint const offset, qd_real *w, qd_real *werr, qd_real *work, mplapackint *iwork, qd_real const pivmin, qd_real const spdiam, mplapackint &info);
void Rlarrr(mplapackint const n, qd_real *d, qd_real *e, mplapackint &info);
void Rlarscl2(mplapackint const m, mplapackint const n, qd_real *d, qd_real *x, mplapackint const ldx);
void Rlartg(qd_real const f, qd_real const g, qd_real &cs, qd_real &sn, qd_real &r);
void Rlartgp(qd_real const f, qd_real const g, qd_real &cs, qd_real &sn, qd_real &r);
void Rlartgs(qd_real const x, qd_real const y, qd_real const sigma, qd_real cs, qd_real sn);
void Rlartv(mplapackint const n, qd_real *x, mplapackint const incx, qd_real *y, mplapackint const incy, qd_real *c, qd_real *s, mplapackint const incc);
void Rlarz(const char *side, mplapackint const m, mplapackint const n, mplapackint const l, qd_real *v, mplapackint const incv, qd_real const tau, qd_real *c, mplapackint const ldc, qd_real *work);
void Rlarzt(const char *direct, const char *storev, mplapackint const n, mplapackint const k, qd_real *v, mplapackint const ldv, qd_real *tau, qd_real *t, mplapackint const ldt);
void Rlas2(qd_real const f, qd_real const g, qd_real const h, qd_real &ssmin, qd_real &ssmax);
void Rlascl(const char *type, mplapackint const kl, mplapackint const ku, qd_real const cfrom, qd_real const cto, mplapackint const m, mplapackint const n, qd_real *a, mplapackint const lda, mplapackint &info);
void Rlascl2(mplapackint const m, mplapackint const n, qd_real *d, qd_real *x, mplapackint const ldx);
void Rlasd5(mplapackint const i, qd_real *d, qd_real *z, qd_real *delta, qd_real const rho, qd_real &dsigma, qd_real *work);
void Rlaset(const char *uplo, mplapackint const m, mplapackint const n, qd_real const alpha, qd_real const beta, qd_real *a, mplapackint const lda);
void Rlasq1(mplapackint const n, qd_real *d, qd_real *e, qd_real *work, mplapackint &info);
void Rlasq2(mplapackint const n, qd_real *z, mplapackint &info);
void Rlasq3(mplapackint const i0, mplapackint &n0, qd_real *z, mplapackint &pp, qd_real &dmin, qd_real &sigma, qd_real &desig, qd_real &qmax, mplapackint &nfail, mplapackint &iter, mplapackint &ndiv, bool const ieee, mplapackint &ttype, qd_real const dmin1, qd_real &dmin2, qd_real const dn, qd_real const dn1, qd_real const dn2, qd_real const g, qd_real &tau);
void Rlasq4(mplapackint const i0, mplapackint const n0, qd_real *z, mplapackint const pp, mplapackint const n0in, qd_real const dmin, qd_real const dmin1, qd_real const dmin2, qd_real const dn, qd_real const dn1, qd_real const dn2, qd_real &tau, mplapackint &ttype, qd_real &g);
void Rlasq6(mplapackint const i0, mplapackint const n0, qd_real *z, mplapackint const pp, qd_real &dmin, qd_real &dmin1, qd_real &dmin2, qd_real &dn, qd_real &dnm1, qd_real &dnm2);
void Rlasr(const char *side, const char *pivot, const char *direct, mplapackint const m, mplapackint const n, qd_real *c, qd_real *s, qd_real *a, mplapackint const lda);
void Rlasrt(const char *id, mplapackint const n, qd_real *d, mplapackint &info);
void Rlassq(mplapackint const n, qd_real *x, mplapackint const incx, qd_real &scale, qd_real &sumsq);
void Rlasv2(qd_real const f, qd_real const g, qd_real const h, qd_real &ssmin, qd_real &ssmax, qd_real &snr, qd_real &csr, qd_real &snl, qd_real &csl);
void Rlaswlq(mplapackint const m, mplapackint const n, mplapackint const mb, mplapackint const nb, qd_real *a, mplapackint const lda, qd_real *t, mplapackint const ldt, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rlaswp(mplapackint const n, qd_real *a, mplapackint const lda, mplapackint const k1, mplapackint const k2, mplapackint *ipiv, mplapackint const incx);
void Rlasyf(const char *uplo, mplapackint const n, mplapackint const nb, mplapackint &kb, qd_real *a, mplapackint const lda, mplapackint *ipiv, qd_real *w, mplapackint const ldw, mplapackint &info);
void Rlasyf_aa(const char *uplo, mplapackint const j1, mplapackint const m, mplapackint const nb, qd_real *a, mplapackint const lda, mplapackint *ipiv, qd_real *h, mplapackint const ldh, qd_real *work);
void Rlasyf_rk(const char *uplo, mplapackint const n, mplapackint const nb, mplapackint &kb, qd_real *a, mplapackint const lda, qd_real *e, mplapackint *ipiv, qd_real *w, mplapackint const ldw, mplapackint &info);
void Rlasyf_rook(const char *uplo, mplapackint const n, mplapackint const nb, mplapackint &kb, qd_real *a, mplapackint const lda, mplapackint *ipiv, qd_real *w, mplapackint const ldw, mplapackint &info);
void Rlatrd(const char *uplo, mplapackint const n, mplapackint const nb, qd_real *a, mplapackint const lda, qd_real *e, qd_real *tau, qd_real *w, mplapackint const ldw);
void Rlatsqr(mplapackint const m, mplapackint const n, mplapackint const mb, mplapackint const nb, qd_real *a, mplapackint const lda, qd_real *t, mplapackint const ldt, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rlauu2(const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, mplapackint &info);
void Rlauum(const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, mplapackint &info);
void Rorbdb5(mplapackint const m1, mplapackint const m2, mplapackint const n, qd_real *x1, mplapackint const incx1, qd_real *x2, mplapackint const incx2, qd_real *q1, mplapackint const ldq1, qd_real *q2, mplapackint const ldq2, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rorbdb6(mplapackint const m1, mplapackint const m2, mplapackint const n, qd_real *x1, mplapackint const incx1, qd_real *x2, mplapackint const incx2, qd_real *q1, mplapackint const ldq1, qd_real *q2, mplapackint const ldq2, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rorg2l(mplapackint const m, mplapackint const n, mplapackint const k, qd_real *a, mplapackint const lda, qd_real *tau, qd_real *work, mplapackint &info);
void Rorg2r(mplapackint const m, mplapackint const n, mplapackint const k, qd_real *a, mplapackint const lda, qd_real *tau, qd_real *work, mplapackint &info);
void Rorgbr(const char *vect, mplapackint const m, mplapackint const n, mplapackint const k, qd_real *a, mplapackint const lda, qd_real *tau, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rorghr(mplapackint const n, mplapackint const ilo, mplapackint const ihi, qd_real *a, mplapackint const lda, qd_real *tau, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rorgl2(mplapackint const m, mplapackint const n, mplapackint const k, qd_real *a, mplapackint const lda, qd_real *tau, qd_real *work, mplapackint &info);
void Rorglq(mplapackint const m, mplapackint const n, mplapackint const k, qd_real *a, mplapackint const lda, qd_real *tau, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rorgql(mplapackint const m, mplapackint const n, mplapackint const k, qd_real *a, mplapackint const lda, qd_real *tau, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rorgqr(mplapackint const m, mplapackint const n, mplapackint const k, qd_real *a, mplapackint const lda, qd_real *tau, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rorgtr(const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *tau, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rorhr_col(mplapackint const m, mplapackint const n, mplapackint const nb, qd_real *a, mplapackint const lda, qd_real *t, mplapackint const ldt, qd_real *d, mplapackint &info);
void Rorm2r(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, qd_real *a, mplapackint const lda, qd_real *tau, qd_real *c, mplapackint const ldc, qd_real *work, mplapackint &info);
void Rormbr(const char *vect, const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, qd_real *a, mplapackint const lda, qd_real *tau, qd_real *c, mplapackint const ldc, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rorml2(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, qd_real *a, mplapackint const lda, qd_real *tau, qd_real *c, mplapackint const ldc, qd_real *work, mplapackint &info);
void Rormlq(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, qd_real *a, mplapackint const lda, qd_real *tau, qd_real *c, mplapackint const ldc, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rormql(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, qd_real *a, mplapackint const lda, qd_real *tau, qd_real *c, mplapackint const ldc, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rormql(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, qd_real *a, mplapackint const lda, qd_real *tau, qd_real *c, mplapackint const ldc, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rormqr(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, qd_real *a, mplapackint const lda, qd_real *tau, qd_real *c, mplapackint const ldc, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rpbequ(const char *uplo, mplapackint const n, mplapackint const kd, qd_real *ab, mplapackint const ldab, qd_real *s, qd_real &scond, qd_real &amax, mplapackint &info);
void Rpbsv(const char *uplo, mplapackint const n, mplapackint const kd, mplapackint const nrhs, qd_real *ab, mplapackint const ldab, qd_real *b, mplapackint const ldb, mplapackint &info);
void Rpbtrs(const char *uplo, mplapackint const n, mplapackint const kd, mplapackint const nrhs, qd_real *ab, mplapackint const ldab, qd_real *b, mplapackint const ldb, mplapackint &info);
void Rpoequ(mplapackint const n, qd_real *a, mplapackint const lda, qd_real *s, qd_real &scond, qd_real &amax, mplapackint &info);
void Rpoequb(mplapackint const n, qd_real *a, mplapackint const lda, qd_real *s, qd_real &scond, qd_real &amax, mplapackint &info);
void Rposv(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_real *a, mplapackint const lda, qd_real *b, mplapackint const ldb, mplapackint &info);
void Rposvx(const char *fact, const char *uplo, mplapackint const n, mplapackint const nrhs, qd_real *a, mplapackint const lda, qd_real *af, mplapackint const ldaf, char *equed, qd_real *s, qd_real *b, mplapackint const ldb, qd_real *x, mplapackint const ldx, qd_real &rcond, qd_real *ferr, qd_real *berr, qd_real *work, mplapackint *iwork, mplapackint &info);
void Rpotf2(const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, mplapackint &info);
void Rpotrf(const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, mplapackint &info);
void Rpotrf2(const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, mplapackint &info);
void Rpotri(const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, mplapackint &info);
void Rpotrs(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_real *a, mplapackint const lda, qd_real *b, mplapackint const ldb, mplapackint &info);
void Rppequ(const char *uplo, mplapackint const n, qd_real *ap, qd_real *s, qd_real &scond, qd_real &amax, mplapackint &info);
void Rppsv(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_real *ap, qd_real *b, mplapackint const ldb, mplapackint &info);
void Rpptrs(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_real *ap, qd_real *b, mplapackint const ldb, mplapackint &info);
void Rptcon(mplapackint const n, qd_real *d, qd_real *e, qd_real const anorm, qd_real &rcond, qd_real *work, mplapackint &info);
void Rptsv(mplapackint const n, mplapackint const nrhs, qd_real *d, qd_real *e, qd_real *b, mplapackint const ldb, mplapackint &info);
void Rptsvx(const char *fact, mplapackint const n, mplapackint const nrhs, qd_real *d, qd_real *e, qd_real *df, qd_real *ef, qd_real *b, mplapackint const ldb, qd_real *x, mplapackint const ldx, qd_real &rcond, qd_real *ferr, qd_real *berr, qd_real *work, mplapackint &info);
void Rpttrf(mplapackint const n, qd_real *d, qd_real *e, mplapackint &info);
void Rpttrs(mplapackint const n, mplapackint const nrhs, qd_real *d, qd_real *e, qd_real *b, mplapackint const ldb, mplapackint &info);
void Rptts2(mplapackint const n, mplapackint const nrhs, qd_real *d, qd_real *e, qd_real *b, mplapackint const ldb);
void Rrscl(mplapackint const n, qd_real const sa, qd_real *sx, mplapackint const incx);
void Rsfrk(const char *transr, const char *uplo, const char *trans, mplapackint const n, mplapackint const k, qd_real const alpha, qd_real *a, mplapackint const lda, qd_real const beta, qd_real *c);
void Rspsv(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_real *ap, mplapackint *ipiv, qd_real *b, mplapackint const ldb, mplapackint &info);
void Rsteqr(const char *compz, mplapackint const n, qd_real *d, qd_real *e, qd_real *z, mplapackint const ldz, qd_real *work, mplapackint &info);
void Rsterf(mplapackint const n, qd_real *d, qd_real *e, mplapackint &info);
void Rstev(const char *jobz, mplapackint const n, qd_real *d, qd_real *e, qd_real *z, mplapackint const ldz, qd_real *work, mplapackint &info);
void Rstevd(const char *jobz, mplapackint const n, qd_real *d, qd_real *e, qd_real *z, mplapackint const ldz, qd_real *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, mplapackint &info);
void Rsyconv(const char *uplo, const char *way, mplapackint const n, qd_real *a, mplapackint const lda, mplapackint *ipiv, qd_real *e, mplapackint &info);
void Rsyconvf(const char *uplo, const char *way, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *e, mplapackint *ipiv, mplapackint &info);
void Rsyconvf_rook(const char *uplo, const char *way, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *e, mplapackint *ipiv, mplapackint &info);
void Rsyequb(const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *s, qd_real &scond, qd_real &amax, qd_real *work, mplapackint &info);
void Rsyev(const char *jobz, const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *w, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rsyevd(const char *jobz, const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *w, qd_real *work, mplapackint const lwork, mplapackint *iwork, mplapackint const liwork, mplapackint &info);
void Rsygs2(mplapackint const itype, const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *b, mplapackint const ldb, mplapackint &info);
void Rsygst(mplapackint const itype, const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *b, mplapackint const ldb, mplapackint &info);
void Rsysv(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_real *a, mplapackint const lda, mplapackint *ipiv, qd_real *b, mplapackint const ldb, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rsysv_aa(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_real *a, mplapackint const lda, mplapackint *ipiv, qd_real *b, mplapackint const ldb, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rsysv_aa_2stage(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_real *a, mplapackint const lda, qd_real *tb, mplapackint const ltb, mplapackint *ipiv, mplapackint *ipiv2, qd_real *b, mplapackint const ldb, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rsysv_rk(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_real *a, mplapackint const lda, qd_real *e, mplapackint *ipiv, qd_real *b, mplapackint const ldb, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rsysv_rook(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_real *a, mplapackint const lda, mplapackint *ipiv, qd_real *b, mplapackint const ldb, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rsysvx(const char *fact, const char *uplo, mplapackint const n, mplapackint const nrhs, qd_real *a, mplapackint const lda, qd_real *af, mplapackint const ldaf, mplapackint *ipiv, qd_real *b, mplapackint const ldb, qd_real *x, mplapackint const ldx, qd_real &rcond, qd_real *ferr, qd_real *berr, qd_real *work, mplapackint const lwork, mplapackint *iwork, mplapackint &info);
void Rsytd2(const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *d, qd_real *e, qd_real *tau, mplapackint &info);
void Rsytf2(const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, mplapackint *ipiv, mplapackint &info);
void Rsytf2_rk(const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *e, mplapackint *ipiv, mplapackint &info);
void Rsytf2_rook(const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, mplapackint *ipiv, mplapackint &info);
void Rsytrd(const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *d, qd_real *e, qd_real *tau, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rsytri(const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, mplapackint *ipiv, qd_real *work, mplapackint &info);
void Rsytri2(const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, mplapackint *ipiv, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rsytri_3(const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *e, mplapackint *ipiv, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rsytri_rook(const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, mplapackint *ipiv, qd_real *work, mplapackint &info);
void Rsytrs(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_real *a, mplapackint const lda, mplapackint *ipiv, qd_real *b, mplapackint const ldb, mplapackint &info);
void Rsytrs2(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_real *a, mplapackint const lda, mplapackint *ipiv, qd_real *b, mplapackint const ldb, qd_real *work, mplapackint &info);
void Rsytrs_3(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_real *a, mplapackint const lda, qd_real *e, mplapackint *ipiv, qd_real *b, mplapackint const ldb, mplapackint &info);
void Rsytrs_aa(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_real *a, mplapackint const lda, mplapackint *ipiv, qd_real *b, mplapackint const ldb, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rsytrs_aa_2stage(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_real *a, mplapackint const lda, qd_real *tb, mplapackint const ltb, mplapackint *ipiv, mplapackint *ipiv2, qd_real *b, mplapackint const ldb, mplapackint &info);
void Rsytrs_rook(const char *uplo, mplapackint const n, mplapackint const nrhs, qd_real *a, mplapackint const lda, mplapackint *ipiv, qd_real *b, mplapackint const ldb, mplapackint &info);
void Rtbtrs(const char *uplo, const char *trans, const char *diag, mplapackint const n, mplapackint const kd, mplapackint const nrhs, qd_real *ab, mplapackint const ldab, qd_real *b, mplapackint const ldb, mplapackint &info);
void Rtgexc(bool const wantq, bool const wantz, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *b, mplapackint const ldb, qd_real *q, mplapackint const ldq, qd_real *z, mplapackint const ldz, mplapackint &ifst, mplapackint &ilst, qd_real *work, mplapackint const lwork, mplapackint &info);
void Rtplqt(mplapackint const m, mplapackint const n, mplapackint const l, mplapackint const mb, qd_real *a, mplapackint const lda, qd_real *b, mplapackint const ldb, qd_real *t, mplapackint const ldt, qd_real *work, mplapackint &info);
void Rtpmlqt(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const l, mplapackint const mb, qd_real *v, mplapackint const ldv, qd_real *t, mplapackint const ldt, qd_real *a, mplapackint const lda, qd_real *b, mplapackint const ldb, qd_real *work, mplapackint &info);
void Rtpmqrt(const char *side, const char *trans, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const l, mplapackint const nb, qd_real *v, mplapackint const ldv, qd_real *t, mplapackint const ldt, qd_real *a, mplapackint const lda, qd_real *b, mplapackint const ldb, qd_real *work, mplapackint &info);
void Rtpqrt(mplapackint const m, mplapackint const n, mplapackint const l, mplapackint const nb, qd_real *a, mplapackint const lda, qd_real *b, mplapackint const ldb, qd_real *t, mplapackint const ldt, qd_real *work, mplapackint &info);
void Rtprfb(const char *side, const char *trans, const char *direct, const char *storev, mplapackint const m, mplapackint const n, mplapackint const k, mplapackint const l, qd_real *v, mplapackint const ldv, qd_real *t, mplapackint const ldt, qd_real *a, mplapackint const lda, qd_real *b, mplapackint const ldb, qd_real *work, mplapackint const ldwork);
void Rtptrs(const char *uplo, const char *trans, const char *diag, mplapackint const n, mplapackint const nrhs, qd_real *ap, qd_real *b, mplapackint const ldb, mplapackint &info);
void Rtpttr(const char *uplo, mplapackint const n, qd_real *ap, qd_real *a, mplapackint const lda, mplapackint &info);
void Rtrexc(const char *compq, mplapackint const n, qd_real *t, mplapackint const ldt, qd_real *q, mplapackint const ldq, mplapackint &ifst, mplapackint &ilst, qd_real *work, mplapackint &info);
void Rtrti2(const char *uplo, const char *diag, mplapackint const n, qd_real *a, mplapackint const lda, mplapackint &info);
void Rtrtri(const char *uplo, const char *diag, mplapackint const n, qd_real *a, mplapackint const lda, mplapackint &info);
void Rtrtrs(const char *uplo, const char *trans, const char *diag, mplapackint const n, mplapackint const nrhs, qd_real *a, mplapackint const lda, qd_real *b, mplapackint const ldb, mplapackint &info);
void Rtrttp(const char *uplo, mplapackint const n, qd_real *a, mplapackint const lda, qd_real *ap, mplapackint &info);
#endif
