# Dockerfile.debian-i386
# Debian i386 GCC build environment for remote release distcheck.
ARG BASE=debian:12
FROM ${BASE}
RUN apt-get update && apt-get install -y \
    build-essential \
    gfortran \
    autoconf \
    automake \
    libtool \
    cmake \
    pkg-config \
    libopenblas-dev \
    ccache \
    python3 \
    git \
    xz-utils \
    bzip2 \
    patch \
    util-linux \
    && rm -rf /var/lib/apt/lists/*
# Docker --platform linux/386 on x86_64 hosts still shares the host kernel;
# use linux32 so uname -m reports i686 for GMP/config.guess.
COPY common/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
ENV CCACHE_DIR=/ccache
ENV PATH="/usr/lib/ccache:${PATH}"
ENV CC="ccache gcc"
ENV CXX="ccache g++"
ENV FC="ccache gfortran"
ENV MPLAPACK_REPO=https://github.com/nakatamaho/mplapack.git
ENV MPLAPACK_REF="master"
WORKDIR /work
COPY distcheck/run-ubuntu-distcheck.sh /run-ubuntu-distcheck.sh
RUN chmod +x /run-ubuntu-distcheck.sh
CMD ["/run-ubuntu-distcheck.sh"]
