# Dockerfile.suse
# GCC build for openSUSE (branch: requires autoreconf)
# Build happens at runtime with ccache mounted from host
ARG BASE=opensuse/leap:15.5
FROM ${BASE}

RUN zypper --non-interactive install \
    gcc-c++ \
    gcc-fortran \
    make \
    autoconf \
    automake \
    libtool \
    ccache \
    python3 \
    git-core \
    gzip \
    awk \
    xz \
    bzip2 \
    patch \
    && zypper clean --all

# Configure ccache (directory will be mounted at runtime)
ENV CCACHE_DIR=/ccache
ENV PATH="/usr/lib/ccache:/usr/lib64/ccache:${PATH}"
ENV CC="ccache gcc"
ENV CXX="ccache g++"
ENV FC="ccache gfortran"

ENV MPLAPACK_REPO=https://github.com/nakatamaho/mplapack.git
# Branch name or commit SHA. Example: release/2.1 or a full SHA.
ENV MPLAPACK_REF="release/2.1"

WORKDIR /work

CMD ["/bin/bash", "-lc", "\
set -euxo pipefail; \
echo '=== ccache stats (before) ==='; ccache -s; \
\
# Fresh checkout every run \
rm -rf /work/mplapack; \
git clone --depth 1 --branch \"$MPLAPACK_REF\" \"$MPLAPACK_REPO\" /work/mplapack || { \
  # If MPLAPACK_REF is a commit SHA, clone then checkout \
  git clone \"$MPLAPACK_REPO\" /work/mplapack; \
  cd /work/mplapack; \
  git checkout \"$MPLAPACK_REF\"; \
}; \
cd /work/mplapack; \
git log -1; \
\
# Autotools prep \
cd mplapack/test/compare; bash gen.Makefile.am.sh; cd /work/mplapack; \
autoreconf --force --install; \
\
ARCH=$(uname -m); \
echo \"Detected architecture: $ARCH\"; \
COMMON_OPTS=\"--enable-gmp=yes --enable-mpfr=yes --enable-binary128=yes --enable-qd=yes --enable-dd=yes --enable-double=yes --enable-test=yes --enable-benchmark=yes\"; \
if [ \"$ARCH\" = \"x86_64\" ] || [ \"$ARCH\" = \"i686\" ]; then \
  CONFIGURE_OPTS=\"$COMMON_OPTS --enable-binary80=yes\"; \
else \
  CONFIGURE_OPTS=\"$COMMON_OPTS\"; \
fi; \
echo \"Configure options: $CONFIGURE_OPTS\"; \
\
./configure $CONFIGURE_OPTS; \
make -j\"$(nproc)\"; \
make install; \
make dist; \
echo '=== ccache stats (after) ==='; ccache -s; \
"]
