# Dockerfile.suse-tarball
# GCC build for openSUSE (tarball: no autoreconf needed)

ARG BASE=opensuse/leap:15.5
FROM ${BASE}

RUN zypper --non-interactive install \
    gcc-c++ \
    gcc-fortran \
    make \
    gmp-devel \
    mpfr-devel \
    mpc-devel \
    blas-devel \
    lapack-devel \
    && zypper clean --all

# Extract and build from tarball
COPY mplapack-*.tar.gz /tmp/
WORKDIR /tmp
RUN tar xzf mplapack-*.tar.gz && rm mplapack-*.tar.gz

WORKDIR /tmp/mplapack-*
RUN ./configure && make -j$(nproc)

CMD ["make", "check"]
